### ISSUE TITLE
Add CLI command to get/set/list environment variables

### ISSUE THREAD

**Issue by ehmicky** [netlify/cli#1011]
This was requested in [Netlify community](https://community.netlify.com/t/are-envs-set-in-build-plugins-available-during-function-runtime/18842/12).

Users can currently get/set/list environment variables using `netlify api updateSite` and `netlify api getSite` but this is quite cumbersome and also:
  - `updateSite` replaces all environment variables (set in the UI), instead of appending to them
  - `getSite` only returns the environment variables set in the UI

It would be nice for users to be able to do something similar to `heroku config:set ENV=value`:
  - `netlify env list`: print all environment variables. This would include the ones set in `netlify.toml`, including `contexts.*.environment` (this can easily be done by using the return value of `@netlify/config`)
  - `netlify env get envVarName`: print a single environment variable's value
  - `netlify env set envVarName value`: this would set the value in the UI, not in `netlify.toml`
  - `netlify env delete envVarName`: or alternatively, allow doing `netlify env set envVarName ""`

What do you think?

**Comment by RaeesBhatti** [comment]
Thank you for opening this ticket @ehmicky. It seems like a good idea!

**Comment by erezrokah** [comment]
> If you'd like some support on this issue, let me know and I'll prepare a PR.

That would be great @Pyrax, you can find our contribution guide here https://github.com/netlify/cli/blob/master/CONTRIBUTING.md
