### ISSUE TITLE
403 Forbidden when Folder and File share name (e.g. hello/ and hello.html)

### ISSUE THREAD

**Issue by FinnWoelm** [netlify/cli#1017]
Hey Netlify :heart:,

Thanks for all the amazing work you do! I found a small bug with netlify dev — its behavior is inconsistent with deployed Netlify when you have a folder and file with the same name.

**- Do you want to request a _feature_ or report a _bug_?**

Report a bug.

**- What is the current behavior?**

When you have a folder and a file with the same name and visit the path, you see the file contents when deployed on Netlify, but you get a 403 Forbidden error with netlify dev.

For example, let's say we have a folder `hello/` and a file `hello.html`. When requesting `/hello`,

- Netlify displays the contents of `hello.html`
- `netlify-dev` responds with 403 Forbidden

**- If the current behavior is a bug, please provide the steps to reproduce.**

*For netlify dev:*

```
git clone https://github.com/FinnWoelm/netlify-same-name-for-folder-and-file
netlify dev
```

Visit localhost:8888/static and see 403 Forbidden.

![Screenshot from 2020-07-26 11-34-25](https://user-images.githubusercontent.com/7606194/88475870-22f5bb00-cf34-11ea-9ea9-7ada479d4c05.png)

*For deployed Netlify:*

Visit https://same-name-for-folder-and-file.netlify.app/hello and see contents of hello.html

![Screenshot from 2020-07-26 11-35-12](https://user-images.githubusercontent.com/7606194/88475866-1d987080-cf34-11ea-8968-86a043710312.png)

**- What is the expected behavior?**

netlify dev should match the behavior of deployed Netlify and display the contents of `hello.html`.

**- Local Environment Information**
```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    npm: 6.13.7 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Firefox: 78.0.2
  npmGlobalPackages:
    netlify-cli: 2.58.0

netlify-cli/2.58.0 linux-x64 node-v12.14.1
```

**How to Fix:**

The issue, I believe, is that `static-server` (used by netlify-cli) responds with `403 Forbidden` when requesting a path that matches a directory. The solution is to make a small change in https://github.com/netlify/cli/blob/932022588ea85a83ba94f5b755a9a1ea052bab93/src/commands/dev/index.js#L130

Replace
```
if (proxyRes.statusCode === 404) {
```
with
```
if (proxyRes.statusCode === 404 || proxyRes.statusCode === 403) {
```

I've already tried this locally and it fixes the problem. What do you think about this solution?

Let me know if I can help or provide any more information!

Thanks for all your amazing work :raised_hands: 
Finn

**Comment by FinnWoelm** [comment]
I just wanted to follow up on this :) Let me know if I can provide any more information or if there is anything else I can do. ✨

**Comment by FinnWoelm** [comment]
Will it be helpful if I make a PR for this change? 

It should require only a single change in https://github.com/netlify/cli/blob/932022588ea85a83ba94f5b755a9a1ea052bab93/src/commands/dev/index.js#L130

Replace
```
if (proxyRes.statusCode === 404) {
```
with
```
if (proxyRes.statusCode === 404 || proxyRes.statusCode === 403) {
```

**Comment by erezrokah** [comment]
Sorry for the late follow @FinnWoelm. A PR would be great.
You can see our contribution guidelines here:
https://github.com/netlify/cli/blob/master/CONTRIBUTING.md

**Comment by FinnWoelm** [comment]
No worries! I just created the PR :) Let me know if there's something I should improve!
