### ISSUE TITLE
unintended function usage?

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#103]
Hi! i was testing out the new cli capability and this happened to me. Its non critical but should probably be looked at in case there are further leaks in the flow.

**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

When i first upload a site using netlify cli (not linked to a repo), i got an email a while later telling me i am using Functions Free. However I know that i never set this up on my site, neither in netlify.toml or on the app UI. When i go to the app UI to confirm, Functions Free is indeed enabled (https://app.netlify.com/sites/confident-villani-c2957c/settings/functions). So the email is correct, just that this automatic enabling of functions when I never used it is probably wrong?

**- If the current behavior is a bug, please provide the steps to reproduce.**

```
netlify init
netlify deploy
netlify deploy --prod
```

(i also tried out `netlify link`, `unlink` and `status` during that same session but i dont believe those are related)

**- What is the expected behavior?**

functions should not be automatically activated for a netlify cli site

**- Please mention your node.js, and operating system version.**

Node 10.5
OSX 10.12

**Comment by bcomnes** [comment]
Interesting, I think maybe this is due to us passing an empty functions field in the body of our request to the API always.  We should not include the `functions` key when there are no functions to be uploaded.

We can talk a look today.

**Comment by bcomnes** [comment]
See https://github.com/netlify/cli/blob/master/src/utils/api/deploy/index.js#L55

**Comment by bcomnes** [comment]
🎉netlify-cli/2.0.0-beta.4🎉

If you see this again, lmk!
