### ISSUE TITLE
Issue with wildcarded _headers during netlify dev but not when deployed

### ISSUE THREAD

**Issue by weotch** [netlify/cli#1041]
**- Do you want to request a _feature_ or report a _bug_?**

Report a bug

**- What is the current behavior?**

When I have this in `_headers`:

```
/*/payload.json
	Access-Control-Allow-Origin: *
```

I get this error when running `netlify dev`:

```
Error: invalid rule (A path rule cannot contain anything after * token) at line: 1
    /*/payload.json
```

However, this rule does work in my deploys.  For example, that header rule gets applied to https://netlify-dev-issue.netlify.app/payload.json but https://netlify-dev-issue.netlify.app/ doesn't.

**- If the current behavior is a bug, please provide the steps to reproduce.**

I set up this test repo https://github.com/weotch/netlify-dev-issue which deploys to https://netlify-dev-issue.netlify.app/

**- What is the expected behavior?**

I'd expect no errors during `netlify dev` since that rule works on deploy.

**- Local Environment Information**

```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 77.0.1
    Safari: 13.1.2
  npmGlobalPackages:
    netlify-cli: 2.58.0

netlify-cli/2.58.0 darwin-x64 node-v12.13.1
```

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
