### ISSUE TITLE
Netlify Dev requires internet connection

### ISSUE THREAD

**Issue by lukesmurray** [netlify/cli#1075]
**- Do you want to request a _feature_ or report a _bug_?**

_feature_

**- What is the current behavior?**

Run netlify dev without internet connection and the command fails due to a request for site add ons. (Potentially related to #458)

```
◈ Error retrieving addons data for site
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

I just run `netlify dev` without an internet connection.

**- What is the expected behavior?**

Netlify dev could work without internet. I know caching could lead to outdated setups but if the connection fails it could be a warning rather than a failure to deploy. An example of when this is useful is if I want to make changes to content while in a coffee shop or some other environment where I may not have a stable connection. Of course I can use a local server to deploy a static site but I lose things like routing and the tight integration/updates to the browser which I really like.

**- Local Environment Information**

I'm using a custom deployment on a mac.
Let me know if there is any extra info you need and I can supply it.

```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.6.0 - /usr/local/bin/node
    npm: 6.14.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 78.0.2
    Safari: 13.1.1
  npmGlobalPackages:
    netlify-cli: 2.54.0

netlify-cli/2.54.0 darwin-x64 node-v14.6.0
```

**Comment by erezrokah** [comment]
Hi @lukesmurray, can you try running with the `--offline` flag?
See https://cli.netlify.com/commands/dev#dev

**Comment by lukesmurray** [comment]
haha thank you that definitely solves this
