### ISSUE TITLE
dotfiles are ignored by 'netlify deploy'

### ISSUE THREAD

**Issue by fool** [netlify/cli#11]
when you 'netlify deploy' a project that has files or directories beginning with dot ("."), they do not get deployed.

**Comment by kirillgroshkov** [comment]
Same here!

**Comment by fool** [comment]
This behavior is not limited to our CLI deploys - it is also the case for git-backed deploys.  The workaround at present is to use the [redirects](https://www.netlify.com/docs/redirects/) functionality to serve dotfiles:

```
/.well-known/* /not-a-dotfile/:splat 200!
```

Ping support@netlify.com in case you can't get that working.

**Comment by kirillgroshkov** [comment]
Yes, support actually helped me today with it by suggesting the same solution. It works!

**Comment by bcomnes** [comment]
We ignore dotfiles except for well-known in the upcoming 2.0.0 release.  Please open an issue with your use case if this doesn't work for you.

**Comment by zalnaRs** [comment]
I still have the issue even with this redirect solutions I wanted to use it for trusted web activities which requires an `.well-known/assetlinks.json` but I can't get it to work so I can access it.

**Comment by fool** [comment]
perhaps you could show us your code and tell us what site you are using it on.  This should work well if you configure things correctly, but asserting that "i can't get it to work" doesn't help us help you troubleshoot.

PS: I'd suggest opening a community thread at https://answers.netlify.com rather than responding to closed github issues, if you'd like for our Support team to help you, too :)
