### ISSUE TITLE
invalid update available messge

### ISSUE THREAD

**Issue by SteveALee** [netlify/cli#1116]
When running "netlify dev function:invoke" I got a message saying a new version of the cli was available and I should run 

`npm -i -g  netlify-cli`

`-i` is invalid and should be just `i`

I can't find this in the source code so guess it's a message from somewhere else.

**Comment by erezrokah** [comment]
Thanks @SteveALee, it is probably coming from https://github.com/yeoman/update-notifier.

Can you please share the output of `npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli` so we can try and reproduce using the same environment?

**Comment by SteveALee** [comment]
Sadly I reinstalled the cli - after having to delete some files (ntl.psi and ntl.cmd) from `...AppData/Roaming/npm/`, even after `npm rm -g netlify-cli`

But anyway
```
C:\Users\steve>npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
npx: installed 1 in 1.639s

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 4.08 GB / 15.86 GB
  Binaries:
    Node: 14.6.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
```

Did you expect netlify-cli there?

```
C:\Users\steve>npm ls -g netlify-cli
C:\Users\steve\AppData\Roaming\npm
`-- netlify-cli@2.59.1
```

**Comment by erezrokah** [comment]
Yeah I was expecting to see see the CLI, but maybe we have some installation issues with Windows machines.
Thanks for the information.

**Comment by SteveALee** [comment]
yes the update notifier text looks correct. And the version bumped .1
Perhaps I imaged the `-i` ?

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
