### ISSUE TITLE
`netlify dev` loads wrong port in development environment on launch.

### ISSUE THREAD

**Issue by integrate-your-mind** [netlify/cli#1126]
**Describe the bug**

Netlify opens up localhost:3000 instead of localhost:8888 when running `netlify dev`, this is pretty confusing.

**To Reproduce**

1. run `netlify dev` or `ntl dev`
2. when your app loads it will load on the wrong port, it will load on 3000 instead of 8888

**Configuration**

```[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"

[build] # Make sure you don't have a duplicate [build] context!
  command = "npm run build"
  functions = ".netlify/functions/"
  publish = "build"

[dev]
  framework = "#custom"
  command = "npm run start" # Command to start your dev server
  targetPort = 3000 # The port for your application server, framework or site generator
  port = 8888 # The port that the netlify dev will be accessible on
  publish = "build" # The path to your static content folder
```

```  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 53.74 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.6.0 - ~/.nvm/versions/node/v14.6.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v14.6.0/bin/npm
  npmGlobalPackages:
    netlify-cli: 2.59.1
```

**Expected behavior**

It should open up `http://localhost:8888/` instead of `http://localhost:3000`

**Comment by ehmicky** [comment]
Hi @integrate-your-mind, 

Thanks for reporting this bug!
Could you try downgrading `netlify-cli` to `2.58.0` and see if this fixes this problem? I am asking only for debugging the root cause, not as a solution to this problem. Thanks!

**Comment by erezrokah** [comment]
Closing this as stale. Please comment if still happens on CLI latest version
