### ISSUE TITLE
[Feature Request] Portable mode/pass access token in deploy step

### ISSUE THREAD

**Issue by alexrussell** [netlify/cli#116]
Vaguely related to #105, but it'd be useful if we could use `netlify-cli` in "portable" mode - specifically to deploy a site without actually being logged in/linked, etc.

The Go client supports this as far as I know (see below for my "evidence" of this) through `deploy -A` where you can pass a token in, but It doesn't appear (at least according to the docs) that the Node client does.

Specifically what I'm looking into is the possibility of adding a "deploy to Netlify" step in my CI pipeline in Gitlab, similarly to how [this article](https://www.jvt.me/posts/2018/04/12/gitlab-ci-netlify/) works (but less downloading/extracting the binary directly and hopefully being able to install it as a project `devDependency`, though I know the docs suggest a global install). The pertinent line in that article is the bit that does the Netlify upload:

    ./netlifyctl deploy -s site-id -P public -A access-token

[Edit: we're self-hosting Gitlab, so can't use the Netlify CD integration as far as I can tell.]

**Comment by DavidWells** [comment]
Hey @alexrussell thanks for the issue!

You can do this with `env` vars right now.

```
// Set the site ID
process.env.NETLIFY_SITE_ID
// Set your netlify access token
process.env.NETLIFY_ACCESS_TOKEN
```

Then you can run any command you want and the `process.env.NETLIFY_SITE_ID` will be the site the commands act on.

**Comment by alexrussell** [comment]
A-ha, thanks for the advice, I'll check it out.

**Comment by bcomnes** [comment]
> we're self-hosting Gitlab, so can't use the Netlify CD integration as far as I can tell.

netlifyctl and the new beta cli both support a `--manual` flag to set up CI for unsupported git hosts.  Basically if your host supports deploy keys and web hooks, you can set up CI with our build bots.

**Comment by alexrussell** [comment]
@jaydorsey this *maaaaay* be because it's actually `NETLIFY_AUTH_TOKEN`: https://github.com/netlify/cli/blob/6d15e2bb32aad07ddf2e5c59fbd546220ce9e0a1/src/base/index.js#L39

I can't say for certain as I didn't quite get around to doing my own implementation today (will hopefully do it tomorrow, everything else is in place now), and I have only briefly looked at the code.

**Comment by bcomnes** [comment]
My apologies.  This is something we will document better asap.

**Comment by bcomnes** [comment]
Also just to confirm, we are committed to supporting prompt free CI workflows.  Let me know which commands are most important to you in a non-interactive context and I'll be sure to make sure they work with ENV vars.

**Comment by alexrussell** [comment]
One thing that I'd say is quite needed is to be able to install as a dev dependency and use with `yarn run netlify` rather than having to install globally.

It would appear that when I install as a dev dependency, the binaries aren't put in `node_modules/.bin/`

**Comment by alexrussell** [comment]
Okay I can say I have successfully managed to use the new version of `netlify-cli` as a dev dependency in my project in order to deploy build assets from a self-hosted Gitlab pipeline using the environment vars (and yes, it is `NETLIFY_AUTH_TOKEN`). Works nicely.

My `deploy` stage is simply `yarn run netlify deploy -d www/ -p -m "$CI_COMMIT_SHA"` in the script. as the `NETLIFY_SITE_ID` and `NETLIFY_AUTH_TOKEN` are already in the env from Gitlab's secret variables panel.

**Comment by bcomnes** [comment]
I want to add some automatic ci detection and prevent prompt hangs at some point.

**Comment by bcomnes** [comment]
I also wonder if it would make sense to default to the commit sha as a comment, if its possible to find one.

**Comment by alexrussell** [comment]
Yeah, as you can see that's what I ended up doing.

**Comment by jaydorsey** [comment]
Good catch @alexrussell. Confirmed, that environment variable works. Thank you for following up with this!
