### ISSUE TITLE
Add plugins command

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#117]
Add ability for users to install additional commands

```
# list installed plugins
netlify plugins
# install plugin
netlify plugins:install netlify-name-of-thing-plugin
# remove plugin
netlify plugins:uninstall netlify-name-of-thing-plugin
# updates installed plugins to latest versions
netlify plugins:update
```

Plugins should follow a naming convention like: `netlify-name-of-thing-plugin`.  

(`netlify-{name-of-thing}-plugin`)

Future:

```
# Search plugin repo for available plugins 
netlify plugins:search query
```

- [ ] Add commands
- [ ] document how to create plugins

**Comment by sw-yx** [comment]
ideally also document how plugins are different from addons (different access levels etc)

**Comment by bcomnes** [comment]
Oh yeah, good point.  Might be a point of confusion.
