### ISSUE TITLE
Add docs on how to contribute

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#118]
We need to add docs on how folks can contribute to the project and create third party plugins

- [x] how to contribute
- [ ] how to build CLI plugins

**Comment by bcomnes** [comment]
I improved the https://github.com/netlify/cli/blob/master/CONTRIBUTING.md section.  How we want to support plugins is still WIPy.

**Comment by bcomnes** [comment]
I'm going to close this since we already have half if this done, and the other half should be covered by https://github.com/netlify/cli/issues/117
