### ISSUE TITLE
Stream back deploy & function logs

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#119]
Add ability for user to see deploy logs in CLI. Also the ability for user to see function logs in the CLI (potentially separate issue)

We could stream back deploy logs on `netlify watch` and `netlify deploy`

**Notes:**

If this requires adding leaking firebase client into the CLI, we should put this feature off until a bespoke logs API is usable via https://open-api.netlify.com/#/default

Fallback potentially looks like: https://github.com/netlify/cli/issues/70 ?

**Future/potential alt API:**

Potentially a master `netlify logs` command

**Comment by RaeesBhatti** [comment]
This functionality was initially implemented in https://github.com/netlify/cli/pull/762 but later reverted because of NodeJS compatibility issues. I'm think maybe we can precompile incompatible code and include that. Opening again to investigate further.

**Comment by Jolg42** [comment]
@RaeesBhatti That would be an amazing feature (that competition already has implemented), would be nice to give it a second shot I think 😃

**Comment by whitep4nth3r** [comment]
I would love to see this!

**Comment by sarahetter** [comment]
This has been added in `netlify-cli@17.5.0` 🎉 

- `netlify logs:deploy` to have an interactive selector for currently active builds
- `netlify logs:functions` to have an interactive selector for all functions on a site
- `netlify logs:functions my-function-name` to instantly stream the logs for a given function, in this case my-function-name
