### ISSUE TITLE
build command throws ENOENT

### ISSUE THREAD

**Issue by zanona** [netlify/cli#1194]
Is bash necessary for executing the build command?

```sh
$ netlify  build --context=development --debug

┌─────────────────────────────┐
│        Netlify Build        │
└─────────────────────────────┘
​
❯ Version
  @netlify/build 3.3.5
​
❯ Flags
  mode: cli
​
❯ Current directory
  /mnt/app
​
❯ Config file
  /mnt/app/netlify.toml
​
❯ Context
  development
​
┌────────────────────────────────────┐
│ 1. build.command from netlify.toml │
└────────────────────────────────────┘
​
$ echo testCommand


┌─────────────────────────────┐
│   "build.command" failed    │
└─────────────────────────────┘
​
  Error message
  Command failed with ENOENT: echo testCommand
  spawn bash ENOENT
​
  Error location
  In build.command from netlify.toml:
  echo testCommand
​
  Resolved config
  build:
    command: echo testCommand
    commandOrigin: config
    environment: ...

```
Expected:
https://github.com/netlify/cli/blob/21a0656fb0bc7dc39129a4d539f8e64a6061ffe6/tests/command.build.test.js#L34

**Comment by erezrokah** [comment]
Hi @zanona, can you please follow the issue template? That would make it easier for us to reproduce locally.

**Comment by zanona** [comment]
Sorry, not sure what happened, but when opening I didn't get the template, I opened by referencing a line of code directly.
Closing in favour of: https://github.com/netlify/build/commit/dab2ef83b6c036873d89da4e473ece4b7a691d21#r41971893

**Comment by ehmicky** [comment]
Hi @zanona,

Bash has been used for many years to run Netlify Build commands. The reason it is currently used is to maintain backward compatibility with Build commands that use Bash-specific syntax.

**Comment by zanona** [comment]
> Hi @zanona,
> 
> Bash has been used for many years to run Netlify Build commands. The reason it is currently used is to maintain backward compatibility with Build commands that use Bash-specific syntax.

Thanks for clarifying, @ehmicky.
I have now added bash as a dependency to my docker container.

**Comment by MiKr13** [comment]
Thanks @ehmicky this helped

> Hi @zanona,
> 
> Bash has been used for many years to run Netlify Build commands. The reason it is currently used is to maintain backward compatibility with Build commands that use Bash-specific syntax.

Thanks @ehmicky this helped a lot!
