### ISSUE TITLE
Docusaurus 2 is not detected by netlify dev

### ISSUE THREAD

**Issue by nickmccurdy** [netlify/cli#1199]
**Describe the bug**

`netlify dev` can detect Docusaurus 1 sites, but does not detect Docusaurus 2 sites and treats them like static sites.

**To Reproduce**

1. `npx @docusaurus/init@next init my-website classic`
2. `cd my-website`
3. `netlify dev`

**Configuration**

```
  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 167.68 MB / 8.00 GB
    Shell: 3.1.2 - /usr/local/bin/fish
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmGlobalPackages:
    netlify-cli: 2.61.1
```

**Expected behavior**

Docusaurus 2 sites should be detected like Docusaurus 1 sites. This could be achieved either by adding 2 support to the existing detector with dynamic commands or adding a new detector for only 2 support.

**CLI Output**

```
◈ Netlify Dev ◈
◈ No app server detected and no "command" specified
◈ Running static server from "cli/site/dist"
```

**Additional context**

It seems like `docusaurus-start` has changed to `docusaurus start`.

**Comment by monsonjeremy** [comment]
I've just made a PR for this issue: https://github.com/netlify/cli/pull/1228
