### ISSUE TITLE
On init flow, use found build commands

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#120]
When `netlify init`ing a site, we should pre-populate the `build` command and build dir if found in netlify.toml (or package.json)

Right now they must be entered manually. 

We can provide defaults if found: https://github.com/netlify/cli/blob/8d7839ff5522246e4a96ffc5cf440aa4e2f172cd/src/utils/init/config-github.js#L59

Code to update: https://github.com/netlify/cli/blob/8d7839ff5522246e4a96ffc5cf440aa4e2f172cd/src/utils/init/config-github.js#L44-L61

**Comment by erezrokah** [comment]
Closing as resolved via https://github.com/netlify/cli/blob/ff8e4dfc3b217cd1c08f0d8ec4e37eeaa5f9e37c/src/utils/init/utils.js#L24
