### ISSUE TITLE
Splat redirects should not be applied to other matching redirects

### ISSUE THREAD

**Issue by nickmccurdy** [netlify/cli#1221]
**Describe the bug**

Splat redirects are always applied to matching paths, even if there's another matching path higher up. According to [Rule processing order](https://docs.netlify.com/routing/redirects/#rule-processing-order) and Netlify deploy previews, only the first matching rule should be used.

This makes one site difficult to develop with because many URLs that are valid on Netlify are redirected to 404s.

**To Reproduce**

Visit `localhost:8888/a`

**Configuration**

```toml
[[redirects]]
  from = "/a"
  to = "/docs/a"

[[redirects]]
  from = "/docs/*"
  to = "/docs/b/:splat"
```

```
  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 300.75 MB / 8.00 GB
    Shell: 3.1.2 - /usr/local/bin/fish
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmGlobalPackages:
    netlify-cli: 2.61.2
```

**Expected behavior**

Should redirect to `/docs/a` as Netlify only matches the first redirect

**Actual behavior**

Redirects to `/docs/b/a` after incorrectly matching the splat redirect as well

**Comment by jgarcialively** [comment]
Has there been any movement on this one? I am experiencing splat issues after attempting to move all of my blog content into the /blog/ subdirectory and now it is splatting on some of my content I did not want there :-(

**Comment by erezrokah** [comment]
Hi @jgarcialively, no progress yet.
We do have an experimental flag you can use to switch to a redirects engine closer to the one we use in production.
You can opt in into in via `ntl dev --edgeHandlers`

**Comment by erezrokah** [comment]
Adding more context.
The second redirect should be applied only when [there is not an existing file](https://docs.netlify.com/routing/redirects/rewrites-proxies/#shadowing).
See https://606eca0dadc0ef00084e4b4f--erez-build-reproductions.netlify.app/a for a deploy without an `a.html` file and https://606eca879cae400007aa9c8e--erez-build-reproductions.netlify.app/a for a deploy with an `a.html` file.

`netlify dev` seems to apply the second redirect even if the `a.html` file exists.
