### ISSUE TITLE
netlify dev does not handle forced redirects correctly

### ISSUE THREAD

**Issue by probablyup** [netlify/cli#1226]
**Describe the bug**

When using forced redirect syntax (`/from /to 301!`) netlify dev does not correctly apply the redirect before typical routing to the relevant `index.html` file. I can verify the redirect itself works when seen inside a deploy preview.

**Comment by monsonjeremy** [comment]
I'd be happy to take this, would you be able to provide a minimum reproducible example so that I can replicate on my local?

**Comment by erezrokah** [comment]
@probablyup can you please follow the issue template https://github.com/netlify/cli/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md&title=Please+replace+with+a+clear+and+descriptive+title ?

**Comment by erezrokah** [comment]
Closing this pending more information
