### ISSUE TITLE
Allow for authentication via specifying access token or path to config.json

### ISSUE THREAD

**Issue by dial3x** [netlify/cli#123]
Currently there is no way to login by specifying the location of the config.json or a similar method to netlifyctl, where you specify the access token.

It would be great if this feature were added in the cli.

**Comment by bcomnes** [comment]
Use the `NETLIFY_AUTH_TOKEN` and `NETLIFY_SITE_ID` env vars.  I am currently refreshing the docs to make this clearer.  

Curious to know what your use cases are as well.  CI deployments? Anything else?

**Comment by bcomnes** [comment]
Closing this unless there are other open issues.  Let me know!

**Comment by bobinrinder** [comment]
Why is this not documented? We would like to deploy from a Third Party CI solution. What do we have to do? Can I call `deploy` if I have the `NETLIFY_AUTH_TOKEN` and `NETLIFY_SITE_ID ` set? If so, where do I get that `NETLIFY_AUTH_TOKEN`? And what is my `NETLIFY_SITE_ID `, the `API ID` or the `Site Name`?
