### ISSUE TITLE
[deploy] Restore ability to deploy drafts regardless of publishing locked state

### ISSUE THREAD

**Issue by mlbrgl** [netlify/cli#1251]
Hi!

**Is your feature request related to a problem? Please describe.**

It used to be possible to deploy while publishing was locked on the GUI. This is not possible anymore as the only option to deploy is now bound to unlocking publishing:

```
Deployments are "locked" for production context of this site

? Would you like to "unlock" deployments for production context to proceed? (y/N)
```

**Describe the solution you'd like**

Passing a flag to `netlify deploy` to force deploys without changing the publishing lock state and without requiring interactivity. 
As we use the `deploy` command in an [automated script which doesn't allow for interactive commands](https://github.com/owid/owid-grapher/blob/2f56919f3e3576777f916ed10ceddd5ca8845d4c/site/server/SiteBaker.tsx#L620), `netlify deploy` ends up hanging indefinitely. 

**Describe alternatives you've considered**

Unlocking publishing prior to deploying (which defeats the purpose of locking in the first place).

---
Thanks!

**Comment by nbibler** [comment]
This seems to be related to disabling the Netlify auto publishing feature in the Netlify site configuration. See KarrLab/datanator_frontend#255.

**Comment by nbibler** [comment]
I _think_ I was able to kind of work around this by installing the `netlify` CLI tool locally, authenticating, building, and deploying from my local environment. This had me "unlock" the auto publishing, which re-enabled publishing on the Netlify site. But, then I was able to "Stop Builds" and "Deploy previews: None" and "Branch deploys: None" in the web interface after having unlocked it. It now _seems_ to work as expected.

**Comment by danielgavrilov** [comment]
It think this issue is a duplicate of https://github.com/netlify/cli/issues/1392 which has now been fixed in https://github.com/netlify/cli/pull/1988 by introducing a `--prodIfUnlocked` flag.

**Comment by erezrokah** [comment]
Thanks @danielgavrilov, `--prodIfUnlocked` falls back to deploying to a draft instead of deploying to production.
I believe this issue is about adding a `--force` flag to the deploy command to suppress any interactive prompt.

**Comment by nbibler** [comment]
@erezrokah: That sounds correct to me. It would've certainly met my need in this ticket: "Push this build to production. Don't ask me any questions."

**Comment by danielgavrilov** [comment]
@mlbrgl (issue opener) is a colleague of mine and `--prodIfUnlocked` flag is exactly what we wanted:

> **Describe the solution you'd like**
> 
> Passing a flag to `netlify deploy` to force deploys **without changing the publishing lock state** and without requiring interactivity.

Just to avoid confusion.

**Comment by erezrokah** [comment]
Thanks @danielgavrilov, to clarify `--prodIfUnlocked` will not deploy to production if publishing is locked.

I can see a valid use case in - `always deploy to production even if locked`. This means use can have it locked but still opt out in some cases when you're absolutely sure it makes sense.

**Comment by mlbrgl** [comment]
Thanks for the follow-up. I did mean "draft deploys" as opposed to "production deploys", sorry for the confusion (I updated the issue title to make it clearer).

Closing this now as `--prodIfUnlocked` solves our issue.
