### ISSUE TITLE
Not logged in. Log in to deploy to a site

### ISSUE THREAD

**Issue by redplane** [netlify/cli#127]
**- Do you want to request a *feature* or report a *bug*?**
- Bug

**- If the current behavior is a bug, please provide the steps to reproduce.**

I tried deploying my site using `netlify-cli` commands.
Here is my command in batch file I'm using : 

```
npm run build
set NETLIFY_SITE_ID=<my site id>
set NETLIFY_ACCESS_TOKEN=<my access token>
netlify deploy --prod --dir=dist
```

An error is thrown to me: 
**Not logged in. Log in to deploy to a site**

**- What is the expected behavior?**
->> Netlify should allow user to pass parameters to deploy to hosting.

**- Please mention your node.js, and operating system version.**
- Node 9.8.0

**Comment by bcomnes** [comment]
Apologies, that env var you are using is incorrect and was documented incorrectly at one point.  Updating the docs as we speak.




Use these instead:

- `NETLIFY_AUTH_TOKEN`
- `NETLIFY_SITE_ID`

**Comment by bcomnes** [comment]
Additionally, we have improvements around prompt behavior when run from a CI environment in the pipeline.

**Comment by bcomnes** [comment]
Let me know if there are any other issues and we can reopen.

**Comment by redplane** [comment]
Thank you,

After having change `NETLIFY_ACCESS_TOKEN` to `NETLIFY_AUTH_TOKEN`, the deployment was successful.
Please update your document, because I've searched for every post about `netlify cli deployment` and found nothing about `NETLIFY_AUTH_TOKEN` before asking this question.

**Comment by bcomnes** [comment]
We should have improvements out by next week.  Thanks for the feedback!
