### ISSUE TITLE
refactor: use async fs calls in src/utils/proxy.js 

### ISSUE THREAD

**Issue by JCMais** [netlify/cli#1275]
**Describe the bug**

This file could easily use the async versions of the fs functions instead of the sync ones.

**Additional context**

See: https://github.com/netlify/cli/pull/1271#discussion_r493164135

**Comment by mugi111** [comment]
If you don't mind, I want to challenge to fix this issue !

**Comment by erezrokah** [comment]
Thanks @mugi111, I assigned you to the issue. Please let me know if there is anything you need.

**Comment by mugi111** [comment]
https://github.com/netlify/cli/blob/5c9fed77e3aaa632c154000180d692ca0742dd1a/src/utils/proxy.js#L235
Let me ask for advice on how to fix this.
Is it correct to filter the `headersFiles` with `fs.stat()` and `isFiles()` once and then use `map()` for that array?

**Comment by erezrokah** [comment]
You could use https://github.com/sindresorhus/p-filter to filter promises, then run `map` in the result.
You can use https://github.com/netlify/cli/blob/5c9fed77e3aaa632c154000180d692ca0742dd1a/src/lib/fs.js#L18 for the filter

**Comment by mugi111** [comment]
Thank you. It was helpful.
I'll deal with it that way.

**Comment by iChenLei** [comment]
This issue looks like solved, why still opened ?

**Comment by ehmicky** [comment]
Yes, this is solved, thanks for raising this @iChenLei :+1:
