### ISSUE TITLE
Addon snippets dont have access to environment variables

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#128]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

Netlify has normal snippets that have access to environment variables through liquid template tags, eg `{{ REPOSITORY_URL }}`.

When I make an addon that adds a snippet, eg https://github.com/sw-yx/addon-viewsource-api/blob/master/index.js#L103 (now available as "viewsource" inside of the `netlify cli` addons), it should have the same access to env variables.

However when i try it (https://babel-blade.netlify.com/,  see the `<a href="" class="github-corner" aria-label="View source on Github">` element on the html of that page) - the `href` doesnt receive the env variable like i would expect it to.

related netlify internal report: https://netlify.slack.com/archives/CBC2U9MMG/p1537209573000100

**- If the current behavior is a bug, please provide the steps to reproduce.**

as above

**- What is the expected behavior?**

env variables should be available to addon snippets

**- Please mention your node.js, and operating system version.**

n/a as its not a cli issue so much as an addons issue

**Comment by erezrokah** [comment]
Closing this as stale and missing reproduction information.
Please comment if still relevant
