### ISSUE TITLE
Allow --site-id on deploy command

### ISSUE THREAD

**Issue by bendg25** [netlify/cli#129]
**- Do you want to request a *feature* or report a *bug*?**

feature

**- What is the current behavior?**

deploy uses .netlify/json file.    I would like to pass site id as a parameter.

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your node.js, and operating system version.**

**Comment by bcomnes** [comment]
We allow the use of the environment variable `NETLIFY_SITE_ID`, to override or bypass the link step, but I'm thinking maybe a flag could be helpful here as well.

**Comment by jared-evari** [comment]
Specifying a site ID when running the command is very useful when deploying multiple sites at the same time (eg. from a mono repo).

**Comment by bcomnes** [comment]
Ok, I decided to to this.  Stay posted.

**Comment by bcomnes** [comment]
I released a beta that should address this issue: see https://github.com/netlify/cli/pull/147#issuecomment-429497857

Expect a full release monday.

**Comment by bcomnes** [comment]
🎉[`netlify-cli@2.1.0`](https://github.com/netlify/cli/releases/tag/v2.1.0)🎉
