### ISSUE TITLE
File shadowing not working for `netlify dev` and redirects always apply.

### ISSUE THREAD

**Issue by overlordofmu** [netlify/cli#1299]
**Describe the bug**

Redirect rules without an "force" option should not apply when an asset exists for a URL with `netlify dev`. However, instead redirect rules always apply even when the assets exist.

**To Reproduce**

1. Run `git clone https://github.com/overlordofmu/nlm-fake-ssg-site`
1. Run `cd nlm-fake-ssg-site/base`
1. Run `./copy-build.sh ; cd ..`
1. Run `netlify dev`
1. In a new shell run: `curl -svo /dev/null http://localhost:8888/` (changing port as needed)
1. Note there is no redirect applied and the status is 200.
1. Use control-c to shutdown `netlify dev` back in the original shell.
1. Run `echo -e '\n[[redirects]]\n  from = "/*"\n  to = "/en/:splat"\n  force = false' >> netlify.toml`
1. Restart `netlify dev`
1. Again use the curl command: `curl -svo /dev/null http://localhost:8888/` (changing port as needed)
1. Note the 301 redirect to `en`.

**Configuration**

```text
$ npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
npx: installed 1 in 1.528s

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.58 GB / 32.00 GB
    Shell: 5.0.17 - /usr/local/opt/bash/bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.16.0/bin/npm
  npmGlobalPackages:
    netlify-cli: 2.64.1
```

**Expected behavior**

The redirect should not apply when the shadowed file exists.

**Comment by samajammin** [comment]
Hey @overlordofmu thanks for creating this issue ❤️ 🙏 ! Do you or @erezrokah have any sense of the timeline here? Currently it's blocking the PR mentions (https://github.com/ethereum/ethereum-org-website/pull/1536).

Thank you both in advance! Love the work you're doing around Netlify CLI.

**Comment by erezrokah** [comment]
Sorry @samajammin, haven't had the change to look it this issue yet and can't promise on a timeline yet.
Will do my best to unblock you as soon as possible.

**Comment by calavera** [comment]
@samajammin do you mind trying the latest release of the cli with the `--trafficMesh` flag? I think that will fix this issue for you, however, it might introduce others :facepalm: because it's still an experimental component that's evolving quicker than the current redirects engine in the cli.
