### ISSUE TITLE
Add a verbose mode

### ISSUE THREAD

**Issue by fool** [netlify/cli#13]
Brought up by a customer in this helpdesk conversation around failing deploys,

https://app.intercom.io/a/apps/q245f50x/inbox/unassigned/conversations/6125957649

However, I've seen a few other situations it would help with as well.

**Comment by fool** [comment]
the commenters in #10 are seeing the same issue as the customer I reference.

**Comment by bcomnes** [comment]
New CLI has a DEBUG mode.  We may add a verbose mode in the future, but lets see if that covers it.
