### ISSUE TITLE
[netlify dev] Allow passing `framework` as a flag

### ISSUE THREAD

**Issue by probablyup** [netlify/cli#1300]
**Describe the bug**

When trying to compose netlify dev in front of a gatsby server:

```
netlify dev -c 'GATSBY_HOT_LOADER=fast-refresh gatsby develop -S -H 0.0.0.0 -p 9000' --port 8000 --targetPort 9000 --functions src/functions
```

I'm receiving the following error:

```
"framework" option must be set to "#custom" when specifying both "command" and "targetPort" options
```

This "framework" option doesn't seem to be in the manual or docs and passing `--framework #custom` does nothing so I'm at a loss.

**To Reproduce**

Private repo, should not be hard to look in the code based on those strings though.

**Configuration**

```
  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 17.78 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.10 - ~/code/butcherbox-frontend/node_modules/.bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  npmPackages:
    netlify-cli: ^2.64.1 => 2.64.1 
```

**Expected behavior**

It should work

**CLI Output**

```
netlify dev -c 'GATSBY_HOT_LOADER=fast-refresh gatsby develop -S -H 0.0.0.0 -p 9000' --port 8000 --targetPort 9000 --functions src/functions --framework #custom
◈ Netlify Dev ◈
◈ Injected build setting env var: [redacted]
◈ Overriding the following env variables with .env.development file: [redacted]
◈ "framework" option must be set to "#custom" when specifying both "command" and "targetPort" options
error Command failed with exit code 1.
```

### Edit

Since we allow passing `targetPort` and `command` as flags, we should allow the same for `framework`

**Comment by grgcnnr** [comment]
you don't seem to be able to pass framework as a commandline parameter, as a workaround you can add the following to your netlify.toml

```
[dev]
  framework = "#custom"

```

**Comment by erezrokah** [comment]
Thanks @grgcnnr, @probablyup this is documented here https://cli.netlify.com/netlify-dev/#netlifytoml-dev-block which is not a very good place to do it. 

I'm keeping this issue open since we should allow passing `framework` as an argument

**Comment by erezrokah** [comment]
Resolved via https://github.com/netlify/cli/pull/2818
