### ISSUE TITLE
Bug: addons env variables are not available when running `netlify build`

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#1331]
When running `netlify build` addons env variables are not set for `@netlify/build`.
We should use a similar approach like https://github.com/netlify/cli/blob/4f376100ff23e41b938bf017bb991896098eff0a/src/commands/dev/exec.js#L19

to set those

### Context

Got this while trying to run `netlify build` locally with https://github.com/nimbella/netlify-plugin-nimbella/blob/beca8fd4b911f939de21ec47a018ba4dfbbe1afa/index.js#L62

**Comment by ehmicky** [comment]
Please note there is an `env` option to `@netlify/build`. It is a plain object with environment variables. Those environment variables will be set in child processes (the build command and Build plugins), but not in the current process (which is good). This option could probably be used for this.

I am not familiar with addons environment variables, do you have more information about those?

**Comment by erezrokah** [comment]
> I am not familiar with addons environment variables, do you have more information about those?

Those can be added to a site when you create an addon via `netlify addons:create`.
For example `netlify addons:create nimbella` will create an env variable `NIMBELLA_LOGIN_TOKEN`.
`netlify addons:create fauna` creates a bunch of those too.

**Comment by erezrokah** [comment]
Closed by mistake
