### ISSUE TITLE
Remove redundant ESLint configuration file

### ISSUE THREAD

**Issue by ehmicky** [netlify/cli#1369]
This project has one ESLint configuration file at the root, and another one for our `site`.

There should not be any strong reason why the coding styling in our code samples/examples shown in our documentation site to our users should differ from our internal codebase.

This duplicated file makes it harder to add/remove rules, without a strong reason for it. Also, the rules are very similar right now. 

I would suggest removing the `site/.eslintrc.js` file to solve this. What do you think @erezrokah?

**Comment by erezrokah** [comment]
Yes, this was a temporary solution until I could organise it better. 
We can use `overrides` for the specific react related rules:
https://github.com/netlify/cli/blob/5497cb7092a234c1daf24f8cbb7a39763543983c/site/.eslintrc.json#L11

**Comment by ehmicky** [comment]
Done at #1431.
