### ISSUE TITLE
Colored help text on plugins

### ISSUE THREAD

**Issue by bcomnes** [netlify/cli#137]
We wrap our command help test to make them more colorful/easier to parse but the way oclif works doesn't allow us to enforce that uniformly.  

For example, adding the help plugin, or the plugin plugin, or any other plugin that doesn't implement help text the way we have in the main cli, we get different colored output which looks janky:

<img width="770" alt="screen shot 2018-10-08 at 4 51 08 pm" src="https://user-images.githubusercontent.com/166301/46639368-62160a80-cb1a-11e8-8c16-08aed6e29a39.png">

@DavidWells you mentioned a few solitons to this, but they seemed to require a fair bit of new code in order to take responsibility of printing these strings.

I propose that we initially embrace this limitation, remove our coloring on the help text that oclif prints for us until we have time to look into a more comprehensive solution, or determine that this approach is fine long term.  This eliminates existing blockers on plugins, the use of some of oclif ecosystem plugins, and takes responsibility off our plate until someone feels compelled to fix it.

**Comment by DavidWells** [comment]
Yeah thats fine by me. Ideally we would control all output from our CLI. 

Possible solutions:

- Perhaps an upstream contribution to oclif
- Maintain our own plugin logic
- remove colors for now

Removing colors for now sounds ok. I think eventually we will hit a limitation where we will need to take over this logic but today isn't that day.
