### ISSUE TITLE
Change submission-created function template to a more generic form handler.

### ISSUE THREAD

**Issue by cfjedimaster** [netlify/cli#1385]
**Is your feature request related to a problem? Please describe.**

So today I noticed that when using `netlify functions:create`, there is a template for it. The template is based on a blog article here, https://css-tricks.com/using-netlify-forms-and-netlify-functions-to-build-an-email-sign-up-widget/, that describes using the function to submit an email address to a listserv.

While this is absolutely a valid example, I really think a more generic one that uses something like SendGrid to send the form data would be more appropriate. 

I'd be happy to file a PR with this change, but I wanted to file this issue first to see if it was something desirable. 

**Describe the solution you'd like**

A change to the submission-created template that may be more helpful.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Can you submit a pull request?**

Yes

**Comment by erezrokah** [comment]
Thanks @cfjedimaster, very cool suggestion. A SendGrid template makes a lot of sense. Do you want to add a new template or modify the current one? If we do modify the current one can we make it backwards compatible? Maybe choose a provide based on the `process.env` token name?

**Comment by cfjedimaster** [comment]
I'm not sure the new template would be backwards compatible as it would be doing something completely different - but as it's just a scaffold for a new function, that should be ok, right?

**Comment by erezrokah** [comment]
> but as it's just a scaffold for a new function, that should be ok, right?

I agree it's just scaffolding a new function, but if someone was using the old template and will try to generate the same function again they will get a different one.

A new template with a distinctive name for SendGrid can keep things explicit.

A more general approach would be to have a mechanism to deprecate templates, but this is out of scope at the moment.

**Comment by minivan** [comment]
Hi @cfjedimaster, thanks for opening this. Feel free to add a PR for the template! I'm closing the issue for now since the original question is answered.
