### ISSUE TITLE
A flag to publish if auto publish is on, create drafts otherwise

### ISSUE THREAD

**Issue by kasbah** [netlify/cli#1392]
**Is your feature request related to a problem? Please describe.**

I'd like to deploy to production when I turn on "auto publish" in the Netlify dashboard, otherwise make drafts. 

**Describe the solution you'd like**

A flag I can set, maybe `--prod=auto`, that deploys to production if I've enabled that in the dashboard but makes drafts otherwise. 

**Additional context**

I think the way the `--prod` flag works was changed. I swear I used to do it this way. 

**Can you submit a pull request?**

Not, really. I mean I could look into it I guess but it would take me a long time.

**Comment by erezrokah** [comment]
Hi @kasbah, I'm not sure I understand the feature request.
Is it this?
1. `netlify deploy` - never deploys to prod.
2. `netlify deploy --prod` always to prod.
3. `netlify deploy --prod=auto` deploys to prod only if auto publishing is enabled.

**Comment by kasbah** [comment]
Exactly right, yeah. 

`netlify deploy --prod` currently asks this when auto-publishing is off: `Would you like to "unlock" deployments for production context to proceed?` and you probably want to keep that behaviour?
