### ISSUE TITLE
test(traffic-mesh): enable traffic mesh tests in CI

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#1396]
`netlify dev -t` tests are currently disabled in CI:
https://github.com/netlify/cli/blob/0c04b78ead901ca4db62e367699362cf389cb533/tests/command.dev.test.js#L15

This is due to some of the tests failing - we should work through the tests one by one enable the ones that pass and open issues for the ones that fail.

**Comment by calavera** [comment]
There are currently two standing failing tests:

1. https://github.com/netlify/cli/blob/master/tests/command.dev.test.js#L369 I don't really understand this test.
2. Form submission: https://github.com/netlify/cli/blob/master/tests/command.dev.test.js#L568

**Comment by erezrokah** [comment]
> 1. https://github.com/netlify/cli/blob/master/tests/command.dev.test.js#L369 I don't really understand this test. I'd really appreciate some help to understand why that's important.

The explanation I could find so far is https://github.com/netlify/cli/pull/885/files#r423899845 and it could be related to the following fix https://github.com/netlify/cli/pull/885/commits/e913f037797dde8c9bd14d6ebec54b8c8751fb0f.
Clicking the commit link directly doesn't show the PR comment, but clicking it from the [PR](https://github.com/netlify/cli/pull/885) does:
![image](https://user-images.githubusercontent.com/26760571/105474090-8fb0fe80-5ca6-11eb-85b8-838d65c3eeac.png)

To me it looks like we were passing `[Object]` as body for `GET` requests.

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
