### ISSUE TITLE
returned URL from netlify deploy -d should not be hash.sitename.netlify.com

### ISSUE THREAD

**Issue by fool** [netlify/cli#14]
...since it could instead be hash--sitename.netlify.com, and this one works with our existing SSL cert!

**Comment by alamottemitchell** [comment]
+1

**Comment by fool** [comment]
@calavera looks like I already did this :)

**Comment by fool** [comment]
https://app.intercom.io/a/apps/q245f50x/inbox/chrism@netlify.com/conversations/6338861148

**Comment by bcomnes** [comment]
We've improved this in the upcoming 2.0.0 release.
