### ISSUE TITLE
Consistent filename case

### ISSUE THREAD

**Issue by ehmicky** [netlify/cli#1437]
The CLI uses a `kebab-case` convention, while `@netlify/build` uses `snake_case`. 
Should we keep it consistent between projects? If so, which one should we use?
I personally think `snake_case` is more idiomatic in Node.js, but I'm fine with any case, as long as we're consistent. What do you think @erezrokah?

Note: both currently lint this using the [`unicorn/filename-case`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/filename-case.md) ESLint rule, but with different options.

**Comment by erezrokah** [comment]
Let's go with `snake_case`

**Comment by sarahetter** [comment]
Not a priority
