### ISSUE TITLE
Maximum line length

### ISSUE THREAD

**Issue by ehmicky** [netlify/cli#1457]
The maximum line length can be enforced with Prettier and Editorconfig.

At the moment, the max length is `120`. In my IDE, due to the left panel (files explorer) and right panel (linting and warnings), 120 characters actually do not fit and some lines are wrapped to the next line. `80` would be better for me and other developers with similar setups. 

However, this is not a huge problem. 
Also, I think many people do like longer line length, for example [Linus Torvalds](https://linux.slashdot.org/story/20/05/31/211211/linus-torvalds-argues-against-80-column-line-length-coding-style-as-linux-kernel-deprecates-it) :)
Finally, this would require a huge PR to review, although the PR would be completely generated by Prettier.

What are your thoughts on this @erezrokah ?

**Comment by erezrokah** [comment]
`80` is quite short IMHO.

I'm good with you choosing the size that fits your editor (will `100` work?)

**Comment by ehmicky** [comment]
`100` would be better (although still slightly short). Does this work for you? This will most likely create a big PR :/

**Comment by erezrokah** [comment]
I don't have a strong opinion here. Whatever works for you. We can also postpone this decision until we get some more feedback from other devs. I think the most important thing is to be aligned cross repos, which I think we are.

**Comment by ehmicky** [comment]
I think we can drop this one, and revisit if other developers than me are having a problem with the current line length :)
