### ISSUE TITLE
Init command not creating site in Team account

### ISSUE THREAD

**Issue by petecorreia** [netlify/cli#146]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

When using the `init` command and choosing the owner as my Team account the CLI always sets up the site on my personal account instead.

**- If the current behavior is a bug, please provide the steps to reproduce.**

* run `netlify init`
* pick a team account instead of your personal account
* site is created on personal account instead of team account

**- What is the expected behavior?**

The site should be created in the team account that is selected .

**- Please mention your node.js, and operating system version.**

Node 8.12.0 / MacOS Mojave 10.14

**Comment by bcomnes** [comment]
I released a beta that should address this issue: see https://github.com/netlify/cli/pull/147#issuecomment-429497857

Expect a full release monday.

**Comment by petecorreia** [comment]
Thanks! So quick 😄 Really appreciated

**Comment by bcomnes** [comment]
🎉[`netlify-cli@2.1.0`](https://github.com/netlify/cli/releases/tag/v2.1.0)🎉

**Comment by petecorreia** [comment]
what a turnaround. cheers @bcomnes! 🎉
