### ISSUE TITLE
Use `zip-it-and-ship-it` logic to detect functions

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#1477]
The CLI uses its own logic to detect functions:
https://github.com/netlify/cli/blob/3baac9cd33330064d2c19b1803697fe72800c409/src/utils/get-functions.js#L7

This logic is not aligned with production https://github.com/netlify/cli/pull/1476.

We should re-use the logic from `zip-it-and-ship-it` to do it:
https://github.com/netlify/zip-it-and-ship-it/blob/b211bc7e6cef4c618f04e64782f8bb63856de2a3/src/main.js#L79

**Comment by ehmicky** [comment]
This is probably needed for our new Functions language support.

**Comment by ehmicky** [comment]
Draft PR at #231.
