### ISSUE TITLE
Use `@netlify/framework-info` in Netlify Dev

### ISSUE THREAD

**Issue by ehmicky** [netlify/cli#1495]
Background at https://github.com/netlify/engineering/issues/106

The Netlify CLI's framework detection logic has been abstracted to [`@netlify/framework-info`](https://github.com/netlify/framework-info). We should integrate it inside Netlify CLI.

**Comment by erezrokah** [comment]
This would require making https://github.com/netlify/framework-info public to give the community the option to add/fix detectors.

**Comment by ehmicky** [comment]
Done :arrow_up:

**Comment by ehmicky** [comment]
Related: https://github.com/netlify/cli/issues/1773 (for `@netlify/framework-info` + `netlify init`)
