### ISSUE TITLE
Investigate arg parsing

### ISSUE THREAD

**Issue by bcomnes** [netlify/cli#150]
It has been reported that equals signs are sometimes needed when parsing args.  This has not been my experience, but I want to look into this anyway.

https://github.com/mozmeao/performance-dashboard/pull/15

**Comment by DavidWells** [comment]
Interesting indeed.

Report says this command failed

```
netlify deploy --prod --dir dashboard
```

But this worked

```
netlify deploy --prod --dir=dashboard
```

We should verify that args don't need `=` to work

**Comment by erezrokah** [comment]
Tried `netlify deploy --prod --dir dashboard` and it seems to work.
Closing as stale
