### ISSUE TITLE
Absolute Imports Create React App Netlify Dev

### ISSUE THREAD

**Issue by nightspite** [netlify/cli#1501]
How can I use absolute imports with Create React App with netlify dev?

**Comment by erezrokah** [comment]
Hi @nickmccurdy, can you please follow one of the issue templates:
https://github.com/netlify/cli/issues/new/choose

In your case maybe feature template would work best.

**Comment by erezrokah** [comment]
Closing this. Please comment with the missing information if still relevant

**Comment by nightspite** [comment]
Sorry that i did not respond. Proper configuration of jsconfig.json and everything is working fine.
