### ISSUE TITLE
Error: Failed getting list of addons: api.listServiceInstancesForSite is not a function

### ISSUE THREAD

**Issue by KazakovKirill** [netlify/cli#1541]
Running `ntl addons:list` or `ntl dev` immediately causes this error
_(single line in console, no other messages or errors)_:

> Error: Failed getting list of addons: api.listServiceInstancesForSite is not a function

What I already tried: reinstall netlify-cli, `ntl unlink` → `ntl logout` → `ntl login` → `ntl link` — site linked again, but error still present :frowning:

`ntl status` output:

```
──────────────────────┐
 Current Netlify User │
──────────────────────┘
Email:  ****@*****.com
Github: *********
Teams: 
  space17's team: Collaborator 
```

`ntl version` output:

> netlify-cli/2.68.0 win32-x64 node-v15.0.0

Few days before I posted this issue on [netlify community](https://community.netlify.com/t/error-failed-getting-list-of-addons-api-listserviceinstancesforsite-is-not-a-function/25919), but nobody replies there.

**Comment by erezrokah** [comment]
Hi @KazakovKirill, thank you for opening this issue.
I was able to run `ntl addons:list` without any issues on `netlify-cli/2.68.0 darwin-x64 node-v15.0.1`.
How are you installing the CLI? Globally? Locally? Via `npm` or `yarn`?

If installing globally, can you share the output of running:
```
npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
npm ls -g netlify-cli
npm ls -g netlify
npm ls -g @netlify/open-api
```

**Comment by KazakovKirill** [comment]
@erezrokah Thank for quick reply!

I installed it **globally** using **yarn**.

> npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
```
 System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 6.30 GB / 15.85 GB
  Binaries:
    Node: 15.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.0.2 - C:\Program Files\nodejs\npm.CMD
```

> npm ls -g netlify-cli
```
C:\Program Files\nodejs -> C:\Users\User\AppData\Roaming\nvm\v15.0.0
└── (empty)
```

> npm ls -g netlify
```
C:\Program Files\nodejs -> C:\Users\User\AppData\Roaming\nvm\v15.0.0
└── (empty)
```

> npm ls -g @netlify/open-api
```
C:\Program Files\nodejs -> C:\Users\User\AppData\Roaming\nvm\v15.0.0
└── (empty)
```

**Comment by erezrokah** [comment]
Hi @KazakovKirill, can you try installing via `npm install -g netlify-cli`?
Please run `yarn global remove netlify-cli` before installing via `npm`

**Comment by KazakovKirill** [comment]
Thank you, @erezrokah! Npm installation solved this weird issue!
