### ISSUE TITLE
Make it possible to use urlencoded payload for `ntl functions:invoke`

### ISSUE THREAD

**Issue by simonmulser** [netlify/cli#1544]
**Is your feature request related to a problem? Please describe.**

Currently it is only possible to pass a stringified JSON to the `--payload` option of `ntl functions:invoke`. The webhooks of the merchant of record Paddle use urlencoded data in their payload - eg.: `firstname=simon&lastname=somebody`.

**Describe the solution you'd like**

Make it possible to simply pass a string to `--payload`. Maybe add a small warning in the console that it is not a JSON object.

**Describe alternatives you've considered**

Add a second option `--payload-unchecked` which doesn't parse the string in the background and simply passes the information to the function which should be invoked.

**Can you submit a pull request?**

Yes.

**Comment by erezrokah** [comment]
Hi @simonmulser, please see my comment https://github.com/netlify/cli/issues/1543#issuecomment-724168222
