### ISSUE TITLE
Announcement: Dropping support for Node.js 8

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#1568]
As Node.js 8 is out of the [maintenance window](https://nodejs.org/en/about/releases/) we should drop support for it and require Node.js 10.
This will allow us to upgrade [a bunch of packages](https://github.com/netlify/cli/blob/d09fa45874839ee4bb2a69ef9aa7e2249a68ddbe/renovate.json5#L13) and drop others we are using due to missing featured in Node.js 8.

### What to expect from this change
- It will be done behind a major version bump
- `package.json` [`engines` field](https://github.com/netlify/cli/blob/d09fa45874839ee4bb2a69ef9aa7e2249a68ddbe/package.json#L14) will be updated accordingly

### Potential breakage
- If you're installing the latest version of the CLI in CI that is running Node.js 8 (e.g. running `npm install -g netlify-cli` inside a GitHub action), that CI job will probably error out (the nature of the error depends on the package manager you're using and the settings passed to it). We recommend to either use a specific version range or update the CI Node.js version to  Node.js 10 or greater.
- If you're installing the CLI locally in a Node.js 8 environment you should get a relevant warning/error message saying the CLI is meant to be used on Node.js 10 or greater.

**If you're already running Node.js 10 or greater no change is needed on your part**

**Comment by ehmicky** [comment]
Once the CLI drops support for Node 8, should we also drop support for Node 8 in the `js-client` and `zip-it-and-ship-it`?

The biggest backward compatibility problem we've got are production builds which set a custom Node version. Those builds require the build command and some plugins to use that version. However, `zip-it-and-ship-it` is used as a core command, i.e. it is not impacted by this. `js-client` is not impacted either.

**Comment by erezrokah** [comment]
Sounds good to me as long as we follow `semver`. I think some customers are using `js-client` directly
