### ISSUE TITLE
Version 2.68.7 with netlify-lambda breaks functions

### ISSUE THREAD

**Issue by kmiyashiro** [netlify/cli#1577]
**Describe the bug**

netlify-lambda fails to build functions during build because the functions do not have `name` in their metadata. `@netlify/zip-it-and-ship-it` is currently set to `^1.3.9`, the fix is in [1.4.0](https://github.com/netlify/zip-it-and-ship-it/commit/5f36bd0761b4fc76593178e332ee2eefc58f63c6).

**To Reproduce**

1. Run `git clone https://github.com/kmiyashiro/netlify-functions-error`
2. Navigate to the cloned repository
3. Run `yarn`
4. Run `netlify dev`
5. See that the CLI exits with an error

**Configuration**

- If possible, please copy/paste below your `netlify.toml`.

```
[build]
  command = "yarn build"
  functions = "functions"
```

- Please enter the following command in a terminal and copy/paste its output:

```bash
npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
  System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 15.90 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmGlobalPackages:
    netlify-cli: 2.61.0
```

^ I use `yarn global add netlify-cli`, the actual version is 2.68.7:

```
➜  netlify-functions-bug git:(main) netlify --version
netlify-cli/2.68.7 darwin-x64 node-v14.9.0
 ›   Error: EEXIT: 0
 ›   Code: EEXIT
```

**Expected behavior**

Build functions successfully

**CLI Output**

```
➜  netlify-functions-bug netlify dev
◈ Netlify Dev ◈
◈ No app server detected and no "command" specified
◈ Using current working directory
◈ Unable to determine public folder to serve files from
◈ Setup a netlify.toml file with a [dev] section to specify your dev server settings.
◈ See docs at: https://cli.netlify.com/netlify-dev#project-detection
◈ Running static server from "netlify-functions-bug"
◈ Function builder netlify-lambda detected: Running npm script build:lambda
 ›   Warning: ◈ This is a beta feature, please give us feedback on how to improve at 
 ›   https://github.com/netlify/cli/
◈ Function builder netlify-lambda building functions from directory functions_src
◈ Function builder netlify-lambda finished building functions from directory functions_src
    TypeError: Cannot read property 'endsWith' of undefined
```

**Comment by ehmicky** [comment]
Hi @kmiyashiro,

`^1.3.9` should install `1.4.0` since it is within the `^` version range.

https://github.com/netlify/cli/blob/fc6b216ba59b7cd0aee8ad2716b95221e3857b85/package-lock.json#L1706-L1707

Could you try uninstalling `netlify-cli` and re-installing it again? This should help install the correct version of `@netlify/zip-it-and-ship-it`.

**Comment by kmiyashiro** [comment]
Yup, that did it. Not sure why the `netlify upgrade` didn't do it?

**Comment by ehmicky** [comment]
That's unfortunately how `npm` and `yarn` works. :-/
Happy this is solving your problem!
