### ISSUE TITLE
Q: Build and Deploy with one command

### ISSUE THREAD

**Issue by soongsta** [netlify/cli#1591]
**Is your feature request related to a problem? Please describe.**
Our build takes 25-30 minutes. It would be nice if the deploy could take place straight away if build is successful

**Describe the solution you'd like**
The ability to deploy immediately after a successful build 
Using a command for example `netlify build-deploy`, 
would build source and deploy
Or report build error.

**Comment by erezrokah** [comment]
Hi @soongsta this is available via `netlify deploy --build`, see docs under https://cli.netlify.com/commands/deploy.

Closing the question. Please comment if the suggestion doesn't solve your use case
