### ISSUE TITLE
FAUNADB_SERVER_SECRET injected without notice and with incorrect value

### ISSUE THREAD

**Issue by bdefore** [netlify/cli#1596]
I use a `FAUNADB_SERVER_SECRET` environment variable specified in both my Netlify site's environment variables as well as in an .env file. I run a React application using `npx --node-arg=--inspect netlify dev` to start Netlify Dev. When it starts up, no mention is made of `FAUNADB_SERVER_SECRET` even though other assignments are. When I log out the value of `FAUNADB_SERVER_SECRET` from a lambda that uses it, a value is output that does not match either the assignment in my site configuration or within my .env file. I was able to workaround the issue by creating a new environment variable in site configuration with a different name (`FAUNA_SECRET`) and was able to see the value reported as injected and that value was available in the lambda.

I'm uncertain if I used the 'addon' functionality of Netlify to integrate Fauna with my site. Currently when I use `netlify addons:list` it shows none are active. It's possible I removed it afterward, but I would still expect the value to propagate to Netlify Dev.

**To Reproduce**

I have not taken steps to reproduce. It's possible it would present if a new Netlify project added an addon and then removed it.

**Configuration**

```bash
→ npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
npx: installed 1 in 0.802s

  System:
    OS: Linux 5.8 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
    Memory: 3.58 GB / 15.56 GB
    Container: Yes
    Shell: 5.0.18 - /bin/bash
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
  npmGlobalPackages:
    netlify-cli: 2.69.0
```

**Expected behavior**

The value for `FAUNADB_SERVER_SECRET` to match what is in my .env file.
The value for `FAUNADB_SERVER_SECRET` to match what is in my site configuration if the assignment is removed from the .env file

```
→ yarn start
yarn run v1.22.10
$ npx --node-arg=--inspect netlify dev
Debugger listening on ws://127.0.0.1:9229/7f7439a7-91c1-4fd8-8d17-473572649403
For help, see: https://nodejs.org/en/docs/inspector
◈ Netlify Dev ◈
◈ Injected .env file env var: REACT_APP_DATA_HOST
◈ Injected .env file env var: REACT_APP_LAMBDA_HOST
◈ Injected .env file env var: SESSION_SECRET
◈ Injected build setting env var: REACT_APP_DELIGHTED_ID
◈ Injected build setting env var: GENERATE_SOURCEMAP
◈ Injected build setting env var: REACT_APP_GOOGLE_ANALYTICS_ID
◈ Function builder netlify-lambda detected: Running npm script build:lambda
 ›   Warning: ◈ This is a beta feature, please give us feedback on how to improve at https://github.com/netlify/cli/
◈ Function builder netlify-lambda building functions from directory ./webpack.lambda.config.js
^C

→ netlify --version
netlify-cli/2.69.0 linux-x64 node-v12.18.0

→ netlify addons:list
No addons currently installed for dcs-x52-profile-maker
> Run `netlify addons:create addon-namespace` to install an addon
```

**Comment by erezrokah** [comment]
Hi @bdefore, thank you for reporting this issue.
Is it possible the `FAUNADB_SERVER_SECRET` env variable is set at the shell level? The CLI will node override any process level envs (this matches `dotenv` behavior).

You can verify it by running `env | grep FAUNADB`.

**Comment by bdefore** [comment]
Thanks, indeed that was the issue. I'd mistakenly exported this variable in one of my dotfiles.

Perhaps Netlify Dev could alert the user if it detects a value is already assigned?

**Comment by erezrokah** [comment]
That's a good suggestion, open https://github.com/netlify/cli/issues/1598 for that
