### ISSUE TITLE
Feature: publish the CLI as a single file

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#1597]
**Is your feature request related to a problem? Please describe.**

Related to https://github.com/netlify/netlifyctl/issues/151, https://github.com/netlify/cli/pull/1521 and https://github.com/netlify/cli/pull/1522

**Describe the solution you'd like**

Publish the CLI as a single executable file under the repo releases

**Describe alternatives you've considered**

Keep using `npm install -g netlify-cli`

**Additional context**

Meant to address some of the concerns of users when migrating from https://github.com/netlify/netlifyctl to the CLI

**Can you submit a pull request?**

Yes

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
