### ISSUE TITLE
Redirect rewrites inconsistent between netlify dev and production

### ISSUE THREAD

**Issue by parkan** [netlify/cli#1605]
**Describe the bug**

Referencing [this netlify community post](https://community.netlify.com/t/querystringparameters-not-working-with-redirect-on-production/3828/15)

Redirects of the form:

```
/echo/:msg /.netlify/functions/echo?msg=:msg 200
```

will populate the queryString parameter `msg` in netlify dev, however they will not in production. While I prefer the netlify dev behavior, I was advised to open a bug here to change it for consistency.

**To Reproduce**

Set a redirect that uses parameter matching and rewrites them into the target URL. The value will be copied to the target query parameter.

**Configuration**
N/A

**Expected behavior**

Nothing should happen (value in target URL should be ignored)

**Additional context**

Of course, I would vastly prefer that one of these two things happened:
- The current netlify dev behavior worked in production
- (even better) any redirects containing path parameters populated the `pathParameters` property of the [APIGatewayEvent](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/trigger/api-gateway-proxy.d.ts#L72) as they do on AWS API Gateway

However, I was advised by the platform team that this probably won't happen, so I will need to add the path expressions to each function, which is brittle and not DRY, but nonetheless the CLI behavior should match production.

My guess is that whatever netlify dev uses as the proxy server does this automagically.

**Comment by robbiehudson** [comment]
Thanks for raising this bug @parkan. This just bit us when we deployed a new function to production. Very unexpected that the dev behaviour doesn't match production (and of course, trying to debug this was hard!).

**Comment by parkan** [comment]
@robbiehudson this definitely took a second to track down, I thought I was losing my mind! this is how I ended up tackling the issue (using pathParameters rather than queryParameters), using the excellent lambda-middleware: https://gist.github.com/parkan/f0b95f343e18aaadd1bb93b4ca67806d

**Comment by robbiehudson** [comment]
@parkan this is great, thank you (and much better than my `String.split` hack that I used to get it working).
