### ISSUE TITLE
CI/CD commands result in constant token authorisation

### ISSUE THREAD

**Issue by andrew-s** [netlify/cli#162]
I think that this is a bug because the current setup seemed to work in an earlier version (slightly different docs) - currently I'm getting;

```
$ netlify deploy --prod --dir /builds/app/dist
Logging into your Netlify account...
Opening https://app.netlify.com/authorize?response_type=ticket&ticket=xxx
---------------------------
Error: Unable to open browser automatically

Please open your browser & open the URL below to login:
https://app.netlify.com/authorize?response_type=ticket&ticket=xxx
---------------------------
```

Same thing happens if I do `netlify init` first. I have the following as environment variables;

```
NETLIFY_AUTH_TOKEN=xxx
NETLIFY_SITE_ID=xxx
```

If I do authorise it, it'll work just for that one session and then the next run of the pipeline will ask for authorisation again.

What are the correct set of commands or any further required environment variables?

Other information;

Docker image: node:8.12.0 
netlify-cli@2.1.2

Thanks!

**Comment by bcomnes** [comment]
You probably dont want to run `init` from a custom CI pipeline, since thats going to try to set up the CI hooks to run builds from webhooks in our CI environment.

Having those env vars, when set, should allow you to run a deploy.  

If its kicking off the login flow, then it means the process doesn't have access to those env vars, or they are not set.

**Comment by andrew-s** [comment]
Thanks @bcomnes - turns out "protected" env variables doesn't mean the same in GitLab as it does in BitBucket so when I `printenv`'d it was missing.

Thanks for pointing me in the right direction!

**Comment by bcomnes** [comment]
Great! Happy hacking 👍
