### ISSUE TITLE
Add Deploy Contexts to the CLI

### ISSUE THREAD

**Issue by zbruhnke** [netlify/cli#1633]
**Is your feature request related to a problem? Please describe.**

We're using trunk based development - for us that means most of our repos work off of one branch `main` and that all Merge Requests go into `main` but that only SOME of them get deployed to master - we create a [Release](https://docs.gitlab.com/ee/user/project/releases/) to do that (releases are widely supported in gitlab and github now) which we find to be easier because we can work off one main branch but have an easy log of every production deploy and its time.

With Netlify this workflow is fairly tough to use because of the branch based mentality. we LOVE the `netlify.toml` file and I'd really love to be able to trigger a build that would use the deploy context appropriately that we pass it.

Right now we can achieve this multiple ways but none of which seem ideal.

1. We can make multiple sites in Gitlab, but we have a limited number of sites to work off of. This would be confusing for devs to understand during onboarding and ultimately the biggest problem is that both of these sites would still see the `main` branch as a "production" context which means we're back at square one trying to figure out how to best combat the context issue.

2. We could build the site using some variation of `.env.staging`, `.env.production` etc. files and then just upload the already built deploy to netlify. This seems like the most likely answer but it also begs the question, why doesn't the CLI just handle contexts so I don't have to manage this some other way outside of netlify (which is infinitely frustrating)

**Describe the solution you'd like**

In an ideal world netlify would add deploy contexts to the CLI. This would allow us to push an `--alias` build that deployed using the `staging` context for instance instead of ALWAYS building with the production context as it does now.

What this would ultimately mean for us is the ability to have our CI trigger a build to the `main` branch in the `staging` context and it could live at a custom subdomain like `main.xxxx.yyyy.com` 

With that in an ideal state we could now focus on the production workflow where we could separately push a tag (read: Release) which would then trigger a netlify production build using the production context and allowing us to set the Release live as a production deploy.

This would effectively allow us to have all be "normal"benefits of what you get if you're using multiple branches without the headache of having to have a new Merge Request every time we want what's on staging to head to production (just push a tag (release) and go roll it out).

**Describe alternatives you've considered**

I've thought about doing this by either manually building on our CI and uploading the files causing us to move the variables (mostly non-sensitive URLs etc we use) into multiple files (one per env) and stop using the `netlify.toml` file altogether.

I've also thought about simply using multiple netlify sites with unique site IDs but that brings added complexity and confusion about which one is the "right" one when debugging something and the added confusion that both would still use the `production` context as we'd have to deploy them which seems both dangerous and a misuse of the intent of the product

**Additional context**

I know we're not the only ones with similar flows and I've seen various versions of requests like this one but none in particular to allow us to pass the build context to the netlify CLI. If we could do that and every single CLI deploy was not built soley with production context that would make a lot more sense.

bonus points if the CLI just recognized the contents of `netlify.toml` and used the correct contexts, only using prod when the `--prod` flag is passed as that was what I expected by default and what seems more intuitive.

**Can you submit a pull request?**

No, AFAICT this functionality is also not available in the API meaning the only way for builds to use netlify context is to be triggered via git which would only work if we used separate branches for staging vs prod.

OF NOTE: It could also work if you started recognizing `Releases` in both gitlab and github as a way to deploy to netlify.

**Comment by erezrokah** [comment]
Hi @zachleat thank you for opening this issue, can you please clarify the feature request (and update the title)?
Is the feature request for being able to run `netlify builld --context staging`? I believe this is supported.
`netlify deploy --alias staging` is also supported.

Can you help me figure out what's missing?

**Comment by zbruhnke** [comment]
ah OK well then apparently your support was wrong yesterday because this is what I was told when asking about every build being built with production ENV variables from `netlify.toml`

```
Regarding the `netlify deploy` command, these deploys bypass the buildbot environment, which means it also doesn't use 'contexts', so only your main build command will be used. As an alternative, you can run your build command separately before calling the netlify deploy command.
```

Are you saying that's incorrect and I can pass a ocmmand like this:

`netlify deploy --context branch-deploy --alias ${COMMIT_REF_SLUG} --build --message "Branch Deploy - ${CI_COMMIT_REF_SLUG}@${CI_COMMIT_SHORT_SHA}`

and it will build with the variables in our `netlify.toml` file for branch deploys as expected?

**Comment by erezrokah** [comment]
`netlify deploy` command doesn't read the `context` flag yet, but you should be able to run:

```
netlify build --context branch-deploy && netlify deploy --alias ${COMMIT_REF_SLUG} --message "Branch Deploy - ${CI_COMMIT_REF_SLUG}@${CI_COMMIT_SHORT_SHA}"
```

**Comment by zbruhnke** [comment]
OK got it - good to know I'll give that a go thanks

**Comment by erezrokah** [comment]
If that doesn't work, please share an example `netlify.toml` so I can make sure I'm not missing anything.

**Comment by zbruhnke** [comment]
looks like that does what we want - not clear why i'd need to build separately but at least I can build it with any context I want I suppose ¯\_(ツ)_/¯
