### ISSUE TITLE
react sanely to errors

### ISSUE THREAD

**Issue by fool** [netlify/cli#17]
When we show an error that bubbles up from the OS, we often stop dead.  Instead, we should:

1. wait a few seconds, and retry in case the error could be transient (eg: ECONNRESET or ECONNREFUSED)

2. provide some explanation if the error is something we understand (eg: ENFILE should provide a link to how ulimit works so people can try increasing their # of file handles - something like http://unix.stackexchange.com/questions/108174/how-to-persist-ulimit-settings-in-osx-mavericks, or at least explain that the deploy has too many files for the current OS configuration)

**Comment by bcomnes** [comment]
I agree with this in general, but there isn't a single switch we can throw to solve it.  Closing in favor of when this comes up specifically, and we can commit to reacting more sanely in those cases.
