### ISSUE TITLE
MaxListenersExceededWarning showing everytime I call a function

### ISSUE THREAD

**Issue by michalhudecek** [netlify/cli#1701]
**Describe the bug**

Everytime I call a function I get hundreds of lines saying MaxListenersExceededWarning which makes debugging impossible because console.logs are completely buried. It was supposed to be fixed by https://github.com/netlify/cli/issues/717 but it is not.

<img width="653" alt="console" src="https://user-images.githubusercontent.com/1215304/103894077-ac6a0580-50ee-11eb-9433-813e2f0e5f7d.png">

 

**To Reproduce**

1. Run `netlify dev`
2. Call any lambda function with console.log()
3. Console.log() is not visible as the whole terminal is filled with MaxListenersExceededWarning 

**Configuration**

My netlify.toml

```
[build]
  functions = "lambda"
  publish = "dist"
  command = "npm run build && npm run build:lambda"

[[headers]]
  for = "/*"
  [headers.values]
    #  Multi-value headers are expressed with multi-line strings
	  cache-control = '''
    private,
	  max-age=3600'''
```

npx output

```
npx: installed 1 in 1.465s

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 4.41 GB / 15.60 GB
  Binaries:
    Node: 12.20.0 - C:\Program Files\nodejs\node.EXE     
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD  
```

I am using `netlify-cli/2.70.0 win32-x64 node-v12.20.0`

**Expected behavior**

There should be no warnings about memory leak

**Comment by michalhudecek** [comment]
Is anyone looking into this? It makes any kind of debugging impossible especially when netlify-lambda doesn't generate sourcemaps that would allow proper debugging in VS Code.

**Comment by erezrokah** [comment]
Hi @michalhudecek sorry for the delay. Do you mind sharing a repo reproducing this issue?
I can't reproduce it by adding `console.log` to a function, so this might be related `netlify-lambda` or something more specific.

**Comment by michalhudecek** [comment]
I cannot share the repo. Yes, it is connected to netlify lambda. Is there anything else beyond the repo itself that would help you? Some kind of log?

**Comment by erezrokah** [comment]
Hi @michalhudecek, maybe share the function's code and `netlify-labmda` setup? An example repo (doesn't have to be your repo, just any public repo with the issue) will help figure out the underlying issue much faster.

**Comment by michalhudecek** [comment]
@erezrokah What do you mean by netlify-lambda setup? I have only netlify.toml file I already posted in the description of the issue. I didn't set up anything else. I just run `netlify dev` and the functions are automatically build. I also posted npx output in the description.

We have around 15 netlify lambda functions of various complexity, all of them has the same issue. This is an example of a simple function that generates hundreds of memory leaks in the console. It does the same on Windows, Mac and Linux. All of our programmers have the same issue.

```
/* eslint-disable no-console */
import axios from "axios";
import { getIndexId } from "./constants/index";
import { getViewsPayload } from "./functions/index";

const elasticHost = process.env.ELASTIC_HOST;
const elasticUser = process.env.ELASTIC_USER;
const elasticPassword = process.env.ELASTIC_PASSWORD;

import * as Sentry from "@sentry/node";
const { initSentry } = require("./functions/sentry.js");
initSentry();

exports.handler = async (event, context) => {
  const docId = event.queryStringParameters["id"];

  const url = new URL(event.headers.referer);
  let indexId = event.queryStringParameters["index"];
  if (indexId !== "sellers") {
    indexId = getIndexId(url.hostname, indexId);
  }

  Sentry.configureScope(scope => {
    scope.setLevel("error");
    scope.setTag("endpoint", "doc");
    scope.setExtra("docId", docId);
    scope.setExtra("index", indexId);
    scope.setExtra("httpMethod", event.httpMethod);
  });

  let responseData;
  try {
    const elasticResponse = await axios.get(
      `${elasticHost}/${indexId}/_doc/${docId}`,
      {
        auth: {
          username: elasticUser,
          password: elasticPassword
        },
        headers: {
          "Content-Type": "application/json"
        }
      }
    );
    responseData = { ...elasticResponse.data };
    // Remove restricted data
    delete responseData._source.restrictedData;
  } catch (error) {
    console.log(error);
    Sentry.captureMessage(error);
    return {
      statusCode: 400,
      body: JSON.stringify(error)
    };
  }
  try {
    const payload = getViewsPayload(url, responseData._source);
    await axios.post(`${elasticHost}/${indexId}/_update/${docId}`, payload, {
      auth: {
        username: elasticUser,
        password: elasticPassword
      },
      headers: {
        "Content-Type": "application/json"
      }
    });
  } catch (error) {
    Sentry.captureMessage(error);
    return {
      statusCode: 400,
      body: JSON.stringify(error)
    };
  }
  return {
    statusCode: 200,
    headers: {
      "content-type": "application/json; charset=utf-8"
    },
    body: JSON.stringify(responseData)
  };
};
```

**Comment by erezrokah** [comment]
Hi @michalhudecek and sorry for the delay to respond. I tried reproducing this issue in https://github.com/erezrokah/netlify-build-reproductions/blob/cli/issue_1701/functions/index.js#L15 by using your function as a reference and adding the missing env variables per the best of my ability.

I tried sending a request to the function and wasn't able to get the same error, so I'm probably missing a lot of the configuration you have.

Providing a public repo with a reproduction will make it much easier to debug and identify the cause.
For debugging in VSCode does the suggestion [here](https://github.com/netlify/netlify-lambda/issues/262#issuecomment-761172036) work for you?
Also you should be able to generate source maps by using a [custom webpack config](https://github.com/netlify/netlify-lambda#webpack-configuration).

**Comment by michalhudecek** [comment]
Hi @erezrokah. I am not sure what could be causing it. Unfortunately, I cannot share it publicly. I could maybe share it in a call.

None of the mentioned suggestions worked for me. I just run `netlify dev`, nothing else. I have no influence on how `netlify-lambda` is called from there.

**Comment by erezrokah** [comment]
Hi @michalhudecek, to clarify - I'm not asking you to share private code.

I'm suggesting you create a public repo reproducing the issue per our [issue reporting guidelines](https://github.com/netlify/cli/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md&title=Please+replace+with+a+clear+and+descriptive+title).

The purpose of doing that is that we can reproduce the issue in **our environment** and also if anyone else is experiencing is they can contribute.

**Comment by michalhudecek** [comment]
After running `netlify dev --inspect` I found out that the errors are coming from sentry/node package

I reported the issue to Sentry https://github.com/getsentry/sentry-javascript/issues/3247, closing this issue here.

**Comment by erezrokah** [comment]
Thank you for the follow up @michalhudecek!

**Comment by michalhudecek** [comment]
It was actually a bug in netlify-cli after all. Got fixed by upgrading to https://github.com/netlify/cli/releases/tag/v5.2.0
