### ISSUE TITLE
Netlify Function Builder Detector for netlify-lambda can detect wrong functions source folder

### ISSUE THREAD

**Issue by Robin-Hoodie** [netlify/cli#1726]
**Describe the bug**

Having an NPM script which uses `netlify-lambda` and options that come **after** the functions source folder will incorrectly detect the option as the function source.

**To Reproduce**

1. Set up a new Netlify repo with `netlify-lambda` as a dependency
2. Add an NPM script, e.g. `functions:build` that runs netlify `netlify-lambda build` and passes an argument **after** specifying the functions source folder, e.g. `netlify-lambda build functions/src -c ./functions/webpack.config.js`
3. Run `netlify dev`, which will pick up the `functions:build` script
4. Notice that Netlify Dev logs "building functions from directory **./functions/webpack.config.js**"
5. Changes in the function source won't be picked up either, only changes to `./functions/webpack.config.js`

**Expected behavior**

The functions source directory should be able to be detected regardless of which spot any options passed to `netlify-lambda` are passed

**Additional context**

As `netlify-lambda build` allows any options to be placed either before or after the functions source folder itself, that should also work when used together with Netlify Dev.

The problem should be quite easily fixed by modifying the regex used here 
https://github.com/netlify/cli/blob/305f8f4a92e030384dc58ae9d572a611880a7b7d/src/function-builder-detectors/netlify-lambda.js#L16

Happy to take a look at the regex and open a PR, just give me a shout

**Comment by erezrokah** [comment]
Thanks @Robin-Hoodie, we would love a contribution for this.
It would be probably be best to use a library to parse the arguments.
`netlify-lambda` uses [commander](https://github.com/netlify/netlify-lambda/blob/710819bb1d5b2382dccd0d066d1dc934943d0016/bin/cmd.js#L7). The CLI uses `oclif` but also has [minimist](https://github.com/netlify/cli/blob/305f8f4a92e030384dc58ae9d572a611880a7b7d/package.json#L135) as a dependency.

**Comment by Robin-Hoodie** [comment]
I've developed a fix for this, though while I was adding tests, it actually seems like the current code was intentionally written with scenarios in mind where no functions folder was provided [which you can see in this test](https://github.com/netlify/cli/blob/305f8f4a92e030384dc58ae9d572a611880a7b7d/src/function-builder-detectors/tests/netlify-lambda.test.js#L109) 

Is this something we want to keep support for? I can't imagine where it would be useful to run `netlify-lambda build` on a webpack config file?

**Comment by erezrokah** [comment]
> Just tried running `netlify-lambda build -c ./functions/webpack.config.js`
> Which results in `error: missing required argument 'dir'`
> 
> I assume I can safely remove support (and the test) for this?

Thanks @Robin-Hoodie, it would be great to get this fixed.

I believe the test's purpose is to explain the limitations of the current implementation. We can remove it or change the code to print a warning in that case (and change the test accordingly).
