### ISSUE TITLE
netlify dev -t strips port number from URL when applying a redirection from a rule (traffic-mesh-agent v0.27.8)

### ISSUE THREAD

**Issue by nonAlgebraic** [netlify/cli#1744]
**Describe the bug**
Since the release of @netlify/traffic-mesh-agent v0.27.8, which resolved an earlier issue I opened, running `netlify dev` with the `-t` flag when there are redirection rules configured in `netlify.toml` causes the redirections that occur to strip the port number from the destination URL, leading to a "connection refused" error since the `netlify dev` server is listening on the port that was stripped out.

**To Reproduce**

1. Clone this minimal repro - https://github.com/nonAlgebraic/netlify-cli-redirect-port-bug-repro
2. run `yarn install`
3. Run `yarn run netlify dev -t`
4. Click the link on the page that opens
5. Observe that the redirection from /some-nonexistent-page is to http://localhost/index.html, instead of http://localhost:9090/index.html, which is the URL of the origin where the link was clicked and indeed the port on which the `netlify dev` server is listening. If you run `netlify dev` without the `-t` flag, the problem goes away.

**Configuration**

`netlify.toml`:
```TOML
[dev]
  command = "yarn start"
  framework = "#custom"
  publish = "public"
  targetPort = 8080
  port = 9090

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 301
```
Output of `envinfo`:
```bash
System:
  OS: macOS 11.1
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Memory: 72.89 MB / 16.00 GB
  Shell: 3.2.57 - /bin/bash
Binaries:
  Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
  Yarn: 1.22.10 - ~/projects/netlify-cli-function-post-bug-repro/node_modules/.bin/yarn
  npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Watchman: 4.9.0 - /usr/local/bin/watchman
npmPackages:
  netlify-cli: ^3.1.1 => 3.1.1 
```

**Expected behavior**

The redirection retains the entire host of the running server instance which includes a port number, instead of just the hostname.

**Note**

I know I've opened a whole bunch of issues relating to the `-t` flag in `netlify dev` in the last week or so. I hope these issues are more helpful than they are annoying, and I'm **very** grateful for your work and responsiveness in addressing the bugs! Truly!

**Comment by calavera** [comment]
> I know I've opened a whole bunch of issues relating to the `-t` flag in `netlify dev` in the last week or so. I hope these issues are more helpful than they are annoying, and I'm **very** grateful for your work and responsiveness in addressing the bugs! Truly!

@nonAlgebraic these issues are super helpful! I really appreciate your help and patience with this.

I'm trying to reproduce your problem, but I'm not having much success with your example, I get redirected to the host with port. Do you mind running the server again with the `--debug` flag and updating the log file in that repository? I can read though it to investigate.

```
curl -vv -L --compressed http://localhost:9090/foo                                                                          
*   Trying 127.0.0.1:9090...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9090 (#0)
> GET /foo HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.68.0
> Accept: */*
> Accept-Encoding: deflate, gzip, br
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< content-length: 0
< location: http://localhost:9090/index.html
< date: Tue, 19 Jan 2021 19:26:54 GMT
< 
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://localhost:9090/index.html'
* Found bundle for host localhost: 0x56357264f7f0 [serially]
* Can not multiplex, even if we wanted to!
* Re-using existing connection! (#0) with host localhost
```

**Comment by nonAlgebraic** [comment]
@calavera  done! logs pushed.

Here's my `curl` btw:
```bash
curl -vv -L --compressed http://localhost:9090/foo
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 9090 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9090 (#0)
> GET /foo HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.64.1
> Accept: */*
> Accept-Encoding: deflate, gzip
> 
< HTTP/1.1 301 Moved Permanently
< content-length: 0
< location: http://localhost/index.html
< date: Tue, 19 Jan 2021 19:39:33 GMT
< 
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://localhost/index.html'
* Found bundle for host localhost: 0x7fbaf7417df0 [can pipeline]
* Could pipeline, but not asked to!
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 80 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connection failed
* connect to 127.0.0.1 port 80 failed: Connection refused
* Failed to connect to localhost port 80: Connection refused
* Closing connection 1
curl: (7) Failed to connect to localhost port 80: Connection refused
* Closing connection 0

**Comment by nonAlgebraic** [comment]
@calavera  happy to run any test or try any change you have in mind! I'm VERY excited to start using `netlify dev -t` as soon as we can so anything I can help/support to push that forward I'm very much on board with.

**Comment by calavera** [comment]
@nonAlgebraic I wonder if the problem is that your version of the cli is `^3.1`. I just checked and yarn downloaded `3.2` for me in your repository:

![image](https://user-images.githubusercontent.com/1050/105095120-20df6580-5a5a-11eb-946b-708739fef26c.png)

**Comment by nonAlgebraic** [comment]
@calavera I'm running 3.2.3. The envinfo output in the Issue description is from several days ago when I first opened it, so it's out-of-date - I've kept this repo up-to-date since opening the issue whenever new version of the packages were published.

![Screen Shot 2021-01-19 at 4 33 29 PM](https://user-images.githubusercontent.com/12376495/105095820-2fd31180-5a74-11eb-9673-89e0a5615b49.png)

**Comment by nonAlgebraic** [comment]
@calavera just to be sure: you are running `netlify dev -t` when trying to reproduce what I experienced, not `netlify dev`, yes? The issueis specifically present when the `-t` flag is set, and is **not** present when it's not. Just confirming we're on the same page.

**Comment by calavera** [comment]
> @calavera just to be sure: you are running `netlify dev -t` when trying to reproduce what I experienced, not `netlify dev`, yes? The issueis specifically present when the `-t` flag is set, and is **not** present when it's not. Just confirming we're on the same page.

yes, that's indeed what I'm testing. I'll keep trying to reproduce it.

**Comment by calavera** [comment]
I got a reproduction case. I'll probably be able to fix it between today and tomorrow.
