### ISSUE TITLE
simple command to trigger build

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#175]
**- Do you want to request a *feature* or report a *bug*?**

feature

**- What is the current behavior?**

`netlify deploy` uploads stuff.

sometimes i just want to trigger deploy. maybe call it `netlify trigger`? optionally have it accept `netlify trigger deploy` just for fun?

this is needed so that we dont have to jump back to the web UI when demoing addons (or really anything else using CLI in future)

**Comment by sw-yx** [comment]
sometimes people may type `netlify deploy` when they actually mean to `netlify trigger` (i certainly would). might want to add a "you may want.." message in "netlify deploy" to minimize surprise/guide people to what they mean to do

**Comment by DavidWells** [comment]
Seems like this happens when you `git push`

Is this issue still relevant? 😃

**Comment by sw-yx** [comment]
what if i dont have any git changes but still want to rebuild for content reasons?

**Comment by DavidWells** [comment]
I see. So external content changes (like contentful)

Yeah makes sense. 

How does this command sound to you?

```
netlify deploy:trigger
// or
netlify deploy --trigger
```

This way we keep top level api smaller

**Comment by sw-yx** [comment]
i like the second option

**Comment by codex-zaydek** [comment]
Hey @sw-yx, I’m not understanding the nuance of a trigger versus a deploy?

Is there a way I can have Netlify simply ship the `build` folder from my GitHub instead of having them download my yarn project and build it everytime? (This is slower than desired because I’m using playwright — large binary — for e2e testing)

**Comment by codex-zaydek** [comment]
[This looks related](https://github.com/netlify/cli/issues/23) but I’m not sure the feature was added or not. 🤷‍♂️

**Comment by sw-yx** [comment]
sorry, no I don't think so. just have to re trigger in UI.

**Comment by joallard** [comment]
Clarifying the use case on this:

Given I have the local repo of a statically-generated site, and I want to re-trigger a build on Netlify.

Currently I have no way to do this with the CLI, and I need to go on the admin interface to do it.

**Comment by erquhart** [comment]
Fair to leave this open, even if we don’t yet have a path forward.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joallard** [comment]
Amazing reactivity guys! 🙏
