### ISSUE TITLE
Allow additional configuration of manual deploys

### ISSUE THREAD

**Issue by sam3d** [netlify/cli#177]
I apologise if this isn't the right place to post this, but I'd like to make a feature request.

---

When running the `netlify init --manual` process, certain options that would be useful to configure are not available. For example:

1. The CLI will attempt to parse the `origin` URL (which currently suffers from `https` parsing errors as per #78), and no other remote can be specified. Ideally, there would be an additional prompt that contains the default parsed `ssh` url, and _allows for a custom SSH URL to be specified_ should the user wish (this should also stipulate that the URL be of type SSH, and probably validate against a non-ssh URL).

2. The "Deploys from manual" in the web ui has a few things about it that aren't ideal. For example, that text that says "Manual" should be either be entirely user configurable (so they can, say, put `Custom Ops Repo` or `GitLab Personal Env`), or so that it uses all or part of the SSH git URL that's provided (such as `organisation/repo`, `personal-gitlab-instance.com:organisation/repo`, or `git@gl-instance.com:org/repo`, for example).

<img width="723" alt="screenshot 2018-11-08 at 01 28 16" src="https://user-images.githubusercontent.com/8385528/48171878-a4875e80-e2f5-11e8-9b6c-3550fbc183c0.png">

3. Also, the URL for clicking on the "manual" appears to take a weird form:

```
https://app.netlify.com/sites/{site_name}/{git_origin_url}
```

Thus making any visitation of that URL, of course, resolve to a `404`:

<img width="1115" alt="screenshot 2018-11-08 at 01 31 21" src="https://user-images.githubusercontent.com/8385528/48172002-0f389a00-e2f6-11e8-8644-e327e0176e2c.png">

This one I'm not entirely sure what the best way to resolve would be. Could be an option to set repository HTTPS URL, and if it isn't set then don't allow the hyperlink at all?

---

Also, for the sake of this issue, I've been focusing on the CLI. Is there anyway that any of these configuration options could make their way into the `netlify.toml` file? I personally believe "infrastructure as code" is an excellent practice, and so the more configuration that can take place in these files the better. Though, I totally understand that might not be the domain of this repo.

**Comment by bcomnes** [comment]
1. Fair, I see your PR ty!
2. Yes, agreed its not ideal.  Ill post back any details I find along the way.
3. Same ^^
4. netlify.toml: yes agreed, but CI hooks are stateful in that, they need to be configured and turned on.  Currently the config file is stateless, so we can't add a feature like that quite yet, although its on the radar.  Additionally, the config file is context scoped right now (what does it mean for a branch and master to point to two different CI systems?), and we haven't developed an all context site convention yet.  Anyway, I agree in principal, but there is no quick fix at the moment for this one.

**Comment by bcomnes** [comment]
I believe we fixed some of this with https://github.com/netlify/cli/pull/178. Noting here to break out any remaining issues into new ones.

**Comment by erezrokah** [comment]
Closing this as stale and resolved in https://github.com/netlify/cli/pull/1619.
If some of the issues still exist please open specific ones with a reproduction.
