### ISSUE TITLE
Improve site name suggestion flow

### ISSUE THREAD

**Issue by eduardoboucas** [netlify/cli#1772]
**Is your feature request related to a problem? Please describe.**

When creating a new site (e.g. via `ntl init`), CLI offers some friendly suggestions for site names, computed based on the user's personal details (slug, full name or email address, based on what is available).

If the user hits Return without filling in a name, then a _different_ site name, selected randomly, will be selected.

The output below illustrates this:

- CLI suggested the name `the-awesome-eduardo-boucas-site-b5941.netlify.app`
- I hit Return without filling in a site name
- CLI showed `undefined` in the field and proceeded to create a site with a different name: `agitated-hodgkin-cbf97e`.

<details>
<summary>CLI output</summary>

```
? Do you want to create a Netlify site without a git repository? Yes, create and deploy site manually
? Team: Eduardo Netlify
Choose a unique site name (e.g. the-awesome-eduardo-boucas-site-b5941.netlify.app) or leave it blank for a random name. You can update the site name later.
? Site name (optional): undefined

Site Created

Admin URL: https://app.netlify.com/sites/agitated-hodgkin-cbf97e
URL:       https://agitated-hodgkin-cbf97e.netlify.app
Site ID:   123456-789654-21234567
"agitated-hodgkin-cbf97e" site was created

To deploy to this site. Run your site build and then netlify deploy
```
</details>

**Describe the solution you'd like**

The behaviour above is technically correct and consistent with the instructions, but it feels a bit counter-intuitive. Currently, If I want to use the name that CLI suggests, I need to copy it from the message and paste it in the _Site name_ field, otherwise I will get a different, randomly-generated (and likely less relevant) name.

Instead, I would expect the suggested name to be used in case I hit Return without filling in a site name.

**Comment by tinfoil-knight** [comment]
@eduardoboucas Can I take this up?

**Comment by eduardoboucas** [comment]
> @eduardoboucas @erezrokah Can I take this up?

Absolutely!
