### ISSUE TITLE
Auth fails with "Failed retrieving user account: Unauthorized."

### ISSUE THREAD

**Issue by kaganjd** [netlify/cli#1787]
**Describe the bug**

We got two reports in the forum about this error when people upgraded to version 3.2.0 and then tried to run `netlify dev` or `netlify status`. The thread is here: https://community.netlify.com/t/failed-retrieving-user-account/30331

A similar error came up in an internal Slack thread, related to PR https://github.com/netlify/cli/pull/1722 in version 3.1.1- maybe same root cause?

**To Reproduce**

1. run `npm i -g netlify-cli` to upgrade to 3.2.0+
2. run `netlify dev`

**Expected behavior**

Auth succeeds.

**CLI Output**

`Failed retrieving user account: Unauthorized. Double-check your login status with 'netlify status' or contact support with details of your error.`

**Additional context**
There's a workaround described in the forum here: https://community.netlify.com/t/failed-retrieving-user-account/30331/3

**Comment by MayMeow** [comment]
I think this is same bug which I getting with 

```bash
netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
```

Error message
```
Failed retrieving addons for site <MY_SITE_ID>: Unauthorized. Double-check your login status with 'netlify status' or contact support with details of your error.
```

**Comment by dominiksipowicz** [comment]
This bug is even when netlify status` and `netlify login`

**Comment by eduardoboucas** [comment]
Hi! Can you please upgrade to version 3.4.3 and check if the issue persists? To do this, please run:

1. `npm i -g netlify-cli`
2. `ntl version` (check that it includes `netlify-cli/3.4.3`)
3. `ntl logout`
4. `ntl login` (this will open your Netlify dashboard in a browser and ask you to authorise CLI)

If you're still experiencing problems after doing this, please let me know.

Thanks!

**Comment by MayMeow** [comment]
@eduardoboucas yes but what about CI ? There i cant open browser to authenticate...

**Comment by eduardoboucas** [comment]
Closing. Please update the issue if the problem persists.
