### ISSUE TITLE
"Error: Not Found" on netlify deploy 

### ISSUE THREAD

**Issue by arunghosh** [netlify/cli#180]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
When I type `netlify deploy` it responding
```
→ netlify deploy           
 ›   Error: Not Found
``` 

**- If the current behavior is a bug, please provide the steps to reproduce.**
Type `netlify deploy` and execute

**- What is the expected behavior?**
The command should deploy the site

**- Please mention your node.js, and operating system version.**
netlify-cli/2.2.1 
Mac darwin-x64 
node-v10.12.0

**Comment by arunghosh** [comment]
No. I don't have `netlify.toml`.

**Comment by DavidWells** [comment]
Hey @arunghosh is the site linked locally?

A.k.a. have you run `netlify link` in the current working directory of your site?

**Comment by CanRau** [comment]
> No. I don't have `netlify.toml`.

For me it worked after adding one, `netlify link` would probably create one right?

**Comment by bcomnes** [comment]
> For me it worked after adding one, netlify link would probably create one right?
No, not yet.  I would like to expand `netlify.toml` maintenance/creation at some point though.  A netlify.toml isn't required.

**Comment by bcomnes** [comment]
If you are still having this issue, can you run:

```
DEBUG=* netlify deploy
```

And see if there is anything of question in the output?  

Running `netlify status` should give you information regarding the link state of the cwd.

**Comment by arunghosh** [comment]
Thank you all. The issue go resolved by linking to a new site. The issue was linking.

**Comment by bcomnes** [comment]
Thank you for the followup.  We will continue to improve that process with time.

**Comment by arunsathiya** [comment]
I have a similar issue and I have reported it here - https://github.com/netlify/cli/issues/213

**Comment by sdbondi** [comment]
`netlify deploy --site=[your site id]` should work too without needing to link.

**Comment by anthonylnt** [comment]
Otherwise look for `.netlify` folder and remove it as it could contain a previous site id

**Comment by ianauxly** [comment]
remove the `.netlify` folder, and run `netlify link` in your local repository. You will be prompted to add your `site ID` which is your 'API ID' in **Settings** > **General** > **Site Details** of Netlify dashboard.

**Comment by Jahongirhacking** [comment]
try `netlify unlink` and then `netlify init`
