### ISSUE TITLE
`netlify lm:install` crashes

### ISSUE THREAD

**Issue by naavis** [netlify/cli#1813]
**Describe the bug**

Runnning
`netlify lm:install`
results in a crash with the following output:
```
$ netlify lm:install
✔ Checking Git version [2.17.1]
✖ Checking Git LFS version
→ Check that Git LFS is installed in your system
Checking Git LFS filters
Installing Netlify's Git Credential Helper for Linux
Configuring Git to use Netlify's Git Credential Helper
Error: Check that Git LFS is installed in your system
at checkLFSVersion (/home/naavis/.local/share/netlify-cli/node_modules/netlify-lm-plugin/lib/requirements.js:38:15)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async Task.task (/home/naavis/.local/share/netlify-cli/node_modules/netlify-lm-plugin/lib/requirements.js:17:29) {
context: [Object: null prototype] {}
```
Despite the error message I have Git LFS installed and working.

**To Reproduce**

1. Run `npm install -g netlify-cli`
2. Run `netlify plugins:install netlify-lm-plugin`
3. Run `netlify lm:install`

**Configuration**

`npx envinfo` prints the following:

```
System:
    OS: Linux 4.15 KDE neon 5.19
    CPU: (4) x64 Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
    Memory: 489.86 MB / 7.49 GB
    Container: Yes
    Shell: 5.4.2 - /usr/bin/zsh
Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.4/bin/npm
    npmGlobalPackages:
        netlify-cli: 3.4.3
```

**Expected behavior**

The command should not crash, but it should install necessary tools and configurations necessary for using Netlify Large Media

**Comment by erezrokah** [comment]
Thanks @naavis, we're in the process of moving https://github.com/netlify/netlify-lm-plugin into the CLI repo, so I'll keep this issue in mind while doing so.
See https://github.com/netlify/cli/pull/1489.

Can you share the output of `git-lfs --version`? That's how we're checking that it's installed:
https://github.com/netlify/netlify-lm-plugin/blob/f129b0ccb90fefd2226cf1f468797f12708a2bf4/src/requirements.ts#L33

**Comment by naavis** [comment]
`git-lfs --version` returns the following error:
```
$ git-lfs --version
Error: unknown flag: --version
Sorry, no usage text found for "git-lfs"
```

However, running `git lfs version` returns this:
```
$ git lfs version
git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.3)
```

**Comment by erezrokah** [comment]
We require `2.5.1` see https://docs.netlify.com/large-media/requirements-and-limitations/#requirements. We should improve that error message though

**Comment by naavis** [comment]
Good point, seems like KDE Neon provides a pretty old version of Git and Git LFS. Thanks.
