### ISSUE TITLE
Paused publishing may block manual deploys

### ISSUE THREAD

**Issue by simplesteph** [netlify/cli#182]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
I run 
```
 netlify deploy --prod --dir build/html
Deploy path: /Users/stephanemaarek/projects/gitlab/kafka-offline-training-web/build/html
Deploying to live site URL...
✔ Finished hashing 48 files
✔ CDN requesting 0 files
✔ Finished uploading 0 assets
✔ Deploy is live!

Logs:              https://app.netlify.com/sites/quirky-kirch-2XXXeb/deploys/5c02619a67610c7e00a03c05
Unique Deploy URL: https://hidden--quirky-kirch-2XXXeb.netlify.com
Live URL:          https://quirky-kirch-2XXXeb.netlify.com
```

and I expect the site to be updated. It is updated for the unique deploy URL, but the live URL is still showing the previous version. 

I have to click on "publish deploy" from the website UI to make things work...
![image](https://user-images.githubusercontent.com/20851561/49327084-624fe680-f55c-11e8-8304-ea2b646b24e8.png)

Is that expected?

**Comment by simplesteph** [comment]
Closing as "Auto Publish" was disabled and that was probably the issue. It'd be great for the CLI to intercept such settings and not misguide users in the log output

**Comment by bcomnes** [comment]
Interesting, reopening to track.
