### ISSUE TITLE
Prompt the user for function directory on function:create

### ISSUE THREAD

**Issue by asavaritayal** [netlify/cli#1822]
**Is your feature request related to a problem? Please describe.**

Currently, if no directory is specified for functions, you get the error below. The user is required to go to the docs to learn how to configure the setting in netlify.toml.
```
mysite % netlify functions:create
◈ No functions folder specified in netlify.toml
```

**Describe the solution you'd like**

```
mysite % netlify functions:create
◈ functions folder not specified in netlify.toml
? Enter the path where your functions should live: netlify/functions
◈ netlify/functions folder not found, creating it...
? Pick a template 
...
```

- Hint text -  `netlify/functions`
- Once specified, auto-populate the path into `netlify.toml`

**Alternate solution**
Since we're actively doing the work to make `netlify/functions` the default functions directory, we could create it automatically if it doesn't exist and no path is specified in `netlify.toml`.

**Additional context**

This will also help with https://github.com/netlify/netlify-react-ui/issues/6943

## Success Metric
https://github.com/netlify/data/issues/1061

**Comment by rybit** [comment]
@tiffanosaurus, in talking with @asavaritayal & the team. Is this something that you can triage and see the level of effort.

**Comment by jacklyn-net** [comment]
@jacklyn-net Tagging myself in this item, since it could have docs impact.

**Comment by rybit** [comment]
tip @jacklyn-net ~ you can click subscribe in the right bar too if you just wanna follow 

![image](https://user-images.githubusercontent.com/406376/107686723-6c042700-6c5a-11eb-8689-40c9bde81b68.png)

**Comment by erezrokah** [comment]
This is the line to change https://github.com/netlify/cli/blob/85dbba50cb011c73c12afc03015018316eeb1f20/src/commands/functions/create.js#L203 and example API call to update the functions directory https://github.com/netlify/cli/blob/85dbba50cb011c73c12afc03015018316eeb1f20/src/utils/init/config-github.js#L213

**Comment by jacklyn-net** [comment]
@asavaritayal I'm not seeing any UI Copy in this item?

**Comment by asavaritayal** [comment]
@jacklyn-net  It's not UI, but the CLI output - 
```
◈ functions folder not specified in netlify.toml
? Enter the path where your functions should live: netlify/functions
◈ netlify/functions folder not found, creating it...
```

**Comment by jacklyn-net** [comment]
I see - this looks good to me. Thanks! Going to remove the label and reassign @tiffanosaurus

**Comment by erezrokah** [comment]
May I suggest we change it to `functions folder not specified in netlify.toml or UI settings` (or something similar to reflect that you can configure it via the UI too)?

**Comment by asavaritayal** [comment]
@erezrokah yes, that sounds good. 

Updated copy here - 
```
◈ functions folder not specified in netlify.toml or UI settings
? Enter the path where your functions should live: netlify/functions
◈ netlify/functions folder not found, creating it...
```

**Comment by tiffanosaurus** [comment]
Just double-checking, it's `netlify/functions`, not `.netlify/functions` right? I've seen it mentioned both ways. [O]fficial functions docs](https://docs.netlify.com/functions/configure-and-deploy/#configure-the-functions-folder) have it without the period prefix.

**Comment by asavaritayal** [comment]
Yes it's `netlify/functions`
