### ISSUE TITLE
Update appears to not work on WSL

### ISSUE THREAD

**Issue by SteveALee** [netlify/cli#1847]
**Describe the bug**

After updating netlify-cli on Windows WSL the report version is unchanged

[netlify-cli entry on npm](https://www.npmjs.com/package/netlify-cli) entry says 3.50 is latest.

but I still see 2.68.7 after I run `npm install netlify-cli -g` and it’s VERY slow to respond

**To Reproduce**

I’ve updated netlify-cli but the version appears to be wrong.

```
$node -v; npm -v; time netlify -v
v10.19.0
6.14.4
netlify-cli/2.68.7 wsl-x64 node-v10.19.0

   ╭──────────────────────────────────────╮
   │                                      │
   │   Update available 2.68.7 → 3.5.0    │
   │   Run npm i netlify-cli to update    │
   │                                      │
   ╰──────────────────────────────────────╯


real    0m10.366s
user    0m1.858s
sys     0m0.816s
```
I also tried uninstalling node / npm and re installing.

**Configuration**

Windows 10 latest fully patched + Ubuntu WSL

```bash
npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli

npx: installed 1 in 2.031s
  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 11.82 GB / 12.37 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  npmGlobalPackages:
    netlify-cli: 3.5.0
```

**Expected behavior**

The version should change to the latest and no delay

**CLI Output**

See above

**Comment by SteveALee** [comment]
whoah - this makes no sense

```bash
$ which netlify
/mnt/c/Users/steve/AppData/Roaming/npm/netlify
```

Despite installing netlify WSL it seems to be picking up the windows version but that should not execute at all!

```bash
echo $PATH
/home/wsl/.rbenv/shims:/home/wsl/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.Ubuntu20.04onWindows_2004.2020.812.0_x64__79rhkp1fndgsc:/mnt/c/Python38/Scripts/:/mnt/c/Python38/:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Program Files/Docker/Docker/Resources/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/Plantronics/Spokes3G/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/:/mnt/c/Program Files/Intel/WiFi/bin/:/mnt/c/Program Files/Common Files/Intel/WirelessCommon/:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Program Files/nodejs/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Git/cmd:/mnt/c/Ruby25-x64/bin:/mnt/c/Users/steve/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/steve/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Program Files (x86)/GitHub CLI/:/mnt/c/Users/steve/AppData/Roaming/npm:/mnt/c/Users/steve/AppData/Local/GitHubDesktop/bin:/snap/bin
```

**Comment by erezrokah** [comment]
Hi @SteveALee maybe [this issue](https://github.com/Microsoft/WSL/issues/3787) can help?

**Comment by SteveALee** [comment]
@erezrokah Good grief! yes. I do not have `/usr/lib/node_modules` at all in WSL, just the windows one on the path!. So it seems you cannot use node both in Windows (Git 4 windows) and WSL! Bizarre and really annoying!

**Comment by erezrokah** [comment]
Thank you for the follow up @SteveALee, that' very helpful to know.

**Comment by SteveALee** [comment]
So my solution for now is to never install netlify-cli globally. That is usually my practice as it means everything is available in the repo. But I made an exception here.

There is also a windows registry setting to stop windows files appearing on the WSL path which seems eminently sensible. You'd then need to add alias' for things like code though
