### ISSUE TITLE
Add function builder detector for Babel

### ISSUE THREAD

**Issue by Robin-Hoodie** [netlify/cli#1874]
**Is your feature request related to a problem? Please describe.**

I've created a project which uses Babel for compiling my functions source code. Currently I use Netlify Dev for local development of this function. As Netlify Dev only offers a function builder detector for netlify-lambda, I currently have to run my script which watches my source files and compiles them with `@babel/cli` on the side.

It would be awesome if this was not necessary and Netlify could automatically detect my Babel script as a function builder

**Describe the solution you'd like**

E.g. checking for  scripts that contain the `babel` command (with a `--watch` flag?)

**Describe alternatives you've considered**

To be clear, I can just run my babel scripts in a separate process, which is not that much of a hassle.

**Additional context**

As mentioned [in the docs under "Bring your own Function Builder"](https://cli.netlify.com/netlify-dev/), you'd encourage requests for adding function builder detectors.

**Can you submit a pull request?**

Yes, I could be part of setting this up

> Pull requests are welcome! If you would like to help us add this feature, please check our
> [contributions guidelines](../../CONTRIBUTING.md).

**Comment by erezrokah** [comment]
Hi @Robin-Hoodie, that sounds like a great idea, thank you for opening the issue.
I assume many people have some kind of `babel` setup in their project. Do you have some insights on how to scope it down only to Netlify functions bundling?

**Comment by Robin-Hoodie** [comment]
My initial idea would be to check for scripts in the following priority:

1) Contains `babel`, `--watch` and `--out-dir` where `--out-dir` is equal to the configured Netlify functions folder 
2) Same as the above, but without `--watch` and add `--watch` ourselves
3) Contains `--out-file` where the file's directory is the same as the configured Netlify functions folder
4) Same as the above, but without `--watch` and add `--watch` ourselves

Just thinking out loud here, WDYT?

**Comment by erezrokah** [comment]
Seems good to me, would look like to open a PR for it?

**Comment by Robin-Hoodie** [comment]
I can put in some work on this yes!

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
