### ISSUE TITLE
Runtime error when trying to push changes after running `netlify lm:setup`

### ISSUE THREAD

**Issue by naavis** [netlify/cli#1895]
**Describe the bug**

I am migrating my website from GitHub LFS to Netlify Large Media. Running `git push` after setting up Netlify Large Media shows the following error message:

```
panic: runtime error: slice bounds out of range [:6] with length 0

goroutine 1 [running]:
github.com/netlify/netlify-credential-helper/credentials.getCredentials(0xbdb040, 0xc000006010, 0xbdb080, 0xc000006018, 0xc0001945b0, 0xb2f1b8)
        /home/david/src/github.com/netlify/netlify-credential-helper/credentials/credentials.go:127 +0xd2e
github.com/netlify/netlify-credential-helper/credentials.handleCommand(0xc0000300f8, 0x3, 0xbdb040, 0xc000006010, 0xbdb080, 0xc000006018, 0xc0008618d0, 0xc0009dfe68)
        /home/david/src/github.com/netlify/netlify-credential-helper/credentials/credentials.go:66 +0x83
github.com/netlify/netlify-credential-helper/credentials.HandleCommand()
        /home/david/src/github.com/netlify/netlify-credential-helper/credentials/credentials.go:53 +0x310
main.main()
        /home/david/src/github.com/netlify/netlify-credential-helper/cmd/netlify-credential-helper/main.go:6 +0x27
```

The execution doesn't end though, and it waits for a username and then password with this prompt: `Username for 'https://<censored>.netlify.app':`. It does not accept my Netlify credentials (email and password).

It's also worth noting that the `/home/david` path mentioned in the error messages does not exist on my PC. I am running Windows 10.

**To Reproduce**

I followed these two guides:
- https://community.netlify.com/t/support-guide-are-there-extra-steps-required-when-moving-from-another-git-lfs-provider-to-netlify-large-media/852
- https://docs.netlify.com/large-media/setup/

1. Install latest version of Netlify CLI: `npm install -g netlify-cli`
2. Run `git lfs fetch origin --all` in a repo with Github LFS
3. Run `netlify lm:install`
4. Run `netlify lm:setup`
5. Run `git add .lfsconfig` to stage the generated Large Media config file
6. Run `git commit` to commit the change
7. Run `git push`
8. The error should appear

**Configuration**

Running `npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli` returns the following:
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 55.52 GB / 63.93 GB
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
```

Running `netlify lm:info` shows this:
```
  √ Checking Git version [2.30.0.windows.1]
  √ Checking Git LFS version [2.13.1]
  √ Checking Git LFS filters
  × Checking Netlify's Git Credentials version
    → Invalid Netlify's Git Credential version 0.1.9. Please update to version 0.1.10 or above by running 'ntl lm:install'
```

Curiously running `ntl lm:install` has no effect. The output of `netlify lm:info` stays the same.

**Comment by erezrokah** [comment]
Hi @naavis, thank you for opening this issue. Can you share your `netlify-cli` version by running `ntl --version`?
Also make sure to be on the latest one by running `npm install -g netlify-cli`.
Also can you try running `netlify lm:install --force` to see if that changes the results of `netlify lm:info`?

**Comment by naavis** [comment]
Netlify CLI version is: `netlify-cli/3.8.3 win32-x64 node-v14.15.3`, so the latest one.

Running `netlify lm:install --force` does not change the situation:
```
$ netlify lm:install --force
  √ Checking Git version [2.30.0.windows.1]
  √ Checking Git LFS version [2.13.1]
  √ Checking Git LFS filters
  √ Installing Netlify's Git Credential Helper for Windows
  √ Configuring Git to use Netlify's Git Credential Helper

$ netlify lm:info
  √ Checking Git version [2.30.0.windows.1]
  √ Checking Git LFS version [2.13.1]
  √ Checking Git LFS filters
  × Checking Netlify's Git Credentials version
    → Invalid Netlify's Git Credential version 0.1.9. Please update to version 0.1.10 or above by running 'ntl lm:install'
```

**Comment by erezrokah** [comment]
Thanks for verifying @naavis.
On windows the helper is installed under ` %USERPROFILE%\AppData\Roaming\netlify\Config\helper` (usually translates to `C:\Users\<user>\AppData\Roaming\netlify\Config\helper`).
Can you try deleting that directory manually and running `netlify lm:install` again?
The CLI should download the relevant version from https://github.com/netlify/netlify-credential-helper/releases/tag/v0.1.10 and extract it to that directory.

**Comment by naavis** [comment]
Unfortunately that didn't do the trick. The end result is the same.

But I did notice something strange. I downloaded the https://github.com/netlify/netlify-credential-helper/releases/download/v0.1.10/git-credential-netlify-windows-amd64.zip package and extracted `git-credential-netlify.exe`. The size of the exe file in bytes is exactly the same as the one in `%USERPROFILE%\AppData\Roaming\netlify\Config\helper\bin`, which makes me think it could be the same file. I tried replacing the existing exe with the one I downloaded and nothing changed. `netlify lm:install` still says I have 0.1.9 installed.

**Comment by naavis** [comment]
A-ha, I might have found a part of the problem. Outside the Git repository folder `netlify lm:info` shows the correct version of the Git Credential Helper. I will check if my repo node_modules folder has some older local version of it or something.

**Comment by naavis** [comment]
Okay, it turns out `%USERPROFILE%\.netlify\helper\bin` also had a copy of git-credential-netlify, and it was in my PATH, and taking precedence over the one in `%USERPROFILE%\.netlify\helper\bin`.

With the newer version I was able to push my changes to Git. Thanks for the help!

**Comment by erezrokah** [comment]
Thanks @naavis that's very helpful. I'll fix the CLI to remove any old versions from `%USERPROFILE%\.netlify\helper\bin` when installing to the new location. That should handle these cases automatically.
