### ISSUE TITLE
Progress bars

### ISSUE THREAD

**Issue by bcomnes** [netlify/cli#192]
It would be neat to have progress bars.  We probably need a couple:

- Hashing
- Uploading

Possible modules we could use:

- https://twitter.com/brian_d_vaughn/status/1066379661314187265?s=21

**Comment by casey** [comment]
This can probably be closed, since the CLI seems to have progress bars in spades. They're awesome, and I love the variety! Did you implement them yourself or use a library?

**Comment by erezrokah** [comment]
Also related to https://github.com/netlify/js-client/issues/157.
Closing as I believe we show progress during `netlify deploy`
