### ISSUE TITLE
Please replace with a clear and descriptive title

### ISSUE THREAD

**Issue by linuxandroid-xyz** [netlify/cli#1944]
arthur@Arthur:~/Desktop/project_chat_application-master/client$ netlify login Already logged in via netlify config on your machine

Run netlify status for account details

To see all available commands run: netlify help

arthur@Arthur:~/Desktop/project_chat_application-master/client$ netlify deploy › Error: Unauthorized arthur@Arthur:~/Desktop/project_chat_application-master/client$ sudo netlify deploy [sudo] password for arthur: Logging into your Netlify account... Opening https://app.netlify.com/authorize?response_type=ticket&ticket=9fbf4c6e0b3fa4f2a309388c98093a22 FetchError: request to https://api.netlify.com/api/v1/oauth/tickets/9fbf4c6e0b3fa4f2a309388c98093a22 failed, reason: socket hang up Code: ECONNRESET arthur@Arthur:~/Desktop/project_chat_application-master/client$ sudo netlify deploy Logging into your Netlify account... Opening https://app.netlify.com/authorize?response_type=ticket&ticket=ab5dd6a6f6d269592fa98743ab32228a FetchError: request to https://api.netlify.com/api/v1/oauth/tickets/ab5dd6a6f6d269592fa98743ab32228a failed, reason: Client network socket disconnected before secure TLS connection was established Code: ECONNRESET arthur@Arthur:~/Desktop/project_chat_application-master/client$ netlify deploy --auth=swWF-o8-tps0FS4CC2XpZiMeC8iOp0edU33GBRLR6iM › Error: Unauthorized arthur@Arthur:~/Desktop/project_chat_application-master/client$ sudo netlify deploy --auth=swWF-o8-tps0FS4CC2XpZiMeC8iOp0edU33GBRLR6iM › Error: Unauthorized arthur@Arthur:~/Desktop/project_chat_application-master/client$ sudo netlify deploy Logging into your Netlify account... Opening https://app.netlify.com/authorize?response_type=ticket&ticket=43a32066e757b23b7d8e606a93899572 › Error: Timed out waiting for authorization. If you do not have a Netlify account, please create one at https://app.netlify.com/signup, then run netlify login again. arthur@Arthur:~/Desktop/project_chat_application-master/client$ netlify status ──────────────────────┐ Current Netlify User │ ──────────────────────┘ Name: Arthur Email: cnspecialcolor@gmail.com Teams: Arthur's team: Collaborator arthur@Arthur:~/Desktop/project_chat_application-master/client$ netlify help

**Comment by linuxandroid-xyz** [comment]
netlify CLI deployment error: error Unauthorized

**Comment by erezrokah** [comment]
Hi @linuxandroid-xyz, can you update the title of the issue to describe the problem you're experiencing?

Also can you try `ntl logout`, then `ntl login`?
