### ISSUE TITLE
Implement Gitlab Configurator

### ISSUE THREAD

**Issue by bcomnes** [netlify/cli#195]
We need a Gitlab configurator.  Ideally it would use an API based on discussed in https://github.com/netlify/cli/issues/194

**Comment by bcomnes** [comment]
Related https://github.com/netlify/cli-utils/issues/2

**Comment by erezrokah** [comment]
Related https://github.com/netlify/cli/issues/344

**Comment by erezrokah** [comment]
Closing in favour of https://github.com/netlify/cli/issues/549
