### ISSUE TITLE
CLI can't make a functions folder more than one level deep

### ISSUE THREAD

**Issue by cfjedimaster** [netlify/cli#1957]
**Describe the bug**

I specified `netlify/functions` as my functions folder in `netlify.toml`. When the CLI tried to create it, it failed:

```
ray:~/projects/tempfornetlify$ ntl functions:create test1
◈ functions folder /home/ray/projects/tempfornetlify/netlify/functions specified in netlify.toml but folder not found, creating it...
    Error: ENOENT: no such file or directory, mkdir '/home/ray/projects/tempfornetlify/netlify/functions'
    Code: ENOENT
```

I assumed because it was multiple levels deep. I created `netlify` as a subdirectory, ran it again and it made the `functions` folder.

**To Reproduce**

Specify a functions folder that is 2+ levels deep and does not exist.

**Expected behavior**

It should intelligently create any folders "along the path" down to the end.

**Comment by erezrokah** [comment]
Closed via https://github.com/netlify/cli/pull/1996
