### ISSUE TITLE
Implement Bitbucket Configurator

### ISSUE THREAD

**Issue by bcomnes** [netlify/cli#196]
Ideally we use an API based configurator described in We need a Gitlab configurator.  Ideally it would use an API based on discussed in https://github.com/netlify/cli/issues/194 but we need this sooner than later.

**Comment by bcomnes** [comment]
Related https://github.com/netlify/cli-utils/issues/2

**Comment by erezrokah** [comment]
Closing in favour of https://github.com/netlify/cli/issues/549
