### ISSUE TITLE
Use prompts

### ISSUE THREAD

**Issue by bcomnes** [netlify/cli#198]
We should consider using

https://github.com/terkelg/promptsw

**Comment by BattulgaTS** [comment]
@bcomnes 
I'm not clear on this. Did you mean that specific feature "togglemessage-initial-active-inactive"?
Or change the package from Inquirer.js to Prompts 😀?

**Comment by bcomnes** [comment]
The hash was a mistake, I made this as a note to consider using prompts instead of inquirer.

**Comment by erezrokah** [comment]
Closing as stale. The link in the issue results in 404
