### ISSUE TITLE
netlify-cli: cannot start dev server locally

### ISSUE THREAD

**Issue by oanaOM** [netlify/cli#1989]
**Describe the bug**

The local server doesn't start when running `netlify dev`. It finishes with `"npm run build" exited with code 0. Shutting down Netlify Dev server` 

**To Reproduce**

1.  Run `netlify dev`
2. See that the CLI exits with an error. 

**Configuration**

-`netlify.toml`:
```[build]
  command = "npm install --prefix=functions && npm run build && npm run export"
  publish = "out"
  functions = "functions"
``` 
```iom@Oanas-MBP/V/O/Y/F/E/r/netlify-gocardless-subscription> npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli

  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 172.17 MB / 8.00 GB
    Shell: 3.1.2 - /usr/local/bin/fish
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /Volumes/OM/Yo/Fun/ExtraFun/react-playground/netlify-gocardless-subscription/node_modules/.bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  npmPackages:
    netlify-cli: ^3.10.11 => 3.10.11 
  npmGlobalPackages:
    netlify-cli: 3.10.11
```

**Expected behavior**

The local dev server should start running locally

**CLI Output**

I received the below output:
![image](https://user-images.githubusercontent.com/15228388/111036387-e0c3b000-8416-11eb-8806-797fb6d2814f.png)

**Comment by erezrokah** [comment]
Hi @oanaOM, I believe this is a somehow duplicate of https://github.com/netlify/cli/issues/1252 where the CLI picks up the build command instead of the dev command when detecting the framework.

Can you try adding the following to your `netlify.toml`

```toml
[dev]
  framework = "next"
  command = "npm run dev"
```

**Comment by oanaOM** [comment]
I get exactly the same output after adding `framework = "next"` in `netlify.toml `  file.

**Comment by erezrokah** [comment]
Hi @oanaOM can you share your `package.json` and full `netlify.toml` or even better a public repo reproducing the issue? Did you set the command under the `dev` block of `netlify.toml`?

**Comment by oanaOM** [comment]
Hi @erezrokah I give it another try by cloning my repo again and made the suggested changes to the `netlify.toml` file and this time it worked!! Thank you so much for you help!
