### ISSUE TITLE
Error TypeError: Cannot read property 'x-github-otp' of undefined

### ISSUE THREAD

**Issue by kamontat** [netlify/cli#199]
**- Do you want to request a *feature* or report a *bug*?** bug

**- What is the current behavior?**

```
TypeError: Cannot read property 'x-github-otp' of undefined
```

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. run `netlify init`
2. enter `Create & configure a new site`
3. choose name and account
4. enter Github username and password
5. ERROR

**- What is the expected behavior?**
prompt authentication

**- Please mention your node.js, and operating system version.**
```bash
$ node --version
v10.14.1
$ npm --version
6.4.1
$ yarn --version
1.12.3
$ sysinfo
OS: macOS Mojave 10.14.1 18B75 x86_64
Shell: zsh 5.6.2
Terminal: iTerm2
```

full error message:
```
 ›   Warning: Github error: undefined
TypeError: Cannot read property 'x-github-otp' of undefined
    at createGithubPAT (~/.config/yarn/global/node_modules/netlify-cli/src/utils/gh-auth.js:52:30)
```

**Comment by kamontat** [comment]
You have to change to `octokit.oauthAuthorizations.createAuthorization` 

ref: https://octokit.github.io/rest.js/#api-OauthAuthorizations-createAuthorization

**Comment by bcomnes** [comment]
Good catch.  Let me get a release out.

**Comment by kamontat** [comment]
I created a pull request @bcomnes
