### ISSUE TITLE
Error reporting currently in json

### ISSUE THREAD

**Issue by FranzSkuffka** [netlify/cli#2]

**Comment by biilmann** [comment]
True. We definitively need to improve the output for error messages.

**Comment by ajdavis** [comment]
For example, when auth times out due to bad network:
```
Error generating authorization ticket: [object Object]
```

**Comment by bcomnes** [comment]
We've tried to improve this in the upcoming 2.0.0 release, but unhandled errors will still be ugly.  If you find one, please open an issue.
