### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by axhamre** [netlify/cli#201]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Nothing relevant seems to be deployed.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Running `netlify deploy` + following promted steps.
2. Getting the following as result:

Site Created

Admin URL: https://app.netlify.com/sites/hubbois
URL:       https://hubbois.netlify.com
Site ID:   56585869-49aa-42ab-b463-08218c7e8f40
Please provide a deploy path relative to:
/Users/omonia/Documents/hubbois
? deploy path /Users/omonia/Documents/hubbois
Deploy path:        /Users/me/Documents/hubbois
Configuration path: /Users/me/Documents/hubbois/netlify.toml
Deploying to draft URL...
✔ Finished hashing 33 files
✔ CDN requesting 0 files
✔ Finished uploading 0 assets
✔ Draft deploy is live!

**- What is the expected behavior?**
Multiple issues:
a) My project has 51 files + all files in node_modules. The report states "33 files".
b) Deploying took approximately 2 seconds, and that is suspiciously way too fast. I'm on a slow internet connection and have a project size of 8 MB + node_modules.
c) The deploy tab in web UI says: "Deploy preview #null"
d) The command specified in the `netlify.toml`file isn't run.
e) When doing automatic deployment via Github (to a separate netlify "site"), the exact same project deploys successfully. 

**- Please mention your node.js, and operating system version.**
Node: v11.3.0
OS: OSX 10.12.6

**Comment by erezrokah** [comment]
Closing this as stale and resolved via https://github.com/netlify/cli/pull/1272.
If this still happens please comment with a reproduction.
