### ISSUE TITLE
`netlify login` connect ETIMEDOUT 35.201.69.186:443

### ISSUE THREAD

**Issue by kimmy-wang** [netlify/cli#2016]
```
ying@YingdeiMac github-trending-api % netlify login        
Logging into your Netlify account...
    FetchError: request to https://api.netlify.com/api/v1/oauth/tickets?client_id=d6f37de6614df7ae58664cfca524744d73807a377f5ee71f1a254f78412e3750 
    failed, reason: connect ETIMEDOUT 35.201.69.186:443
    Code: ETIMEDOUT
```

**Comment by erezrokah** [comment]
Hi @realkimmy, where are you trying to login from? We've had cases where our API IP address is blocked in some countries.
The solution is to use the CLI with a proxy configured, see https://github.com/netlify/cli/issues/170#issuecomment-667674965

**Comment by realkimmy** [comment]
@erezrokah Stuck here.
<img width="1021" alt="截屏2021-03-17 20 46 19" src="https://user-images.githubusercontent.com/19725091/111469788-10015680-8762-11eb-88f2-ed2386f15638.png">

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
