### ISSUE TITLE
feat: add a log message when we modify users `.gitignore`

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#2038]
**Is your feature request related to a problem? Please describe.**

See https://github.com/netlify/cli/issues/2029#issuecomment-803581401

Modifying users files without letting them know is not very nice. We should at least log that we're changing `.gitignore`

**Describe the solution you'd like**

When the CLI modifies `.gitignore` we should print a log message reflecting the change to the user

**Describe alternatives you've considered**

We could also prompt the user to approve/deny the change

**Can you submit a pull request?**

Yes

**Comment by ngonsoto** [comment]
Hi @erezrokah, I would like to work on this issue.
