### ISSUE TITLE
feature(command-status): add status:auth sub command

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#2040]
~~**Describe the bug**~~

~~This was introduced as a result of https://github.com/netlify/cli/pull/1999.~~

~~Prior to #1999 [the code to fail](https://github.com/netlify/cli/blob/624cc5f69b6e7eb3e9a3f0639a5b3298da0d98e6/src/commands/status/index.js#L60) if running outside a linked site was being ignored since we used to exit early if we didn’t find a `netlify.toml`.~~

~~**To Reproduce**~~

~~1. `npm install -g netlify-cli`~~
~~2. `netlify login`~~
~~3. `netlify status` from a directory not linked to a site~~
~~4. See that authentication information is printed, but then an error message to run `netlify link` is printed~~

~~**Expected behavior**~~

~~To be honest - not sure if this is a real bug as I could go either way. The confusion is because `ntl status` handles both authentication status and site information status~~

~~Perhaps we should have a `status:auth` subcommand~~

### Update

Changing this to a feature request to be able to print authentication status outside a linked directory without failing

**Comment by verythorough** [comment]
Hm, yeah, that behavior feels pretty normal to me. I suppose there could be some value in having the `status:auth` command that _only_ checks auth, but I'm not sure there's enough demand to justify the effort.

Perhaps we wait and see if we get any other requests for this?

**Comment by erezrokah** [comment]
Thanks @verythorough I updated the title and description

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
