### ISSUE TITLE
[Question] Could we duplicate the `netlify dev` session?

### ISSUE THREAD

**Issue by kobaji** [netlify/cli#2048]
Hi there,

I am wondering if I can duplicate the `netlify dev` session.
If you knew any solutions and kindly told me, I would be very grateful.
N.B.
I would like to resolve without generating another VM.

## What I'd Like to Achieve

Editing a website src at the same time

## What I've Tried and The Result

1. Access to 1 VM (e.g. `172.16.4.0`), which renders one website
2. Duplicate the session: session1 and session2 (therefore in both sessions, IPs are the same with `172.16.4.0`)
3. In session1, fix something in the website
4. In session1, execute `netlify dev` (what fixed is rendered)
5. In session2, fix something in the website which is different from the fix in session1
6. In session2, execute `netlify dev`
7. (Result) what fixed in session1 is rendered, not session2

## What I've tried reading

https://github.com/netlify/cli/blob/master/docs/netlify-dev.md but I could be misunderstanding this document.

**Comment by kobaji** [comment]
Simply my question seems to be the following:

In https://github.com/netlify/cli/blob/master/docs/netlify-dev.md , and in one VM, only 1 Netlify Dev and only 1 Browser are acceptable, or many Netlify Dev and many Browsers are acceptable.
(I am focusing on where pointed with `**` )

```
                            ┌───────────────┐
                            │   Project     │
                            │               │
                            └localhost:5000─┘
                                    │
                                    │
       ┌──────────┐                 │
       │  Addons  ├────┐            ▼
       └──────────┘    │    ┌localhost:5000─┐     ┌──────────────┐
       ┌──────────┐    └───▶│               │     │              │
       │functions ├────────▶│    Netlify    │     │   Browser    │
       └──────────┘    ┌───▶│      Dev      │     │              │
       ┌──────────┐    │    │               │     │              │
       │_redirects│────┘    └**localhost:8888**─▶ **localhost:8888**┘
       └──────────┘
```

**Comment by erezrokah** [comment]
Hi @kobaji I'm not sure I understand the question.

Are you trying to run `netlify dev` twice from the same directory and expecting changes from the first run not to be reflected on the second run?

That won't work as `netlify dev` reads file from the directory you run it from (putting aside the need to prevent ports collision).

If you do want different "sessions" you'll need to clone the directory and configure ports per session via `netlify.toml` `[dev]` block

**Comment by kobaji** [comment]
Thank you so much @erezrokah for your kind help.
Your explanation is an answer I am looking for.

> Are you trying to run netlify dev twice from the same directory and expecting changes from the first run not to be reflected on the second run?

Yes I expected changes from the first run not to be reflected on the second run.

And the workaround you told was pretty helpful!!

Thank you again for your kindness.
