### ISSUE TITLE
`netlify dev` fails to start

### ISSUE THREAD

**Issue by KhalidH82** [netlify/cli#2057]
Hi, I’m trying to run netlify dev in my project so I can run serverless functions locally. I have the latest version of netlify-cli/3.13.9 darwin-x64 node-v15.10.0 running on my machine. The error I’m experiencing when running netlify dev from my cli is…

```
Netlify Dev could not verify that your framework server is responding to requests.

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘

error while proxying request: socket hang up
```

Then it opens up http://localhost:8888/ and is stuck in the reloading state infinitely.
My netlify.toml reads…

```
[build]
command = “yarn run build”
functions = “functions”
```

In addition in when running Netlify status Netlify user and site info are correct.
If I’m missing any information or steps please advise. Thanks in advance for your help!

**Comment by KhalidH82** [comment]
Hi @erezrokah Thanks for your quick response. My scripts section is the following

{
  "name": "*****",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "node-fetch": "^2.6.1",
    "node-sass": "^5.0.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-facebook-login": "^4.1.1",
    "react-google-login": "^5.2.2",
    "react-responsive-modal": "^6.0.1",
    "react-scripts": "4.0.3",
    "styled-components": "^5.2.1",
    "universal-cookie": "^4.0.4",
    "web-vitals": "^1.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

Unfortunately I cannot share a public repo, let me know if there is any other additional information I can provide. TY.

**Comment by erezrokah** [comment]
Thanks for the additional information. Can I assume you're using `create-react-app`? When you run `npm run start`, on which port the server starts?

**Comment by KhalidH82** [comment]
Hi, yes I'm using create-react-app, server runs on port 3000.

**Comment by KhalidH82** [comment]
@erezrokah Hi, I wanted to know if I could provide any more information on this or if there were any updates? TY.

**Comment by erezrokah** [comment]
Hi @KhalidH82, no progress yet. It's hard to figure this out without a reproduction scenario.
When you run `npm run start` can you access `http://localhost:3000`?

If that works, I think we'll need a way to reproduce this locally (a repo reproducing would be great - it doesn't have to be your private repo, just a public one with the same issue).

**Comment by KhalidH82** [comment]
Hi @erezrokah I've managed to get the dev server to run locally. I had to remove my .env file because I believe it was conflicting with the environment variables already set in Netlify UI. Thanks again, best!
