### ISSUE TITLE
Error: API Request rate limit surpassed for application

### ISSUE THREAD

**Issue by mispy** [netlify/cli#206]
I'm running into this problem:

```
✔ Finished hashing 10849 files
- CDN diffing files...
✔ CDN requesting 2218 files
- Uploading 2218 files
 ›   Error: API Request rate limit surpassed for application
```

That was the first deploy today, so it's not an issue of deploying too frequently. It seems that the CLI tool doesn't limit itself to match the API rate limits?

Environment:

```
owid@terra3:~$ /mnt/volume-nyc1-01/owid/mispytest-grapher-code//node_modules/.bin/netlify --version
netlify-cli/2.6.0 linux-x64 node-v10.14.2
```

**Comment by fool** [comment]
Thanks for the report, @mispy .  This is not unique to you, and our developers will be taking a look as soon as they can

**Comment by fool** [comment]
developing a list of customers to inform once we have a fix:

- https://app.intercom.io/a/apps/q245f50x/inbox/inbox/1479299/conversations/20320282682
- https://app.intercom.io/a/apps/q245f50x/inbox/inbox/search/conversations/20233263008
- https://app.intercom.io/a/apps/q245f50x/inbox/inbox/search/conversations/20148633045

**Comment by c0b41** [comment]
I have same problem, that's why i moved firebase for now

**Comment by fool** [comment]
Just an update - we have identified the problem and have a proposed solution that we'll implement soon.  For the meantime, you can successfully deploy with our old (still functional and supported) CLI netlifyctl:  https://github.com/netlify/netlifyctl

We'll report here when we have a fix.

**Comment by niklasravnsborg** [comment]
I also have the same problem:
<img width="737" alt="screenshot 2019-01-11 at 12 53 36" src="https://user-images.githubusercontent.com/6717303/51032340-efe11600-159f-11e9-8cb8-e9ba60e9d056.png">

Hope there is a fix soon.

**Comment by bcomnes** [comment]
Working on a fix for this now.

**Comment by bcomnes** [comment]
Issue is solved in master, expect a release tomorrow morning.

**Comment by bcomnes** [comment]
🎉`netlify-cli@2.6.2`🎉

Please give that version and shot and let me know how it goes.

**Comment by njam** [comment]
I have the same problem, with version 2.6.2:
```console
$ npm install -g netlify-cli
/usr/local/bin/ntl -> /usr/local/lib/node_modules/netlify-cli/bin/run
/usr/local/bin/netlify -> /usr/local/lib/node_modules/netlify-cli/bin/run
+ netlify-cli@2.6.2
added 292 packages from 167 contributors in 13.138s

$ netlify deploy --site=$NETLIFY_SITE --auth=$NETLIFY_AUTH_TOKEN --dir=dist/ --prod
Deploy path: /builds/denkmal/denkmal-website/dist
Deploying to live site URL...
- Hashing files...
✔ Finished hashing 748 files
- CDN diffing files...
✔ CDN requesting 718 files
- Uploading 721 files
 ›   Error: API Request rate limit surpassed for application
```

Second run succeeded with 202 files uploaded. So I guess the first run uploaded ~500 files before it errored.

**Comment by thomasjsn** [comment]
Same problem as before here as well; able to upload about 500 files at the time;

```
Deploy path: /home/hebron/uctrl-hugo/public
Deploying to live site URL...
✔ Finished hashing 3432 files
✔ CDN requesting 1855 files
🕑  (795/1856) Uploading img/parts/sized/ir-pir-sensor-qerk04-48.jpeg... ›   Error: Uploaded file /img/parts/sized/kapton-tape-gold-qerxy4-96.jpeg did not match deploy
➜  uctrl-hugo git:(master) ✗ netlify deploy --dir=public --prod
JSONHTTPError: Too Many Requests
    at NetlifyAPI.getCurrentUser (/usr/lib/node_modules/netlify-cli/node_modules/netlify/src/open-api/index.js:152:15)
➜  uctrl-hugo git:(master) ✗ netlify deploy --dir=public --prodDeploy path: /home/hebron/uctrl-hugo/public
Deploying to live site URL...
✔ Finished hashing 3432 files
✔ CDN requesting 1074 files
* (433/1075) Uploading img/parts/sized/ac-adapter-zgvz5q-96.jpeg... ›   Error: Uploaded file /img/parts/sized/air-pollution-sensor-r4dn8g-96.jpeg did not match deploy
- (433/1075) Uploading img/parts/sized/ac-adapter-zgvz5q-96.jpeg...%                                         
➜  uctrl-hugo git:(master) ✗ netlify deploy --dir=public --prod
JSONHTTPError: Too Many Requests
    at NetlifyAPI.getCurrentUser (/usr/lib/node_modules/netlify-cli/node_modules/netlify/src/open-api/index.js:152:15)

```

**Comment by RajaBellebon** [comment]
Same problem `using 2.6.3`

```
 $ netlify deploy --dir dist/ -a $NETLIFY_TOKEN -s $NETLIFY_SITE_ID --prod
  Deploy path: /opt/atlassian/pipelines/agent/build/website/dist
  Deploying to live site url...
  - Hashing files...
  ✔ Finished hashing 3105 files
  - CDN diffing files...
  ✔ CDN requesting 3075 files
  - Uploading 3075 files
  ›   Error: API Request rate limit surpassed for application
```

**Comment by bcomnes** [comment]
Reopening.  @thomasjsn that problem was fixed in `2.6.3` although it still sounds like there is an open issue.  I will investigate.

**Comment by bcomnes** [comment]
I think I identified the issue.  I'll work to get a fix out tomorrow.

**Comment by bcomnes** [comment]
Ok, releasing https://github.com/netlify/cli/issues/206 with a fix once it's green.

**Comment by bcomnes** [comment]
Give `netlify-cli@2.6.4` a shot.

**Comment by RajaBellebon** [comment]
@bcomnes just a question - why do we have to use node 8.10 >= ? any particular reason?

**Comment by bcomnes** [comment]
Oclif requires it: https://github.com/oclif/oclif/blob/master/package.json#L50

**Comment by bcomnes** [comment]
Use https://github.com/nodesource/distributions or https://github.com/creationix/nvm to get modern Node.js.

**Comment by bcomnes** [comment]
Rate limit was significantly increased, you should rarely see rate limits now.
