### ISSUE TITLE
Empty args assigned, this is an internal Netlify Dev bug, please report your settings and scripts so we can improve

### ISSUE THREAD

**Issue by pvinis** [netlify/cli#2067]
**Describe the bug**

I'm getting `Empty args assigned, this is an internal Netlify Dev bug, please report your settings and scripts so we can improve` on `netlify dev`, first try.

**To Reproduce**

1. Run `git clone git@github.com:pvinis/batler.git`
2. Navigate to the cloned repository
3. Run `netlify dev`
4. See that the CLI exits with an error

**Configuration**

- If possible, please copy/paste below your `netlify.toml`.
```
[build]
  functions = "./functions"
```

- Please enter the following command in a terminal and copy/paste its output:

```bash
npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
```

```

  System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.89 GB / 16.00 GB
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 14.13.1 - ~/.asdf/installs/nodejs/14.13.1/bin/node
    Yarn: 1.22.10 - ~/.asdf/shims/yarn
    npm: 6.14.8 - ~/.asdf/installs/nodejs/14.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman

```

**Expected behavior**

**CLI Output**

If applicable, add the CLI output to help explain your problem.

**Additional context**

**Comment by erezrokah** [comment]
Thanks @pvinis, we're in the process of refactoring the `netlify dev` logic, so I'll verify https://github.com/netlify/cli/pull/1704 solves this issue as well.

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
