### ISSUE TITLE
`package-lock.json` has wrong version

### ISSUE THREAD

**Issue by Xenonym** [netlify/cli#2082]
The [`package-lock.json` for `3.15.1`](https://raw.githubusercontent.com/netlify/cli/1c19f2faff386009eaec0b9247a6df01d7fbaa35/package-lock.json) seems to have the wrong version number:

```json5
{
  "name": "netlify-cli",
  "version": "3.15.1", // <-- This is correct, but...
[...]
  "packages": {
    "": {
      "name": "netlify-cli",
      "version": "3.15.0", // <- This is wrong
[...]
```

**Comment by erezrokah** [comment]
This is closed via https://github.com/googleapis/release-please/pull/887
