### ISSUE TITLE
Deployments failing with `TypeError: Cannot read property '0' of undefined`

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#2086]
**Describe the bug**

Deployment randomly throws with `TypeError: Cannot read property '0' of undefined`.

This happens on and off and is hard to pin down. If I had to guess I'd say about 1 in 15 this error occurs.

```
> site@0.1.0 draft /Users/xyz/abc/site
> netlify deploy --dir out

Deploy path:        /Users/xyz/abc/site/out
Configuration path: /Users/xyz/abc/site/netlify.toml
Deploying to draft URL...
✔ Finished hashing 246 files
✔ CDN requesting 77 files
 ›   Warning:
 ›   {}
 ›
    TypeError: Cannot read property '0' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! site@0.1.0 draft: `netlify deploy --dir out`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the site@0.1.0 draft script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**To Reproduce**

This is a non-deterministic bug and is tricky to reproduce. 

Running `netlify deploy` again after encountering the issue usually works. 

**Configuration**

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 456.26 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
    Yarn: 1.22.10 - ~/xyz/site/node_modules/.bin/yarn
    npm: 6.10.0 - ~/.nvm/versions/node/v12.7.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    netlify-cli: ^3.13.7 => 3.13.7
  npmGlobalPackages:
    netlify-cli: 3.13.4
```

**Expected behavior**

If this error occurs with the SDK automatically retry the deployment?

**Additional context**

If I recall correctly, when trying to track this down a while back, there is an issue with how the open API sdk handles specific types of errors. This results in this parsing issue and the error it throws. Hope this helps 😃

**Comment by erezrokah** [comment]
Thanks @DavidWells! Somehow related to https://github.com/netlify/js-client/issues/157 (as I believe fixing https://github.com/netlify/js-client/issues/157 will make it easier to handle issues like this one)

**Comment by DavidWells** [comment]
Just saw it again on another project. 

Seems like it happens when I do `npm run build && npm run deploy`. Possibly just a coincidence tho 😅

![image](https://user-images.githubusercontent.com/532272/114290938-2b494400-9a38-11eb-8c73-d3814b438592.png)

**Comment by erezrokah** [comment]
> Seems like it happens when I do `npm run build && npm run deploy`.

Thanks @DavidWells, unrelated but you can use `netlify deploy --build` to run a build before a deploy.

**Comment by erezrokah** [comment]
Also related to https://github.com/netlify/js-client/issues/38

**Comment by EvanJo** [comment]
exact same error. Site runs fine locally, or when netlify builds it directly from github. 

Adding --build fixed it. Thanks for the answer above.
