### ISSUE TITLE
functions don't deploy when only defined in netlify.toml

### ISSUE THREAD

**Issue by mxrlkn** [netlify/cli#209]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

`netlify deploy` doesn't deploy functions when functions are defined in netlify.toml as:

```
[build]
  publish = "dist"
  functions = "functions"
```

I have to add the cli flag to make it work `netlify deploy --functions=functions`

The documentation mentions that it should work with netlify.toml alone: https://www.netlify.com/docs/cli/#manual-deploys

**- If the current behavior is a bug, please provide the steps to reproduce.**

- create functions
- create netlify.toml with: 
```
[build]
  publish = "dist"
  functions = "functions"
```
- run `netlify deploy`

**- What is the expected behavior?**

That functions will be deployed

**- Please mention your node.js, and operating system version.**

Node v11.6.0
MacOS 10.14.2

**Comment by bcomnes** [comment]
Found the source, releasing a fix today.
