### ISSUE TITLE
allow selective deploy within directory tree

### ISSUE THREAD

**Issue by fool** [netlify/cli#21]
Requested by a customer but perhaps has wider appeal than one person:

an ability to select files to exclude or include during a deploy of a directory.

Perhaps it could behave like .gitignore, where you could set patterns (eg node_modules/* or *.o) not to be deployed?

**Comment by dimkir** [comment]
Was looking around your documentation for this feature (most simple use case is that when I make static website on my dev machine, and want to publish it via `netlify deploy`, I usually don't want `node_modules` to be uploaded. 

Surge.sh have done it  in very simple way: by adding a [custom ignore file and some reasonable defaults](https://surge.sh/help/ignoring-files-and-directories).  

Is something like this possible in today's  `netlify-cli` ?

**Comment by fool** [comment]
Nothing like that exists, but we'd accept contributions :)

All development going forward is going to be on the Go client:  https://github.com/netlify/netlifyctl so if you're hoping for it to get implemented by us - that's the one to file the feature request on.

**Comment by bcomnes** [comment]
The upcoming 2.0.0 cli ignores `node_modules` and `.dotfiles` (except for `.well-known`) by default.  Generally, it's better to copy the files you want hosted into a deploy folder than it is to deploy in folders that have files you want ignored.  We may expand this capability in the future though.

**Comment by jimniels** [comment]
Would be nice to have this.

[Certain files are already being excluded](https://github.com/netlify/js-client/pull/226/files) and the js-client [used to have a deploy method](https://github.com/netlify/js-client/blob/96cd640a7b4480265f5119dd4c52b48d773d5dc4/CHANGELOG.md#700-2021-05-27) which would allow you to specify a `filter` function for filtering out files you didn't want.

Would be nice to have some kind of glob pattern you could pass in that excludes files matching a certain pattern in your deploy dir, i.e.

```
netlify deploy --dir ./build --exclude "{**/_nested-name}"
```
