### ISSUE TITLE
3.17.0 causes continuous spawn of processes when combined with `npm-run-all` or `concurrently`

### ISSUE THREAD

**Issue by artdevgame** [netlify/cli#2110]
**Describe the bug**

Using the latest version of `netlify-cli` causes `npm-run-all` or `concurrently` to respawn processes continuously. 

This wasn't happening in **3.14.0**

**To Reproduce**

1. Run `https://github.com/artdevgame/tailwind-jit-bug`
2. Navigate to the cloned repository
3. Run `yarn` to install the deps
4. Run `yarn dev` to see the problem

**Expected behavior**

I expect multiple processes to start and hang around (stable), not respawn continuously.

**Additional context**

Originally raised on Tailwind as I believed that to be the issue, but found that by downgrading `netlify-cli` to 3.14.0 the problem went away: https://github.com/tailwindlabs/tailwindcss/issues/4031

**Comment by eduardoboucas** [comment]
Hi @artdevgame! Thanks for filing this. Can you please try downgrading to v3.16.2 specifically and let me know if the issue persists?

**Comment by erezrokah** [comment]
Hi @artdevgame, I believe this is related to the new `vite` support https://github.com/netlify/cli/pull/2083.
`netlify dev` now detects a `vite` project and runs the `vite` command for you.

You should be able to just run the `dev:netlify` script and remove `concurrently` all together. Can you see if that helps?

**Comment by artdevgame** [comment]
Thanks for taking a look @erezrokah.

I've updated the repo at https://github.com/artdevgame/tailwind-jit-bug with different versions. The last version to work with concurrently appears to be **3.15.2**

Dropping `concurrently` and just using `netlify dev` does work, but it's still an issue as I hang more than those commands off `yarn dev`, I just simplified them for demo purposes, i.e. I have a `dev:tunnel` script too.

I need to be able to run `concurrently` (or `npm-run-all`), here's another test that simplifies what I'm trying to do further, but still demonstrates the problem:
https://github.com/artdevgame/tailwind-jit-bug/blob/main/3.17.0-alt/package.json

**Comment by erezrokah** [comment]
> I need to be able to run `concurrently` (or `npm-run-all`)

Hi @artdevgame, you **_can_** run `concurrently` or `npm-run-all`. You just don't need to run `yarn dev:vite` when you run `netlify dev` (`netlify dev` [does that for you](https://cli.netlify.com/netlify-dev/#project-detection)).

I tested `https://github.com/artdevgame/tailwind-jit-bug/blob/main/3.17.0-alt/package.json` and it seems to work:
![image](https://user-images.githubusercontent.com/26760571/114572671-5e7e1400-9c80-11eb-9403-1603c2b5b6d5.png)

Can you describe what's not working? e.g. explain this:
> Using the latest version of netlify-cli causes npm-run-all or concurrently to respawn processes continuously.

by listing the process that are being spawned

**Comment by artdevgame** [comment]
Sorry for the late reply. I think I was getting confused on how to use `netlify dev` but I've just figured it out.
It doesn't help that my test case (the repo I linked) was overly simplified.

My real project looked more like:
```
"scripts": {
    "dev": "concurrently \"yarn dev:tunnel\" \"yarn dev:netlify\" \"yarn dev:vite\"",
    "dev:netlify": "netlify dev",
    "dev:tunnel": "../../Downloads/tunnelto.exe --port 3000",
    "dev:vite": "vite",
    "build": "concurrently \"yarn build:functions\" \"yarn build:site\"",
    "build:functions": "netlify-lambda build serverless-functions/src --config ./webpack.serverless-functions.js",
    "build:site": "vite build",
    "serve": "vite preview"
  },
```

When I ran `yarn dev`, I would see the the processes respawn (the lines with the `[0]` & `[1]` in your pic above would be output again and again, nested each time)

I've since figured it out though, my package.json now looks like:
```
"scripts": {
  "dev": "concurrently \"yarn dev:site\" \"yarn dev:tunnel\"",
  "dev:site": "vite",
  "dev:tunnel": "../../Downloads/tunnelto.exe --port 3000",
  "build": "concurrently \"yarn build:functions\" \"yarn build:site\"",
  "build:functions": "netlify-lambda build serverless-functions/src --config ./webpack.serverless-functions.js",
  "build:site": "vite build",
  "serve": "vite preview"
},
```

and I have a netlify.toml that contains the following:
```
[dev]
  autoLaunch = false
  command = "yarn dev"
  framework = "#custom"
  port = 8888
  targetPort = 3000
```

That seems to be working how I want.
Sorry for burning up some of your time, I do appreciate you taking a look and replying @erezrokah

**Comment by erezrokah** [comment]
No worries @artdevgame, thank you for sharing your use case and solution 🎉
