### ISSUE TITLE
New site URL is incorrect

### ISSUE THREAD

**Issue by zackharley** [netlify/cli#214]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

When creating a new site using the CLI, upon completion, the Site URL and Admin URL are both incorrect. The API converts the supplied site name to `kebab-case` but return whatever name was supplied. This means that supplying `A Long Site Name` as the site name, the Site URL will be 

https://a-long-site-name.netlify.com

but will show up in the console as

```URL:       https://A Long Site Name.netlify.com```

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a new folder, `mkdir my-site`
1. Initialize it as a git repo ,`git init`
1. Create a repo on GitHub
1. Add the GitHub repo as a remote in your folder, `git remote add origin <url>`
1. Initialize the site with Netlify CLI, `netlify init`
1. When prompted what you would like to do, specify "Create & configure a new site"
1. When prompted to enter a site name, enter something like "A Long Site Name"
1. Finish initialization
1. Upon successful initialization, see incorrect Admin URL and Site URL

**- What is the expected behavior?**

The Admin URL and Site URL should match what was actually created, e.g. https://a-long-site-name.netlify.com and not `https://A Long Site Name.netlify.com`

**- Please mention your node.js, and operating system version.**
Node v8.11.1
MacOS Mojave v10.14.1
netlify-cli/2.6.1 darwin-x64 node-v8.11.1

**Comment by lisnb** [comment]
I came across the same problem as this. 

I chose ```icanibb.club``` as my site name, then the cli told me my URL was ```icanibb.club.netlify.com``` while the actual URL is ```icanibb-club.netlify.com```

**Comment by bcomnes** [comment]
Thank you for the report, we will investigate.

**Comment by djadmin** [comment]
This seems to be fixed now. Only alphanumeric characters and hyphens are allowed in the Site name which will not accept anything like `A Long Site Name` / `canibb.club` as an input.

**Comment by RaeesBhatti** [comment]
This has been fixed. We have a [testing regex in place](https://github.com/netlify/cli/blob/fafc7fd1d4896cf616e580ad6d310ecb8e0ad295/src/commands/sites/create.js#L73) to make sure a valid site name is selected.
