### ISSUE TITLE
Correctly detect netlify-lambda if it's being run locally rather than globally

### ISSUE THREAD

**Issue by bengal75** [netlify/cli#2147]
**Is your feature request related to a problem? Please describe.**

I recently set up a project with the Netlify CLI which included netlify-lambda for function transpilation. To try and keep this portable across a team, I installed both this package and the netlify-lambda package locally (i.e. using `yarn install` and not `yarn global install` as recommended).

I then tried to configure the function build in my package.json as
```json
"build:functions": "yarn netlify-lambda build src/functions"
```
but this ended up failing with the confusing error message "Command 'netlify-lambda build' was detected in script 'build:functions', but contained 2 or more function folders".

**Describe the solution you'd like**

To figure out what was going on, I needed to dig into the code of this package and search for the error message - so as a baseline, some improved error messaging would be good. But if the package were to detect this situation and report on it with a different error, I guess it may as well support it and run without throwing!

**Describe alternatives you've considered**

I'm currently working around this by specifying the command as
```json
"build:functions": "node_modules/.bin/netlify-lambda build src/functions"
```
but that doesn't feel as elegant or "just works" as it could be.

**Can you submit a pull request?**

Yes, but I'd welcome guidance on where to draw the limits. My current thinking would be to modify [this line](https://github.com/netlify/cli/blob/main/src/function-builder-detectors/netlify-lambda.js#L17) so it stopped assuming it was the first two values it needed to drop, and then perhaps figure out the position of `netlify-lambda` and `build` in the list, then take the rest of the arguments from that point.

I'm also aware that the docs for both of these packages note that detection is currently basic with plans to improve it, so this may already be covered by a wider bug/feature request.

**Comment by erezrokah** [comment]
Hi @bengal75, I think you don't need the `yarn` in your script, `"build:functions": "netlify-lambda build src/functions"` should work.

Also, we've recently introduced `esbuild` support to our functions bundler so you might not need `netlify-lambda` all togther.
Read more about it [here](https://www.netlify.com/blog/2021/04/02/modern-faster-netlify-functions/).
You can opt-in by adding:
```toml
[functions]
  node_bundler = "esbuild"
```
to your `netlify.toml` file

**Comment by bengal75** [comment]
Hi @erezrokah, thanks for the speedy response. You're right - having the script specified as `"build:functions": "netlify-lambda build src/functions"` does in fact work absolutely fine when I run it via Yarn. I think I had previously tried it by simply running `netlify-lambda build src/functions` directly in the terminal, which doesn't work (it returns `netlify-lambda: command not found`) but I hadn't clicked that it isn't quite the same environment.

Thanks also for the esbuild info - that's a really exciting development! I intend to give this a try and would agree that it negates the need for netlify-lambda in our case, so I'll close this issue in favour of both of those solutions.
