### ISSUE TITLE
feat: command to start functions server

### ISSUE THREAD

**Issue by chihab** [netlify/cli#2151]
### Problem

I am always frustarted when I want to prerender routes that use netlify function endpoints to fetch the data. 

Each time I create or update a function,  I have to run the pipeline twice, the first time only to get the functions deployed, the second to prerender the static pages using the data fetched from the deployed functions.

### Proposed solution(s)

The ideal solution would be to deploy the netlify functions first at build time (not sure whether it could fail the entire build if it times out) 

Otherwise, I would like to be able to start the netlify functions server before prerendering the application that uses those served functions to fetch the data.

The command could be:

``` netlify functions:start ```

I would use `start-server-and-test` to start the functions server, prerender the app that would target the functions server endpoints and kill the server when the prerendering is done.

```toml
[build]
command = "NODE_ENV=production npm run prerender"
functions = "./server/functions"
publish = "dist"
```

```json
"prerender:app": "...", // Gatsby / Angular Universal build command
"prerender:serve": "netlify functions:start"
"prerender": "start-server-and-test prerender:serve http://localhost:9999/.netlify/functions/catalog prerender:app",
```

### Alternatives

I've considered two alternatives to `netlify functions:start`:

#### Using netlify-cli internal startFunctionsServer method.

```js
const path = require("path");
const {
  startFunctionsServer,
} = require("netlify-cli/src/utils/serve-functions");
startFunctionsServer({
  config: {},
  settings: {
    functions: path.resolve(__dirname, "../server/functions"),
    functionsPort: 9999,
  },
  site: {},
  log: console.log,
  warn: console.warn,
  errorExit: console.error,
  capabilities: {},
});
```

#### Using an express app that imports the functions and call their handlers

```js
const express = require('express');
const app = express();
const cors = require('cors');

app.use(cors());

app.use('**/.netlify/functions/:endpoint', async (req, res) => {
  const endpoint = require(`./functions/${req.params.endpoint};
  const response = await endpoint.handler({ path: req.path }); // full mapping to be done (opposite of serverless-http)
  res.status(response.statusCode).send(response.body);
});

app.listen(9999);
```

**Can you submit a pull request?**

I can try.

**Comment by erezrokah** [comment]
Thanks for opening the issue @chihab,

I'm a bit confused about your use case.

You're using Netlify Functions to pre-render pages, and you'd like the functions to be deployed before the site is built in the same build? If that's the case, have you considered having a separate site just for the functions?

If I understand correctly - the other solution you proposed is to run the functions locally in a server using the CLI, and using that server to pre-render? If that's the case, any reason those needs to be Netlify Functions?

What am I missing here? Can you share a public repo with your setup? That might help be understand your use case

**Comment by chihab** [comment]
Netlify functions only act as an api to server data, product catalog...

In my application I use the netlify functions to get the data on some page. For example, when a component is mounted we might call `fetch('/.netlify/functions/catalog` get the product catalog.

To pre-render the application pages, the functions need to be available at build time because in the process of pre-rendering the component are mounted and the api calls are actually made to get the data to put statically in the html outputs.

Once deployed, the static pages still need the apis because the call is made a second time to get fresher data eventually.

If we consider having a separate site only for the functions, since the functions and the application are part of the same repo, pushing to that repo will trigger the build on both sites and we don't guarantee that the functions will be deployed before building the app so we can end up with 404 on some api calls because the functions haven't been deployed yet.

You can find an example using the second alternative here: https://github.com/ngMorocco/ngx-darija and here is the pipeline https://app.netlify.com/sites/ngx-darija/deploys/60599788d589670007b8f8d8

**Comment by erezrokah** [comment]
> If we consider having a separate site only for the functions, since the functions and the application are part of the same repo, pushing to that repo will trigger the build on both sites and we don't guarantee that the functions will be deployed before building the app so we can end up with 404 on some calls (to new apis since the last deploy) because the new functions haven't been deployed yet.

Hi @chihab, you should be able to use [`ignore`](https://docs.netlify.com/configure-builds/file-based-configuration/#ignore-builds) to manage that.

That configuration is useful in a monorepo setup, where you have `backend` and `frontend` logic in the same repo.
See more [here](https://www.netlify.com/blog/2019/10/09/launching-monorepo-support-for-netlify-sites/)

**Comment by chihab** [comment]
I don't think that fixes the issue. Let's say I update the web app and the netlify function at the same time the build should be triggered for both.

Unless there is a way to say that, for the same commit, this build should wait for another build to finish before starting, the only solutions I see are:
* Deploying the functions **before** building the app
* Starting the functions from the pipeline before building the app
