### ISSUE TITLE
Error: Uploaded file X did not match deploy

### ISSUE THREAD

**Issue by njam** [netlify/cli#216]
When trying to deploy a site I sometimes get this error:
>  ›   Error: Uploaded file 
> ›   /en/events/basel/2019-01-19/c4b5e3d0-b2a5-4ea5-8ae7-a84bca92cf6f/index.htm
> ›   l did not match deploy

What does that mean, and how can I avoid it?

Site ID: 7e292fb9-d837-4606-b4a2-ed7f09e59fcc

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

```console
$ netlify deploy --site="$NETLIFY_SITE" --auth="$NETLIFY_AUTH_TOKEN" --dir=dist/ --prod --message="$CI_COMMIT_MESSAGE"
Deploy path: /builds/denkmal/denkmal-website/dist
Deploying to live site URL...
- Hashing files...
✔ Finished hashing 748 files
- CDN diffing files...
✔ CDN requesting 718 files
- Uploading 721 files
 ›   Error: Uploaded file 
 ›   /en/events/basel/2019-01-19/c4b5e3d0-b2a5-4ea5-8ae7-a84bca92cf6f/index.htm
 ›   l did not match deploy
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

Cannot reliably reproduce.
Happened for 2 out of 5 deploys, with the command above.

**- What is the expected behavior?**

Deployment should succeed.

**- Please mention your node.js, and operating system version.**

Netlify-cli: 2.6.2
NodeJS: version 11, from docker image `node:11-alpine`
OS: Linux on gitlab CI

**Comment by bcomnes** [comment]
I'm seeing that periodically too.  Thank you for the report, we will investigate.

**Comment by bcomnes** [comment]
Fixed in https://github.com/netlify/js-client/pull/32

Will release in a few minutes.

**Comment by bcomnes** [comment]
This should be working now via https://github.com/netlify/cli/pull/217

Closing, please re-open if you are seeing any similar issues;

Be sure to update to  netlify-cli@2.6.3.

We recently had some rate-limiting changes with our API which we are still tweaking.  If your deploy is rate limited, it will back off for around 60 seconds.  This is un-ideal and I will be bringing up the issue next week to find a solution.
