### ISSUE TITLE
TypeScript functions cannot import local modules

### ISSUE THREAD

**Issue by kamsar** [netlify/cli#2183]
**Describe the bug**

Importing a relative file from one of the new esbuild-powered TypeScript functions cannot resolve the import.

**To Reproduce**

1. Run `git clone https://github.com/kamsar/netlify-functions-ts-repro.git`
2. `npm i`
3. Run `npm run dev` (runs `netlify dev`)
4. See that the build errors:

``` 
> netlify/functions/hello.ts:2:22: error: Could not resolve "../../ref"
    2 │ import { hello } from "../../ref";
```

**Configuration**

Default Netlify config, CLI 3.21, Windows 10 + Node 14.15.4

**Expected behavior**

Importing a local file from a Netlify function should bundle that file into the resultant function.

**Additional context**

This occurs because this import is not resolved: 

https://github.com/kamsar/netlify-functions-ts-repro/blob/24c6f6b1772ae420404003024b0ca1989d434b4e/netlify/functions/hello.ts#L2

Removing the import will make the function work fine. This worked fine with historical `netlify-lambda` based builds, but not with the integral esbuild mode.

**Comment by eduardoboucas** [comment]
Thanks for the detailed report @kamsar! This should be fixed in version `3.21.2` of the CLI. If you still encounter any issues, please add a comment and I'll reopen.
