### ISSUE TITLE
TypeScript function cache is not cleaned

### ISSUE THREAD

**Issue by kamsar** [netlify/cli#2190]
**Describe the bug**

If you create a TypeScript function, then delete it, its built .js files still live on within `.netlify/functions-serve` for subsequent runs.

**To Reproduce**

1. Create a new TypeScript function (hello world is fine)
2. Run `netlify dev`, note that `.netlify/functions-serve/funcname` now exists
3. Delete the function file
4. Run `netlify dev` again. The existing function is still in `.netlify/functions-serve/funcname` and is evaluated and run as part of `netlify dev` still.

**Configuration**

Default settings (no netlify.toml), CLI 3.21.2

**Expected behavior**

Deleting a function that previously had a build error, the build error should stop being reported on later runs of `netlify dev`

**Comment by eduardoboucas** [comment]
Hi @kamsar! This should be fixed in version `v3.21.5` of the CLI. If you're still experiencing any issues, please add a comment and I'll reopen. Thanks again for reporting!
