### ISSUE TITLE
Better messaging to detect issues that require `external_node_modules`

### ISSUE THREAD

**Issue by kamsar** [netlify/cli#2191]
**Is your feature request related to a problem? Please describe.**

While porting my existing `netlify-lambda` based functions to the new esbuild bundler I ran across a misbehaving package, `@sentry/node`, that we are using to trace errors in our functions.

The eventual solution was that I needed to add `@sentry/node` to the [`external_node_modules` in my `netlify.toml`](https://docs.netlify.com/configure-builds/file-based-configuration/#functions) because I think the dead code elimination was being overly aggressive, but the path to get there involved process of elimination in my code after getting this error from zisi:

```
◈ Function builder zip-it-and-ship-it finished building functions from directory C:\snip\functions
    Error: In file "C:\snip\.netlify\functions-serve\v1-integrations\v1-integrations.js"
    Cannot find module 'exports'
    Require stack:
    - C:\snip\node_modules\@netlify\zip-it-and-ship-it\src\node_dependencies\resolve.js
    - C:\snip\node_modules\@netlify\zip-it-and-ship-it\src\node_dependencies\index.js
    - C:\snip\node_modules\@netlify\zip-it-and-ship-it\src\main.js
    - C:\snip\node_modules\netlify-cli\src\utils\get-functions.js
    - C:\snip\node_modules\netlify-cli\src\utils\serve-functions.js
    - C:\snip\node_modules\netlify-cli\src\commands\dev\index.js
    - C:\snip\node_modules\@oclif\config\lib\plugin.js
    - C:\snip\node_modules\@oclif\config\lib\config.js
    - C:\snip\node_modules\@oclif\config\lib\index.js
    - C:\snip\node_modules\@oclif\command\lib\command.js
    - C:\snip\node_modules\@oclif\command\lib\index.js
    - C:\snip\node_modules\netlify-cli\src\index.js
    - C:\snip\node_modules\netlify-cli\bin\run
```

**Describe the solution you'd like**

It'd be nice if the error message could be a bit less cryptic and point me to that `external_node_modules` could be a potential solution. This might be hard since I think that's coming out of `require.resolve` (maybe?) and since the typescript is already JS-ified and bundled it could be difficult to figure out the offending module name other than how I already did it.

As a secondary note, it's kinda weird that the options for `node_bundler` in `netlify.toml` are `zisi` or `esbuild`, but even with it set to `esbuild`, zip-it-and-ship-it is all over in the console output. I'm _pretty sure_ it's working and using esbuild since zisi does depend on it... ;)

**Comment by eduardoboucas** [comment]
Hi @kamsar! Apologies for the slow response. We've added new messaging to the build logs which warn you whenever one of your dependencies is requiring files using dynamic expressions, which the bundler cannot resolve at build time. I believe this is the case with `@sentry/node`. Can you please confirm that you see the new message?

As for the `zisi` value in `node_bundler`, I see your point. `zip-it-and-ship-it` is the name of the bundling service, which under the hood can use either esbuild or the initial bundler. We refer to the old bundler `zisi`, but I understand how that is confusing — naming things is hard! 😬 

So, if you've opted in to esbuild using `node_bundler = "esbuild"`, you are indeed using esbuild and there's nothing to worry about. Sorry for the confusion!

I'll close this issue, but if you don't see the new message or you feel that it doesn't satisfy your initial request, please add a comment and I'll reopen.

Thanks!
