### ISSUE TITLE
SyntaxError while creating site through CLI with added data

### ISSUE THREAD

**Issue by alucardu** [netlify/cli#2192]
**Describe the bug**

I'm trying to create a site through the CLI using a data object for the name:

**To Reproduce**

Install CLI and run:

`netlify api createSite --data '{ "name": "test123"}'`

**Expected behavior**

A site to be created

**CLI Output**

```C:\Users\alucardu>netlify api createSite --data '{ "name": "test123"}'
SyntaxError: Unexpected token ' in JSON at position 0```

**Comment by erezrokah** [comment]
Hi @alucardu, can you try:
```
netlify api createSite --data '{ "body": { "name": "test123" } }'
```

Also see https://cli.netlify.com/commands/sites#sitescreate. You should be able to use `netlify sites:create --name <name>`

**Comment by alucardu** [comment]
`netlify sites:create --name <name>` also works but I want to integrate it with our CI and when I run that command I get a prompt to select a team. 

`netlify api createSite --data '{ "body": { "name": "test123" } }'` returns the same error.

**Comment by erezrokah** [comment]
> `netlify sites:create -n=test123 -a=slugName`
> 
> That works fine :)

💯 Was just going to write that

Closing the issue. Please let me know if you need anything else
