### ISSUE TITLE
Question: how to get site id based on the name

### ISSUE THREAD

**Issue by alucardu** [netlify/cli#2199]
I'm trying to integrate Netlify in my CI (Azure Devops) and I want to dynamically create Netlify sites to deploy (temporary) sites to. For that I need the site id, but I can't request the site id based on the sites name.

**Describe the solution you'd like**

Request site id based on the sites name.

**Comment by erezrokah** [comment]
Hi @alucardu you should be able to use `netlify sites:list --json` parse the JSON, then filter by name.

**Comment by erezrokah** [comment]
Hi @alucardu, closing this issue per my comment. Please comment if using `netlify sites:list --json` doesn't solve your use case.
