### ISSUE TITLE
feat(docs): recommend users to use a lock file and npm ci when running in CI

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#2208]
**Is your feature request related to a problem? Please describe.**

Related to https://github.com/netlify/cli/issues/2202

When users run `npm install netlify-cli -g` they always get the latest minor/patch versions of CLI dependencies. This usually works ok and helps users get the latest security updates, but can cause issues when packages don't follow semver.

When running in CI it is recommended to use a lock file and `npm ci` or `yarn install --frozen-lockfile` to ensure reproducible builds.

**Important** `npm install netlify-cli -g` also means users opt in to any CLI major (breaking) version change. Those are less frequent but still happen.

**Describe the solution you'd like**

Update the docs to recommend using a lock file when using the CLI in CI environments

**Describe alternatives you've considered**

https://github.com/netlify/cli/issues/2223
https://github.com/netlify/cli/issues/1597

**Can you submit a pull request?**

Yes

**Comment by JGAntunes** [comment]
Related to https://github.com/netlify/engineering/issues/318.
