### ISSUE TITLE
Document NETLIFY_AUTH_TOKEN variable for CI/CD

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#221]
Add `NETLIFY_AUTH_TOKEN` to the docs.

If you set `NETLIFY_AUTH_TOKEN` in your terminal session or in CI/CD that will be the auth token used to connect with Netlify

example

```
export NETLIFY_AUTH_TOKEN=21251552511
```

**Comment by bcomnes** [comment]
It's mentioned here: https://github.com/netlify/buildbot/issues/322

**Comment by RaeesBhatti** [comment]
Closing this since the usage and description is documented here: https://cli.netlify.com/commands/deploy/
