### ISSUE TITLE
TypeError Plugin: netlify-cli: memoizeOne is not a function

### ISSUE THREAD

**Issue by zmwangx** [netlify/cli#2219]
**Describe the bug**

Latest release v3.21.8 fails with `TypeError Plugin: netlify-cli: memoizeOne is not a function`. 

**To Reproduce**

1. `yarn add netlify-cli`
2. `yarn run netlify`

**Configuration**

N/A.

**Expected behavior**

No error.

**CLI Output**

```
(node:3023) TypeError Plugin: netlify-cli: memoizeOne is not a function
module: @oclif/config@1.17.0
task: runHook init
plugin: netlify-cli
root: /private/tmp/nc/node_modules/netlify-cli
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Additional context**

This is really a continuation of #2202. Opening a new issue because that one is closed and claimed to be fixed, which is confusing. (Btw I can confirm that v3.21.7 did fix the issue for a while, but it's broken again.)

**Comment by rquiroz32** [comment]
Also experiencing this issue, on this post in the forum another user said downgrading to an older version resolved it. What's the best way to do that ? (sorry if that's a dumb question).

https://answers.netlify.com/t/typeerror-plugin-netlify-cli-memoizeone-is-not-a-function/36458/4

**Comment by zmwangx** [comment]
I'm pinning to `v3.21.6` for now.

```
yarn global add netlify-cli@3.21.6
# or
npm install -g netlify-cli@3.21.6
```

**Comment by ehmicky** [comment]
Hi everyone,

Thanks for reaching out.
[`netlify-cli@3.21.9`](https://github.com/netlify/cli/releases/tag/v3.21.9)  should fix this problem.
Please let us know if this does not.

**Comment by zmwangx** [comment]
Works now, thanks.
