### ISSUE TITLE
Feature: support invoking submission-created in functions:invoke

### ISSUE THREAD

**Issue by helloiamlukas** [netlify/cli#2221]
**Describe the bug**

I'm not able to include a custom payload when I'm invoking my `submission-created` function.

I tried it with a stringified JSON, but also with a file path to a JSON file.

```
netlify functions:invoke submission-created --payload "{\"foo\": 1}"
```
```
netlify functions:invoke submission-created --payload "./functions/test-payload.json"
```

Neither of them works.

**Code**

 `./functions/submission-created.js`

```js
exports.handler = async function (event, context, callback) {
  const { payload } = JSON.parse(event.body)

    statusCode: 200,
    body: JSON.stringify({
      ...payload
    }),
  })
}
```

 `./functions/test-payload.json`

```json
{
   "foo": 1
}
```

**System Configuration**

```bash
  System:
    OS: macOS 11.2.3
  Binaries:
    Node: 14.16.0
    Yarn: 1.22.5
    npm: 7.8.0
    netlify-cli: 3.21.9
```

**Expected behavior**

I would expect `{ "foo": 1 }` to be returned by the `submission-created` function.

**Actual behavior**

No matter if I'm using the stringified JSON or the file path to my json, I get returned the following by the `submission-created` function:

```json
{
   "TODO": "mock up payload data better"
}
```

**Comment by erezrokah** [comment]
Hi @helloiamlukas, the `submission-created` is a "special" kind of function triggered by Netlify, so a having a custom payload won't really simulate the production environment.

Can you try sending an `application/x-www-form-urlencoded` `POST` request to the Netlify dev server and see if that works.
You can use the following command to do so:
`curl -i -d "foo=1" --header "Content-Type: application/x-www-form-urlencoded" http://localhost:8888`

**Comment by helloiamlukas** [comment]
I tried a `POST` request to `http://localhost:8888` as you described and got this:
```bash
HTTP/1.1 404 Not Found
x-powered-by: Express
access-control-allow-origin: *
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept
content-security-policy: default-src 'none'
x-content-type-options: nosniff
content-type: text/html; charset=utf-8
content-length: 150
date: Sun, 25 Apr 2021 21:51:29 GMT
connection: close

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /index.html</pre>
</body>
</html>
```

Whenever I make a request to any other path than root, it works – but my received payload looks a bit different then expected:
```json
{
   "data": { "foo": "1", "ip": "::ffff:127.0.0.1", "user_agent": "curl/7.64.1" },
   "created_at": "2021-04-25T21:56:01.622Z",
   "human_fields": { "Foo": "1" },
   "ordered_human_fields": [ { "title": "Foo", "name": "foo", "value": "1" } ],
   "site_url": "https://xyz.netlify.app"
}
```

I would expect just `{ "foo": 1 }` to be returned.

**Comment by erezrokah** [comment]
For the `submission-created` **_event triggered function_** - this is the expected payload.
See https://docs.netlify.com/functions/trigger-on-events/#payload

**Comment by helloiamlukas** [comment]
Alright, thank you for the clarification! I was a bit confused, since the docs don't mention the further structure of the payload.

Anyway, if this can be triggered (and is working correctly) with a custom `POST` request, this should work with the `netlify functions:invoke` command too, right?

**Comment by erezrokah** [comment]
True, it should work with `functions:invoke`, but it should still not allow a custom payload as described in the issue - it should transform it to the expected structure (I'll update the title to reflect that).

Since `functions:invoke' only supports JSON payload at the moment we would need to to resolve https://github.com/netlify/cli/issues/980 first.

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
