### ISSUE TITLE
feat: consider publishing an `npm-shrinkwrap` file

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#2223]
**Is your feature request related to a problem? Please describe.**

Related to https://github.com/netlify/cli/issues/2202

When users run `npm install netlify-cli -g` they always get the latest minor/patch versions of CLI dependencies. This usually works ok and helps users get the latest security updates, but can cause issues when packages don't follow semver.

By publishing [`npm-shrinkwrap`](https://docs.npmjs.com/cli/v7/commands/npm-shrinkwrap) file we will be essentially locking down CLI dependencies during installation on users machines.

This is useful when installing the CLI globally, but prevents users from having full control of their dependency tree if installing the CLI locally.

See more [here](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#package-lockjson-vs-npm-shrinkwrapjson)

**Describe the solution you'd like**

Publishing an `npm-shrinkwrap` file to pin CLI dependencies.

**Describe alternatives you've considered**

https://github.com/netlify/cli/issues/2208
https://github.com/netlify/cli/issues/1597

**Can you submit a pull request?**

Yes

**Comment by eduardoboucas** [comment]
I think this is a great idea.

**Comment by JGAntunes** [comment]
Related to https://github.com/netlify/engineering/issues/318.
