### ISSUE TITLE
Netlify CLI can't get authorizations from my GitHub account; `netlify init` cannot setup Continuous Deploy

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#2229]
**Describe the bug**

netlify init fails to set up github auth through the site,

and it also hard crashes when manually typing in my credentials

**To Reproduce**

first error

```bash
$ ntl init
Logging into your Netlify account...
Opening https://app.netlify.com/authorize?response_type=ticket&ticket=6a069e4b4752f6efae8761abaa1029f0

You are now logged into your Netlify account!

Run netlify status for account details

To see all available commands run: netlify help

? What would you like to do? +  Create & configure a new site
? Team: swyxteam
Choose a unique site name (e.g. the-awesome-sw-yx-site.netlify.app) or leave it blank for a random name. You can update the site name later.
? Site name (optional): sveltekitnetlifyforms

Site Created

Admin URL: https://app.netlify.com/sites/sveltekitnetlifyforms
URL:       https://sveltekitnetlifyforms.netlify.app
Site ID:   ef72bc23-9e3a-4c62-9a8c-d8e7316853d7

? Netlify CLI needs access to your GitHub account to configure Webhooks and Deploy Keys. What would yo
u like to do? Authorize with GitHub through app.netlify.com
    Error: Got invalid parameters for CLI login
```

second error

```bash
$ ntl init

? Netlify CLI needs access to your GitHub account to configure Webhooks and Deploy Keys. What would yo
u like to do? Enter your GitHub credentials manually
? Your GitHub username: sw-yx
? Your GitHub password: *********
Deprecation: [@octokit/rest] Setting the "new Octokit({ auth })" option to an object without also setting the "authStrategy" option is deprecated and will be removed in v17. See (https://octokit.github.io/rest.js/#authentication)
    at authenticationPlugin (/usr/local/lib/node_modules/netlify-cli/node_modules/@octokit/rest/plugins/authentication/index.js:58:5)
    at /usr/local/lib/node_modules/netlify-cli/node_modules/@octokit/rest/lib/constructor.js:26:37
    at Array.forEach (<anonymous>)
    at new Octokit (/usr/local/lib/node_modules/netlify-cli/node_modules/@octokit/rest/lib/constructor.js:26:11)
    at getGitHubClient (/usr/local/lib/node_modules/netlify-cli/src/utils/gh-auth.js:111:19)
    at authManually (/usr/local/lib/node_modules/netlify-cli/src/utils/gh-auth.js:137:19)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async getGitHubToken (/usr/local/lib/node_modules/netlify-cli/src/utils/gh-auth.js:156:3)
    at async getGitHubToken (/usr/local/lib/node_modules/netlify-cli/src/utils/init/config-github.js:25:20)
    at async configGithub (/usr/local/lib/node_modules/netlify-cli/src/utils/init/config-github.js:185:17)
    TypeError: Cannot read property 'oauthAuthorizations' of undefined
```

**Configuration**

```bash
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 28.38 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.5.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.3.0 - /usr/local/bin/npm
  npmGlobalPackages:
    netlify-cli: 2.69.11
```

**Comment by sw-yx** [comment]
i see i have an old version of the cli.

i upgraded to `netlify-cli/3.21.10` and tried again and got this.

```bash
$ ntl init                                                                                 

? Netlify CLI needs access to your GitHub account to configure Webhooks and Deploy Keys. What would you like to do? Authorize with GitHub through app.netlify.com
```

`https://app.netlify.com/cli?host=http%253A%252F%252Flocalhost%253A3000&provider=github`

![image](https://user-images.githubusercontent.com/6764957/116008685-5cd12a80-a648-11eb-87be-ca01babb4a30.png)

**Comment by sw-yx** [comment]
idk what the cause is but your version of `@octokit/rest` is at v16 and the latest is v18

**Comment by erezrokah** [comment]
Hi @sw-yx thank you for opening the issue. The `Authorize with GitHub through app.netlify.com` flow worked for me.
However, looks like the username and password flow was deprecated by GitHub:
https://github.com/octokit/auth-basic.js/#%EF%B8%8F-deprecation-warning
https://developer.github.com/changes/2020-02-14-deprecating-password-auth/

I think the most reasonable  way to fix it is to ask the user for a GitHub personal access token. I'll do that as a part of https://github.com/netlify/cli/pull/2250

**Comment by sw-yx** [comment]
what do you need from me to help you reproduce the `Authorize with GitHub through app.netlify.com` flow issue? bc i think thats quite important and its definitely broken for me

**Comment by erezrokah** [comment]
What the CLI does is to set up a local server on `http://localhost:3000` to facilitate the auth flow, then opens the Netlify UI to start the flow. 
After finishing the authentication flow, the Netlify UI redirects the user to that local server and passes the token via the URL parameters.

If you could check into the browser traffic for errors when opening the URL `https://app.netlify.com/cli?host=http%253A%252F%252Flocalhost%253A3000&provider=github` that will help a lot to see what goes wrong.

Also maybe trying with a different browser/private mode can help? Maybe an extension blocking this?

**Comment by sw-yx** [comment]
ah i see. its quite common to have an app on port 3000 already running, so can you change the default port that you use to do this auth flow thing?

**Comment by erezrokah** [comment]
We use [`get-port`](https://github.com/sindresorhus/get-port) so if the preferred port is taken we use a random one.

Do you have anything running on port `3000`? Maybe there's a race condition by the time we check if the port is open, to the time we acquire it. Those two operations happen very close to each other:
https://github.com/netlify/cli/blob/c94d30f623b7fd88f9696126a70b8e54bce1ed6e/src/utils/gh-auth.js#L52
but still possible

**Comment by erezrokah** [comment]
FYI, [`v3.24.3`](https://github.com/netlify/cli/releases/tag/v3.24.3) replaces the user & password flow with a personal access token one.

**Comment by sw-yx** [comment]
ok. i probaably wont repro the UI login flow problem soon since i am done with my original need but will reopen to this issue if it comes up again.

**Comment by deekshant57** [comment]
Hey I am also getting the same authorization error while logging into Netlify via Github. What could be the reason behind this? Anyone solved this in past?

**Comment by kevincam3** [comment]
I'm getting this problem too.
