### ISSUE TITLE
Deeper CLI + Buildbot integration

### ISSUE THREAD

**Issue by phae** [netlify/cli#226]
We need the CLI to live inside the buildbot as a base dependancy.

The CLI is will be critical piece in the way devs work on site locally and plugin additional functionality (ie add-on CLI plugin, Typescript function plugin, etc) 

The idea behind the "Netlify Build Lifecycle" is allowing users to hook into and customize the base functionality of the way the Netlify Buildbot operates. The levers to do this can live in `netlify.toml` or be code in CLI plugins.

**"Netlify Build Lifecycle" Example:**

`Initialize`
👇 > Do stuff with initial config
preConfig  
Config
postConfig
👇 > customize how functions get built/transpiled 
preFunctionBuild
FunctionBuild
postFunctionBuild
👇 > customize how build works
preBuild
Build
postBuild
👇 > customize how asset pipeline works
preAssetOptimization
AssetOptimization
postAssetOptimization
👇
etc.

This way users can run custom logic via `[scripts]` in `netlify.toml` or via custom plugins defined in `[plugins]` in `netlify.toml`. Those plugins would contain code use to modify, overide, or cancel those lifecycle methods.

**Example use case: **

If Buildbot ran `netlify config`, I could have a custom plugin that parses a `netlify.yml` file, populates config values from remote sources and it outputs the `netlify.toml` file for the buildbot to continue using.

**Comment by erezrokah** [comment]
Closing as stale due to work done in https://github.com/netlify/build
