### ISSUE TITLE
Plugin discoverablity

### ISSUE THREAD

**Issue by phae** [netlify/cli#228]
Adding a way for users to discover what plugins are available

`netlify plugins:search`

**Comment by calavera** [comment]
MVP:

1. Put list of available plugins in a file in this repository.
2. Add this command to the cli that downloads the file and scans it.

Very easy and low friction to implement, if someone wants to add a new plugin, they can do it by adding it here. This is also good for discovering plugins when you browse this repository.

**Comment by erezrokah** [comment]
Closing as wontfix as I don't see a great demand for it.
Please comment if you feel otherwise
