### ISSUE TITLE
Security Flaw: production-level env easily extractable by non-authorized devs

### ISSUE THREAD

**Issue by MentalGear** [netlify/cli#2282]
**Describe the bug**

Handling env vars and secret API keys can be challenging, that's why you suggest to put sensitive vars into the Netlify's env UI interface so only admin level users can see/change these instead of everyone with access to the repo.

<img width="951" alt="Screenshot 2021-05-01 at 20 10 55" src="https://user-images.githubusercontent.com/2837147/116792085-d9d42800-aabe-11eb-8e7c-e36f66f78ac6.png">

However, your netlify.toml file uses a hierarchical override, which makes it super easy for non-authorized devs with access to any branch to extract production level API keys.

They only need to delete the branch overrides in the config file, and print the values somewhere in the code of their local build.

//comment this:
<img width="201" alt="Screenshot 2021-05-01 at 20 53 47" src="https://user-images.githubusercontent.com/2837147/116792177-59fa8d80-aabf-11eb-9b90-47fcc00198c1.png">

Done, all secrets revealed.
<img width="248" alt="Screenshot 2021-05-01 at 20 16 32" src="https://user-images.githubusercontent.com/2837147/116792100-e8bada80-aabe-11eb-8505-ef3dedb4d861.png">

**To Reproduce**

Steps to reproduce the behavior using netlify dev:

1. netlify.toml: Delete env overrrides
2. The topmost keys will be displayed, which are the one's in the netlify UI (most probably production level)

**Suggested Solutions**

Here are some ideas to avoid this security leak.
- add restrictions in the admin UI to avoid trickling production keys down stream
- make env keys independent of each other (preferred to avoid unintentional env pollution)
- or use a reverse hierarchical order where the lowest level keys are overridden by the highest (highest being netlify UI)

**Sidenote**
netlify-dev '◈ Reloading redirect rules from [ 'netlify.toml' ]' is logged, however needs a full restart for effects in the config file to take effect

**Comment by erezrokah** [comment]
Hi @MentalGear,

Thank you for reporting this issue.

Is the attack vector you're describing is:
1. Bad actor forks the repo
2. Bad actor changes the repo code to log env variables
3. Bad actor creates a PR with the code change
4. Netlify builds site with code change and exposes env variables.

If that's the case, please see https://docs.netlify.com/configure-builds/environment-variables/#sensitive-variable-policy.

By default Netlify will require owner approval for forked PRs if the site has secrets (not every env variable is considered to be a secret - GitHub tokens for example are considered to be so).

You can control that behavior [here](https://docs.netlify.com/configure-builds/environment-variables/#sensitive-variable-policy).

Please let me know if that solve the issue.
If it doesn't I suggest reporting it directly to `security@netlify.com` or submit a report to our [bug bounty program](https://hackerone.com/netlify), as this repo is intended for the Netlify command line interface.

**Comment by erezrokah** [comment]
Closing this per my comment. Please comment on the issue if you have any further questions or concerns.

**Comment by MentalGear** [comment]
HI @erezrokah ,

The 'attack' scenario is the following:
A group of devs are working on the source using netlify cli, but on development branches. Production ENV are only stored on netlify UI.  Different env ([branch.environment]) are used.

If one of these devs would now simple delete all the [...environment] files in the netlify.toml, the netlify cli would load the env from netlify UI (production) and they could be displayed and extracted by the devs.

**Comment by erezrokah** [comment]
Hi @MentalGear, thanks for the additional information.

Can you clarify what you mean by "normal devs"? Do these devs have access to the repo and or site?  If so don't those environment variables are required for building the site?
Also, they don't need to change any code as they should be able to retrieve the site information via https://open-api.netlify.com/#operation/getSite

I believe this is similar to other CI environments, e.g. GitHub actions where having write access gives you access to read secrets as they are most likely needed for the CI job.

Are you asking for an option to define environment variables only for the production context?
