### ISSUE TITLE
add a deploy local command

### ISSUE THREAD

**Issue by Haroenv** [netlify/cli#23]
**- Do you want to request a *feature* or report a *bug*?**

feature

**- What is the current behavior?**

You have to navigate to a particular page by its eventual url, without being able to rely on the rewrites

**- What is the expected behavior?**

```
$ netlify local
...
builds and serves locally
```

**Comment by bcomnes** [comment]
We are working on a netlify dev proxy that will let you wrap dev servers with a proxy that provides a similar experience to our production environment.  In the meantime, using branch deploys is probably the best way to experiment with things.  Keep an eye peeled for a PR with this soon.

**Comment by Haroenv** [comment]
cool!

**Comment by kirillgroshkov** [comment]
Yes, would be nice
