### ISSUE TITLE
Better test harness

### ISSUE THREAD

**Issue by phae** [netlify/cli#231]
Improving tests would be nice

**Comment by bcomnes** [comment]
The testing inside of this repo is poor, but its decent in the pieces that have been broken out (cli-utils, js-client etc).

**Comment by DavidWells** [comment]
Started here: https://github.com/netlify/cli/pull/254

- [ ] Setup new CI tool (no one has azure access)
- [ ] Validate commands succeed in CI (no prompt) context
- [ ] Validate commands fail when netlify tokens invalid

**Comment by erezrokah** [comment]
Going to close this as stale. I will open relevant specific issues for testing when I triage more CLI issues.
