### ISSUE TITLE
WebSocket error on re-build with TailwindCSS

### ISSUE THREAD

**Issue by kylesloper** [netlify/cli#2310]
Hello, when serving my site netlify-cli throws no error and it works fine but when I edit a file TailwindCSS passes etc.. "tailwind.config.js, "tailwind.css" the cli will throw this error:

```
C:\Users\REDACTED\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\netlify-redirector\lib\redirects.js:116
      throw ex;
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

Perhaps this could be an issue on the Tailwind end but I thought it wise to run it by you guys first.

Cheers.

**Comment by erezrokah** [comment]
Thanks @kylesloper, can you please fill in the missing information from the issue template? Specifically a reproduction scenario? It's very hard to figure out the cause for the issue without it.

**Comment by kylesloper** [comment]
Hey @erezrokah, sorry about that here you are:

1.  Clone [this repo](https://github.com/kylesloper/ntl-cli-testing)
2. `npm install`
3. `ntl dev`
4. try and save the `tailwind.config.js` file

Sorry about that 😃

**Comment by erezrokah** [comment]
Hi @kylesloper, sorry for the delay, I'm not getting this error when editing the file:
![image](https://user-images.githubusercontent.com/26760571/117659363-88a1f380-b1a4-11eb-8b31-4d5bd68312ee.png)

Can you share the result of `npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli`?
Also the full error log/CLI output will help
