### ISSUE TITLE
Manual site creation issue with some remotes

### ISSUE THREAD

**Issue by bcomnes** [netlify/cli#233]
Reported from a user via support:

> When parsing the locale repo in the init command, the https://www.npmjs.com/package/git-remote-origin-url doesn’t return ssh:// and in this case, the correct path is lost. (issue: https://app.intercom.io/a/apps/q245f50x/inbox/inbox/conversation/20585273612#part_id=comment-20585273612-2590190500)

**Comment by hmoffatt** [comment]
I found that "netlify init --manual" got the URL wrong for my remote also. It is

`ssh://git@dev.mycompany.com/some/path/repo.git`

Once the site was created, the repository URL showed up just as:

`some/path/repo.git`

with no username/host portion at all.

I was able to set "netlify sites:create -m --with-ci" to set it up manually.

**Comment by jackmawer** [comment]
Is there a way to fix this for a site that has already been setup?

**Comment by hmoffatt** [comment]
@jackmawer I think you would have to contact support and ask them to do it. The sites API has the repository settings, but I wasn't able to change the URLs using the PATCH or PUT methods - changes to the URL fields were ignored. I don't know why they changes couldn't be allowed.
