### ISSUE TITLE
Husky failure when updating netlify-cli

### ISSUE THREAD

**Issue by SteveALee** [netlify/cli#2331]
This is more a FYI 

When updating just now husky threw an error about a missing package,json in my current project directory

- I performed a global install so my CD is irrelevent
- I do indeed not have a package.json. I'm using "Netlify Build && Netlify dev" to build and serve a jekyll site.

**Configuration**

Ubuntu WSL on windows

**Expected behavior**

No problems or warnings

**CLI Output**

 ``` bash
wsl@OD-X1-CARBON:~/wai/wai-coga-design-guide$  npm i -g netlify-cli
/home/wsl/.nvm/versions/node/v14.16.0/bin/ntl -> /home/wsl/.nvm/versions/node/v14.16.0/lib/node_modules/netlify-cli/bin/run
/home/wsl/.nvm/versions/node/v14.16.0/bin/netlify -> /home/wsl/.nvm/versions/node/v14.16.0/lib/node_modules/netlify-cli/bin/run

> husky@4.3.8 install /home/wsl/.nvm/versions/node/v14.16.0/lib/node_modules/netlify-cli/node_modules/husky
> node husky install

husky > Setting up git hooks
Can't find package.json in /home/wsl/wai/wai-coga-design-guide directory or parents
Please check that your project has a package.json or create one and reinstall husky.
husky > Failed to install
```

**Comment by erezrokah** [comment]
Hi @SteveALee, thanks for reporting.
I find it very odd that `npm` runs a `postinstall` script from a dev dependency 😕 

I was able to reproduce this with Node.js 12 and `npm@6`, but not with `npm@7`. Can you try updating to `npm@7` by running `npm install -g npm`?

**Comment by SteveALee** [comment]
@erezrokah I totally agree. 

I'll try rolling back the CLI and updating again again with npm 7. The trouble is I can't think of any way to discover what version I had before as it's global so not in git. Is the a log someplace?

**Comment by erezrokah** [comment]
> I had before as it's global so not in git. Is the a log someplace?

Not sure, but I was able to consistently reproduce this by using `npm install -g npm@6`.

**Comment by SteveALee** [comment]
I mean the problem occurred when I up upgrade netlify-cli from some unknown version. is there anyway to discover what that was.

Or have you foud another way to reproduce without upgrading?

**Comment by BenJackGill** [comment]
FYI - I just got the same error when trying to install Netlify CLI (globally) for the first time. Upgrading to `npm7` using the command `npm install -g npm` fixed the problem.
