### ISSUE TITLE
Error to run login: Error: Unable to open browser automatically

### ISSUE THREAD

**Issue by GiancarlosIO** [netlify/cli#238]
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
Cli logs a error to run "login"
```
Error: Unable to open browser automatically
spawn /home/gian/.nvm/versions/node/v10.14.2/lib/node_modules/netlify-cli/node_modules/cli-ux/lib/xdg-open ENOENT

```
**- If the current behavior is a bug, please provide the steps to reproduce.**
install netlify-cli
run `netlify login`
**- What is the expected behavior?**
`netlify login` should run without errors
**- Please mention your node.js, and operating system version.**
linux-x64
netlify-cli/2.6.6
node-v10.14.2

**Comment by meatherly** [comment]
I believe it's related to: https://github.com/oclif/cli-ux/issues/62

**Comment by DavidWells** [comment]
Linux machines typically don't work with the `opn` npm package.

I think we will need to swallow this error and display the URL for linux folks to visit manually.

@meatherly can you think of a CLI you have used on your machine that has successfully opened the browser? Maybe we can fix for linux

**Comment by bcomnes** [comment]
It should print a warning and a URL as a fallback the user can either copy-paste into a browser or Ctl-click of the terminal supports it.

**Comment by GiancarlosIO** [comment]
@DavidWells Webpack-cli can open a browser with --open flag and yes, @bcomnes is correct, it should show the URL in the console if it fails to open a browser.

**Comment by DavidWells** [comment]
Looks like we are logging a message

https://github.com/netlify/cli/blob/master/src/utils/open-browser.js#L27 and or https://github.com/netlify/cli-utils/blob/master/src/utils/open-browser.js#L26-L28

Will need to dig into this digger.

**Comment by ehmicky** [comment]
This happened to me on Ubuntu `19.04`, Node `12.9.1`, netlify-cli `2.13.0` as well.

```
$ npm install netlify-cli
$ netlify login
Logging into your Netlify account...
Opening https://app.netlify.com/authorize?response_type=ticket&ticket=6ae9xxxxxxxxxxxxxxxx
---------------------------
Error: Unable to open browser automatically
spawn /home/ether/code/cv-website/node_modules/cli-ux/lib/xdg-open ENOENT

Please open your browser & open the URL below to login:
https://app.netlify.com/authorize?response_type=ticket&ticket=6ae9xxxxxxxxxxxxxxxx
```

**Comment by bitwhys** [comment]
> @meatherly @GiancarlosIO can you think of a CLI you have used on your machine that has successfully opened the browser? Maybe we can fix for linux

I just started using [hub](https://github.com/github/hub) and it opens the browser just fine. Also heroku cli and I'm sure that last one is created with oclif as well

**Comment by erezrokah** [comment]
Closing this as resolved via https://github.com/netlify/cli/pull/2169.
Please comment if still happens.
