### ISSUE TITLE
netlify config resolve does not respect httpProxy flag

### ISSUE THREAD

**Issue by xhebox** [netlify/cli#2399]
**Describe the bug**

~cli is using `@netlify/config` to resolve config, but `@netlify/config/src/api/site_info.ts:getSiteInfo` does not respect offline flag. It will try to retrieve site info until timeout. I found this when `netlify dev`, but later found that all sub commands resolving config will suffer from it.~

As pointed by erezrokah, it actually works. So this issue turns to the problem of `httpProxy`.

**Additional context**

BTW, resolve config does not respect `httpProxy`, too. That is how I found this. It will be better if config resolve can use the httpAgent.

**Comment by erezrokah** [comment]
Thanks for reporting @xhebox, `@netlify/config` returns `undefined` for the API when passing the `offline` flag:
https://github.com/netlify/build/blob/0d2009aa3fb308f93a71425a312c2f5a8ca9aa40/packages/config/src/api/client.js#L8
which then should cause `getSiteInfo` to not return any data:
https://github.com/netlify/build/blob/0d2009aa3fb308f93a71425a312c2f5a8ca9aa40/packages/config/src/api/site_info.js#L13

For `httpProxy` this looks like a bug and I agree passing down the `httpAgent` looks like the solution.

**Comment by xhebox** [comment]
Wow, really quick response. And yes, I found that it works now. Maybe I messed code. I've modified the issue for `httpAgent`.

**Comment by xhebox** [comment]
@erezrokah I think I figured out why offline does not work for me. It is still a bug. `--offline` works, but not `-o`. `minimist` parsed `argv.o = true`, but config is using `argv.offline` to judge. Looks like it is another kind of bug...

**Comment by erezrokah** [comment]
Thanks @xhebox, that's very helpful. I opened a new issue for that bug https://github.com/netlify/cli/issues/2400

**Comment by erezrokah** [comment]
Closing in favor of https://github.com/netlify/cli/issues/3115
