### ISSUE TITLE
bug(command-dev): offline flag shorthand version `o` doesn't work

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#2400]
**Describe the bug**

See https://github.com/netlify/cli/issues/2399#issuecomment-841801570

`netlify dev --offline` works but not `netlify dev -o`

**To Reproduce**

1. Run `netlify dev -o` on a machine without network connection

**Configuration**

```bash
  System:
    OS: macOS 11.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 173.85 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.11.2 - ~/.nvm/versions/node/v16.1.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmGlobalPackages:
    netlify-cli: 3.29.15
```

**Expected behavior**

Shorthand version of `offline` should work

**Additional context**

Relevant code https://github.com/netlify/cli/blob/b6da1ac6e1d971c82e00986132da34d6c540a789/src/utils/command.js#L141
See workaround for `deploy`:
https://github.com/netlify/cli/blob/b6da1ac6e1d971c82e00986132da34d6c540a789/src/utils/command.js#L330

The proper solution is to not use `minimist` in the `Command` base class and only rely on `oclif` parsing.

**Comment by tinfoil-knight** [comment]
@erezrokah 
I ran both `./bin/run dev -o` and `./bin/run dev --offline` on a machine with no network. They just opened up a static page with Not Found. (The same thing happened with a network connection.) 

Is there something else I'm supposed to do to reproduce the bug?

```
◈ Netlify Dev ◈
◈ Injected netlify.toml file env var: NODE_VERSION
◈ Injected netlify.toml file env var: AWS_LAMBDA_JS_RUNTIME
◈ Ignored general context env var: LANG (defined in process)
◈ No app server detected and no "command" specified
◈ Running static server from "cli/site/dist"
◈ Loaded function telemetry.
◈ Functions server is listening on 53904

◈ Server listening to 3999

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘
   ```

**Comment by erezrokah** [comment]
Oh sorry I should have been more specific - try setting an env variable in the UI, link the site, and see if those env variables are injected

**Comment by tinfoil-knight** [comment]
The initialization of the `BaseCommand` in `utils/command.js` calls the method `getConfig` which seems to be setting the `offline` variable instead of the oclif parse being used on the `DevCommand` class. I couldn't find a way to use the oclif parser due to the current order of config initialization. Should I just use `argv.offline || argv.o` for a temporary fix here or is there a way to re-structure things to allow oclif parsing?

https://github.com/netlify/cli/blob/53c18ed65e2acb1829146cdfb7fa95b35ef135d0/src/utils/command.js#L146

**Comment by erezrokah** [comment]
> I couldn't find a way to use the oclif parser due to the current order of config initialization. Should I just use `argv.offline || argv.o` for a temporary fix here or is there a way to re-structure code to allow oclif parsing (which would be helpful in multiple places)?

Yes, I think we can go for the fast fix in this case
