### ISSUE TITLE
lm:install, credential helper not configured when using ~/.config/git/config

### ISSUE THREAD

**Issue by kvnsmth** [netlify/cli#2422]
**Describe the bug**

Running `netlify lm:install` did not install correctly since I am using `~/.config/git/config` for my global config. I manually added it to my config but was unable to use LFS (kept getting a credential prompt) before doing so.

**To Reproduce**

1. Use `~/.config/git/config` for global git config.
2. Run `netlify lm:install`
3. See that the credential helper is not installed

**Expected behavior**

Credential helper is installed.

**Additional context**

I think this line is the culprit. A baked in assumption about where the git config lives.

https://github.com/netlify/cli/blob/bc47458f32bffe14e5ecf90d1a30b150931e907d/src/utils/lm/install.js#L163

See the git reference manual for valid global git config locations: https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration

**Comment by sarahetter** [comment]
Large Media is being deprecated
