### ISSUE TITLE
Netlify CLI is only compatible with Node 15 as of earlier today

### ISSUE THREAD

**Issue by Haegin** [netlify/cli#2427]
**Describe the bug**

We use the netlify-cli package on our CI servers as part of our deployment process. As of earlier today it has started failing to install because of an incompatible Node version. The install log is shown below in the CLI output section.

**To Reproduce**

1. Install Node 14 or earlier
2. Install Netlify CLI

**Configuration**

- If possible, please copy/paste below your `netlify.toml`.
- Please enter the following command in a terminal and copy/paste its output:

**Expected behavior**

Netlify CLI installs and runs successfully.

**CLI Output**
```
yarn global add 'netlify-cli@3.29.15' Failed in 00:27
yarn global v1.22.5 00:05
[1/4] Resolving packages... 00:05
warning netlify-cli > @netlify/plugin-edge-handlers > rollup-plugin-node-polyfills > rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject. 00:07
warning netlify-cli > copy-template-dir > readdirp > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated 00:07
warning netlify-cli > copy-template-dir > readdirp > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated 00:07
[2/4] Fetching packages... 00:27
info @netlify/traffic-mesh-agent-darwin-x64@0.27.10: The platform "linux" is incompatible with this module. 00:27
info "@netlify/traffic-mesh-agent-darwin-x64@0.27.10" is an optional dependency and failed compatibility check. Excluding it from installation. 00:27
info @netlify/traffic-mesh-agent-win32-x64@0.27.10: The platform "linux" is incompatible with this module. 00:27
info "@netlify/traffic-mesh-agent-win32-x64@0.27.10" is an optional dependency and failed compatibility check. Excluding it from installation. 00:27
info fsevents@2.3.2: The platform "linux" is incompatible with this module. 00:27
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation. 00:27
error @netlify/eslint-config-node@2.6.11: The engine "node" is incompatible with this module. Expected version ">=15.0.0". Got "10.22.0" 00:27
error Found incompatible module.
```
**Additional context**

I'm running this on Semaphore CI in case that's useful.

**Comment by erezrokah** [comment]
Hi @Haegin, can you share the output of `npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli`?

`@netlify/eslint-config-node@2.6.11` is a dev dependency so it should not be installed.

Can you:
1. Update your `npm` version via `npm install -g npm`
2. Install via `npm` via `npm install -g netlify-cli`

**Comment by Wyfy0107** [comment]
I experienced this earlier today in github actions

**Comment by erezrokah** [comment]
Hi @Wyfy0107 this should be fixed in https://github.com/netlify/cli/releases/tag/v3.30.2.

Can you try via `yarn add global netlify-cli`?
