### ISSUE TITLE
chore: add tests on the published npm artifact

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#2430]
Since we automate `npm` publishing, it should be fairly easy to add tests that ensure the published artifact installs/works correctly.

We can achieve this by `npm` or `yarn` installing the published version in CI after we publish it.

> We might need to retry the installation as sometimes there's a delay between the time `npm publish` finishes to the time the package is available

**Comment by ehmicky** [comment]
One note: it sometimes takes several seconds after `npm publish` to be able to `npm install` a package.

**Comment by erezrokah** [comment]
A better way to do it might be to use a local registry for testing https://verdaccio.org/docs/en/e2e
