### ISSUE TITLE
"netlify dev" specific context

### ISSUE THREAD

**Issue by mashaalmemon** [netlify/cli#2433]
**Is your feature request related to a problem? Please describe.**

I have setup my app to work with "dev_local" (development code on local machine), "development" (development code in shared environment), "staging" (near production code in shared environment), "production" (production code in production environment). Lets call these application environments. I have settings specific to each in my secret environment variables stored in the netlify environment that is stored in netlify. However, I need one environment variable to be set, "APP_ENV" in order to have my code use the proper secret environment variables.

This setup works great with build contexts and branch contexts. However I don't have a way of setting "APP_ENV" explicitly for "netlify dev".

**Describe the solution you'd like**

 I'd like to set environment variables for "netlify dev". Are there any plans to allow environment variables to be set in a context specifically for "netlify dev"? Maybe something like a "context.dev" option? 

Alternatively, if there was a --context switch for the netlify dev command, that would be workable. Then I could run "netlify dev" with environment variables set for a particular context. Right now it seems to only run in the "context.production" context.

**Describe alternatives you've considered**

Based on #444:

* I understand we can use .env files for "netlify dev". If I wanted to propogate such settings to my team I'd need to checking the .env file. It's also not clear, will the .env file affect production settings or will it only override environment variables for "netlify dev"?
* We can also check "NETLIFY_DEV" env variable and use conditions to do specific things in code. Not an ideal solution but workable.

**Additional context**

None.

**Can you submit a pull request?**

No.

**Comment by erezrokah** [comment]
Hi @mashaalmemon, using `dev` context should work with `netlify dev` like [any other context](https://docs.netlify.com/configure-builds/file-based-configuration/#deploy-contexts).

Can you try using the following in `netlify.toml`?

```toml
[context.dev.environment]
HELLO = "World"
```

**Comment by erezrokah** [comment]
Closing this as stale
