### ISSUE TITLE
[v2.7.0] netlify addons:create broken/does not fail gracefully

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#244]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**

`netlify addons:create fauna` in a fresh, linked, project gets this error:

```
TypeError: Cannot read property 'id' of undefined
    at addonsCreateCommand.run (~/.nvm/versions/node/v10.13.0/lib/node_modules/netlify-cli/src/commands/addons/create.js:43:22)
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

as above

**- What is the expected behavior?**
should create or at least give a helpful error

**- Please mention your node.js, and operating system version.**
node 10, mac osx

---

Commentary: the source of this error is the addons list returning `[]` [here](https://github.com/netlify/cli/blob/master/src/commands/addons/create.js#L26). regardless, when we use [find](https://github.com/netlify/cli/blob/master/src/commands/addons/create.js#L36) we should make sure to null check before [referring to the id](https://github.com/netlify/cli/blob/master/src/commands/addons/create.js#L38).

TypeScript would help here.

**Comment by Muaaz852** [comment]
I am also getting this error, anybody found any solution?

**Comment by DavidWells** [comment]
@Muaaz852 we have found the issue and are releasing the fix soon!

**Comment by Muaaz852** [comment]
@DavidWells Thanks Sir, I am waiting for the release.

**Comment by bcomnes** [comment]
Fix in `netlify-cli@2.8.0`! https://github.com/netlify/cli/releases/tag/v2.8.0

**Comment by DavidWells** [comment]
Ok its out now https://github.com/netlify/cli/releases/tag/v2.8.0

Sorry for the troubles.

What add-on are you trying to use?

**Comment by Muaaz852** [comment]
@DavidWells FaunaDB
That's a very fast response. Thanks @DavidWells  @bcomnes
