### ISSUE TITLE
Credential helper doesn't add osxkeychain to config file

### ISSUE THREAD

**Issue by jordanthornquest** [netlify/cli#2447]
My existing global `~/.gitconfig` includes a credential helper for using `osxkeychain`. After running `netlify lm:install`, the contents of `~/Library/Preferences/netlify/helper/git-config` are:

```

# The first line resets the list of helpers so we can check Netlify's first.
[credential]
  helper = ""

[credential]
  helper = netlify
```

This results in my Git configuration failing to recognize my Git credentials when pushing to my repositories. I'm assuming that the Netlify helper is supposed to identify that I'm using the `osxkeychain` helper and migrate it, but it doesn't appear to do so. If I manually update Netlify's config to include the following line:

```
# Also fixed the empty first line in the generated file
# The first line resets the list of helpers so we can check Netlify's first.
[credential]
  helper = ""

[credential]
  helper = netlify
  helper = osxkeychain
```

It works again. I'm on Big Sur 11.3.1 with an M1 MacBook Air.

**Comment by jordanthornquest** [comment]
For sure. Running the command in my home folder returns:

```shell
  System:
    OS: macOS 11.3.1
    CPU: (8) arm64 Apple M1
    Memory: 987.78 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.2.0 - ~/.nvm/versions/node/v16.2.0/bin/node
    npm: 7.13.0 - ~/.nvm/versions/node/v16.2.0/bin/npm
  npmGlobalPackages:
    netlify-cli: 3.30.4
```

**Comment by sarahetter** [comment]
Large Media is deprecated
