### ISSUE TITLE
Add `--silent` and `--json` flags

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#248]
Certain commands need 2 flags

`--silent` This will stop all console.log and output back to stdout

`--json` This will stop all console.log message and instead of printing tables/words/etc the raw API responses will be returned. This is for programatic usage with tools like [jq](https://stedolan.github.io/jq/)

## What will need to change

We need to do an overhaul on all the `this.log` + `console.log` into a common utility logger. This way we can silence output in one place. It could be implemented under `this.log` if we have access to change that.

Here is pseudo example:

```
function logger(msg) {
  if(argv[0].silent || process.env.NETLIFY_NINJA_MODE) {
    return
  }
  console.log(msg)
} 
```

**Comment by DavidWells** [comment]
You can see the `--json` flag in action with the `netlify addons:list --json` command.

Ideally we could make this global so we don't need to add flag everywhere but it would be okay to add to individual commands that actually have JSONable output

**Comment by travismiller** [comment]
This is something I'd like to help out with 👋

`this.log` comes from extending [`@oclif/command`](https://github.com/oclif/command/blob/fa7de62c92b3f9ded0d8453587baf7b4c5fe7e3d/src/command.ts#L94-L98) so if clobbering existing functionality from oclif is acceptable, it could easily be overridden in `BaseCommand`.

Alternatively, would it be worth considering directing meta output to *stderr* ?

###### References
- https://oclif.io/docs/commands#command-methods
- https://github.com/oclif/command/blob/fa7de62c92b3f9ded0d8453587baf7b4c5fe7e3d/src/command.ts#L94
- Reasonable universal logging library: https://github.com/winstonjs/winston

**Comment by DavidWells** [comment]
Asking oclif https://spectrum.chat/oclif/general/possible-to-set-global-flags~ea91f640-8e41-42fa-a8dc-0d601c1d12bc

We might need another way to achieve this.

**Comment by DavidWells** [comment]
Also a global `--auth` flag would be nice.

**Comment by DavidWells** [comment]
Related https://github.com/netlify/cli/issues/222
