### ISSUE TITLE
netlify dev --live not hot-reloading

### ISSUE THREAD

**Issue by jfrancos** [netlify/cli#2509]
**Describe the bug**

`netlify dev --live` does create a tunnel, but does not hot reload

**To Reproduce**
```
npx create-react-app live-test
cd live-test
netlify init
netlify dev --live
```
[edit the page and save, it does not hot reload]

**Configuration**

- If possible, please copy/paste below your `netlify.toml`.
- Please enter the following command in a terminal and copy/paste its output:

```
System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 139.49 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.2.0 - ~/.nvm/versions/node/v16.2.0/bin/node
    npm: 7.13.0 - ~/.nvm/versions/node/v16.2.0/bin/npm
```
```
$ netlify --version
netlify-cli/3.32.1 darwin-x64 node-v16.2.0
```

**Expected behavior**

I expect that when I edit `App.js` and save it, the edits I make will update in the webpage opened by the dev --live command without me having to refresh the page manually.  This works correctly with `netlify dev`, sans `--live`

**Comment by jfrancos** [comment]
In case it helps, sometimes I see this message in the js console:
```
hmr-client.js:58 WebSocket connection to 'wss://xxxxx.netlify.live:3000/' failed:
(anonymous) | @ | hmr-client.js:58
```

**Comment by serhalp** [comment]
Marking this as stale as it is is several years old. Please feel free to reopen if you are still having issues.
