### ISSUE TITLE
[Addons] netlify addons:delete doesn't work

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#256]
**Describe the bug**
through the cli, i can create an addon, but when i try to delete it, it says my addon isn't there

**To Reproduce**
1. fresh project
2. netlify addons:create demo
3. netlify addons:delete demo
4. `No add-on "demo" found for site. Add-on already deleted or never existed!`

**Expected behavior**
it should delete properly

**Screenshots**
![image](https://user-images.githubusercontent.com/6764957/53193715-c4e1dd00-35b5-11e9-8bb3-862dbd39280a.png)

**Additional context**
Add any other context about the problem here

**Comment by erezrokah** [comment]
Closing this as stale. Please comment if still relevant
