### ISSUE TITLE
Information about global uniquness requirement for site name (in error message and/or documentation)

### ISSUE THREAD

**Issue by szpak** [netlify/cli#257]
I'm new to the Netlify world and it took me some time to create the first site using cli due to that ~bug~ behavior.

**- Do you want to request a *feature* or report a *bug*?**
A bug

**- What is the current behavior?**
**- If the current behavior is a bug, please provide the steps to reproduce.**

When trying to create **the first site** with a **custom** (human readable) **name** (as offered by many  commands in cli, including: init, deploy, sites:create, ...) the procces fails with confusing error.

```
$ netlify sites:list
Loading your sites... done
$ netlify deploy
This folder isn't linked to a site yet
? What would you like to do? +  Create & configure a new site
Choose a site name or leave blank for a random name. You can update later.
? Site name (optional): test3
? Account: XXX YYY  (personal)
Error 422: Unprocessable Entity from createSiteInTeam call
 ›   Error: A site with name test3 already exists. Please try a different slug
```

As a workaround I needed to create the first side with undefined name and after that the following sites with a custom name are created fine.

```
$ netlify sites:create
Choose a site name or leave blank for a random name. You can update later.
? Site name (optional): undefined
? Account: XXX YYY  (personal)

Site Created
...

$ netlify sites:create --name test7
? Account: XXX YYY  (personal)

Site Created
...
```

**- What is the expected behavior?**
I would like to create the first site on the new account with a custom name (or at least get less cryptic error message).

**- Please mention your node.js, and operating system version.**
Software: netlify-cli/2.8.0 linux-x64 node-v10.15.0 on Fedora 29.

**- More information.**
I could provide debug logs if you had problem reproducing the issue for the new account.

Btw, I had to grep the source code to get know how to enable debug logging for netlify-cli. I haven't found `DEBUG=*` in the project documentation (and I'm not a nodejs developer to know that). IMO, it would be good to add it to https://www.netlify.com/docs/cli/

It may be somehow related to #157.

**Comment by szpak** [comment]
Ehhh, I didn't know that site names have to unique globally... Anyway, the error message could inform about that.

Closing as invalid.

**Comment by bcomnes** [comment]
@szpak Thats a good suggestion. I'm going to reopen as a reminder to investigate.

**Comment by erezrokah** [comment]
Closing this as stale. Tried to reproduce and couldn't so it seems this was fixed by https://github.com/netlify/cli/pull/342
