### ISSUE TITLE
Connecting site by git remote url not working for private repos

### ISSUE THREAD

**Issue by verythorough** [netlify/cli#258]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
When running `netlify link` to connect a local repo to an existing site, you have the option to find the matching site using the current git remote url:
![use-current-remote](https://user-images.githubusercontent.com/6111186/53278062-e3320080-36bb-11e9-98ab-d06ebdd44276.png)

I've tested on several private and public repos now, and the public ones consistently work, and the private ones consistently fail to find a linked repo:
![not-found](https://user-images.githubusercontent.com/6111186/53278135-5f2c4880-36bc-11e9-829a-3bfe2f9b2dc6.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**
In a local clone of a private repo, run `netlify link`, and choose the default option to find the site by remote.

**- What is the expected behavior?**
It finds the site(s) in all cases. :)

**- Please mention your node.js, and operating system version.**

Tried on multiple machines:
netlify-cli/2.8.0 win32-x64 node-v10.15.0
netlify-cli/2.8.0 darwin-x64 node-v10.15.0

**Comment by DavidWells** [comment]
The API call needs `?filter=all`. `https://api.netlify.com/api/v1/sites?filter=all`

Needs to get updated here: https://github.com/netlify/cli/blob/f9bc8177e6f75ea85c44b9ef6455393a2e96ebb0/src/utils/link/link-by-prompt.js#L60

@bcomnes does https://github.com/netlify/js-client support query params like this?

**Comment by bcomnes** [comment]
@DavidWells any parameter listed in the operations over at https://open-api.netlify.com/#/default/listSites will work if you pass them in as an object to the call

```js
const sites = await api.listSites({
  name: 'whatever',
  filter: 'foo bar'
})
```

**Comment by DavidWells** [comment]
Tried that here https://github.com/netlify/cli/blob/f9bc8177e6f75ea85c44b9ef6455393a2e96ebb0/src/utils/link/link-by-prompt.js#L60

```
const sites = await api.listSites({
   filter: 'all',
})
```

It pulls back more sites but not all if you have more than 100. Pagination params didn't seem to work

**Comment by bcomnes** [comment]
Yeah, still need to add https://github.com/netlify/js-client/issues/39

**Comment by erezrokah** [comment]
`filter: all` was done in https://github.com/netlify/cli/pull/500.
Keeping this open until we sort pagination
