### ISSUE TITLE
Serverless functions timing out when "Expect:100-continue" header recieved

### ISSUE THREAD

**Issue by benlavalley** [netlify/cli#2591]
**Describe the bug**

Upon receiving a POST request from a third party webhook (Snipcart) with an "Expect: 100-continue" header, my serverless functions on my development environment would time out with the following error:

```
BadRequestError: request aborted
    at IncomingMessage.onAborted (/usr/local/lib/node_modules/netlify-cli/node_modules/body-parser/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:314:20)
    at abortIncoming (_http_server.js:533:9)
    at socketOnClose (_http_server.js:526:3)
    at Socket.emit (events.js:326:22)
    at TCP.<anonymous> (net.js:675:12)
```

```
1) Setup an app that uses a Netlify serverless function
2) Execute a curl command against that function's API as follows:

curl -d '{"somefield":"somevalue"}' -H 'Content-Type: application/json' -H 'Expect: 100-continue' http://localhost:8000/.netlify/functions/yourServerlessFunction -v

3) Observe the error above being written after around 60 seconds

```
**Expected behavior**

I would expect this function to at least receive the event / context values, but it is instead not throwing an error at all.

**Additional Context**

On my Netlify production app, it properly receives the event and context, so this appears to be specific to netlify-cli and/or netlify-lambda.

I opened a PR to add a feature to Netlify to allow it to strip out unwanted headers as far upstream as I could in the http handling stack, and it did solve my issue (https://github.com/netlify/cli/pull/2572).

**Comment by erezrokah** [comment]
This is due to https://github.com/http-party/node-http-proxy/issues/1219.

There is a suggested workaround in that issue.

**Comment by erezrokah** [comment]
Hi @benlavalley, I opened https://github.com/netlify/cli/pull/2599 to fix this issue.
Thanks for pointing us in the right direction. 

I'm also good with merging your fix if you modify it per https://github.com/http-party/node-http-proxy/issues/1219#issuecomment-511110375
