### ISSUE TITLE
Add `netlify api` command

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#261]
Add a new command that proxies to calls to underlying [js-client](https://github.com/netlify/js-client) based on the [OpenAPI](https://open-api.netlify.com/#/default) spec.

Example:

```
netlify api listSiteForms
# calls https://open-api.netlify.com/#/default/listSiteForms and returns json
```

```
netlify api --help
# list out available lower lvl CLI calls
```

```
netlify api listSiteFiles
# run https://open-api.netlify.com/#/default/listSiteFiles
```

This will give people an easy way to make netlify API calls in their CI processes.

I have a use case where I need to query the existing deploys in my CI process and right now I need to wire together my own custom scripts to achieve this. Where as with a simple CLI command I could get the data I need

```
netlify api listSiteDeploys | jq length
# returns number of deploys 2
```

## Considerations

Deletion calls should require a `--confirm` flag to avoid accidentally destroying resources.

## About

This is modeled off the AWS cli where you can call out directly to lower level commands. https://docs.aws.amazon.com/cli/latest/reference/acm/index.html

**Comment by DavidWells** [comment]
This is also an escape hatch for commands that don't have a top level CLI command (and likely never will)

**Comment by calavera** [comment]
this is cool :+1:

**Comment by bcomnes** [comment]
Sounds good, could be dangerous but fun.
