### ISSUE TITLE
Support for Background Functions

### ISSUE THREAD

**Issue by compwright** [netlify/cli#2697]
When testing via `netlify dev`, [events](https://docs.netlify.com/functions/trigger-on-events/#available-triggers) do not trigger [background functions](https://docs.netlify.com/functions/background-functions/).

For instance, given the `submission-created` event, only `submission-created.js` is invoked, and `submission-created-background.js` is not invoked (if present).

**Describe alternatives you've considered**

A workaround is available by using a stubbing out a normal event handler function to execute the background event handler function code:

```javascript
// submission-created.js
if (process.env.CONTEXT === 'dev') {
  const background = require('./submission-created-background');
  exports.handler = function (event, context) {
    // invoke the background function and then return a response
    background(event, context);
    return { statusCode: 204 };
  }
}
```

**Comment by erezrokah** [comment]
Hi @compwright, thank you for reporting this issue. I changed the classification to a bug.

To confirm - you're running `netlify dev` and then `netlify functions:invoke submission-created-background`?

**Comment by erezrokah** [comment]
Another possible issue `curl -i -d '{"somefield":"somevalue"}' -H 'Content-Type: application/x-www-form-urlencoded' http://localhost:8888/some-form` should trigger either `submission-created` or `submission-created-background`, which at the moment it only triggers `submission-created`.

**Comment by compwright** [comment]
@erezrokah that was fast! Thank you for addressing this.
