### ISSUE TITLE
Netlify-dev not stopping previous functions

### ISSUE THREAD

**Issue by NAllred91** [netlify/cli#2703]
**Describe the bug**

I'm using netlify-dev to work on my Netlify Functions locally.  When I make a change to my functions, they are automatically rebuilt and when I call the function I can tell it picked up my changes.

However, it seems that the previous function versions remain alive.  I would expect that when netlify-dev rebuilds my functions, the old ones are terminated.  Alternatively, I'd expect some way that I can tell netlify-dev to stop these functions.

**To Reproduce**

1. Create a netlify functions
2.  Add the following setInterval
```
setInterval(() => {
    console.log('Hello');
}, 5000);
```
3. Call the function and see the interval start.
4. Remove the setInterval and see the functions rebuild.
5. Call the function again, but you'll see the setInterval from the previous function is still going.

**Additional Information**

I'm using `serverless-http` for my express routes in my function. I'm keeping my database connection so that I only create the connection on a cold start of the function.

Unfortunately, every time my functions rebuild the database connection from the previous function remains.

**Comment by NAllred91** [comment]
Just to clarify, I'm putting the `setInterval` outside of my handler function.

**Comment by serhalp** [comment]
Marking this as stale as it is is several years old. Please feel free to reopen if you are still having issues.
