### ISSUE TITLE
Absolute redirects not working

### ISSUE THREAD

**Issue by codefromthecrypt** [netlify/cli#2708]
**Describe the bug**

redirects like below redirect to a relative path, not the full URL

**To Reproduce**

Setup a redirect and run `netlify dev`. execute `curl -v http://localhost:8888/FROM_PATH_HERE`

**Configuration**

```
[[redirects]]
from = "/download/*"
to = "https://github.com/tetratelabs/archive-envoy/releases/download/:splat"
force = true
status = 302
```

**Expected behavior**

I'd expect `curl -v http://localhost:8888/download/v1.12` to result in a Location: https://github.com/tetratelabs/archive-envoy/releases/download/v1.12

**CLI Output**

**Additional context**

maybe #2327

**Comment by tinfoil-knight** [comment]
@erezrokah Tried this out locally. Redirects work for me. I think this was fixed by https://github.com/netlify/cli/pull/4109. Please check once and close the issue.
