### ISSUE TITLE
DX: Better error handling when function/publish folder missing

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#272]
Right now the error message is 

`No such directory! Make sure to run your build command locally first`

https://github.com/netlify/cli/blob/ccdaabc7ecc83ece9629be0b38ca80f3bddd1c71/src/commands/deploy.js#L347

This doesn't tell the user which directory is missing. Is it the "functions" directory or the "publish" directory.

We need to add in context of what is missing so people can easily fix the issue

**Comment by sw-yx** [comment]
quick fixed put in https://github.com/netlify/cli/commit/783c4cc398ec2c7a3f7b66c7842d34f321ca3ba0. can always improve error msg so leaving issue open

**Comment by erezrokah** [comment]
Closing this as stale. We can re-visit in the future is needed.
