### ISSUE TITLE
chore: refactor logging

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#2728]
At the moment we need to pass down the `oclif` logging utilities down to each function.
That makes it very hard to refactor existing functions and uglifies the code.

We could create a global logging utility/object and initialize it during command initialization.
Then we could expose it to be used from any function simply by requiring it.

Somehow related to https://github.com/netlify/cli/issues/1846

**Comment by tinfoil-knight** [comment]
The changes made in https://github.com/netlify/cli/pull/2827 to extract the utilities from the base `Command` class would fix this issue too.

**Comment by tinfoil-knight** [comment]
@erezrokah Should I take this one up after #2827 is merged?

**Comment by erezrokah** [comment]
> @erezrokah Should I take this one up after #2827 is merged? (Please assign if so.)

Yes please, that would be great!


> Would be refactoring the leftover `warn` and `error` utilities.

💯

**Comment by ehmicky** [comment]
Fixed thanks to @tinfoil-knight! :tada:
