### ISSUE TITLE
Quick fix: Update "link directory text"

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#273]
Remove odd character: https://github.com/netlify/cli/blob/ccdaabc7ecc83ece9629be0b38ca80f3bddd1c71/src/commands/deploy.js#L30

`â‡„  Link this directory to an existing site`, the `â‡„ ` character looks odd/broken

Swap it out for literally anything else 😁

**Comment by sw-yx** [comment]
git blame says this one is @bcomnes's artwork :) something youre trying to tell us bret?
