### ISSUE TITLE
when command requires linked site but isnt linked, offer to netlify link, and then continue command flow

### ISSUE THREAD

**Issue by swyxio** [netlify/cli#277]
**- Do you want to request a *feature* or report a *bug*?**

feature

**- What is the current behavior?**

when a command requires linked site but isnt linked, it generally just complains and dies. experienced by Mathias during a demo today

**- What is the expected behavior?**

when command requires linked site but isnt linked, offer to `netlify link`, and then continue command flow

**- Please mention your node.js, and operating system version.**

n/a

**Comment by DavidWells** [comment]
Sounds good!

One note: the prompt shouldn’t effect CI use. That is to say: when the CLI is running in CI (no humans) the CLI should fail and not show any prompt.

**Comment by BattulgaTS** [comment]
@DavidWells what does CI stand for?

**Comment by erezrokah** [comment]
This happens with the `deploy` command, but not with `addons`:
https://github.com/netlify/cli/blob/01b3419f85b4bae941bafb3ad9ad85db473314a7/src/commands/deploy.js#L49
https://github.com/netlify/cli/blob/01b3419f85b4bae941bafb3ad9ad85db473314a7/src/commands/addons/create.js#L27

**Comment by sarahetter** [comment]
deprecating addons
