### ISSUE TITLE
Redirect converts POST request to a GET request without body

### ISSUE THREAD

**Issue by varna** [netlify/cli#2785]
**Describe the bug**

Redirect converts POST request to a GET request without body

**To Reproduce**

1. Create a POST function i.e. `/.netlify/functions/create-ticket`
2. Redirect `/create-ticket` to `/.netlify/functions/create-ticket` via `_redirects` or `netlify.toml`
3. POST `/create-ticket` redirects to GET `/.netlify/functions/create-ticket` without body

Same happens in `netlify dev` (netlify-cli/3.39.0 darwin-x64 node-v12.7.0) and production deployments.

**Configuration**

- If possible, please copy/paste below your `netlify.toml`:
```
[build]
  functions = "functions"
[[redirects]]
  from = "/create-ticket"
  to = "/.netlify/functions/create-ticket"
```
- Please enter the following command in a terminal and copy/paste its output:
```bash
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 114.97 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.10 - /usr/local/bin/npm
  npmGlobalPackages:
    netlify-cli: 3.39.0
```

**Expected behavior**

POST `/create-ticket` redirects to POST `/.netlify/functions/create-ticket` with body

**CLI Output**

While in `netlify dev` and requesting POST `/create-ticket` I receive this message in bash:
```
Request from ::1: GET /.netlify/functions/create-ticket
```

**Comment by rgrannell1** [comment]
I'm encountering this bug too, has it been patched?

**Comment by varna** [comment]
> I'm encountering this bug too, has it been patched?

dunno, haven't touched that project since 2021 Jun

**Comment by mecklundie** [comment]
I can confirm the same problem is occurring here. 

Redirecting all Requests. With the first redirect intended to trump the catch-all redirect. The create-token should be a POST request. It's redirecting just fine, hitting the lambda function just fine, however, it's changing from a POST request to a GET request when the redirect occurs.

[[redirects]]
from = "/api/rest/create-token"
to = "/.netlify/functions/create-token"
status = 200

[[redirects]]
from = "/api/rest/*"
to = "/.netlify/functions/router"
status = 200

**Comment by Razz21** [comment]
Try with temporary redirect status

```
[[redirects]]
  from = "/create-ticket"
  to = "/.netlify/functions/create-ticket"
  status=307 // <-- temporary redirect
  force = true
```

**Comment by serhalp** [comment]
Marking this as stale as it is is several years old. Please feel free to reopen if you are still having issues.
