### ISSUE TITLE
DX: Validate function names before deploy

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#279]
If files in `functions` directory have `.` in them they will cause the deploy to hang indefinitely. 

Before deploying, we need to validate the function file names and stop the deploy if there are invalid function names.

https://drive.google.com/a/netlify.com/file/d/1JU29h4kYapXfXcYMYhEz9NtuL3k3V8zd/view?usp=drivesdk

`functions/foo.test.js` should cause `netlify deploy` to throw with warning "Invalid character in function name, please rename the file or move it to a sub directory"

**Comment by erezrokah** [comment]
I can confirm this issue is resolved. See error:
![image](https://user-images.githubusercontent.com/26760571/117151969-3cc90600-adc2-11eb-81af-43ac3dbbb07f.png)
