### ISSUE TITLE
Netlify Rewrites does not work in Netlify App but works when using `netlify dev`

### ISSUE THREAD

**Issue by surjithctly** [netlify/cli#2793]
**Describe the bug**

I have a simple Next.js App with a  [slug].js and I have no index.js file. Instead I have added an option to rewrite `/` to `/home` using rewrites. It worked perfectly on `netlify dev` but when I updated in netlify app, It doesn't work. 

This is what I written on `_redirects`

```
/  /home  200!
```

The rewrites works as expected in dev cli, but in netlify app, its not working.  This has also been discussed on https://answers.netlify.com/t/next-js-rewrites-not-working/40017/ before adding it as an issue here. 

**To Reproduce**

1. create next.js app
2. delete `pages/index.js` and add `[slug].js` which can handle `/home`
3. Run `netlify dev` and see `/` redirects to `/home` as expected
4. Now Push the project to Netlify
5. See the `/` no more rewriting. 

**Configuration**

Issue is in Netlify Production server.

**Expected behavior**

`/` should redirect to `/home` dynamic path same as `netlify dev` for Netlify Server as well. If the feature is not supported, then `netlify dev` should throw error. 

**netlify dev CLI Output**

![image](https://user-images.githubusercontent.com/1884712/123804279-efd54d80-d8a1-11eb-9e90-ba57bcd99907.png)

**Comment by erezrokah** [comment]
Hi @surjithctly, thanks for reporting this issue.

Can you share a public repo as a reproduction?

If not can you answer the following questions:
1. Are you using the [Next.js plugin](https://github.com/netlify/netlify-plugin-nextjs)? If so, which version?
2. What are your build command, publish directory and functions directory as configured in Netlify?
3. Can you share your `netlify.toml` file if exists?
4. Can you add the output of the following command `npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli`?

Thanks!

**Comment by surjithctly** [comment]
Hello,

1. Yes, Next plugin is added automatically, so It should be latest 3.5.0
2. Build command is also default. No changes made. All set by netlify
3. file does not exists but I have `_redirects` with above code
4. Not sure how to run this command on netlify dashboard, And I think I don't need to run it in my system since there is no issue here. The issue is on the Netlify Server. Local machine works fine.
5. /pages contains [slug].js which has getstaticprops & getstaticpaths with fallback true. 

Let me know if you need anything else.

**Comment by serhalp** [comment]
Marking this as stale as it is is several years old. Please feel free to reopen if you are still having issues.
