### ISSUE TITLE
Fails to deploy after linking unlinked project

### ISSUE THREAD

**Issue by theTulga** [netlify/cli#280]
**- Do you want to request a *feature* or report a *bug*?**
BUG

**- What is the current behavior?**
When netlify deploy is run in unlinked folder, Netlify offers linking and successfully links but it complains "Error: Missing required param site_id".
https://drive.google.com/file/d/12qdmpHm3YTRDGotbWc5J5yQ3oiS6fnXJ/view?usp=sharing

**- If the current behavior is a bug, please provide the steps to reproduce.**
on your command line run:
`Netlify unlink`
`Netlify deploy`

**- Please mention your node.js, and operating system version.**
Node 11.10.0, Mac OS

**Comment by DavidWells** [comment]
Sites need to be linked to a live site for deployment to work.

```
netlify link
netlify deploy
```

^ this should fix your issue

**Comment by DavidWells** [comment]
or 

```
netlify init
netlify deploy
```
