### ISSUE TITLE
production branch deployments to work with locked deployments

### ISSUE THREAD

**Issue by kirillgroshkov** [netlify/cli#281]
**- Do you want to request a *feature* or report a *bug*?**

We internally consider it a bug, because it's not documented and not obvious for our developers.

**- What is the current behavior?**

You have branch `abc` in git, you push a commit there, you get a url with the fragment that matches your git branch name, e.g `abc--project.netlify.com`. That's an amazing feature and one of the reasons we use Netlify. All great.

It works good for all branches, *but* the "production branch" (branch that you set as "production branch" in netlify UI).

We use "locked deployments", so we lock our production website to use specific deployment, unless we want to "publish" a new deployment.

If `abc` is the name of your production branch, then `abc--project.netlify.com` will NOT show you the most up-to-date deployment from this branch (as expected). Instead it will show you the same deployment that is currently published. So, `abccompany.com` (public url) content will match `abc--project.netlify.com` URL, despite the fact that `abc` branch had more commits after.

**- What is the expected behavior?**

`abc--project.netlify.com` points to the HEAD of `abc` branch deployment.
`abccompany.com` points to "published" deployment.

**- Workaround**

We've found a workaround of this "bug" internally, but it doesn't feel good to use it. It's the following.

Create a fake branch called `fake` and assign it as Production branch in netlify CLI. This way branch `abc` that previously was Production will stop being that, and hence will avoid the bug described above. Win. Meanwhile it's still possible to publish deployments from non-production branch `abc`.

What is not nice here, is that UI in Netlify will show wrong branch (`fake`) as "Production". Could be more not nice consequences.

**Comment by erezrokah** [comment]
Not sure if this still an issue, and sorry for the lack of response.
This doesn't seem like a CLI issue.
I recommend reporting in our community http://community.netlify.com/ if still relevant.
