### ISSUE TITLE
[easy] add .netlify to .gitignore if exists, on `netlify init`

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#282]
**- Do you want to request a *feature* or report a *bug*?**
[easy] add .netlify to .gitignore if exists, on `netlify init`

**- What is the current behavior?**

no action

**Comment by biilmann** [comment]
I don't think we want to ignore the .netlify folder - it's useful that everyone in the same repo get the same site id if doing manual deploys

**Comment by DavidWells** [comment]
`.netlify` will likely contain more things in the future (caches, plugin data, etc). 

If people want to manually set the ID (which limits the reuse of the repo), they can set that in the `netlify.toml` file 

I’d wager this property is not used very often in Netlify.toml. 

I think we should ignore the `.netlify` folder by default
