### ISSUE TITLE
netlify.toml variable overriding doesn't work as expected

### ISSUE THREAD

**Issue by sartios** [netlify/cli#284]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

I've defined a netlify.toml file with my environment variables for a gatsby site. The variables overriding doesn't work as expected.

**- If the current behavior is a bug, please provide the steps to reproduce.**

 I have defined the following sections in the netlify.toml file.

Prodction section
[context.branch-deploy.environment]
  GATSBY_TEST_VAR_1="sth"

Branch specific section
[context."feat/a-branch".environment]
  GATSBY_TEST_VAR_1=""

**- What is the expected behavior?**

I expect the GATSBY_TEST_VAR_1 to be an empty string when I access the deployed branch. However, it gets the non-empty value from the upper scope.

If I add extra variables on the branch-specific configuration, they are accessible

**- Please mention your node.js, and operating system version.**

**Comment by erezrokah** [comment]
Sorry for the very late response.
Not sure if this is happening for the CLI or when deploying on Netlify.
Going to close as stale.
If still an issue please submit a reproduction scenario with possibly a repo with can use
