### ISSUE TITLE
CLI authentication chokepoint?

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#285]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
authenticated cli calls take some time.

https://github.com/netlify/cli/blob/932c001b0334aaf3fb1c27e8843074bc4502996b/src/base/index.js#L86

i believe this is a key choke point for our CLI perf - we keep having to check current user even though we have a recent/valid access token. that adds 1-3ish seconds to every authenticated call. i’d like to remove it, and/or implement some sort of expiry strategy. can i? cc @bcomnes  and whoever else knows this better

**Comment by bcomnes** [comment]
Open to ideas.

**Comment by DavidWells** [comment]
We might be able to:

1. Check local token for expiration (no validation)
2. Try / catch the api calls if they fail
3. If failure, prompt for “Netlify login” to refresh token

This might* work and cut out the additional request. It should only effect users who OAuth CLI and have revoked token

**Comment by sw-yx** [comment]
clsoing as duplicate of #286 i'm not sure what i was thinking
