### ISSUE TITLE
Remove license incompatible safe-join dependency

### ISSUE THREAD

**Issue by timroes** [netlify/cli#2896]
`netlify-cli` is currently using the [`safe-join`](https://www.npmjs.com/package/safe-join) package as a dependency. This package is unlicensed (i.e. has full propietary protection) and thus is incompatible with the MIT license `netlify-cli` uses. I think given that the code in that package is super small, it would make more sense just inlining a utility function that does the same. Despite the legal problem of using this package with incompatible licenses, having that dependency can cause issues in projects depending on `netlify-cli` who do automatically check their licenses to make sure only compatible licenses are used.

**Comment by erezrokah** [comment]
Thanks @timroes, would https://github.com/jfromaniello/url-join serve as a good replacement?
I actually favor super small utility libraries as they usually do one thing very well, they have tests to cover edge cases we won't think about.

`url-join` hasn't been updated in a while, but seems to be [very highly used](https://www.npmjs.com/package/url-join).

**Comment by timroes** [comment]
Since my concern is mainly around licensing, I'd say `url-join` would be a viable replacement, given it's licensed under MIT :-)

And without going into too much discussion into wether small utility libraries are a good thing or a bad thing, I'd just saw, that very highly used is unfortunately not an indicator for whether it will not break your code your ecosystem at some point (just thinking back about the [left-pad desaster](https://qz.com/646467/how-one-programmer-broke-the-internet-by-deleting-a-tiny-piece-of-code/)).

**Comment by erezrokah** [comment]
> And without going into too much discussion into wether small utility libraries are a good thing or a bad thing, I'd just saw, that very highly used is unfortunately not an indicator for whether it will not break your code your ecosystem at some point (just thinking back about the [left-pad desaster](https://qz.com/646467/how-one-programmer-broke-the-internet-by-deleting-a-tiny-piece-of-code/)).

True, we're trying to minimize such issues by pinning dependencies using a [shrinkwrap](https://docs.npmjs.com/cli/v7/commands/npm-shrinkwrap) file and relying on [this policy](https://www.npmjs.com/policies/unpublish) being enforced.

**Comment by erezrokah** [comment]
To the issue at hand, we'd be happy to accept a PR for this change.

**Comment by radiantly** [comment]
Hi, I'd be happy to work on this. Taking a look at the [url-join repository](https://github.com/jfromaniello/url-join), it seems to have fallen out of maintenance and only has tests running up to Node v10. Since the currently used safe-join [source code](https://www.npmjs.com/package/safe-join#entire-source-code) is quite short, I'm in favor of inlining the function.

**Comment by erezrokah** [comment]
Inlining the code doesn't solve the licensing issue unless you significantly change the implementation.

How about we make sure `parseRepoURL` returns `ownerAndRepo` and `contentsPath` without leading and trailing `/`. Then we won't need any dependency.

Please let me know what you think?

**Comment by radiantly** [comment]
Alright, that sounds good
