### ISSUE TITLE
login to different account?

### ISSUE THREAD

**Issue by johhansantana** [netlify/cli#29]
Hello

Is there a way to login with the cli to different accounts?

**Comment by bcomnes** [comment]
In the upcoming 2.0.0 release, you can `netlify logout` and `netlify login`.  In the future, we may add multi-account support.

**Comment by lourencorodrigo** [comment]
And in version 1.2.3 how can we log out?

**Comment by bcomnes** [comment]
@lourencorodrigo iirc delete `~/.netlify`.  Version 2.0.0 has a logout command, and `netlifyctl` does as well.  Apologies for the awkwardness during this transition period.  We are likely adding multi-account support sometime after launch of 2.0.0.

**Comment by janosh** [comment]
@bcomnes Any update on the multi-account support? That would be sweet!

**Comment by DavidWells** [comment]
`~/.netlify` is setup to handle multiple logins. 

The last step we need to implement is the `netlify switch` Or `netlify auth:switch` command

Right now you will need to `netlify logout && netlify login` to switch between accounts

**Comment by janosh** [comment]
Cool, really looking forward to this functionality!

**Comment by cizza** [comment]
> `~/.netlify` is setup to handle multiple logins.
> 
> The last step we need to implement is the `netlify switch` Or `netlify auth:switch` command
> 
> Right now you will need to `netlify logout && netlify login` to switch between accounts

I'd like to ask for a clarification on this. What do you mean by "multiple logins"? Is it the ability to log in  by multiple team members or does it mean to switch between multiple netlify accounts? 
Thank you.

**Comment by RaeesBhatti** [comment]
Hey @cizza, you can login to multiple accounts. For example, you can use a personal account to manage personal website and a separate corporate account for work. `netlify switch` allows you switch between different accounts for different projects. It also allows you to log into new accounts.

**Comment by cizza** [comment]
Amazing, I just noticed the "switch" option is listed under netlify help commands. Just one question on this topic. Is it possible to use "netlify switch" with an account parameter? What I mean is I don't access terminal directly but I execute cli command from php. So the prompt to choose the account I want to switch to is not really an option. Something like "netlify switch --acc=xxxxxxxx".

**Comment by RaeesBhatti** [comment]
Hm... not yet but PR's welcome. Switch command is implemented here: [https://github.com/netlify/cli/blob/master/src/commands/switch.js](https://github.com/netlify/cli/blob/2b594134c2d3bf8c5815b31e4634b84f8ce3bd57/src/commands/switch.js)

**Comment by cizza** [comment]
Hi RaeesBhatti, I've submitted PR for this. pull #690
