### ISSUE TITLE
netlify dev fails for Gatsby project

### ISSUE THREAD

**Issue by janosh** [netlify/cli#290]
**- Do you want to request a *feature* or report a *bug*?**

Bug (maybe).

**- What is the current behavior?**

`netlify dev` in the root directory of a Gatsby project fails with the error

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at preferredScriptsArr.filter.s (~/.nvm/versions/node/v11.3.0/lib/node_modules/netlify-cli/node_modules/netlify-dev-plugin/src/detectors/utils/jsdetect.js:72:25)
    at Array.filter (<anonymous>)
    at scanScripts (~/.nvm/versions/node/v11.3.0/lib/node_modules/netlify-cli/node_modules/netlify-dev-plugin/src/detectors/utils/jsdetect.js:72:6)
    at Array.module.exports (~/.nvm/versions/node/v11.3.0/lib/node_modules/netlify-cli/node_modules/netlify-dev-plugin/src/detectors/gatsby.js:15:28)
    at module.exports.serverSettings (~/.nvm/versions/node/v11.3.0/lib/node_modules/netlify-cli/node_modules/netlify-dev-plugin/src/detect-server.js:15:40)
    at DevCommand.run (~/.nvm/versions/node/v11.3.0/lib/node_modules/netlify-cli/node_modules/netlify-dev-plugin/src/commands/dev/index.js:187:26)
```

**- What is the expected behavior?**

Get a local server with hot-reloading running the Gatsby site.

**- Please mention your node.js, and operating system version.**

- macOS 10.14.4
- node 11.3.0
- netlify-cli 2.11.0

**Comment by sw-yx** [comment]
acknowledged and investigating

**Comment by sw-yx** [comment]
what does your `package.json` look like? do you have any npm `scripts`?

**Comment by janosh** [comment]
Negative. Only the usual meta data, `dependencies`, `devDependencies` and `eslintIgnore`.

**Comment by janosh** [comment]
Will the fix be published today? Excited to try `netlify dev`!

**Comment by sw-yx** [comment]
fixed! npm install netlify-cli -g v2.11.2

**Comment by janosh** [comment]
Fix confirmed. Compilation now succeeds. However, opening the dev server at http://localhost:8888 now runs into

> Error: It appears like Gatsby is misconfigured. JSONStore is Gatsby internal development-only component and should never be used in production.

The command netlify cli inferred to compile the site is correct:
```sh
./node_modules/.bin/gatsby develop
```
Any idea what's the cause of this issue?

**Comment by sw-yx** [comment]
absolutely no idea! i think your gatsby setup is extremely strange. if its open source or you wanna invite me to a repo, i'd be happy to take a look for you, if not i'll need more context to figure out whats wrong

**Comment by janosh** [comment]
Thanks for offering to help! It's all [open source](https://github.com/janosh/janosh.io).

Out of interest, why do think my setup is strange?

**Comment by sw-yx** [comment]
well, no "scripts" in `package.json`, for one thing :)

**Comment by sw-yx** [comment]
![image](https://user-images.githubusercontent.com/6764957/55829880-bd32b500-5add-11e9-8200-b77ed9a77747.png)
seems to work fine

**Comment by janosh** [comment]
Yes, compilation succeeds without problems. But the site can't be displayed once it's done.

Btw, what key should the command in the `netlify.toml` `[[dev]]` block have? I don't think it's documented anywhere yet.

**Comment by erezrokah** [comment]
Closing this as stale. Please comment if still relevant
