### ISSUE TITLE
Make CLI installable vie homebrew

### ISSUE THREAD

**Issue by brianm** [netlify/cli#291]
**- Do you want to request a *feature* or report a *bug*?**

*feature*

**- What is the current behavior?**

Install via `npm install -g netlify-cli`

**- If the current behavior is a bug, please provide the steps to reproduce.**

n/a

**- What is the expected behavior?**

Install via `brew install netlify/netlify-cli`

Netlify should provide a homebrew tap with the CLI available under the name netlify. Install via NPM is not appropriate for end-user application installation (vs node.js dev tools).

**- Please mention your node.js, and operating system version.**

**Comment by bcomnes** [comment]
+1 

I would like to see this as well, it's a matter of time to set up the automation.   Since the dev launch, we should prioritize this.

**Comment by cglong** [comment]
I actually recently added this in Homebrew/homebrew-core#41453 🎉 You can now install the CLI using:

    brew install netlify-cli
