### ISSUE TITLE
npm t fail

### ISSUE THREAD

**Issue by Berkmann18** [netlify/cli#293]
**- Do you want to request a *feature* or report a *bug*?**
Bug.
**- What is the current behaviour?**
It goes all the way to `dependency-check ./package.json ...` and fails with some contradicting logs.
```shell
run-s test:*
> netlify-cli@2.11.4 test:ava /mnt/c/Users/max/Projects/netlify-cli
> nyc --reporter=lcov ava --verbose && nyc report
✔ camelCase to NETLIFY_ENV_CASE
✔ isDotProp detects doPropPaths
2 tests passed
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
 util.js  |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|
> netlify-cli@2.11.4 test:lint /mnt/c/Users/max/Projects/netlify-cli
> eslint src
> netlify-cli@2.11.4 test:deps /mnt/c/Users/max/Projects/netlify-cli
> dependency-check ./package.json --entry "src/**/!(*.test).js" --unused --missing --no-dev --no-peer -i @oclif/plugin-not-found -i @oclif/config -i @oclif/plugin-help -i @oclif/plugin-plugins
Fail! Modules in package.json not used in code: netlify-dev-plugin
Success! All dependencies used in the code are listed in package.json
```

**- If the current behaviour is a bug, please provide the steps to reproduce.**
```shell
git clone https://github.com/netlify/cli.git netlify-cli && cd netlify-cli
npm i
npm t
```

**- What is the expected behaviour?**
The test passed with no errors.

**- Please mention your node.js, and operating system version.**
Node: v11.12.0
OS: Ubuntu 18.10 (WSL)

**Comment by bcomnes** [comment]
Ah yeah, oclif has a bespoke dependency injection system, so it breaks standard dependency resolution algorithms.  The solution is to add that plugin to the ignore list.

**Comment by bcomnes** [comment]
It also looks like Azure isn't catching failed tests, which is why I didn't notice this right away https://github.com/netlify/cli/issues/295
