### ISSUE TITLE
How to get the source map files of function with esbuild

### ISSUE THREAD

**Issue by zoexx** [netlify/cli#2932]
**It's not a feature or a bug,  but I am really frustrated to use it with esbuild.**

I used to build the functions with `netlify-lambda` and upload the source map files to sentry with a custom webpack configration.
Since switched to esbuild plugin, did not find a good way to do so.

I found `@sentry/netlify-build-plugin` works for the client side map files in `public` folder, how about the functions? 

I try to find the map files in somewhere of the outputs, so that I could add the path to `@sentry/netlify-build-plugin`

I noticed there's 
```
const addFunctionsConfigDefaults = (config) => ({
  ...config,
  '*': {
    nodeSourcemap: true,
    ...config['*'],
  },
})
```
and  
`sourceMapSupport.install()` 

in `zisi.js`, but I did not find any map files in the zip files.

```
➜  xxx git:(upgrade-v3) ls -R .netlify/functions/my-test-function/functions
my-test-function

.netlify/functions/my-test-function/functions/my-test-function:
index.js
```

Anyone has a solution? 

```
  //
 ('>
 / rr
*\))_
```

**Comment by eduardoboucas** [comment]
Hi @zoexx! Thanks for opening this.

There's currently no way of including the sourcemap with the function payload, but I agree that's something we should allow people to do. All the functionality is there, we just need a new configuration property that allows it to be enabled by users.

I'll work on this and update the issue as soon as I have any updates.

**Comment by zoexx** [comment]
> Hi @zoexx! Thanks for opening this.
> 
> There's currently no way of including the sourcemap with the function payload, but I agree that's something we should allow people to do. All the functionality is there, we just need a new configuration property that allows it to be enabled by users.
> 
> I'll work on this and update the issue as soon as I have any updates.

Hi @eduardoboucas , how's going? is there anything I can help?
