### ISSUE TITLE
Allow overwriting environment variables for Netlify Dev

### ISSUE THREAD

**Issue by cbetta** [netlify/cli#298]
**- Do you want to request a *feature* or report a *bug*?**

Feature

**- What is the current behavior?**

`.env` files are ignored

**- What is the expected behavior?**

I'd love to be able to overwrite some local environment variables for testing/development purposes when using Netlify Dev.

**- Please mention your node.js, and operating system version.**

Not relevant

**Comment by pawelmadeja** [comment]
I'm struggling with that too. It seems that automatically reading .env files is not ready yet (see: https://github.com/netlify/cli/issues/474) and for now you have to do it on your own.

**Comment by sw-yx** [comment]
yes. for now what i've seen users do is use `dotenv` locally and that does the overwrite nicely, which naturally falls away in production where you can use prod variables.

**Comment by RaeesBhatti** [comment]
Implemented in the latest release.

**Comment by kijanawoodard** [comment]
is there a doc for this? doesn't appear to be working, but maybe i have the .env file in the wrong location?

**Comment by kijanawoodard** [comment]
Found it. :-D

> Netlify Dev also supports local environment variables through .env files. Netlify Dev will look in project root directory for .env file and will provide those variables to the spawned site generator/server and Netlify Functions.

https://github.com/netlify/cli/blob/master/docs/netlify-dev.md

**Comment by eduardoboucas** [comment]
@kijanawoodard Glad you found it. I'm interested in making this information (i.e. the location and behaviour of the various environment variable sources) as easy to find as possible. If this was difficult to find, or it was not where you'd expect it to be, can you share this information with me?

Many thanks! 🙌🏻
