### ISSUE TITLE
netlify dev fails to start on parcel framework

### ISSUE THREAD

**Issue by clawfire** [netlify/cli#3001]
**Describe the bug**

Using https://github.com/clawfire/covid19-passbook-generator/ , I launch a `netlify dev` command, and ... it crashes with an `error while proxying request: socket hang up` even when the page isn't loaded in the browser. Meanwhile, the started server from parcel works just well.

The command executed is npx parcel serve src/index.html --https && cp node_modules/qr-scanner/qr-scanner-worker.min.js dist/qr-scanner-worker.min.js

**To Reproduce**

1. Clone https://github.com/clawfire/covid19-passbook-generator/ 
2. Navigate to the cloned repository
3. Run `netlify dev`
4. See that the CLI exits with an error

**Configuration**

```
# example netlify.toml
[build]
  command = "yarn run build"
  functions = "netlify/functions"
  publish = "/dist"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

[context.production]
    command = "yarn run build"
    NODE_ENV = "production"
[content.branch-deploy]
    command = "yarn run deploy-preview"
    NODE_ENV = "production"

[dev]
port = 3000 # Port that the dev server will be listening on
publish = "dist" # Folder with the static content for _redirect file
command = "yarn start" # Command to start your dev server
targetPort = 1234
```
And the system infos
```
  System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 185.53 MB / 16.00 GB
    Shell: 5.1.8 - /usr/local/bin/bash
  Binaries:
    Node: 16.5.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.19.1 - /usr/local/bin/npm
  npmGlobalPackages:
    netlify-cli: 4.4.2
```

**Expected behavior**

Serve the page

**CLI Output**

`error while proxying request: socket hang up`

**Additional context**

Originally post on #404

**Comment by coelmay** [comment]
For what it's worth, I used parcel regularly and don't have any issue with a `package.json` that reads
```
...
"scripts": {
    "build": "parcel build src/index.html",
    "start": "parcel src/index.html"
},
...
```
and setting `command = "yarn start"` or `command = "yarn build"` in my `netlify.toml` both `parcel` and `netlify dev` run properly (currently using `"parcel": "2.0.0-beta.2"`.)

**Comment by clawfire** [comment]
Yep, the issue was indeed with the `--https` I was using when only using parcel for local dev and not `netlify dev` 😃 
Removing the `--https` of my yarn/npm script invocation make it works like a charm.
