### ISSUE TITLE
Functions are not deployed from internal functions dir if base is in subdirectory

### ISSUE THREAD

**Issue by ascorbic** [netlify/cli#3004]
**Describe the bug**

If the site is deployed from a subdirectory of the repo, any functions in the internal functions dir are not deployed from the CLI. When running in CI they deploy correctly.

**To Reproduce**

1. Clone `git@github.com:ascorbic/functions-dir.git`
2. Link the site
3. Run `ntl deploy --build`
4. Observe that a function is created in `subdirectory/.netlify/funcitons-internal` but is not deployed

**Comment by lindsaylevine** [comment]
sorry just happened to see this and curious -- doesn't the CLI not even deploy funcs from .netlify (but rather the actual unbundled functions src)? i recall eduardo saying this when jason and i were trying to update the zip files for asana. or maybe this has changed or i'm missing something. jw!

**Comment by ascorbic** [comment]
It bundles them (again) at deploy time.

**Comment by eduardoboucas** [comment]
This should be fixed as of CLI v5.2.6.
