### ISSUE TITLE
Netlify Status shows TypeError

### ISSUE THREAD

**Issue by AdrianLuk** [netlify/cli#3021]
**Describe the bug**

Running `netlify status` returns `TypeError: (intermediate value) is not iterable`

**To Reproduce**

1. Run `netlify status`

**Configuration**

- If possible, please copy/paste below your `netlify.toml`.
- Please enter the following command in a terminal and copy/paste its output:

Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD

`netlify -v` returns `netlify-cli/5.2.8 win32-x64 node-v14.15.4` 

**Expected behavior**

showing the status. Stopped working after upgrading from 5.2.0 to 5.6.2

**CLI Output**

`TypeError: (intermediate value) is not iterable`

**Additional context**

**Comment by eduardoboucas** [comment]
Thanks @AdrianLuk! We have a fix in #3022. We'll have a new version out shortly.

**Comment by erezrokah** [comment]
Thanks @AdrianLuk, a fix for this is released in [v5.2.10](https://github.com/netlify/cli/releases/tag/v5.2.10).

You can update via `npm install -g netlify-cli`
