### ISSUE TITLE
Expand description of `netlify init`

### ISSUE THREAD

**Issue by KyleBlankRollins** [netlify/cli#3025]
**Describe the bug**

The [current description for `netlify init`](https://cli.netlify.com/commands/init) makes it seem as if continuous integration and git are required. This can be confusing if people want to create a site that's not tied to those things.

Conversation started in the [Netlify forums](https://answers.netlify.com/t/how-to-creat-a-site-so-can-use-local-dev-but-no-git/41243).

Possible update to the description:
- “Configure continuous deployment for a existing site or create a new site without continuous deployment.”

**Comment by erezrokah** [comment]
Hi @KyleBlankRollins, the `ntl init` command can also configure continuous deployment for a new site.

The `ntl init` command falls black to creating a new site in case the project is not a git repo (so we can't complete continuous deployment).

How about we point to the `sites:create` command instead? For example: 
`Configure continuous deployment for a new or existing site. To create a site without continuous deployment see the 'sites:create' command.`

**Comment by KyleBlankRollins** [comment]
@erezrokah, that makes a lot of sense. :) I can open a PR if that's the preferred docs workflow for this repo.

**Comment by erezrokah** [comment]
That would be great @KyleBlankRollins, thank you!

Please note the CLI docs are autogenerated from the code so you'll need to update the following line:
https://github.com/netlify/cli/blob/44122805e6a9d2faecf6c0efffa835c0f7d9571d/src/commands/init.js#L203

and run `npm run site:build` locally to sync the docs.
