### ISSUE TITLE
Support deploying by site name

### ISSUE THREAD

**Issue by jamesplease** [netlify/cli#3033]
**Is your feature request related to a problem? Please describe.**

I often need to deploy one project (the term “project” here refers to a git repository that contains the source code for a webapp) to more than one Netlify site.

The current CLI is great for deploying to one Netlify site, but the experience could be improved when needing to deploy to more than one site. I believe that adding support for deploying by site name could improve the ergonomics of this use case.

**Describe the solution you'd like**

Site names are created by developers and often more memorable than UUIDs. For my use case, the different site names for each project would be generated using a predictable pattern. For example: given a project `my-app`, there could be two Netlify sites: `my-app-A` and `my-app-B`. This would allow a developer to quickly run `netlify deploy` passing the appropriate site name. For example:

```
netlify deploy --site my-app-A
```

My understanding is that site names are unique, so there should always be a 1:1 mapping between a site name and its ID.

This mapping could be cached locally at `./netlify/state.json`. Perhaps:

```json
{
  "sites": {
    "my-app-A": "uuid1",
    "my-app-B": "uuid2"
  }
}
```

If site names do not map 1:1 to IDs, then perhaps a new concept could be introduced. Let's call this concept "targets" (although the name could be anything). The CLI command for this might be:

```
netlify deploy --target my-app-A
```

And the associated `state.json`:

```json
{
  "targets": {
    "my-app-A": "uuid1",
    "my-app-B": "uuid2"
  }
}
```

Targets would only exist on the developer's machine: this would not require a change to the Netlify backend system. The way that it would work is that the CLI would look for a matching ID for the given target name within `state.json`. If a match is not found, then it begins the process of creating the new site. Once the site is created, its site ID is stored within `state.json` under the associated target. On subsequent deploys, that site ID would be passed to the `netlify deploy` command to redeploy the site.

If there's any interest in either of these approaches, then additional changes could be made for DX. For example, if `"sites"` (or `"targets"`) exists within `state.json`, but `siteId` does not, and a user runs `netlify deploy` without any flags, then it could prompt the user if they wish to deploy one of those specific sites or if they wish to make a new one.

**Describe alternatives you've considered**

It's possible to implement either the `sites` or `targets` behavior described above in a wrapper CLI. That's my current plan. This isn't ideal because I'll be creating a new directory, perhaps `.deploy`, to keep the cached info in, and managing a separate `state.json` object. I'd love it if the Netlify CLI supported this directly!

**Additional context**

Related: #2199 

**Can you submit a pull request?**

I'd be happy to if there's interest from the team.

---

Thank you so much for taking the time to read this!

**Comment by erezrokah** [comment]
Hi @jamesplease!
Thank you for opening the issue.

Linking https://github.com/netlify/cli/issues/157 for context - we used to support `ntl deploy --site <site-name>` so it makes sense to bring that back.
That is, for the following command `ntl deploy --site <site>`:
1. If `<site>` is an id the CLI will deploy to that site.
2. If `<site>` is a name, the CLI will look up that site id and deploy to it. To support your use case of creating the site we can add a new `--force` flag that creates the site if it doesn't exist.

How does that sound?

> If site names do not map 1:1 to IDs, then perhaps a new concept could be introduced. Let's call this concept "targets" (although the name could be anything). The CLI command for this might be:

While site names are linked to an id, those can change (a site can be renamed) so managing a cache have some additional complexity.

As a workaround I think you should be able to achieve what you need using the following commands (they should work in a `bash` like environment with `jq` installed):

```
netlify api createSiteInTeam --data '{ "body": { "name": "<site-name>" }, "accountSlug": "<account-slug>" }'
netlify deploy --site $(netlify api listSites --data '{ "name" : "<site-name>" }' | jq -r -c '.[0].id')
```

`createSiteInTeam` will fail if the site exists, so you can ignore that failure for your use case.

**Comment by jamesplease** [comment]
> How does that sound?

That sounds dreamy, to be honest!

One thing I want to mention is that that for our current use case my team wouldn't need `--force`. The current behavior of `netlify deploy` where it asks the series of prompts when `.netlify/state.json` doesn't exist would be sufficient. But there may be other use cases where `--force` is useful so I'm not opposed to if y'all think it's worth adding!

> While site names are linked to an id, those can change (a site can be renamed) so managing a cache can have some additional complexity.

Great point.

> As a workaround I think you should be able to achieve what you need using the following commands

Whoa. Thank you **so much** for writing those commands up for me. I really appreciate it!

**Comment by tinfoil-knight** [comment]
@erezrokah Can I pick this one up?
