### ISSUE TITLE
[low priority idea] recursive prompting based on folder existence

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#309]
**- Do you want to request a *feature* or report a *bug*?**
very minor feature

**- What is the current behavior?**
if a folder exists, we quit or prompt once. to my knowledge we dont recursively check. this recursive strategy: https://github.com/palmerhq/tsdx/pull/53 is a good idea.

**Comment by DavidWells** [comment]
What is this for exactly?

**Comment by RaeesBhatti** [comment]
Intent of then feature is unclear. Please reopen with more details.
