### ISSUE TITLE
netlify --help output is black on black

### ISSUE THREAD

**Issue by Daniel15** [netlify/cli#31]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
`netlify --help` output is unreadable as it prints black text on a black background:
![](http://ss.dan.cx/2017/08/05-15.20.47.gif)

**- If the current behavior is a bug, please provide the steps to reproduce.**
```
netlify --help
```

**- What is the expected behavior?**
I can utilize my eyeballs to ingest the help content

**- Please mention your node.js, and operating system version.**
Node v7.8.0
Windows 10 insider preview build 16193

**Comment by bcomnes** [comment]
This should be addressed in the upcoming 2.0.0 release.

**Comment by bcomnes** [comment]
Just go a user report that this is still happening.  Reopening

**Comment by verythorough** [comment]
Or not! Wrong version. Everything looks ok in 2.0.
