### ISSUE TITLE
Use open-api addons endpoints

### ISSUE THREAD

**Issue by bcomnes** [netlify/cli#310]
We need to swap the use of `netlify/src/addons` to use the open-api definitions 

- `createAddon` -> `createServiceInstance`
- `getAddons` -> `showServiceInstance`
- `deleteAddon` -> `deleteServiceInstance`
- `updateAddon` -> `updateServiceInstance`

See https://open-api.netlify.com/#/default/updateServiceInstance

All the addons command need to be updated with the new names and probably shape: https://github.com/netlify/cli/search?q=src%2Faddons&unscoped_q=src%2Faddons

Then delete this file: https://github.com/netlify/js-client/blob/master/src/addons.js

**Comment by erezrokah** [comment]
We are still referencing the feature as `addons`:
https://docs.netlify.com/partner-add-ons/get-started/#work-with-add-ons

so the current naming makes sense to me, even if the underlying implementation uses `service instances`.
Comment if still relevant

**Comment by keiko713** [comment]
@erezrokah is there any way to somehow make an alias with this, so that it'll keep the name part (or rather, it can be called in both ways) but it'll use the open-api defined method behind the scene?
I just got bitten by this, since current addon code (https://github.com/netlify/js-client/blob/master/src/addons.js) is hard coding `api.netlify.com`.
Although, I guess that means that the functions shape is gonna change so maybe it's not an option. Let me know in that case, maybe we can use xxxServiceInstance way in https://github.com/netlify/netlify-lm-plugin/blob/b9323387bf0cff230739ebef6ebf5953ae2871fe/src/commands/lm/setup.ts#L7 instead for the workaround

**Comment by erezrokah** [comment]
Thanks @keiko713.
Re-opening this.
Clearing up some confusion I had from the initial issue description.
There are 2 issues here:
1. How the internal implementation works - we should update it to use the open-api defined methods.
2. How the commands are called in the CLI - not sure we should update them to mention service instances (but we could alias them).

Looks like:
1. https://github.com/netlify/js-client/blob/960089a289288233bd2a17fcbd8ab4730ca49135/src/addons.js#L8 can be replaced by directly by https://open-api.netlify.com/#operation/createServiceInstance
2. https://github.com/netlify/js-client/blob/960089a289288233bd2a17fcbd8ab4730ca49135/src/addons.js#L50 should be replaced by https://open-api.netlify.com/#operation/deleteServiceInstance but I'm not sure if I should reference the `instanceId` in the `open-api` spec.
3. https://github.com/netlify/js-client/blob/960089a289288233bd2a17fcbd8ab4730ca49135/src/addons.js#L69 should be replaced by https://open-api.netlify.com/#operation/updateServiceInstance, but also not sure about `instanceId`.
4. https://github.com/netlify/js-client/blob/960089a289288233bd2a17fcbd8ab4730ca49135/src/addons.js#L30 should be replace by https://open-api.netlify.com/#operation/getServices. Not sure if the response structure is the same in that case.

Please let me know if I'm missing anything.

**Comment by keiko713** [comment]
thanks for taking a look!!

> How the internal implementation works - we should update it to use the open-api defined methods.

I agree with you that the internal implementation needs to be tweaked, but also think that we can't retire the functions like `createAddon`, as people might be using them, and not sure if there is any straight forward way to tweak the internal implementation without changing the shape of how it's called 🤔 

> How the commands are called in the CLI - not sure we should update them to mention service instances (but we could alias them)

I'd say that we want to keep the `netlify addon` commands. It's referred by docs and potentially some blog posts too, safe/better to keep it around.

> https://github.com/netlify/js-client/blob/960089a289288233bd2a17fcbd8ab4730ca49135/src/addons.js#L50 should be replaced by https://open-api.netlify.com/#operation/deleteServiceInstance but I'm not sure if I should reference the instanceId in the open-api spec.

> https://github.com/netlify/js-client/blob/960089a289288233bd2a17fcbd8ab4730ca49135/src/addons.js#L69 should be replaced by https://open-api.netlify.com/#operation/updateServiceInstance, but also not sure about instanceId.

Oh wow, I think the open-api is wrong about these two. They both need `instance_id` to be passed (PUT or DELETE with `/api/v1/sites/${siteId}/services/${addon}/instances/${instanceId}`).

> https://github.com/netlify/js-client/blob/960089a289288233bd2a17fcbd8ab4730ca49135/src/addons.js#L30 should be replace by https://open-api.netlify.com/#operation/getServices. Not sure if the response structure is the same in that case.

This should be the same as it's poking the same endpoint.

**Comment by erezrokah** [comment]
> Oh wow, I think the open-api is wrong about these two

Do you want me to open an issue for it in the `open-api` repo?

**Comment by keiko713** [comment]
Sorry for the late reply, I was on vacation! I've created a PR for it: https://github.com/netlify/open-api/pull/258

**Comment by erezrokah** [comment]
Thanks, I subscribed to that PR and will follow up once it's deployed.
