### ISSUE TITLE
netlify deploy thorough Circle CI or any other CI 

### ISSUE THREAD

**Issue by udayvunnam** [netlify/cli#311]
How should we use `netlify deploy` from Circle CI.

We would need to set netlify token set in Circle CI. Is there any documentation or aproach available.

**Comment by DavidWells** [comment]
Hey @udayvunnam 

Checkout https://cli.netlify.com/commands/deploy

You will want to set `NETLIFY_AUTH_TOKEN` environment variable for the CLI to deploy from circle CI

Then you can do something like:

```
# install netlify-cli if not already there
npm install netlify-cli -g
#  deploy to live site
netlify deploy --prod --dir build-dir --message "site deployed from circle ci"  --site 123
```

You can also set the auth token in the deploy command if deploying into multiple accounts and the `NETLIFY_AUTH_TOKEN` wont work for you

```
netlify deploy --prod --dir build-dir --message "site deployed from circle ci" --auth xyz --site 123
```

**Comment by verythorough** [comment]
@udayvunnam You can find steps for getting the Netlify auth token here: 
https://www.netlify.com/docs/cli/#obtain-a-token-in-the-netlify-ui

**Comment by kirillgroshkov** [comment]
Is there a way to get a draft URL after it's deployed?

I've just opened an issue about it: https://github.com/netlify/cli/issues/312

I'm doing exactly what's described here - deploying it from CircleCI.

**Comment by udayvunnam** [comment]
> Hey @udayvunnam
> 
> Checkout https://cli.netlify.com/commands/deploy
> 
> You will want to set `NETLIFY_AUTH_TOKEN` environment variable for the CLI to deploy from circle CI
> 
> Then you can do something like:
> 
> ```
> # install netlify-cli if not already there
> npm install netlify-cli -g
> #  deploy to live site
> netlify deploy --prod --dir build-dir --message "site deployed from circle ci"  --site 123
> ```
> 
> You can also set the auth token in the deploy command if deploying into multiple accounts and the `NETLIFY_AUTH_TOKEN` wont work for you
> 
> ```
> netlify deploy --prod --dir build-dir --message "site deployed from circle ci" --auth xyz --site 123
> ```

I have stumbled upon where netlify would look for a token earlier.
- env variables, 
- ~/.netlify/config.json, 
- .netlify/state.json, 
- netlify.toml

So, netlify cli would look for env variable 'NETLIFY_AUTH_TOKEN'. Thanks that works.
