### ISSUE TITLE
`netlify deploy` to output Site URL in parseable way

### ISSUE THREAD

**Issue by kirillgroshkov** [netlify/cli#312]
**- Do you want to request a *feature* or report a *bug*?**

Feature

**- What is the current behavior?**

`netlify deploy` right now prints this log in the console, but I'm trying to dig a "Live Draft URL" from it:

```
netlify deploy
Deploy path:        /Users/kirill/Idea/NCApp3/www
Configuration path: /Users/kirill/Idea/NCApp3/netlify.toml
Deploying to draft URL...
✔ Finished hashing 462 files
✔ CDN requesting 0 files
✔ Finished uploading 0 assets
✔ Draft deploy is live!

Logs:           https://app.netlify.com/sites/ncapp3/deploys/5ccc804689fd0d017b26ad78
Live Draft URL: https://5ccc804689fd0d017b26ad78--ncapp3.netlify.com

If everything looks good on your draft URL, take it live with the --prod flag.
netlify deploy --prod

```

**- What is the expected behavior?**

I'd like to have a way for `netlify deploy` to have a parseable output (e.g json).
Example API:
`netlify deploy --output deployResult.json`

that would output a `deployResult.json` file with operation metadata, e.g:
```json
{ "draftUrl": "https://..." }
```

Right now I'm trying to grep/awk/madness/parse it, but it doesn't feel right.

**Comment by bcomnes** [comment]
Good idea.  Feel like sending a pr?

- Flags here: https://github.com/netlify/cli/blob/master/src/commands/deploy.js#L270
- Output here: https://github.com/netlify/cli/blob/master/src/commands/deploy.js#L174-L189

Our spinners hit stderr, but stdout might not be 100% clean yet so watch out, you may need to guard for that.

**Comment by DavidWells** [comment]
Related https://github.com/netlify/cli/issues/248

We need a `--json` flag on the deploy command and that will allow for programatic parsing

**Comment by kirillgroshkov** [comment]
Meanwhile, sharing my ugly parsing script workaround:

```typescript
/*

yarn tsn-script ./scripts/netlifyDeployUrl.ts --inputPath ./netlify_deploy.txt --outputPath ./netlify_deploy.json

Parses ./netlify_deploy.txt to get "Live Draft URL" from it and then saves it into netlify_deploy.json

 */

import * as yargs from 'yargs'
import * as fs from 'fs-extra'

main().catch(err => {
  console.error(err)
  process.exit(1)
})

async function main () {
  const {inputPath, outputPath} = yargs.options({
    inputPath: {
      type: 'string',
      demandOption: true,
    },
    outputPath: {
      type: 'string',
      demandOption: true,
    },
  }).argv

  const input = await fs.readFile(inputPath, 'utf8')
  const [line] = input.split('\n').filter(s => s.includes('Live Draft URL'))
  // console.log(line)
  const url = 'https' + line.split('https')[1]
  console.log({url})

  await fs.writeJson(outputPath, {
    NETLIFY_URL: url,
  }, {spaces: 2})
}

```

**Comment by DavidWells** [comment]
Haha cool thanks @kirillgroshkov 

Once https://github.com/netlify/cli/pull/313 is merged and we cut a new CLI version you can use the `--json` flag with `netlify deploy`

**Comment by bcomnes** [comment]
Woo! Nice work @DavidWells.

**Comment by maximilianschmid** [comment]
GREAT!
