### ISSUE TITLE
Question: Caching of Gatsby sites

### ISSUE THREAD

**Issue by janosh** [netlify/cli#314]
Question: Every time I run `netlify deploy` on a Gatsby site, it seems to upload all files required for that site anew. That can easily be on the order of several hundred and may take a while depending on the connection. Is this or could this be cached? Does `netlify` work with [`gatsby-plugin-netlify-cache`](https://github.com/axe312ger/gatsby-plugin-netlify-cache)?

**Comment by bcomnes** [comment]
We do content addressed de-duplication on deploys, so if all of your pages aren't changing every build, then only the ones that change get uploaded.  If you have some kind of timestamp in a layout, this can trigger slight changes in file contents on every page.  

Start by looking at one build and comparing it to a second build.  Look at a file you don't expect to change in the first build, and diff it against the second build.  If the sha1's are different, the change is uploaded.  Looking at a content diff can help provide hints as to what is changing between builds.

**Comment by janosh** [comment]
Thanks for the quick reply? I assume the same applies to assets? I.e. they only re-upload, if their SHA-1 changes rather than being tied to the re-upload of the page they appear on?

**Comment by bcomnes** [comment]
All files and assets in the deploy folder, yes.
