### ISSUE TITLE
DX: Ask for GH Personal Access Token, or Explain why we need your GitHub credentials, don't just ask

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#319]
Encountered during [my livestream](https://www.youtube.com/watch?v=vrSoLMmQ46k&feature=youtu.be) with @jlengstorf

**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
for first time users, we [prompt for GH password and OTP token](https://github.com/netlify/cli/blob/8d87cfbe1c583ce396762e60294e906da48ba5bc/src/utils/gh-auth.js#L18-L44) - this is a big trust step and we should explain what we use it for and what we have access to.

EDIT: we really only use it to get a personal access token, and we should offer the option of letting the user set it up for themselves so they dont need to trust us with their password.

**Comment by DavidWells** [comment]
Maybe we add a message above this prompt:

"Please insert your github credentials. Netlify needs these to wire up your repo and live site. For more information see: https://link-to-reason.com"
