### ISSUE TITLE
netlify dev --live not working with Gatsby site

### ISSUE THREAD

**Issue by janosh** [netlify/cli#321]
**Do you want to request a *feature* or report a *bug*?**

Maybe a bug or just an incompatibility.

**What is the current behavior?**

`netlify dev --live` succeeds and prints

> Server now ready on https://janosh-9def22.netlify.live 

Following that link results in an error page stating

> Error: It appears like Gatsby is misconfigured. JSONStore is Gatsby internal development-only component and should never be used in production.

![error-pag](https://user-images.githubusercontent.com/30958850/58709193-9001d500-83b1-11e9-84a9-c635ab85c38a.png)

Not sure if this is a problem on Gatsby's or Netlify's side or if failed to configure something properly.

**What is the expected behavior?**

Live, shareable view of my development server.

**- Please mention your node.js, and operating system version.**

- macOS 10.14.4
- node 10.15.3
- netlify-cli 2.11.0

**Comment by erezrokah** [comment]
Closing this as stale (seems more like a Gatsby issue).
If still an issue please comment.
