### ISSUE TITLE
```ntl dev``` should start the dev server

### ISSUE THREAD

**Issue by subhamBharadwaz** [netlify/cli#3242]
```ntl dev``` should open the dev server on port 8888.

![Netlify CLI](https://user-images.githubusercontent.com/72348711/130580645-5331d2fa-b885-4ee6-aec3-20102a0ad60e.png)

How to solve this issue?

**Comment by subhamBharadwaz** [comment]
After deleting the ```.eleventy.js``` file, it's working correctly. Any solution?
My ```.eleventy.js``` files looks like this

```javascript

module.exports = (config) => {
  config.addPassthroughCopy('src/css');
  config.addPassthroughCopy('src/images');
  config.addPassthroughCopy('src/js');

  return {
    dir: {
      input: 'src',
    },
  };
};
```

**Comment by verythorough** [comment]
@subhamBharadwaz When you run `ntl dev` with your `.eleventy.js` file, and it displays the lines you screenshotted above, what happens when you visit the first listed URL at `https://localhost:8088`? What's being served at that address?

**Comment by erezrokah** [comment]
By default `ntl dev` will try to connect to port `8080` for an 11ty site:
https://github.com/netlify/framework-info/blob/043520db19c06ed9fe4b562c264dafe5487fb7d2/src/frameworks/eleventy.json#L12

@subhamBharadwaz, looks like your site is configured to run on `8088`, so you'll need to configure it via `ntl dev --targetPort 8088` or via the `netlify.toml` [dev block](https://cli.netlify.com/netlify-dev#netlifytoml-dev-block).

@verythorough I think the main issue is that [we don't print any kind of progress](https://github.com/netlify/cli/blob/388bc795e9b171907fe28ace7cc0c7377c381543/src/commands/dev/index.js#L106) while waiting for the framework server to start, and the timeout for that operation is 10 minutes.

**Comment by subhamBharadwaz** [comment]
> 
> 
> @subhamBharadwaz When you run `ntl dev` with your `.eleventy.js` file, and it displays the lines you screenshotted above, what happens when you visit the first listed URL at `https://localhost:8088`? What's being served at that address?

eleventy site was served at 8088 and netlify functions was at a different port. But after upgrading to ```netlify cli```, it's working correctly today. Thank you!

![Untitled](https://user-images.githubusercontent.com/72348711/131799198-00a1f2a5-a25d-4a8b-87a1-ad7786ffaab3.png)

**Comment by subhamBharadwaz** [comment]
> 
> 
> By default `ntl dev` will try to connect to port `8080` for an 11ty site:
> https://github.com/netlify/framework-info/blob/043520db19c06ed9fe4b562c264dafe5487fb7d2/src/frameworks/eleventy.json#L12
> 
> @subhamBharadwaz, looks like your site is configured to run on `8088`, so you'll need to configure it via `ntl dev --targetPort 8088` or via the `netlify.toml` [dev block](https://cli.netlify.com/netlify-dev#netlifytoml-dev-block).
> 
> @verythorough I think the main issue is that [we don't print any kind of progress](https://github.com/netlify/cli/blob/388bc795e9b171907fe28ace7cc0c7377c381543/src/commands/dev/index.js#L106) while waiting for the framework server to start, and the timeout for that operation is 10 minutes.

It is working correctly after upgrading ```ntlify cli```. Thank you!!

**Comment by Morazee** [comment]
atfter installing npm install netfly-cli -g 
i run ntl dev but didnt work?
![devrun](https://user-images.githubusercontent.com/100149661/170692211-534e4bfd-e05c-45bd-8ac7-20c0cde0408e.png)

**Comment by Morazee** [comment]
one more question please? 
after runin > npm run dev 
do i need to cancel batch to run 
>npm install netlify-cli -g
![npmrundevcalncel](https://user-images.githubusercontent.com/100149661/170693028-295ac352-9bed-4bfb-b98b-5dc60b0cfd4b.png)

**Comment by Morazee** [comment]
let me know what's going on please ASAP cause i've being stuck with this for 3 days now and my brain is burning .
thank you for your time and your help is much appreciated

**Comment by verythorough** [comment]
@Morazee for help with your Netlify site, I recommend you visit the Support Forums at https://answers.netlify.com/. Netlify's professional Support team and Community Pilots are there to help you out!
