### ISSUE TITLE
feat(docs-vs-debugging): add information on debugging with `esbuild`

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#3248]
**Is your feature request related to a problem? Please describe.**

Related to https://github.com/netlify/cli/blob/f5743f02bf3bb091b243862a3ff49e2481c817b9/docs/vscode.md#add-vscode-launch-configurations

Per @eduardoboucas 

>when we use esbuild, the files that we serve are actually different from the files people write (we transpile them and serve them from a different directory). we need to tell VS Code to transform the locations of breakpoints accordingly. we need this line in the VS Code launch file configuration: `"outFiles": ["${workspaceFolder}/.netlify/functions-serve/**/*.js"]`

**Describe the solution you'd like**

Update the docs with a note about `esbuild` debugging

**Describe alternatives you've considered**

Keeping the docs as they are and point to https://answers.netlify.com/t/debugging-typescript-functions/42816

**Can you submit a pull request?**

Yes

**Comment by Patil2099** [comment]
I would love to take this up
