### ISSUE TITLE
Local functions dev: function event shows path: '/.netlify/non-existent-path' in several different cases

### ISSUE THREAD

**Issue by kaganjd** [netlify/cli#3255]
**Is your feature request related to a problem? Please describe.**

An enterprise customer noticed when testing role-based access locally that `req.url` gets overwritten with a placeholder path at the beginning of the process to check whether a JWT should allow access to a certain path: https://github.com/netlify/cli/blob/cc84d2ab4da62c8fc523b30362d243c044d71c57/src/utils/proxy.js#L144

The placeholder path is supposed to be reset to be a real path if the JWT check succeeds, but several customers have reported that an auth function works when deployed to Netlify (`event.rawUrl` shows the correct path) that, when tested locally, shows `event.path` as the placeholder path.

So, another way:
- function deployed to Netlify, successful auth:
```
rawUrl: 'https://deploy-preview-1215--my-site-dot-com.netlify.app/correct/path',
rawQuery: '',
path: '/correct/path',
```
- same function locally, presumably successful auth since it worked in prod:
```
path: '/.netlify/non-existent-path',
```

This is super confusing.

**Describe the solution you'd like**

When `console.log`ing the event within a local function, I should see an actual path instead of a placeholder path.

**Describe alternatives you've considered**

Deploy to a live site to test

**Additional context**

Slack thread here (internal only): https://netlify.slack.com/archives/C01UU1XGNMT/p1629922565025900

**Comment by kaganjd** [comment]
Another enterprise customer running into this today: https://netlify.zendesk.com/agent/tickets/66121 (internal only)

**Comment by ehmicky** [comment]
Thanks for raising this up @kaganjd.
I will investigate this problem. :+1:

**Comment by ehmicky** [comment]
Minimal steps to reproduce:

`netlify.toml`:

```toml
[[redirects]]
from = "/test"
to = "/admin"
conditions = {Role = ["user"]}

[[redirects]]
from = "/test"
to = "/.netlify/functions/auth"
status = 200
```

`/netlify/functions/auth.js`:

```js
module.exports.handler = async function (event) {
  return { statusCode: 200, body: event.path }
}
```

When requesting `http://localhost:8888/test`, `/.netlify/non-existent-path` is returned, while it should be `/netlify/functions/auth.js`.

**Comment by ehmicky** [comment]
PR to fix this: https://github.com/netlify/cli/pull/3316

**Comment by ehmicky** [comment]
This should be fixed now! :tada:
