### ISSUE TITLE
socket io on your reverse proxy xD 

### ISSUE THREAD

**Issue by Dj-jom2x** [netlify/cli#326]
can you tell me how to redirect socket io on your reverse proxy xD i still dont get it
/socket.io/* https://demo.com:4500/socket.io/:splat  200
sorry I don't know where to ask this

**Comment by erezrokah** [comment]
Sorry for the late reply. Closing this as stale.
If still relevant can you please follow the issue template:
https://github.com/netlify/cli/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md&title=Please+replace+with+a+clear+and+descriptive+title

**Comment by plh97** [comment]
...netlify not support proxy ws protocol
