### ISSUE TITLE
netlify status fails because of undefined full_name

### ISSUE THREAD

**Issue by tbassetto** [netlify/cli#3287]
**Describe the bug**

I am a paying customer and I believe my profile on the website is complete. It does have my name in the settings. But this is the result of `netlify status`:
![2021-09-02 09_04_30-PowerShell](https://user-images.githubusercontent.com/211630/131798643-990175c5-b7d8-4088-bc37-90d75e02d78a.png)

**To Reproduce**

1. For me it's just about `netlify status`

**Configuration**

CLI's version:
```bash
netlify-cli/6.8.4 win32-x64 node-v14.17.5
```

**Expected behavior**

Details about my profile :)

**CLI Output**

```
──────────────────────┐
 Current Netlify User │
──────────────────────┘
    TypeError: Cannot read property 'full_name' of undefined
```

**Comment by erezrokah** [comment]
This is probably coming from https://github.com/netlify/cli/blob/d6929baf62796f3594e7a6a71361650395d03262/src/commands/status/index.js#L45

@tbassetto do you mind running with `DEBUG=* netlify status` so we can get additional information?

Also, can you try `netlify logout` and then `netlify login`? That should refresh the authentication token.

**Comment by tbassetto** [comment]
![2021-09-02 12_22_07-PowerShell](https://user-images.githubusercontent.com/211630/131829023-9c11ccd2-ca9e-4da4-9927-77309fff5ff2.png)

Logging out and in again solved it!

**Comment by erezrokah** [comment]
Thanks @tbassetto! I'm keeping the issue open as I believe the error handling here:
https://github.com/netlify/cli/blob/d6929baf62796f3594e7a6a71361650395d03262/src/commands/status/index.js#L36

is missing some use cases, and at the very least we should exit with a generic error if we have an error but are unable to classify it.

**Comment by tinfoil-knight** [comment]
Closing this issue since it has been resolved now.

---

Terminal output in various cases tested with `netlify-cli/11.0.0`

Without Logging In:
```
Not logged in. Please log in to see site status.

Login with "netlify login" command
```

Logged In but directory is not linked to a site
```
──────────────────────┐
 Current Netlify User │
──────────────────────┘
Email: keith.kevin99@yahoo.com
Teams:
  keith-kevin99's team: Collaborator
 ›   Warning: Did you run `netlify link` yet?
 ›   Error: You don't appear to be in a folder that is linked to a site
```

Logged In and directory is linked to a site
```
ncli status
──────────────────────┐
 Current Netlify User │
──────────────────────┘
Email: keith.kevin99@yahoo.com
Teams:
  keith-kevin99's team: Collaborator
────────────────────┐
 Netlify Site Info  │
────────────────────┘
Current site: super-cool-site-by-keith-kevin99-yahoo-com-7564d
Netlify TOML: /Users/kunal/Desktop/myfolder.nosync/oss/p-cli-test/with-redirects/netlify.toml
Admin URL:    https://app.netlify.com/sites/super-cool-site-by-keith-kevin99-yahoo-com-7564d
Site URL:     https://super-cool-site-by-keith-kevin99-yahoo-com-7564d.netlify.app
Site Id:      93f53f84-27c6-49f0-b342-6de3379bcdaa
```
