### ISSUE TITLE
Function in `submission-created` doesn't have `payload.form_name`

### ISSUE THREAD

**Issue by jdsteinbach** [netlify/cli#3290]
Netlify provides a `form_name` value in the `payload` for `submission-created.js` functions. This is necessary for handling multiple forms in a single Netlify site. `netlify-cli` doesn't provide that key/value in `payload` for `submission-created.js`.

**Configuration**

* Install `netlify-cli`
* Create `submission-created.js` in your functions folder. 
* Have 2 forms in your site.
* Try to use `payload.form_name` in Netlify live: it works.
* Try to use `payload.form_name` in `netlify-cli`: it's missing.

**Expected behavior**

`netlify-cli` should expose `payload.form_name` for form functions, just like Netlify.com

**Comment by netlify-team-account-1** [comment]
Hi @jdsteinbach! Due to the mechanics behind the form submission system, it's not trivial for us to add that behaviour to the CLI (at the moment). That could chance in the future. As a workaround for you, you could embed a hidden form field into your forms:

```diff
<form netlify name="foo">
+  <input type="hidden" name="form-name" value="foo">
  ...
</form>
```

**Comment by jdsteinbach** [comment]
@netlify-team-account-1 Thanks for the reply! I'll use the hidden field workaround for now.

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
