### ISSUE TITLE
Incorrect hook given in "configure webhook" prompt

### ISSUE THREAD

**Issue by cheapsteak** [netlify/cli#33]
Am given `https://api.netlify.com/hooks/{xxxxxxx}`, which 404s when put into github

Not sure if this is the right one, but the web ui shows a `https://api.netlify.com/build_hooks/{xxxxx}` api. Was it removed or renamed?

**Comment by fool** [comment]
The build_hooks one is the right one!  We're looking into the bug here - thanks for letting us know!

**Comment by bcomnes** [comment]
This will be fixed in the 2.0.0 release.
