### ISSUE TITLE
updateSite API method not working

### ISSUE THREAD

**Issue by Hrishikesh-K** [netlify/cli#3303]
**Describe the bug**

The updateSite API method doesn't seem to work. It works perfectly when calling the API directly, but doesn't seem to make the required changes when making the change through CLI.

Tested in cases:

https://netlify.zendesk.com/agent/tickets/64498 (INTERNAL-ONLY LINK)
https://answers.netlify.com/t/updating-a-sites-custom-domain-from-the-cli-does-not-work/43578

**To Reproduce**

1. Create a Netlify website and get its API ID.
2. Run the following command:

`netlify api updateSite --data '{ "site_id": "id-from-above", "name": "footer" }'`

**Configuration**

```bash
  System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 166.34 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.8.0 - /usr/local/bin/node
    npm: 7.21.0 - /usr/local/bin/npm
```

**Expected behavior**

The command should actually update the site's settings.

**CLI Output**

It logs the output from the API returned data.

**Comment by ehmicky** [comment]
Hi @Hrishikesh-K,

The correct syntax is `netlify api updateSite --data '{ "site_id": "id-from-above", "body:" { "name": "footer" } }'`. Does this work for you?

**Comment by Hrishikesh-K** [comment]
Thank you for suggesting that. That's it, it works!
