### ISSUE TITLE
Functions event.isbase64Encoded discrepancy in CLI vs Production

### ISSUE THREAD

**Issue by Hrishikesh-K** [netlify/cli#3315]
**Describe the bug:**

The production server encodes the function's `event.body` to `base64` except for a few content-types as mentioned here: https://answers.netlify.com/t/changed-behavior-in-function-body-encoding/19000.

When submitting a file using a (non-Netlify) form to a Netlify Function, we have to use `multipart/form-data` content-type which is encoded according to the above post. Thus, we need to decode it as:

```js
Buffer.from(event.body, 'base64').toString('utf8')
```

However, when doing the same in CLI, the body is not encoded and available easily as `event.body`.

It can easily be worked around like:

```js
if (event.isbase64Encoded) {
  Buffer.from(event.body, 'base64').toString('utf8')
} else {
  event.body
}
```

But, it leads to confusion.

**To reproduce:**

1. Clone this commit: https://github.com/Hrishikesh-K/formFile/tree/1f7d002c18eff4830614d6d405d84cee4dd106e8.
2. Navigate to the cloned repository.
3. Run `netlify dev`.
4. Try to submit the form with any random file and log `event.body`. Then, log the same in production environment.

**Configuration:**

`netlify.toml`:

```toml
[build]
  command = "echo Hi!"
  publish = "dist"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
```

System info:

```bash
  System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 746.86 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.0 - /usr/local/bin/node
    npm: 7.21.1 - /usr/local/bin/npm
```

**Expected behaviour:**

The CLI should encode `event.body` to `base64`.

**Additional context:**

Slack discussion (INTERNAL ONLY): https://netlify.slack.com/archives/C023PC3D08J/p1631194079008400

**Comment by bettse** [comment]
I just ran into this myself recently.
I haven't found where the base64 encoding is happening for production, but I believe the discrepancy in the CLI is in this regex: https://github.com/netlify/cli/blob/main/src/lib/functions/utils.js#L6

I suspect adding `multipart/form-data` would align the experience.

**Comment by bettse** [comment]
I tracked down what causes this in production, I'll drop the details in slack
