### ISSUE TITLE
netlify dev with vue cli

### ISSUE THREAD

**Issue by bluelovers** [netlify/cli#332]
**- Do you want to request a *feature* or report a *bug*?**

i think is a bug???

**- What is the current behavior?**

http://localhost:8888/ <== i think this from netlify dev
http://localhost:8080/ <== i think this from vue cli

use view source on http://localhost:8888/ 

![image](https://user-images.githubusercontent.com/167966/59422071-52199d80-8e02-11e9-862f-129f3cb6efc9.png)

click one of link
```
<script src=/js/chunk-vendors.915ffe73.js></script><script src=/js/app.6b7dd2af.js></script></body></html>
```

![image](https://user-images.githubusercontent.com/167966/59422376-dd932e80-8e02-11e9-8907-8fa325f43a2b.png)

all redirect to index.html

---

but if view http://localhost:8080/

everything work

---

![image](https://user-images.githubusercontent.com/167966/59422326-ceac7c00-8e02-11e9-9383-37b77302bd5b.png)

![image](https://user-images.githubusercontent.com/167966/59422349-d4a25d00-8e02-11e9-9a79-a65d91ebf9d9.png)

repo
https://github.com/bluelovers/ws-novel-vue

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your node.js, and operating system version.**

**Comment by RaeesBhatti** [comment]
This has been fixed in the latest version. Please update to `netlify-cli@2.46.0` and let us know if the problem still persists.
