### ISSUE TITLE
Support for Expo (React Native for web) apps

### ISSUE THREAD

**Issue by EvanBacon** [netlify/cli#333]
**- Do you want to request a *feature* or report a *bug*?**

# Feature Request

Now with first-class web support coming to [React Native](https://blog.expo.io/expo-cli-and-sdk-web-support-beta-d0c588221375) it would be great to have feature detection built into the deployment command. 

**- What is the current behavior?**

* Run `expo build:web` to generate a static site
* `netlify deploy` starts the flow
* choose a name
* ? **deploy path** ( . ) - `/web-build`

This last step doesn't seem to persist my choice. It'd be cool if it checked to see if the `app.json` (React Native config file) exists in the root directory, then possibly checks to see if `expo.web.build.output` is defined (custom output path). 

So if `/web-build` exists and `app.json` exists you would get the following:
* ? **deploy path** (web-build)

and if `expo.web.build.output` is defined you would get that value as the auto suggested path.

# How

I'm happy to work on this PR if you guys are interested.

**Comment by sw-yx** [comment]
hey evan! been watching your RN demos and am very excited you are using netlify! 

this request is an excellent use case for splitting out detectors from Netlify Dev: https://github.com/netlify/netlify-dev-plugin/tree/master/src/detectors

we have been planning for this to be a standalone, reusable feature anyway and just need some work to take out some netlify dev specific assumptions.

i think i will need to do some heavy lifting to do this "split out project" and will free up after my conf commitments this week. wont need anything from you in the meantime but thanks for the push.

**Comment by lupelius** [comment]
any news with this?

**Comment by sw-yx** [comment]
no, sorry. i left the company. feel free to open up a new issue/pr
