### ISSUE TITLE
Error thrown when adding a TypeScript function, with basic `netlify.toml` + Nuxt

### ISSUE THREAD

**Issue by jonlambert** [netlify/cli#3345]
**Describe the bug**

When attempting to add a simple TypeScript function and running `netlify dev`, the function fails to build with the following error:

```
Failed reloading function test with error:
Cannot destructure property 'inputs' of '(intermediate value)' as it is undefined.
```

**To Reproduce**

1. Run `git clone git@github.com:jonlambert/netlify-typescript-issue.git`
2. Navigate to the cloned repository
3. Run `npm install && netlify dev`
4. See that the CLI emits an error

**Configuration**

- `netlify.toml`:

```
[dev]
  functions = "./functions"

[build]
  functions = "./functions"

```

- Environment:

```
  System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Memory: 72.77 MB / 16.00 GB
    Shell: 3.2.2 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.7.0 - /usr/local/bin/node
    npm: 7.11.2 - /opt/homebrew/bin/npm
    Watchman: 2021.08.02.00 - /opt/homebrew/bin/watchman
  npmGlobalPackages:
    netlify-cli: 6.9.6
```

**Expected behavior**

The TypeScript function to be built and served.

**CLI Output**

```

◈ Netlify Dev ◈
◈ Ignored general context env var: LANG (defined in process)
◈ Loaded function test.
◈ Functions server is listening on 55103
◈ Starting Netlify Dev with Nuxt
◈ Failed reloading function test with error:
Cannot destructure property 'inputs' of '(intermediate value)' as it is undefined.

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘


 WARN  Address localhost:3000 is already in use.

ℹ Trying a random port...
ℹ Listening on: http://localhost:55111/
ℹ Preparing project for development
ℹ Initial build may take a while
✔ Builder initialized
✔ Nuxt files generated
ℹ Compiling Client
ℹ Compiling Server
✔ Server: Compiled successfully in 939.80ms
✔ Client: Compiled successfully in 1.15s
ℹ Waiting for file changes
ℹ Memory usage: 138 MB (RSS: 243 MB)
ℹ Listening on: http://localhost:55111/
```

**Additional context**

N/A

**Comment by eduardoboucas** [comment]
Hi @jonlambert, thanks for filing this. We found a problem with the path resolution logic in the CLI, which we're in the process of fixing.

In the meantime, and to get you unblocked, can you try removing the `functions` property from the `[dev]` block? This property shouldn't be necessary, as it has the same value as `functions` in `[build]`. 

If you do need a different path for the local environment, can you try to temporarily set it to a full path, instead of a relative path?

Let me know if this works for you.

**Comment by dmmulroy** [comment]
We're also running into this problem even running `netlify functions:serve` and pointing it directly at our functions directly still causes the issue.

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
