### ISSUE TITLE
Use pkg to bundle cli

### ISSUE THREAD

**Issue by jschatz1** [netlify/cli#337]
We should use [`pkg`](https://www.npmjs.com/package/pkg) to distribute the cli. Doing this will allow us to put all deps in the dev dependencies which won't print out any logs from install and will allow us to have one file that gets distributed which will make the install run wicked fast. 

cc @sdras

**Comment by DavidWells** [comment]
Note: using `pkg` precludes the use of certain native bindings like the `opn` package

This means removing the "open browser for me functionality" via `netlify open` command (and other --open flags like on `deploy`)

**Comment by sdras** [comment]
Oh damn- we would need that for VS Code too to trigger the authentication flow.

**Comment by DavidWells** [comment]
There are going to be 2 builds for the `cli` soonish. 

1 for humans and another for CI systems. The "CI version" will exclude `opn` and be bundled by `pkg` for snappier installs like mentioned for netlify buildbot/external systems.

If you really want to hide the install message we will need to install CLI via an external tool (IE electron desktop app like https://github.com/zeit/now-desktop/blob/ee6fe612f6665bd310b8edd0bd6b64764818de82/main/binary.js#L469 or remove/fork the dependancies creating the logs)

**Comment by DavidWells** [comment]
Closing this for now
