### ISSUE TITLE
[feature idea] functions dependency install command

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#339]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
we just have crappy failures when functions have dependencies that aren't installed. even causes users to do ugly things like check node modules into git https://github.com/fauna/public-slack-invite/tree/master/functions/request-slack-invite ugh.

**- What is the expected behavior?**

we should have some sort of command, maybe `netlify functions:install` that just goes through every folder and installs deps. this isnt onlyuseful for buildbot, we might also want this for local usage as well.

**Comment by DavidWells** [comment]
+ 1000

Something like:

If (command === 'deploy' || command === 'dev') {
  // check deps, hash package.json
  // install deps if missing
} 

Buildbot also needs to do this automatically (recursive installation of deps)

**Comment by sw-yx** [comment]
ohh your way is probably smarter. mine would be a whole new command.

**Comment by erezrokah** [comment]
Closing in favour of https://github.com/netlify/cli/issues/454
