### ISSUE TITLE
Bug Report: Netlify-Cli Update Version Error Notification During Deployment

### ISSUE THREAD

**Issue by sgrobert** [netlify/cli#341]
**- Do you want to request a *feature* or report a *bug*?**
This is a minor bug, but I do believe it got quite annoying when I was deploying a few time more and the bug still persist.

**- What is the current behavior?**
"**Update Netlify-Cli Notification**" does not align with current version installed. Latest being installed yet notification does not recognise installed version and still poses update notification.

<img width="233" alt="Screenshot 2019-07-01 13 02 44" src="https://user-images.githubusercontent.com/759805/60411704-9bd6f600-9c00-11e9-9fab-f8e3c893d9ab.png">
<img width="369" alt="Screenshot 2019-07-01 12 50 42" src="https://user-images.githubusercontent.com/759805/60411707-9da0b980-9c00-11e9-9521-99caef0154b5.png">

**- If the current behavior is a bug, please provide the steps to reproduce.**
After doing a compile using "**yarn build**" for my React code, and subsequently a "**netlify deploy**" and "**netlify deploy --prod**" to complete the deployment process, a "_Update Available_" notification kept showing up though the the current version is already up to date.

This bug seemed to be persistent for quite a while already, so I would just like to double-check is it a bug that is on the system.

**- What is the expected behavior?**
The tool does recognise the updated version and only notify when there is an update that is really different from the one existing in the system

**- Please mention your node.js, and operating system version.**

node.js==6.9.2
macosx==10.14.5

"netlify-cli": "^2.11.23"

**Comment by erezrokah** [comment]
Closing as stale. Please comment with a reproduction repo and the output of `npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli` if still relevant.
