### ISSUE TITLE
Redirects for functions result in a 404

### ISSUE THREAD

**Issue by jlengstorf** [netlify/cli#3427]
**Describe the bug**

When using a `_redirects` file, proxy redirects for Netlify Functions 

**To Reproduce**

1. Clone https://github.com/jlengstorf/feature-tour-sep29-2
2. Install the latest Netlify CLI
3. Run `netlify dev`
4. Visit `http://localhost:8888/api/hello-world`

**Configuration**

see repo

**Expected behavior**

redirect should work

**CLI Output**

it appears to be trying for HTML, but not a function

```
[access] /api/hello-world
[access] /404
[access] Not Found: /api/hello-world
[access] /api/hello-world.html
```

**Comment by ehmicky** [comment]
Hi @jlengstorf,

Thanks for the report.
I am not able to reproduce using the repository:

```
$ netlify dev
◈ Netlify Dev ◈
◈ Ignored general context env var: LANG (defined in process)
◈ Loaded function hello-world.
◈ Functions server is listening on 42209
◈ Starting Netlify Dev with Astro

> @example/starter@0.0.1 dev
> astro dev

[19:56:36] [snowpack] Hint: run "snowpack init" to create a project config file. Using defaults...
[19:56:37] [snowpack] Ready!
[19:56:37] [snowpack] watching for file changes... 
[dev server] Server started in 715ms.
[dev server] Local: http://localhost:3000/
[access] /

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘

[access] /
◈ Rewrote URL to /.netlify/functions/hello-world
Request from ::ffff:127.0.0.1: GET /.netlify/functions/hello-world
Response with status 200 in 43 ms.
```

![world](https://user-images.githubusercontent.com/8136211/135658535-6ea5af94-d7e4-488c-b118-1cccb6ae582d.png)

I am using Netlify CLI `6.9.28`. Could you try again using the reproduction repository with that Netlify CLI version and confirm this is still not working for you?

**Comment by jlengstorf** [comment]
I haven't hit this again, so I'm going to assume something was weird in my setup
