### ISSUE TITLE
Verify gitlab remotes work with `netlify init` 

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#344]
Jacob ran into git error "No git configurator found" when connecting to gitlab repo.

https://github.com/netlify/cli/blob/b517775b907d3e5f428948502b30dc32ed2e46da/src/utils/get-repo-data.js#L4-L5

Seems like the underlying `git-remote-origin-url` pkg or `parse-github-url` libs are returning that error

**Comment by jschatz1** [comment]
<img width="458" alt="Screen Shot 2019-07-01 at 3 16 31 PM" src="https://user-images.githubusercontent.com/322665/60460984-3b9d7f80-9c13-11e9-822d-afee4e44994c.png">

**Comment by DavidWells** [comment]
mmm related https://github.com/netlify/cli/issues/242

**Comment by DavidWells** [comment]
Error comes from here: https://github.com/netlify/cli/blob/fca626a319901c2d7f34fb81e0f80a8eb1c9764e/src/commands/init.js#L212-L215

We are missing gitlab config.

The logic that connects the netlify site to the gitlab repo and adds the build webhooks needs to be extracted out of the netlify UI and used here.

These bits of logic https://github.com/netlify/netlify-react-ui/tree/ee6d2c8f664e7e1fa095af1823fb61ad183eeb2b/src/lib/gitproviders need to be shared by the UI & the CLI. This is so we are replicating the logic in multiple projects

**Comment by DavidWells** [comment]
Ideally we pluck out the logic of how repos get connected into a service.

Then a client library can consume the service API.

This will require syncing with API team on how github apps integration works

**Comment by erezrokah** [comment]
Closing in favour of https://github.com/netlify/cli/issues/195
