### ISSUE TITLE
set default start command

### ISSUE THREAD

**Issue by mdskinner** [netlify/cli#347]
Is it possible to set the desired start command?

On a sapper project:  netlify dev
returns:
![Screenshot 2019-07-09 at 11 28 46 AM](https://user-images.githubusercontent.com/147073/60849062-3e185e80-a23d-11e9-87ee-da861474f231.png)

It shouldn't be giving vue-cli as an option as I don't have any reference to vue in my package.json file.. but I'd also like to specify [svelte] npm dev   (3rd line)  as my default

**Comment by sw-yx** [comment]
yes, use the netlify dev block:

```
[dev]
   command = "npm start"
```

do you have `@vue/cli-service` anywhere in your package.json? [thats how this detector is supposed to work.](https://github.com/netlify/netlify-dev-plugin/blob/master/src/detectors/vue.js). If you don't then i would appreciate a repro to investigate why this is matching vue-cli, this is a very strange report if so.

**Comment by mdskinner** [comment]
sorry, I should have specified, I've already got that set.

[build]
  functions = 'src/lambda'

[dev]
  command="npm run dev"
  port=3000

**Comment by sw-yx** [comment]
![image](https://user-images.githubusercontent.com/6764957/60856139-2b1d7400-a1d4-11e9-9815-e83c5a49eb60.png)
this is what i see when i run netlify dev on your repo. do we have version issues? i'm on `netlify-cli/2.11.23 darwin-x64 node-v10.13.0`.

yes `svelte` should probably also check for sapper and disambiguate itself.

**Comment by mdskinner** [comment]
`netlify-cli/2.11.23 darwin-x64 node-v10.16.0`

**Comment by sw-yx** [comment]
updated https://github.com/netlify/netlify-dev-plugin/blob/master/src/detectors/svelte.js
