### ISSUE TITLE
netlify deploy --toml <path-to-toml> is missing

### ISSUE THREAD

**Issue by dan003400** [netlify/cli#3480]
I find it very very odd that simply supplying a path to the toml file is not something that is included in this cli, this blows my mind actually.

We are not using netlify builders and want to simply deploy from circleci but we are in a subdirectory of a monorepo.

All issues would be removed if you could simply supply a path to the config toml, I am not sure I have ever used a cli where this is not one of the most basic arguments to a command like deploy.

**Comment by ehmicky** [comment]
> unless providing a --site flag to the deploy command removed the need to use the link command all together?

Yes, exactly. The `--site` flag can be provided without having to perform `netlify link`. Based on the above, it appears this might solve your problem. :+1:

**Comment by dan003400** [comment]
Well that is frustrating, seems we should have used this to begin with rather than supplying the toml file path. The hanging user supplied inputs make it seem as if the toml file could not be found, as it "can" include the ID under `[Settings]` but that seems to be ignored completely, which is VERY odd.

**Comment by ehmicky** [comment]
Yes, you're correct.
Did this solve your problem?

**Comment by dan003400** [comment]
Yes, --site is all that was needed. Seems the docs do not make this clear, nor does it make it clear that the [Settings] ID from toml is completely ignored...

**Comment by verythorough** [comment]
Hi @dan003400, I'm glad to hear you've got things working. To better understand potential docs improvements, could you help me understand the following?

- What caused you to try adding `[Settings] ID` to your `netlify.toml` file? We don't support this configuration option, so I'm hoping to figure out if there's a place where we need to remove an errant reference to it.
- The `--site` flag is documented in the [deploy command reference](https://cli.netlify.com/commands/deploy) and in the output for `netlify deploy help`. Did you find either of these sources when looking for a `--toml` flag? Are there other places you checked for this information? Understanding where you looked and what you found can help us improve discoverability.

**Comment by BenLune** [comment]
Hi,
I'm trying to target 2 different toml files depending on build mode.
I'm working on Angular applications, with Scully for SSG.
SSG is only triggered for master branch and tags, otherwise it's a default Angular build.
When I'm building a default Angular App, I need Netlify to redirect every url to index.html.
When I'm on SSG mode, the urls targets some real SSG folders and I don't want the default SPA redirection to index.html. I need also to redirect to language prefix when I'm on SSG mode.
So if I could easily target a toml file or another depending on the type of build, it would be very helpful.

**Comment by BenLune** [comment]
I hope this command will work soon : 
`netlify deploy --config <path-to-toml>`
Meanwhile I had to deal with file rename while CI process (netlify-default.toml OR netlify-scully.toml depending on context to netlify.toml).

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
