### ISSUE TITLE
Github credentials have expired. CLI throwing error but not prompting for updated credentials.

### ISSUE THREAD

**Issue by leemartin** [netlify/cli#3488]
**Describe the bug**

When I try and init a new project using the netlify-cli, everything works as planned until the cli attempts to link the netlify project to the associated git repository. At that point it throws the following error:

**Error: Failed retrieving GitHub repository information with error: Bad credentials**

I've looked through the CLI docs but I'm not sure how to reset my Github credentials.

**To Reproduce**

For me, this occurs during the `netlify init` process with a new netlify project and an existing (linked) github repository. Again, the netlify project is created but the `init` process ends in error and I must visit the netlify.com interface to link the Github project.

**Expected behavior**

I suppose I expected the CLI to prompt me to update my Github credentials or for the documentation to explain how I can do this.

**CLI Output**

```
Error: Failed retrieving GitHub repository information with error: Bad credentials
```

**Comment by erezrokah** [comment]
Hi @leemartin, thank you for opening this issue.

GitHub credentials are stored in a `config.json` file under the user [shared preferences directory](https://docs.netlify.com/cli/get-started/#config-json-location), so at the moment the best way to reset them is to edit that file.

A better way to handle this in the code will be to improve this function:
https://github.com/netlify/cli/blob/6d6022ec50546dd59e733d2bda871601cafc611a/src/utils/init/config-github.js#L22

to validate the token using a request to GitHub.
