### ISSUE TITLE
cli perf tip from rn cli

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#350]
**- Do you want to request a *feature* or report a *bug*?**
feature
**- What is the current behavior?**
slow cli
**- If the current behavior is a bug, please provide the steps to reproduce.**
https://mobile.twitter.com/thymikee/status/1092885415365877760

**Comment by erezrokah** [comment]
This will require adding a build step for the CLI.
We would need to consider if we really want that and also would need to measure the actual benefit.
