### ISSUE TITLE
DX: Improve broken token error message

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#355]
The current error if you make a netlify API call with invalid token looks like this:

```
FetchError: invalid json response body at https://api.netlify.com/api/v1/sites?filter=all reason: Unexpected end of JSON input
    at ~/Netlify/repos/cli/node_modules/node-fetch/lib/index.js:272:32
```

We need to make those nicer for users.

These are thrown down in the https://github.com/netlify/js-client

**Comment by erezrokah** [comment]
Closing in favour of https://github.com/netlify/cli/issues/174
