### ISSUE TITLE
"netlify dev --live" error

### ISSUE THREAD

**Issue by theFlexOne** [netlify/cli#3561]
This is what happens when I run "netlify dev --live".

      flexone@penguin:~/code/flatiron/projects/project-1-weather-app$ netlify dev --live
      ◈ Netlify Dev ◈
      ◈ Ignored general context env var: LANG (defined in process)
      ◈ No app server detected. Using simple static server
      ◈ Running static server from "project-1-weather-app"
      ◈ Functions server is listening on 46415
      
      ◈ Static server listening to 3999
          Error: Command failed with exit code 2: /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client 
          version
          /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client: 1: 
          /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client: H1�H1��8P�8P��@P�@P��iF: not found
          /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client: 1: 
          /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client: ��: not found
          /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client: 1: 
          /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client: ELF: not found
          /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client: 1: 
          /home/flexone/.config/netlify/tunnel/bin/live-tunnel-client: Syntax error: Unterminated quoted string

I've removed netlify-cli and reinstalled it, through npm, and I created a brand new site at netlify and ran "netlify init" to relink my project.

"netlify dev" works...

**Comment by lukasholzer** [comment]
@theFlexOne can you please provide more details on your netlify version by running: `netlify --version`.

It would be great to get a step by step list on how to reproduce this issue otherwise we cannot fix it.

Thank you already in advance for your help 🎉

**Comment by charliegerard** [comment]
Hey @lukasholzer! I've been running into the same issue today and I think I might know what's not working.

Personally, I was trying to run `netlify dev --live` on a RaspberryPi and it seems like the `live-tunnel-client` is an [amd64 package](https://github.com/netlify/live-tunnel-client/blob/master/checksums/0.1.0.txt), so it can't run on a Pi, cause I think it only supports arm64.

I'm not familiar with how that usually works so I'm not sure if we can build the package for arm64 but maybe that would fix it?

**Comment by erezrokah** [comment]
Thanks @charliegerard! For context, the place to add a new architecture should be in (private link): https://github.com/netlify/live-tunnel/blob/40e678407da73cdaaaa21f28fd80a9914f20efcd/Makefile#L118

**Comment by lukasholzer** [comment]
@erezrokah I'm already on it 👍 I think we should do a better erroring inside the CLI if the CPU architecture or os is not supported.

**Comment by lukasholzer** [comment]
We are using always an `amd64` binary -> 

```
package: `${execName}-${platform}-amd64.${extension}`,
```

which seems incorrect for me (strangely it works on my m1 chip, as it should be darwin arm64 for me)

what about windows and `ia32` shouldn't we use `process.arch` and `process.platform` to detect which binary to download @erezrokah

**Comment by erezrokah** [comment]
> @erezrokah I'm already on it 👍 I think we should do a better erroring inside the CLI if the CPU architecture or os is not supported.

Yep completely agree with both comments. We should error out if we don't support the `arch`, and then consider building the tunnel client with more arch targets.
