### ISSUE TITLE
chore: remove deprecated querystring package with URLSearchParams

### ISSUE THREAD

**Issue by tinfoil-knight** [netlify/cli#3562]
**Describe the bug**

The [querystring](https://www.npmjs.com/package/querystring) package has been deprecated now and should be replaced by URLSearchParams API as recommended in its documentation.

It's used in 3 files: `functions-templates/javascript/google-analytics/{{name}}.js`, `functions/form-submissions-handler` and `utils/gh-auth`.

**Comment by tinfoil-knight** [comment]
@ehmicky Should I pick this one up?

**Comment by tinfoil-knight** [comment]
The URLSearchParams API isn't supported Node.js 12.0.0. Since there's ongoing work to upgrade the repo Node version to that in https://github.com/netlify/cli/issues/3512, I'm just leaving this open for now.

**Comment by ehmicky** [comment]
I believe `URLSearchParams` was added in Node `6.13.0` and made [a global object in Node `10.0.0`](https://nodejs.org/api/url.html#class-urlsearchparams)?

**Comment by tinfoil-knight** [comment]
Just checked again. What you're saying is correct but the lint extension was reporting this:
![image](https://user-images.githubusercontent.com/51631122/139876530-6dc95256-c087-4b54-8a6c-96070efca46f.png)

I probably mixed up the version from another lint error which can be fixed with a polyfill:
![image](https://user-images.githubusercontent.com/51631122/139878038-51e6650d-0b4a-48ee-937e-a2ca9fa5636f.png)


Added the engines property for the function template. Working now.
