### ISSUE TITLE
Let netlify dev output an error if you are not logged in with the right account

### ISSUE THREAD

**Issue by martinjagodic** [netlify/cli#3572]
**Is your feature request related to a problem? Please describe.**

I switch between Netlify accounts in my CLI and today it took me a long time to realize that I'm on the wrong account. `netlify dev` would just stop after injecting environment vars and it didn't tell me why.

**Describe the solution you'd like**

the CLI should show an error/warning if you're trying to run `netlify dev` on a site that is linked to another account that you are currently logged into.

**Describe alternatives you've considered**

You have to know/guess what is the problem.

**Additional context**

This is how it looks like when it stops without any relevant info.

![Screenshot 2021-11-03 at 09 38 00](https://user-images.githubusercontent.com/42938138/140030068-62f60599-390f-4700-a9bf-15561bfe0f7c.png)

**Can you submit a pull request?**
No.

**Comment by lukasholzer** [comment]
@martinjagodic  would this be sufficient?

<img width="1079" alt="CleanShot 2021-11-04 at 10 44 03@2x" src="https://user-images.githubusercontent.com/11156362/140292161-62c8f389-43a6-4470-b82f-a7b508141ceb.png">

**Comment by martinjagodic** [comment]
This is great @lukasholzer, thank you!
