### ISSUE TITLE
feature: add env:transfer CLI command

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#3575]
**Is your feature request related to a problem? Please describe.**

I would like to transfer UI environment variables from one site to another

**Describe the solution you'd like**

```
# from current linked site to a new site
netlify env:transfer <to-site-id-or-name>

# from one site to another 
netlify env:transfer <from-site-id-or-name> <to-site-id-or-name>
```

**Describe alternatives you've considered**

Manually transferring variables via copy/paste

**Additional context**

https://github.com/netlify/product/issues/836 (internal link)

**Comment by ashalfarhan** [comment]
Hi @erezrokah , can i grab this up?

**Comment by erezrokah** [comment]
Thanks @ashalfarhan, I've assigned you to the issue. The relevant code is here https://github.com/netlify/cli/tree/main/src/commands/env
