### ISSUE TITLE
Netlify Dev Server doesn't start on Node 17.x/18.x

### ISSUE THREAD

**Issue by Hrishikesh-K** [netlify/cli#3617]
**Describe the bug**

Similar to this: https://github.com/netlify/cli/issues/2882#issue-939909811

Netlify Dev tries to start a server, it injects the environment variables, parses the configuration files and starts the local server of the framework, however it never starts the Netlify CLI's server.

Till now, the behaviour has been observed with Vite and Create React App (but more frameworks could be affected). This has been observed on MacOS 12. Other Operating Systems have not been checked.

This works with Node `14.17.5`, possibly with any other Node version than Node 17.

**To Reproduce:**

1. Use Node 17 (17.0.1 at the time of writing).
1. Try running `netlify dev` in a project (possibly in a Vite or CRA project)
1. See that the dev server never starts.

**Configuration**

```bash
  System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 891.31 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - ~/.nvm/versions/node/v17.0.1/bin/node
    npm: 8.1.1 - ~/.nvm/versions/node/v17.0.1/bin/npm
```

**Expected behaviour**

The Netlify Dev server should start.

**CLI Output**

Vite:

```
◈ Netlify Dev ◈
◈ Ignored general context env var: LANG (defined in process)
◈ Starting Netlify Dev with vite

> dev
> vite


  vite v2.4.1 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 217ms.
```

**Additional context**

Marked `low-priority` as there's a workaround to use a different Node version.

**Comment by erezrokah** [comment]
In case someone would like to pick this up, the line we wait for the framework server (e.g. Vite) is here:
https://github.com/netlify/cli/blob/51e7b69dd8065b18081c564aeb6d1e225d83380a/src/commands/dev/index.js#L104

**Comment by tinfoil-knight** [comment]
@erezrokah Is this related to https://github.com/vitejs/vite/issues/5365? 
As per the organisation member:
> In the current state, we don't support node 17 right now.

**Comment by erezrokah** [comment]
@tinfoil-knight woo - great find.

This was also reported for `create-react-app` on the [related issue](https://github.com/netlify/cli/issues/2882#issuecomment-962267640).

@LuskeyNoah does reverting to Node.js < 17 work for you?
This will help us confirm if this is a Vite specific issue or not.

**Comment by ryansburgoyne** [comment]
I have encountered this as well with a Hugo site: https://answers.netlify.com/t/netlify-dev-server-not-starting-for-hugo-site/47222

One interesting bit is that it works the first time I try after rebooting my machine (I have to navigate to the Hugo-launched page first, and that will trigger it to launch the Netlify server on port 8888), but after killing the server I can't get it back up again without rebooting.

**Comment by LuskeyNoah** [comment]
> @LuskeyNoah does reverting to Node.js < 17 work for you? This will help us confirm if this is a Vite specific issue or not.

Yes, reverting to node 16 LTS fixes the issue for me.

**Comment by erezrokah** [comment]
Reported for Vue too in https://github.com/netlify/cli/issues/3772

**Comment by MincePie** [comment]
Is this still current?

**Comment by tkrunning** [comment]
@MincePie Yes, seems so. With `netlify-cli` version `9.16.3` and node `v17.9.0` the dev server is still not starting for me when running `netlify dev` (for a Jekyll project). Works fine with `v16.13.2`.

**Comment by robvanderleek** [comment]
Also bumped into this problem recently and reverted Node to v16.
FWIW this is how to downgrade to Node  16.x on macOS with Brew:
```shell
brew uninstall --ignore-dependencies node
brew install node@16
brew link node@16
```

**Comment by SeanCassiere** [comment]
Can confirm that this issue also persists on Node 18 as well.

My app uses `create-react-app`, and like the others on Node@17 (and above including 18), the local webpack server starts, however, the Netlify Dev server (localhost:8888) does not. (Both the react-app content and the functions are not available at 8888)

```bash
seanc ⋊> ~/c/nav-credit-card-update git:(main) node -v                                                                                                                                                                                11:49:22
v18.0.0
seanc ⋊> ~/c/nav-credit-card-update git:(main) netlify dev                                                                                                                                                                            11:49:24
◈ Netlify Dev ◈
◈ Ignored build settings env var: REACT_APP_API_BASE_URL_V3 (defined in .env file)
◈ Injected .env file env var: REACT_APP_API_BASE_URL_V3
◈ Ignored build settings env var: V3_AUTH_URL (defined in .env file)
◈ Injected .env file env var: V3_AUTH_URL
◈ Ignored build settings env var: V3_CLIENT_ID (defined in .env file)
◈ Injected .env file env var: V3_CLIENT_ID
◈ Ignored build settings env var: V3_CLIENT_SECRET (defined in .env file)
◈ Injected .env file env var: V3_CLIENT_SECRET
◈ Ignored build settings env var: REACT_APP_QA_API_BASE_URL_V3 (defined in .env file)
◈ Injected .env file env var: REACT_APP_QA_API_BASE_URL_V3
◈ Ignored build settings env var: QA_V3_AUTH_URL (defined in .env file)
◈ Injected .env file env var: QA_V3_AUTH_URL
◈ Ignored build settings env var: QA_V3_CLIENT_ID (defined in .env file)
◈ Injected .env file env var: QA_V3_CLIENT_ID
◈ Ignored build settings env var: QA_V3_CLIENT_SECRET (defined in .env file)
◈ Injected .env file env var: QA_V3_CLIENT_SECRET
◈ Injected .env file env var: REACT_APP_API_BASE_URL
◈ Injected .env file env var: REACT_APP_V3_AUTH_URL
◈ Injected .env file env var: REACT_APP_DEVELOPMENT
◈ Injected .env file env var: SERVER_PORT
◈ Loaded function GetTokenV3 http://localhost:8888/.netlify/functions/GetTokenV3.
◈ Functions server is listening on 57852
◈ Starting Netlify Dev with Create React App
yarn run v1.22.18
$ react-scripts start
ℹ ｢wds｣: Project is running at http://0.0.0.0:3000/
ℹ ｢wds｣: webpack output is served from 
ℹ ｢wds｣: Content not from webpack is served from /Users/seanc/code/nav-credit-card-update/public
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...

Compiled successfully!

You can now view nav-reservation-cc-update in the browser.

  http://localhost:3000

Note that the development build is not optimized.
To create a production build, use yarn build.
```

**Comment by twofingerrightclick** [comment]
I get this issue - no proxy from the apps port to the netlify functions port- whenever I use typescript with Nuxt. It is very frustrating not to be able to use the api. Netlify-cli 10.3.0, Node 16.x.x, Nuxt 2.15.8.
I have tried using various versions of Node 16.x.x but no luck. 
![image](https://user-images.githubusercontent.com/11265760/167285849-ff2ee21b-3c3a-4a11-8b97-3399ac6aea32.png)

**Comment by Hrishikesh-K** [comment]
Just came back to say that this seems to be the case for Node 18 too. I thought someone else might have reported by now, but since no one had, just adding a note here.

**Comment by agnescameron** [comment]
also having this issue with node 18!

**Comment by Kirbyasdf** [comment]
Its rekt for me too....lets get it going @sw-yx

**Comment by mosesoak** [comment]
Fails for us using nvm with the following:
```
3:37:20 PM: Python version set to 2.7
3:37:20 PM: Attempting node version '18' from .nvmrc
3:37:21 PM: Downloading and installing node v18.5.0...
3:37:21 PM: Downloading https://nodejs.org/dist/v18.5.0/node-v18.5.0-linux-x64.tar.xz...
3:37:22 PM: Computing checksum with sha256sum
3:37:22 PM: Checksums matched!
3:37:24 PM: node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by node)
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by node)
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
nvm is not compatible with the npm config "prefix" option: currently set to ""
3:37:24 PM: Run `nvm use --delete-prefix v18.5.0` to unset it.
3:37:24 PM: Failed to install node version '18'
```

**Comment by nth-child** [comment]
Fails for me using nvm to install node 16.16.0
```
Downloading and installing node v16.16.0...
Downloading https://nodejs.org/dist/v16.16.0/node-v16.16.0-darwin-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with shasum -a 256
Checksums matched!
Now using node v16.16.0 (npm v8.11.0)
MBP-3:my-app comp$ netlify dev
bash: netlify: command not found
```

**Comment by nth-child** [comment]
Fails for me using nvm to install node 16 (all releases)
```
Downloading and installing node v16.13.0...
Downloading https://nodejs.org/dist/v16.13.0/node-v16.13.0-darwin-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with shasum -a 256
Checksums matched!
Now using node v16.13.0 (npm v8.1.0)
Ians-MBP-3:generate-email-app ian$ netlify dev
bash: netlify: command not found
```

**Comment by nth-child** [comment]
Fails for me using nvm to install node 16 (all releases)
```
Downloading and installing node v16.13.0...
Downloading https://nodejs.org/dist/v16.13.0/node-v16.13.0-darwin-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with shasum -a 256
Checksums matched!
Now using node v16.13.0 (npm v8.1.0)
MBP-3:my-app comp$ netlify dev
bash: netlify: command not found
```

**Comment by pedroarthuralvesdeoliveira** [comment]
Hey, guys, what's up? I am getting this error too... Even using Node LTS version or the latest now (19.7.0)

**Comment by Hrishikesh-K** [comment]
Note 18 is working fine, I haven't checked with Node 19 yet. Could you share the output you get when running `netlify dev` in Node 18 environment?

**Comment by pedroarthuralvesdeoliveira** [comment]
Actually, when I run the functions in dev mode, I get this errors: 
![image](https://user-images.githubusercontent.com/69775937/224409331-69bc0619-46aa-44ee-8d36-832ebb81e50e.png)
![image](https://user-images.githubusercontent.com/69775937/224409661-6085be78-e2fb-433c-8ea5-f657ac9877e8.png)

The structure folder: 
![image](https://user-images.githubusercontent.com/69775937/224409785-2a51bd15-a271-40c1-a16e-528603d8f968.png)

The netlify.toml
![image](https://user-images.githubusercontent.com/69775937/224410202-13841966-844b-4791-a2cf-cdedf4a4bf6c.png)

**Comment by Hrishikesh-K** [comment]
Doesn't see related to this issue. Please open another one or write in Netlify Forums: https://answers.netlify.com/

**Comment by 1-800-jono** [comment]
Running Gatsby v4 and Node v18. Running `netlify dev` gets stuck in `Waiting for framework port 8000. This can be configured using the 'targetPort' property in the netlify.toml`
