### ISSUE TITLE
As a new user I don't know how to invoke my functions when served with `ntl dev`

### ISSUE THREAD

**Issue by lukasholzer** [netlify/cli#3618]
**Is your feature request related to a problem? Please describe.**

As a new user I don't know how I can invoke my functions when running with the `ntl dev` command

**Describe the solution you'd like**

I would expect something like this on startup by running: `ntl dev`

```diff
◈ Netlify Dev ◈
◈ Ignored general context env var: LANG (defined in process)
◈ No app server detected. Using simple static server
◈ Running static server from "build-reproductions/dist"
- ◈ Loaded function hello.
+ ◈ Loaded function hello available under: http://localhost:8888/.netlify/functions/hello 
◈ Functions server is listening on 58458

◈ Static server listening to 3999

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘

```

**Additional context**

Furthermore it is hard to find this information somewhere, needed some while to stumble over: https://answers.netlify.com/t/how-do-you-access-functions/746

**Can you submit a pull request?**

Yes.

**Comment by joeyaiello** [comment]
Ack and good with this, seems like a reasonable thing to do to drive clarity, hopefully fairly cheap to implement as well.
