### ISSUE TITLE
Convert CLI & related projects into Lerna mono-repo

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#365]
Convert related CLI projects into a github monorepo

## Why

There are an increasing amount of different github repos relating to the CLI.

- https://github.com/netlify/cli
- https://github.com/netlify/cli-utils
- https://github.com/netlify/zip-it-and-ship-it
- https://github.com/netlify/netlify-dev-plugin/
- https://github.com/netlify/netlify-lm-plugin
- ...

Releasing updates & bumping shared dependancies will become *a lot* easier with everything in one repo.

## About

The folder structure would be something like this:

```
packages/
packages/command # Base CLI command class used by all cli commands
packages/cli  # current https://github.com/netlify/cli code
packages/dev-command.    # netlify-dev-plugin
packages/function-bundler # zip-and-ship
packages/project-heurstics # dev detectors & other project heuristic utils
```

Then we can have easier release/PR process, like so:

```
lerna changed

"These things changed"
- package-x
- package-y
```

And release like so:

```
lerna publish
# publishes changed packages to npm
```

This also would make testing easier. 

```
lerna run test
# runs all tests for all packages
```

**Comment by erezrokah** [comment]
Don't think this is relevant anymore (we can re-visit).
