### ISSUE TITLE
Auto-detected frameworks cannot use the static server

### ISSUE THREAD

**Issue by ascorbic** [netlify/cli#3655]
**Describe the bug**

If a framework has an entry in framework-info it disables the static server, meaning that any framework that needs this cannot use auto-detection, so misses out on the other benefits of auto-detection, such as build command.

**To Reproduce**
Cannot be reproduced because it would require adding a framework to framework-info, but the code is here: 
https://github.com/netlify/cli/blob/main/src/utils/detect-server-settings.js#L260

This is related to #3654, and could be fixed with a similar solution to that, or more simply by starting the static server if the framework specifies no dev command and/or target port.

**Comment by erezrokah** [comment]
My comment [here](https://github.com/netlify/cli/issues/3654#issuecomment-972756052) is relevant for this issue to

**Comment by erezrokah** [comment]
@ascorbic I opened https://github.com/netlify/framework-info/issues/657.

Once we have that I think this issue will be about adding `useStaticServer: true` here https://github.com/netlify/cli/blob/f5323c45fec92c3a1e4604f472ea6ee9e468b67b/src/utils/detect-server-settings.js#L295 when a command/port is missing.
