### ISSUE TITLE
Have a dedicated flag to show up local environment information

### ISSUE THREAD

**Issue by jamesgeorge007** [netlify/cli#366]
Presently, the user is required to provide his/her local environment information as per the `issue template`. IMO it would be good to have a dedicated command for the purpose :thinking: 

## Proposed API

`netlify info`

We could utilize [envinfo](https://npmjs.com/package/envinfo)

**Comment by jamesgeorge007** [comment]
cc @DavidWells

**Comment by jamesgeorge007** [comment]
I would love to submit a PR :clap:

**Comment by DavidWells** [comment]
Hey James!

Instead of a new command perhaps we can add this as a flag to `netlify status`?

Like 

```
netlify status --verbose
# prints normal status + envinfo
```

https://github.com/netlify/cli/blob/master/src/commands/status/index.js

How does that sound?

**Comment by jamesgeorge007** [comment]
Great, I shall submit a PR soon

**Comment by jamesgeorge007** [comment]
I shall shoot up a PR soon :+1:
