### ISSUE TITLE
Evaluate any features that have been in Beta that should be marked in GA

### ISSUE THREAD

**Issue by MelanieCrissey** [netlify/cli#3661]
**Is your feature request related to a problem? Please describe.**

We have multiple commands and subcommands in Beta that should be moved out of it, as they are stable enough.
Search `beta` in https://cli.netlify.com/ to find them.

We can move everything out except `addons`.

**Describe the solution you'd like**

Remove `Beta` from the description of those commands.

**Describe alternatives you've considered**

Stay in Beta forever [Gmail style](https://www.nytimes.com/2009/07/08/technology/companies/08google.html#:~:text=Released%20on%20April%201%2C%202004,product%20to%20be%20fully%20baked.)

**Additional context**

Internal discussion https://netlify.slack.com/archives/CBC2U9MMG/p1637185529026800

**Comment by erezrokah** [comment]
Thanks @MelanieCrissey, I updated the issue to match our issue template
