### ISSUE TITLE
[netlify deploy] decide whether functions folder is mandatory for all CLI developer experience

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#368]
**- Do you want to request a *feature* or report a *bug*?**

`netlify init` doesnt create a functions folder for you by default, but does put a `functions` key in the `netlify.toml` that is created. to my knowledge, nothing in the netlify ecosystem fails when the functions folder is empty or nonexistent. i think this is a good thing? but i could be convinced otherwise.

however in `netlify deploy` it is mandatory. this is inconsistent.

![image](https://user-images.githubusercontent.com/6764957/61636435-9bf86d80-ac63-11e9-8668-cbb0e7b92fd5.png)

we just need a policy for this

**Comment by erezrokah** [comment]
We no longer fail if the functions directory doesn't exist when deploying site:
https://github.com/netlify/cli/blob/25ae7fc116503b0a363bfc7299c999bf20ed9939/src/commands/deploy.js#L118
