### ISSUE TITLE
-a flag stopped working

### ISSUE THREAD

**Issue by mtm-sig** [netlify/cli#369]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

`netlify deploy -a $TOKEN -s $ID --prod` returns:

```
Error: invalid json response body at 
 ›   https://api.netlify.com/api/v1/sites/xxx 
 ›   reason: Unexpected end of JSON input
```

Last week this command worked fine. I tried creating a new token but the same error appears.

Using export `NETLIFY_AUTH_TOKEN=$TOKEN` Works correctly though.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Run `netlify deploy -a $TOKEN -s $ID --prod`

**- What is the expected behavior?**

site is deployed correctly. 

**- Please mention your node.js, and operating system version.**

node 11
Alpine linux (latest)

**Comment by DavidWells** [comment]
Need to update the base cli command.

In the meantime, with `--auth` flag and it should work.

Thanks for the report

**Comment by sw-yx** [comment]
@DavidWells i think you fixed this? in case its done now
