### ISSUE TITLE
How to pass commit message on manual deployment?

### ISSUE THREAD

**Issue by minthemiddle** [netlify/cli#37]
**- What is the current behavior?**
When pushing a manual deployment via `netlify cli` there is no flag to pass a commit message that later shows in the *Deploys* section (now: "No deploy message").

**- What is the expected behavior?**
I would expect to pass an additional argument when using the CLI, such as `netlify deploy -m 'Add: Feature X'`

**- Please mention your node.js, and operating system version.**
Latest

**Comment by calavera** [comment]
Hi @minthemiddle,

The bad news are that this cli is no longer maintained and it won't get updated with that feature request.

The good news is that our new cli, netlifyctl, already supports that flag! 🎉 

https://github.com/netlify/netlifyctl/blob/master/commands/deploy/deploy.go#L39

You can get the latest version from the releases page: https://github.com/netlify/netlifyctl/releases
Or Homebrew if you use an Apple computer: https://github.com/netlify/netlifyctl#homebrew

**Comment by minthemiddle** [comment]
Perfect, I did not know there was a new CLI. I just followed the docs…

**Comment by fool** [comment]
yup.  Netlifyctl does this now:  https://github.com/netlify/netlifyctl/blob/0908af8ac8da1801083b99015246715bc77cb111/commands/deploy/deploy.go#L42

**Comment by iiroj** [comment]
Yes. I just switched from `netlifyctl` to `netlify-cli@next` like 10 minutes ago. The deploy's working fine here:

* Job with new cli: https://gitlab.com/iiroj/iiro.fi/-/jobs/96836229
* Job with old cli: https://gitlab.com/iiroj/iiro.fi/-/jobs/96001464

Here's the difference in Netlify's deploy list:

<img width="616" alt="screen shot 2018-09-12 at 6 28 59" src="https://user-images.githubusercontent.com/11628889/45400517-27bd6880-b655-11e8-9b06-762ee15f36ab.png">

**Comment by DavidWells** [comment]
I've added this to the todo list. It should be a super quick fix in https://github.com/netlify/cli/blob/master/src/commands/deploy.js#L88-L90
