### ISSUE TITLE
[DX] "stale-while-revalidate" policy on site info

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#370]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
we check `.netlify/state.json` and pull everything off the siteId. this means we need to wait for the api ping and also cant work offline.

**- What is the expected behavior?**
we could cache more data like site url and site name and addon list in state.json. make it an explicit stale-while-revalidate policy - firing off the update check AFTER our command finishes, and if there is an update, printing a message to the console. this optimises for the 95% of the time nothing changes in our site data, as opposed to now, where we assume nothing and are always using live data, however are much slower

**Comment by sw-yx** [comment]
>  one thing i would really like to explore is stale-while-revalidate local caching of things where it is acceptable. so for example right now we only store siteId in netlify.json, so that anytime we netlify open it takes quite a while to open up. we should aggerssively store more metadata (about sitename, user, functions, forms, etc) since, while these things can change, they dont change often, and the cost of being out of date is simply popping up an async warning and saying "hey we detected new information please kill and refresh" similar to other UI paradigms.

**Comment by erezrokah** [comment]
We can handle this as a part of https://github.com/netlify/cli/issues/458
