### ISSUE TITLE
Remove oclif and replace with commander

### ISSUE THREAD

**Issue by lukasholzer** [netlify/cli#3716]
The full problem and discussion about which tool can be found on our internal issue: https://github.com/netlify/pod-workflow/issues/343

**Comment by XhmikosR** [comment]
@lukasholzer would it make sense to use commander instead of minimist too?

**Comment by erezrokah** [comment]
> @lukasholzer @erezrokah would it make sense to use commander instead of minimist too? minimist is currently used in netlify-lambda only:

Yes it will. We were trying to scope down this big refactoring as much as possible.
This especially makes sense since `netlify-lambda` uses `commander` too https://github.com/netlify/netlify-lambda/blob/1645b4aff5914eff4c4952dfa26ad57b78599188/bin/cmd.js#L7

**Comment by XhmikosR** [comment]
Cool, I have already included this suggestion in #3941, feel free to add more there :)
