### ISSUE TITLE
`netlify dev -c '...' -d '...'` doesn’t serve

### ISSUE THREAD

**Issue by surma** [netlify/cli#372]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
The web server starts and the build starts. Once the build finishes, the entire command exits and the dev server is shut down.

**- If the current behavior is a bug, please provide the steps to reproduce.**
I am running `$ netlify dev -c 'npm run build' -d 'build'`

**- What is the expected behavior?**
I was kinda expecting this to behave like a commit to a Netlify-enabled repository. I expect this command to run my build command (`npm run build`) and then _continually_ serve the build directory (`build`), just like the form fields I have to fill out when setting up Netlify.

**- Please mention your node.js, and operating system version.**
```
$ netlify version
netlify-cli/2.11.29 darwin-x64 node-v12.2.0
```

**Comment by DavidWells** [comment]
⊂◉‿◉つ

What kind of site are you building here? Can you point me to a repo?

Am I correct in understanding you are trying to use `netlify dev` as a live-reload replacement for a static web app?

**Comment by surma** [comment]
> Am I correct in understanding you are trying to use netlify dev as a live-reload replacement for a static web app?

Not necessarily live-reload. I am mostly just looking for a static web server that respects `netlify.toml`, `headers` et al so I can test them locally.
