### ISSUE TITLE
Netlify dev does not honour custom 404 redirects

### ISSUE THREAD

**Issue by philhawksworth** [netlify/cli#373]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

Custom 404 routes specified as redirects in netlify.toml do not work locally when being run under `netlify dev`, although they work as expected when deployed to the ADN

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a site with the following redirect rule specified in the netlify.toml:
```
[[redirects]]
  from = "/posts/*"
  to = "/no-post-found.html"
  status = 404
```
2. Serve a site locally under `netlify dev` which includes:
  - at least on page within the `/posts/` directory
  - a page such as `/no-post-found.html` to serve as a 404

3. Navigate to a URL within the `/posts/` directory
4. Note that the 404 page is deployed even if a 200 should have been returned from the URL

**- What is the expected behavior?**

- If the page exists, it should be displayed
- only unfound URLs for the redirect pattern should yield 404s
- The behaviour locally under `netlify dev` should be the same as when deployed to the ADN

**- Please mention your node.js, and operating system version.**

- Mac OSX 10.14.5
- Node 10.15.3

netlify-cli/2.11.29 darwin-x64 node-v10.15.3

**Comment by raeesbhatti** [comment]
Fixed in https://github.com/netlify/cli/pull/538
