### ISSUE TITLE
CLI not working with Vue.js projects

### ISSUE THREAD

**Issue by coelmay** [netlify/cli#3772]
**Describe the bug**

When running `netlify dev` on a Vue.js project, `http://localhost:8888` is never available while `http://localhost:8080` is. There are no issues with other frameworks (e.g. Astro, NuxtJS).

**To Reproduce**

1. Run `git clone git@github.com:coelmay/vue-netlify-basic.git`
2. Run `netlify dev` or `netlify dev -o`
3. Wait for `webpack.Progress` to finish (see #1282)
4. Netlify CLI never launches `http://localhost:8888`

**Configuration**

```bash
  System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz
    Memory: 124.03 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  npmGlobalPackages:
    netlify-cli: 8.0.15
```

**Expected behavior**

To have `http://localhost:8888` available and launched (unless `autoLaunch = false`) to enable function testing.

**CLI Output**

Final messages displayed in console
```
<s> [webpack.Progress] 100%


  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.0.137:8080/

  Note that the development build is not optimized.
  To create a production build, run yarn build.
```

**Additional context**

Tested on previously working repositories https://github.com/coelmay/vue-netlify-basic (no functions) and https://github.com/coelmay/vue-ethereal-email (uses functions) without success.

**Edit:**
After downgrading to node `v16` everything works as expected leading me to believe this is (possibly/probably) entirely a node.js `v17` issue.

**Comment by erezrokah** [comment]
Thanks @coelmay, lets track this under https://github.com/netlify/cli/issues/3617 as it was reported for Vite and some other frameworks too.

**Comment by coelmay** [comment]
Thanks @erezrokah. That'll teach me for not doing a more thorough search before posting!

**Comment by erezrokah** [comment]
No worries, I don't think we've had Vue reported yet so useful to have it documented
