### ISSUE TITLE
SyntaxError: The requested module 'micro-api-client' is expected to be of type CommonJSPlease replace with a clear and descriptive title

### ISSUE THREAD

**Issue by rohan-paul** [netlify/cli#3776]
**Describe the bug**

I installed the CLI and the simple command `netlify` is showing me all the available options. But then when I ran `netlify login` it throws error.

`SyntaxError: The requested module 'micro-api-client' is expected to be of type CommonJS`

**To Reproduce**

1. Installed the CLI with `npm install netlify-cli -g`
2. Run command `netlify login`

**Configuration**

- If possible, please copy/paste below your `netlify.toml`.
- Please enter the following command in a terminal and copy/paste its output:

```bash
npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
```
### Output of running above command

```
npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
npx: installed 1 in 0.985s

  System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
    Memory: 17.50 GB / 31.24 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
  npmGlobalPackages:
    netlify-cli: 8.0.15
```

**CLI Output - Full Error that I am getting after running `netlify login`**

```bash
(node:31201) UnhandledPromiseRejectionWarning: file:///home/paul/.nvm/versions/node/v14.4.0/lib/node_modules/netlify-cli/node_modules/netlify/src/methods/response.js:1
import { JSONHTTPError, TextHTTPError } from 'micro-api-client'
         ^^^^^^^^^^^^^
SyntaxError: The requested module 'micro-api-client' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'micro-api-client';
const { JSONHTTPError, TextHTTPError } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31201) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31201) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:31201) UnhandledPromiseRejectionWarning: file:///home/paul/.nvm/versions/node/v14.4.0/lib/node_modules/netlify-cli/node_modules/netlify/src/methods/response.js:1
import { JSONHTTPError, TextHTTPError } from 'micro-api-client'
         ^^^^^^^^^^^^^
SyntaxError: The requested module 'micro-api-client' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'micro-api-client';
const { JSONHTTPError, TextHTTPError } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
(node:31201) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
file:///home/paul/.nvm/versions/node/v14.4.0/lib/node_modules/netlify-cli/node_modules/netlify-headers-parser/src/netlify_config_parser.js:5
import { parse as loadToml } from 'toml'
         ^^^^^
SyntaxError: The requested module 'toml' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'toml';
const { parse as loadToml } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:135:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async addHeaders (/home/paul/.nvm/versions/node/v14.4.0/lib/node_modules/netlify-cli/node_modules/@netlify/config/src/headers.js:19:31)
    at async getFullConfig (/home/paul/.nvm/versions/node/v14.4.0/lib/node_modules/netlify-cli/node_modules/@netlify/config/src/main.js:236:21)
    at async loadConfig (/home/paul/.nvm/versions/node/v14.4.0/lib/node_modules/netlify-cli/node_modules/@netlify/config/src/main.js:153:78)
    at async resolveConfig (/home/paul/.nvm/versions/node/v14.4.0/lib/node_modules/netlify-cli/node_modules/@netlify/config/src/main.js:73:72)
    at async LoginCommand.getConfig (/home/paul/.nvm/versions/node/v14.4.0/lib/node_modules/netlify-cli/src/utils/command.js:93:14)
    at async LoginCommand.init (/home/paul/.nvm/versions/node/v14.4.0/lib/node_modules/netlify-cli/src/utils/command.js:49:26)
    at async LoginCommand._run (/home/paul/.nvm/versions/node/v14.4.0/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:42:13)
```

**Comment by erezrokah** [comment]
Hi @rohan-paul, thank you for opening this issue.

Do you mind trying with the latest version of `npm`:
1. `npm uninstall -g netlify-cli`
2. `npm install -g npm`
3. `npm install -g netlify-cli`

**Comment by alessiopremoli** [comment]
Got the same issue using Node 13.x in a Github Actions, this should be a clean install of npm. In my case the issue started five days ago downloading **netlify-cli@8.0.6**.

**Comment by erezrokah** [comment]
> Got the same issue using Node 13.x in a Github Actions, this should be a clean install of npm. In my case the issue started five days ago downloading **netlify-cli@8.0.6**.

Thanks @alessiopremoli.

@rohan-paul and @alessiopremoli can you please update your Node.js version? We dropped support for Node.js 13 and some versions of Node.js 12 in v8, see https://github.com/netlify/cli/releases/tag/v8.0.0 and https://github.com/netlify/cli/blob/e4c2308e88864c5207fd1b0c0474e7794334053d/package.json#L14

**Comment by rohan-paul** [comment]
> > Got the same issue using Node 13.x in a Github Actions, this should be a clean install of npm. In my case the issue started five days ago downloading **netlify-cli@8.0.6**.
> 
> Thanks @alessiopremoli.
> 
> @rohan-paul and @alessiopremoli can you please update your Node.js version? We dropped support for Node.js 13 and some versions of Node.js 12 in Netlify CLI v8, see https://github.com/netlify/cli/releases/tag/v8.0.0 and
> 
> https://github.com/netlify/cli/blob/e4c2308e88864c5207fd1b0c0474e7794334053d/package.json#L14

Thanks @erezrokah - after I upgraded node to the latest LTS version 16 - and then freshly reinstalled netlify cli, and then all works just fine. Thanks again.

**Comment by alessiopremoli** [comment]
> > Got the same issue using Node 13.x in a Github Actions, this should be a clean install of npm. In my case the issue started five days ago downloading **netlify-cli@8.0.6**.
> 
> Thanks @alessiopremoli.
> 
> @rohan-paul and @alessiopremoli can you please update your Node.js version? We dropped support for Node.js 13 and some versions of Node.js 12 in Netlify CLI v8, see https://github.com/netlify/cli/releases/tag/v8.0.0 and
> 
> https://github.com/netlify/cli/blob/e4c2308e88864c5207fd1b0c0474e7794334053d/package.json#L14
> 
> `npm` should show a warning log when you install the CLI since we declare the supported versions in `package.json` engines config

Thanks @rohan-paul, upgrading node in the Action fixed the issue!
