### ISSUE TITLE
Problem with installing

### ISSUE THREAD

**Issue by ansidev** [netlify/cli#378]
**- Do you want to request a *feature* or report a *bug*?** It's a bug.

**- What is the current behavior?**

https://gitlab.com/ansidev/vue-bible-verse/-/jobs/258695725

**- If the current behavior is a bug, please provide the steps to reproduce.**

View the file .gitlab-ci.yml

**- What is the expected behavior?**

Installing netlify-cli successfully

**- Please mention your node.js, and operating system version.**

- Node 12.6.0
- Docker GitLab Runner.

**Comment by iannickb** [comment]
I have the same problem with node.js v8.10.0

**Comment by DavidWells** [comment]
Fixed via `netlify-cli@2.11.31`

We just swapped out our CI system. Sorry for the trouble.

Install latest version:

```
npm install netlify-cli -g
```

**Comment by DavidWells** [comment]
Please ping me if your issues are not fixed by the above ^

⊂◉‿◉つ
