### ISSUE TITLE
ntl command

### ISSUE THREAD

**Issue by ruyadorno** [netlify/cli#381]
hi @DavidWells, I see you recently added **ntl** as a shorthand command for the cli https://github.com/netlify/cli/commit/5423db514b48152ce2a4982ddeb284e0b4b6a422

Just a heads up that **ntl** already exists as a command in the **npm** ecosystem: https://www.npmjs.com/package/ntl and you might want to avoid the extra headache for the small portion of your users that were using it 😊 

I just recently received a first bug report: https://github.com/ruyadorno/ntl/issues/46 and I guess it would make sense for **ntl** to also have a longhand command version and avoid these in the future but still wanted to let you aware of it 😄

**Comment by sw-yx** [comment]
it’s not recent, we’ve had it for years. sorry for the name clash but we are unlikely to change it. happy to modify our readme to warn people.

**Comment by ruyadorno** [comment]
ooohh I see, if that's the case then the clashing alias is rare enough to not worry 😊 not even sure if it's worth a readme note at that rate... 

anyways, thanks for the clarification! 😄

**Comment by radulescuandrew** [comment]
Amazing. Came later to party, tried to install the cli and got ```File exists: /Users/..../.nvm/versions/node/v18.19.0/bin/ntl``` because I have that package installed. Cool stuff
