### ISSUE TITLE
Automatically link a site post creation via CLI

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#3827]
Moved here from a private repo, cc @joelcloralt 

When running the command `netlify site:create` the CLI returns a success message with Admin URL, URL, and Site ID. However running a command like `netlify build` right after fails with the error "Could not find the site ID. Please run netlify link".

We should automatically link the site post creation.

<img width="1250" alt="Screen Shot 2021-12-10 at 2 09 49 PM" src="https://user-images.githubusercontent.com/881780/145647794-81cd9309-1973-46f7-9a51-ccac9f2b8b5c.png">

**Comment by ximenasandoval** [comment]
Hi! I'd like to work on this issue

**Comment by lukasholzer** [comment]
@erezrokah should we run the linking as a post step or is the command used in bulk operations as well? (thinking about larger customers)

IMO there are multiple ways to achieve a good UX

1) automatic link the site - needs a flag to disable it `--disable-linking` would be a breaking change IMO
2) Add a prompt that asks if it should link the directory - needs a flag for CI to skip the prompt (Not Ideal IMO)
3) Enhance logging to communicate what is needed next (would not break any exisiting behaviour)

For example: 

```diff
➜  static-ts-function ntl sites:create
? Team: Lukas Holzer's team
Choose a unique site name (e.g. the-awesome-lukas-holzer-site-aba9f.netlify.app) or leave it blank for a random name. You can update the site name later.
? Site name (optional): static-ts-function-test

Site Created

Admin URL: https://app.netlify.com/sites/static-ts-function-test
URL:       https://static-ts-function-test.netlify.app
Site ID:   895b29e8-39f9-4988-bde9-af34f0631181

+ It seems that you created the site in a new folder that is not associated with any existing site.
+ If you want to deploy it you need to link it by running:
+ $ netlify link --id 895b29e8-39f9-4988-bde9-af34f0631181
```

my question is what should be done if someone creates a new site from the CLI inside an existing folder that is already linked?

**Comment by erezrokah** [comment]
@lukasholzer That's a good point about this being a breaking change.

>Add a prompt that asks if it should link the directory - needs a flag for CI to skip the prompt (Not Ideal IMO)

We could do this, and detect if running in CI and not link the site, unless a `--force` flag is passed (we use `--force` in other places in the repo, but not consistently. This is similar to `-y` (yes) in other CLIs). 

>my question is what should be done if someone creates a new site from the CLI inside an existing folder that is already linked?

Same behavior as above - if the user replied with `yes` to linking the site, and we detect the folder is already linked we can prompt to ask in we should overwrite. In CI we don't prompt. default to `no` unless `--force` is passed.

Let me know if I explained my self correctly here.

also cc @joelcloralt for product feedback

**Comment by ximenasandoval** [comment]
Hi! I had been working on this issue but considering only the first option *(automatic link the site - needs a flag to disable it)*

But I can work on adding the prompt that asks to link the current directory for option 2 🙌🏽 
> Add a prompt that asks if it should link the directory - needs a flag for CI to skip the prompt (Not Ideal IMO)

and also update the tests to make sure they are considering this change too!

**Comment by joelcloralt** [comment]
Hi all. The linking doesn't override if there is a linked site already so it wouldn't be a breaking change. The step would also be skipped if the user has a flag or environment variable set as they take precedence over the commands. 

So I would only go with option 1. Not sure we need the other two options.
