### ISSUE TITLE
bug: netlify sites:create --json output is blank

### ISSUE THREAD

**Issue by moltar** [netlify/cli#385]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

```
netlify sites:create --name foo -a bar --json
```

Produces an empty output.

**- If the current behavior is a bug, please provide the steps to reproduce.**

```
netlify sites:create --name foo -a bar --json
```

**- What is the expected behavior?**

Output is a valid JSON with information about newly created site.

**- Please mention your node.js, and operating system version.**

❯ node -v
v10.15.3

**Comment by DavidWells** [comment]
Thanks for the report. We need to add `this.logJson(site)` here https://github.com/netlify/cli/blob/master/src/commands/sites/create.js#L154 to support the json output of the site data
