### ISSUE TITLE
`netlify dev -d "_something"` serves a different folder

### ISSUE THREAD

**Issue by surma** [netlify/cli#386]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
netlify-cli seems to detect that I am using 11ty and starts serving 11ty’s output folder rather than the folder I specified.

**- If the current behavior is a bug, please provide the steps to reproduce.**
- Take an eleventy project
- Run `npx netlify dev -d "_something"`

**- What is the expected behavior?**
The folder `_something` should be served

**- Please mention your node.js, and operating system version.**
netlify-cli/2.12.0 darwin-x64 node-v12.4.0

**Comment by RaeesBhatti** [comment]
This has been fixed for some time now. Please update to the latest version `netlify-cli@2.46.0` to get the solution. Keep in mind that current 11ty detector doesn't work when you don't have a `.eleventy.js` file, [there's a PR for that](https://github.com/netlify/cli/issues/830) and a fix will be released soon.
