### ISSUE TITLE
Enhance log on `site:create` if it is not linked to the directory

### ISSUE THREAD

**Issue by lukasholzer** [netlify/cli#3862]
**Is your feature request related to a problem? Please describe.**

When running `ntl site:create` in a new folder it will create a site but not link it.
This is ok but I expected that it got linked

We could enhance the existing log output:

```diff
➜  static-ts-function ntl sites:create
? Team: Lukas Holzer's team
Choose a unique site name (e.g. the-awesome-lukas-holzer-site-aba9f.netlify.app) or leave it blank for a random name. You can update the site name later.
? Site name (optional): static-ts-function-test

Site Created

Admin URL: https://app.netlify.com/sites/static-ts-function-test
URL:       https://static-ts-function-test.netlify.app
Site ID:   895b29e8-39f9-4988-bde9-af34f0631181

+ It seems that you created the site in a new folder that is not associated with any existing site.
+ If you want to deploy it you need to link it by running:
+ $ netlify link --id 895b29e8-39f9-4988-bde9-af34f0631181
```

This would not break any behaviour for users that want to bulk create sites but would highlight the next steps needed for new users.

**Describe alternatives you've considered**

We could link it by default on creation or add a prompt to do so (but prompts are always tricky on CI)
**Can you submit a pull request?**

Yes

> Pull requests are welcome! If you would like to help us add this feature, please check our
> [contributions guidelines](../../CONTRIBUTING.md).

**Comment by erezrokah** [comment]
Hi @lukasholzer, I think this is a duplicate of https://github.com/netlify/cli/issues/3827.

I'll let you decide which one to keep. We already have someone wanting to work on https://github.com/netlify/cli/issues/3827#issuecomment-994940898

**Comment by lukasholzer** [comment]
Oh cool! Have not seen this just realized this behaviour previously and found it odd I will close it then in favor of the existing one!
