### ISSUE TITLE
Cannot install `netlify-cli` with `npm@6`

### ISSUE THREAD

**Issue by ehmicky** [netlify/cli#3869]
**Describe the bug**

Running `npm install netlify-cli` with `npm@6` produces the following error:

```
npm WARN checkPermissions Missing write access to /home/user/repo/node_modules/netlify-cli/node_modules/eslint-plugin-local-rules

npm ERR! code ENOENT
npm ERR! syscall access
npm ERR! path /home/user/repo/node_modules/netlify-cli/node_modules/eslint-plugin-local-rules
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, access '/home/uer/repo/node_modules/netlify-cli/node_modules/eslint-plugin-local-rules'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**To Reproduce**

  - Use `npm@6`.
  - Run `npm install netlify-cli`

**Configuration**

```
  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 53.95 GB / 62.75 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  npmPackages:
    netlify-cli: ^8.2.0 => 8.2.0
```

**Expected behavior**

Users of `npm@6` should be able to install `netlify-cli`.
`netlify-cli` supports Node 12 and 14 which come both with `npm@6`, so we need to support it.

**Additional context**

The problem seems to be this line of code, which was introduced by the Oclif removal (https://github.com/netlify/cli/pull/3717):

https://github.com/netlify/cli/blob/5ffbd6c5c74c27d0a625c6db57a434fcaa800544/package.json#L196

**Comment by lukasholzer** [comment]
Something https://github.com/netlify/pod-workflow/issues/339 would have covered. I guess no one tried the rc versions on npm 6

Would It work to just ship the files in the package under `tools/eslint-rules/**` @ehmicky?

**Comment by ehmicky** [comment]
I am not sure, but this is a good idea worth trying out IMHO.
If that does not work, then maybe we could explore whether there is another way to use those rules without the `file:` scheme?

**Comment by ehmicky** [comment]
This can be reproduced in [the following PR](https://github.com/netlify/build-plugin-template/pull/244) ([Deploy logs](https://app.netlify.com/sites/build-plugin-template/deploys/61c0be9ce86e680007d9f154)).

Some other sites seem to have experienced in production as well: Humio logs [here](https://cloud.us.humio.com/netlify-us-production/search?query=%22npm%20ERR%21%20enoent%20ENOENT%3A%20no%20such%20file%20or%20directory%2C%20access%20%27%2Fopt%2Fbuild%2Frepo%2Fnode_modules%2Fnetlify-cli%2Fnode_modules%2Feslint-plugin-local-rules%27%22%20%7C%20groupBy%28repo_url%29%20%7C%20sort%28%29&live=false&start=1d&fullscreen=false) and [there](https://cloud.us.humio.com/netlify-us-production/search?query=%22checkPermissions%20Missing%20write%20access%20to%20%2Fopt%2Fbuild%2Frepo%2Fnode_modules%2Fnetlify-cli%2Fnode_modules%2Feslint-plugin-local-rules%22%20%7C%20groupBy%28repo_url%29%20%7C%20sort%28%29&live=false&start=1d&fullscreen=false).
