### ISSUE TITLE
Serverless functions cannot decode POST requests when running in Dev

### ISSUE THREAD

**Issue by philhawksworth** [netlify/cli#387]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

Serverless functions used to handle POST data from a form do not work locally under Netlify Dev while they work correctly when deployed as Netlify Functions.

Netlify dev seems unable to parse the POST data like so:

```
 const params = querystring.parse(event.body);
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

Create an HTML form with action of `./netlify/functions/parseParams` and a method of `POST` 

Include an input field of `firstname` in the form.

Create a Netlify Function of `parseParams.js` to handle the form submissions

Use code such as the following code in `parseParams.js`:

```
const querystring = require('querystring');
exports.handler = async (event, context) => {
  const params = querystring.parse(event.body);
  const name = params.firstname || "World";
  return {
    statusCode: 200,
    body: `Hello, ${name}`
  };
};
```

Run the site locally using `netlify dev`

Post data using the form

**- What is the expected behavior?**

The function should return the value of your input posted in the form. As it does when this code is deployed on Netlify.

**- Please mention your node.js, and operating system version.**

netlify-cli/2.12.0 darwin-x64 node-v10.15.3

**Comment by RaeesBhatti** [comment]
Working in the latest version!
