### ISSUE TITLE
Timeout during deploy: TimeoutError: Promise timed out after 1200000 milliseconds

### ISSUE THREAD

**Issue by akomakom** [netlify/cli#388]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
Persistent timeout during deploy using `netlify deploy -d /some/path` while running in Microsoft Azure Pipelines environment on an Ubuntu host.  Timeout error mentions **120000ms**, but actual deploy execution time before failure is much longer than that (**over 20 minutes**)

```
> npm install netlify-cli	

npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.

> netlify-cli@2.12.0 postinstall /home/vsts/work/node_modules/netlify-cli
> node ./scripts/postinstall.js


Success! Netlify CLI has been installed!

Your device is now configured to use Netlify CLI to deploy and manage your Netlify sites.

Next steps:

  netlify init     Connect or create a Netlify site from current directory
  netlify deploy   Deploy the latest changes to your Netlify site

For more information on the CLI run netlify help
Or visit the docs at https://cli.netlify.com

npm WARN saveError ENOENT: no such file or directory, open '/home/vsts/work/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/vsts/work/package.json'
npm WARN work No description
npm WARN work No repository field.
npm WARN work No README data
npm WARN work No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ netlify-cli@2.12.0
added 722 packages from 402 contributors and audited 13182 packages in 42.61s
found 4 vulnerabilities (2 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> netlify deploy -d /home/vsts/work/1/b

Deploy path: /home/vsts/work/1/b
Deploying to draft URL...
- Hashing files...
✔ Finished hashing 34740 files
- CDN diffing files...
✔ CDN requesting 2 files
- Uploading 2 files
✔ Finished uploading 2 assets
- Waiting for deploy to go live...
 ›   Warning: 
 ›   {
 ›      "name": "TimeoutError"
 ›   }
 ›
TimeoutError: Promise timed out after 1200000 milliseconds
    at Timeout.setTimeout [as _onTimeout] (~/work/node_modules/p-timeout/index.js:27:54)
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

We run this in Azure Pipelines on ubuntu-latest Microsoft-hosted hosts.  The directory being deployed to netlify is fairly large, but this used to work some months ago.  Exact steps are:

1. Set up authentication (set $NETLIFY_SITE_ID and $NETLIFY_AUTH_TOKEN)
2. Generate a website (a large site) to $BUILD_BINARIESDIRECTORY (our is 673M and 38086 files)
3. npm install netlify-cli	
4. $(npm bin)/netlify deploy -d $BUILD_BINARIESDIRECTORY

**- What is the expected behavior?**

Deploy should succeed

**- Please mention your node.js, and operating system version.**

* nodejs: v10.16.0
* npm: 6.10.2
* Ubuntu Xenial (16.04)

**Comment by sw-yx** [comment]
ok and just to be sure of the source of the problem, does this still happen if you revert the CLI version from 6.12.x to a few-months-old version?

**Comment by akomakom** [comment]
Interesting thing happened after I opened this.  
After several months of failures, deploy succeeded on the full site, but only after I accidentally deployed an empty directory (because site generation failed earlier).  

I am re-running to see if this continues to succeed.

**Comment by sw-yx** [comment]
Heisenbug!

**Comment by akomakom** [comment]
Basically.

Succeeded a second time as well.  Perhaps deploying an empty directory corrected a bad state somewhere.

I'll re-open if this re-occurs.

**Comment by akomakom** [comment]
On a possibly related note, I attempted to add `netlify deploy --prod` after `deploy` and it hung for over an hour before I killed it at:

```
- CDN diffing files...
✔ CDN requesting 2 files
- Uploading 2 files
✔ Finished uploading 2 assets
- Waiting for deploy to go live...
```

This feature isn't important for us, but I'm mentioning it just in case.

**Comment by sw-yx** [comment]
no clue at all. maybe @davidwells can help, otherwise i’d leave it for now
