### ISSUE TITLE
`netlify: command not found` after running `nvm use`

### ISSUE THREAD

**Issue by parkeragee** [netlify/cli#389]
**- Do you want to request a *feature* or report a *bug*?**

**- What is the current behavior?**
Running `netlify` after running `nvm use` results in `netlify: command not found`

**- If the current behavior is a bug, please provide the steps to reproduce.**
- add a `.nvmrc` file to a project
- `first, run `netlify` to make sure the netlify command is found
- next, run `nvm use` to switch to the specified node version in the `.nvmrc` file
- run `netlify` again and see that it says `netlify: command not found`

**- What is the expected behavior?**
Should be able to execute `netlify` commands

**- Please mention your node.js, and operating system version.**
Default node version is `v8.15.0`. When running `nvm use`, it switches to `v10.15.3`

**- Screenshots**
![Kapture 2019-08-07 at 16 16 17](https://user-images.githubusercontent.com/4029349/62658585-bbafb700-b92e-11e9-9504-6998d45e7d81.gif)

**Comment by fool** [comment]
`nvm use X` is usually used to switch versions of node, and each version of node maintains its own package installations.  You'd need to `npm i -g netlify-cli` after running `nvm use X` to make it available for that version.

This is normal behavior of npm and not specific to netlify.  Please let me know if it doesn't :)
