### ISSUE TITLE
Cannot set build context when using `netlify deploy --build`

### ISSUE THREAD

**Issue by gavinhenderson** [netlify/cli#3897]
**Describe the bug**

You cannot set the build context when you are building via the deploy command.

Due to [this issue](https://github.com/netlify/cli/issues/3792) I must use `netlify deploy --build` rather than `netlify build` followed by `netlify deploy`.

**To Reproduce**

When you run `netlify build --context deploy-preview` in any repo you will see the output will say:

```
❯ Context
  deploy-preview
```

When you then run `netlify deploy --build --context deploy-preview` you get:

```
Error: unknown option '--context'
```

**Expected behavior**

Accept the`--context` flag in the `deploy` command and pass it through to the building step.

**Comment by gavinhenderson** [comment]
@erezrokah Would you accept a PR to add the context flag to the `deploy` command?

**Comment by erezrokah** [comment]
@gavinhenderson, yes please! We'd be happy to

**Comment by erezrokah** [comment]
I'm also wondering if `context` should implicitly set `alias`, see https://github.com/netlify/cli/issues/1984#issuecomment-797120748

**Comment by gavinhenderson** [comment]
> I'm also wondering if `context` should implicitly set `alias`, see [#1984 (comment)](https://github.com/netlify/cli/issues/1984#issuecomment-797120748) - @erezrokah 

Not sure that would make sense. I set my `context` to `deploy-preview` but then I use `alias` to set the name of the specific branch so I get a URL with the branch name. 

Here is an example (with a github action variable):

```
netlify deploy --context deploy-preview --alias=${{ needs.CalculateDeployKey.outputs.deploy-key }} --build
```

We could add some logic to default to only set `alias` if there is no explicit `alias` passed, but that seems like complexity that would cause confusion
