### ISSUE TITLE
Persist mutated config after build

### ISSUE THREAD

**Issue by ascorbic** [netlify/cli#3906]
**Is your feature request related to a problem? Please describe.**

Currently any config mutations in build plugins are lost once the build has completed. This means that if the user then runs `ntl dev` or `ntl deploy` the site is deployed without the expected config changes. This is particularly problematic with redirects, which are hard to reproduce. This also means the framework plugins/runtimes cannot persist the required redirects for SSR and ODB handler, meaning that customers cannot simply run `netlify build` followed by `netlify deploy`.

**Describe the solution you'd like**

- When a build is run, save the mutated config into `.netlify`
- When running `ntl dev`, if a persisted config exists check if `netlify.toml`, `_headers` or `_redirects` have been modified since the mutated config was written. If it has, log a warning saying they should run a new build. Then in either case, use the mutated config instead of the other files.
- When running `ntl deploy`, do the same checks.

**Describe alternatives you've considered**

Currently my workflow for testing redirects is either to use `ntl deploy --build` and test the deploy preview, or kill the process after it has modified the toml, then run `ntl dev --framework=#static`

**Additional context**

Would work well alongside #3905
Would replace #3792

**Can you submit a pull request?**

Yes, subject to agreeing behaviour

> Pull requests are welcome! If you would like to help us add this feature, please check our
> [contributions guidelines](../../CONTRIBUTING.md).

**Comment by lemusthelroy** [comment]
To resolve this, I wonder if we could cache the mutations in the `.netlify` folder. Then when the `ntl dev` or `ntl deploy` command is run, we can include those mutations in the arguments that are passed to the build function that runs.

**Comment by lemusthelroy** [comment]
I agree with the suggested solution on this.

**Comment by sarahetter** [comment]
Closed as migrated to linear
CT-72
