### ISSUE TITLE
docs: search is broken

### ISSUE THREAD

**Issue by XhmikosR** [netlify/cli#3946]
**Describe the bug**

Search doesn't work on http://cli.netlify.com/

**To Reproduce**

1. Go to http://cli.netlify.com/
2. try to search something.
3. nothing happens apart from 403 errors in the browser console

**Comment by fool** [comment]
Thanks!  We're aware and working on it with our search service provider.  Not sure exactly when we'll get it fixed but I am pretty sure "within the next 48 hours" will be true based on some internal conversations about it.

Sorry for the hassle!

**Comment by fool** [comment]
well, I am glad I didn't commit to a timeline since I heard we just got it fixed 10 minutes later.  @XhmikosR do you see it working better for you now, too?

**Comment by XhmikosR** [comment]
Confirmed, cheers!
