### ISSUE TITLE
Implement the "start with template" feature

### ISSUE THREAD

**Issue by charliegerard** [netlify/cli#3947]
**Is your feature request related to a problem? Please describe.**

We have a new feature available in the UI to start a new site from template that I think should also be available in the CLI.

**Describe the solution you'd like**

Implement a new command to start a site from template.

**Describe alternatives you've considered**

Not do that but then we don't have feature parity.

**Can you submit a pull request?**

Yes

**Comment by tinfoil-knight** [comment]
Closing since this has been implemented.
