### ISSUE TITLE
ReferenceError: error is not defined

### ISSUE THREAD

**Issue by i8ramin** [netlify/cli#400]
**- Do you want to request a *feature* or report a *bug*?**

BUG

**- What is the current behavior?**

When the Netlify toml parser detects invalid redirect rules, it tries to print out the error in a console.error() statement from within the https://github.com/netlify/netlify-rules-proxy (private) repo. There is some code inside that repo that is referencing an undefined variable.

```js
result.errors.forEach(err => {
  console.error(`  ${error.lineNum}: ${error.line} -- ${error.reason}`)
})
```
`${error.lineNum}: ${error.line} -- ${error.reason}` should actually be referencing `err` and not `error`

**- If the current behavior is a bug, please provide the steps to reproduce.**

Put some invalid redirect rules in a local netlify.toml file and run netlify dev

**- What is the expected behavior?**

It should report the error correctly in the console

**- Please mention your node.js, and operating system version.**

N/A

**Comment by raeesbhatti** [comment]
Fixed here: https://github.com/netlify/cli/pull/518/files#diff-82b51b617e17110e3eff436121be73edR28. Please update to latest version to see the changes.
