### ISSUE TITLE
Unclear how to hit function from within Create React App in a way that is seamless between dev and production

### ISSUE THREAD

**Issue by brandonweiss** [netlify/cli#401]
I’m just getting started with Netlify Dev and found it unclear what URL to use to run functions.

My particular use-case is using Netlify Dev inside a Create React App project, but this might apply to using Netlify Dev with other frameworks as well.

When I run `netlify dev` it detects CRA and starts it as well. The output looks like this:

```
netlify dev
◈ Netlify Dev ◈
◈ Starting Netlify Dev with create-react-app
Waiting for localhost:3000.
◈ Lambda server is listening on 34567

> reach@0.1.0 start /Users/brandon/Code/reach
> react-scripts start

...Starting the development server...

.
Connected!
Waiting for localhost:34567.
Connected!

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘

Compiled successfully!

You can now view reach in the browser.

  Local:            http://localhost:3000/
  On Your Network:  http://192.168.7.110:3000/

Note that the development build is not optimized.
To create a production build, use npm run build.
```

My first thought was that Netlify Dev would mount a server in front of CRA to intercept functions and any non-function paths would get served by CRA. So I made a function at `functions/test.js`, looked at the localhost URL at the bottom of the output, and tried `localhost:3000/.netlify/functions/test`, which didn’t work.

It took me a fair amount of time fiddling with the `functions` config in `netlify.toml`, reading docs, and fiddling with the path before I noticed Netlify Dev mentioned there is also a server running at `localhost:8888` in the output.

OK, so now I can hit the function at `localhost:8000/.netlify/functions/test`. But now I’m confused as to how this is all supposed to work in development vs. production.

In development there are two servers, but in production there will be one. Or rather, there will be some routing rules that I can guess at but don’t seem to be represented here. Presumably static files will get routed first if they exist. And in order to make CRA work I’ll probably have to add a redirect for something like `/*` to `/index.html`. And then maybe Netlify handles any path that starts with `/.netlify/functions` specially and knows to route those to the functions?

So now back to working locally, inside of CRA if I want to link to a function, what do I do? If I link to `/.netlify/functions/test` it will resolve to `localhost:3000/.netlify/functions/test` which won’t work. But if I link to `localhost:8888/.netlify/functions/test` it will work in development but will break when I deploy to production. 

What is the best practice here? Do I need to write a small utility to generate different URLs depending on the environment?

**Comment by RaeesBhatti** [comment]
You can use `/.netlify/functions/<functionName>` without `host` and it will work on both `netlify dev` and production including draft URL's. Like so:
```js
const response = await fetch('/.netlify/functions/hello-world').then(r => r.json())
```
If you have a need to use use `host`, you can use `window.location.host` and it will work on `netlify dev` and in production. Like so:
```js
const response = await fetch(window.location.host + '/.netlify/functions/hello-world').then(r => r.json())
```

Thank you for opening this issue. Apologies for the long delay. You can ask usage questions on http://community.netlify.com as well.
