### ISSUE TITLE
Error on deploy command due to regression on dependency(prettyjson)

### ISSUE THREAD

**Issue by giuseppelt** [netlify/cli#4011]
After prettyjson patch update(1.2.1 --> 1.2.2), deploy commands fail on line
https://github.com/netlify/cli/blob/d9a41aa0d2508892d592e025bba42f2dc5e49626/src/commands/deploy/deploy.js#L517

because the logged object has some properties undefined (when the site has no functions or config).
In the previous version prettyjson simply skipped undefined properties, now crashes the process.

Linked issue: https://github.com/rafeca/prettyjson/issues/58

**Comment by giuseppelt** [comment]
fixed by prettyjson v.1.2.5

**Comment by erezrokah** [comment]
Reported in https://github.com/netlify/cli/issues/4012 too
