### ISSUE TITLE
Invalid redirects cause an error in rules-proxy package

### ISSUE THREAD

**Issue by dan-dr** [netlify/cli#407]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
When running `netlify dev` and my `_redirects` file is invalid, it throws and doesn't work

**- If the current behavior is a bug, please provide the steps to reproduce.**
put `/whatever undefined 301` in _redirects and run `netlify dev`

**- What is the expected behavior?**
Should show an error message and continue working.

**- Please mention your node.js, and operating system version.**
10.15.3, Solus Linux

The problem is in the [netlify rules-proxy package](https://www.npmjs.com/package/@netlify/rules-proxy) index file line netlify/netlify-dev-plugin#28. it tries to log an error that has been received as the `err` parameter to the function but refers to it as `error` instead:
```javascript
function parseFile(parser, name, data) {
  const result = parser(data)
  if (result.errors.length) {
    console.error(`${NETLIFYDEVWARN} Warnings while parsing ${name} file:`)
    result.errors.forEach(err => {
      console.error(`  ${error.lineNum}: ${error.line} -- ${error.reason}`) // THISSSSSSSSS
    })
  }
  return result.success
}
```

**Comment by raeesbhatti** [comment]
Fixed here: https://github.com/netlify/cli/pull/518/files#diff-82b51b617e17110e3eff436121be73edR28

Thanks for reporting!
