### ISSUE TITLE
yarn audit returns Prototype Pollution for mixin-deep (security 🚨)

### ISSUE THREAD

**Issue by opantsjoha** [netlify/cli#408]
**- Do you want to request a *feature* or report a *bug*?**
🐛 bug

**- What is the current behavior?**
`yarn audit` returns the following for `netlify-cli` module:

high: `Prototype Pollution`
Package: `mixin-deep`
Patched in: `>=1.3.2 <2.0.0 || >=2.0.1`
Dependency of: `netlify-cli`
Path: `netlify-cli > netlify-dev-plugin > netlify > @netlify/zip-it-and-ship-it > chokidar > readdirp > micromatch > snapdragon > base > mixin-deep`
More info: `https://www.npmjs.com/advisories/1013`

**- If the current behavior is a bug, please provide the steps to reproduce.**
run `yarn audit` with "netlify-cli": "^2.11.23" node module

**- What is the expected behavior?**
Self explanatory

**- Please mention your node.js, and operating system version.**
node v11.15.0 + OSx 10.14.4

**Comment by erezrokah** [comment]
Closing as stale. This is no longer an issue with the latest version
