### ISSUE TITLE
Local Functions Not Working with Node 17+

### ISSUE THREAD

**Issue by jamesqquick** [netlify/cli#4088]
**Describe the bug**

When running `netlify dev`, local functions are not accessible on port 8888 when using Node.js version 17.

**To Reproduce**

1. Create a new hello world function inside of a functions directory
2. Install Node.js 17+
3. Run `netlify dev` in the project and try to access in the browser at `http://localhost:8888/.netlify/functions/helloWorld`

**Expected behavior**

Should return back hello world from the browser.

**Comment by wad-im** [comment]
Check out [#3617](https://github.com/netlify/cli/issues/3617). The issue has been reported for different frameworks. Had the same issue after updating to Node.js 17+. Going back to an older version of Node solved the issue for now.
