### ISSUE TITLE
git-credential-netlify is not supported on darwin with CPU architecture arm64

### ISSUE THREAD

**Issue by nlshawver** [netlify/cli#4094]
**Describe the bug**

**To Reproduce**

1. Run `git clone git@github.com:owner/repo-with-cli-bug.git`
2. Navigate to the cloned repository
3. Run `netlify dev`
4. See that the CLI exits with an error

**Configuration**

- If possible, please copy/paste below your `netlify.toml`.
- Please enter the following command in a terminal and copy/paste its output:

```bash
npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
```

**Expected behavior**

**CLI Output**

If applicable, add the CLI output to help explain your problem.

**Additional context**

**Comment by erezrokah** [comment]
Hi @nlshawver, do you mind feeling in the missing parts of the issue template? That makes it much easier and faster to resolve the issue.

Also, for more context, the credential helper is built here https://github.com/netlify/netlify-credential-helper/blob/50b6ff358730db8dabea61a1d6e52b847fa49c4e/Makefile#L78

**Comment by erezrokah** [comment]
Closing in favor of https://github.com/netlify/cli/issues/4098
