### ISSUE TITLE
git-credential-netlify is not supported on darwin with CPU architecture arm64

### ISSUE THREAD

**Issue by lukasholzer** [netlify/cli#4098]
**Describe the bug**

Running now the `ntl lm:setup` command esits with an error as we don't provide a binary for `arm64 on darwin:

![CleanShot 2022-01-20 at 12 03 46](https://user-images.githubusercontent.com/11156362/150326913-56a5726d-9239-4c80-a78e-b1b72169c579.png)

CLI Version: 
`netlify-cli/8.10.2 darwin-arm64 node-v16.13.1`

**Comment by erezrokah** [comment]
Thanks @lukasholzer, see my comment in https://github.com/netlify/cli/issues/4094#issuecomment-1017394393
