### ISSUE TITLE
netlify dev doesn't use the [dev] command nor -c option

### ISSUE THREAD

**Issue by thomasmorice-zz** [netlify/cli#410]
I want to report a bug related to the command when I run netlify dev

Whether I : 

- have command = "yarn dev" in my **[dev] toml file**
- run `netlify dev -c "yarn dev"`

Netlify will keep asking me which command it needs to run. It should run the command without asking I supposed. 

Netlify dev is linked to my account properly, I'm on Windows, using node 8.12

**Comment by richtera** [comment]
This is still an issue, I have several package.json script entries it thinks would match so no matter if I specify the exact command I want in either -c or command = in the toml file, it asks me which one of 4 to use. This causes major confusion with other developers on the project.

**Comment by richtera** [comment]
Seems to only work if "yarn start" is in fact the only command available. Here is my output:
```$ yarn netlify:dev
yarn run v1.17.3
$ netlify dev
◈ Netlify Dev ◈
? Multiple possible start commands found (Use arrow keys or type to search)
❯ [create-react-app] yarn start 
  [create-react-app] yarn serve 
  [gatsby] yarn start 
  [gatsby] yarn develop 
  [gatsby] yarn netlify:gatsby 
  [gatsby] yarn develop:gatsby ```
This is which netlify-cli@2.15.0
i.e
```$ netlify -v
netlify-cli/2.15.0 darwin-x64 node-v10.16.3
```
So it seems still broken.

**Comment by raeesbhatti** [comment]
Hey there , I've confirmed this issue. While `netlify dev` does use the value `-c` flag or the `command` you specify in `[dev]` section at the end, it does ask you to choose between different possible commands first when it has doubts about the framework. As mentioned in the starting comment, it should remember the kind of framework you're using.
Please hold on while we fix this.

**Comment by lukasholzer** [comment]
I've tried to reproduce this issue but it seems that over time the framework detection enhanced significantly so that it works like expected. 

Therefore I will close this issue. If there should be anything similar please open up a new issue with a detailed steps to reproduce guide.

**Comment by zane** [comment]
It appears that if there's ambiguity about the framework you'll still be prompted to choose between them even if `command` is set. Setting `framework` explicitly resolves the issue for me.
