### ISSUE TITLE
Add an option to turn off autoLaunch in dev command

### ISSUE THREAD

**Issue by albertodeago** [netlify/cli#4100]
**Is your feature request related to a problem? Please describe.**

I really would like to have an option to be able to turn off the `autoLaunch` behaviour of the dev command.
I understand [why by default it's turned on](https://github.com/netlify/cli/pull/729#issuecomment-591701356), but I think that it would be a nice addition to add a way to turn it off if needed.

**Describe the solution you'd like**

I would like to add (I can already open a PR if accepted) an option called `--autoLaunch` on the dev command. By default it would be `true` so that there would be no breaking change, but if provided a false value, the browser won't be auto opened.

**Describe alternatives you've considered**

I know that this can already be done via `toml` file, but I think it would be a nice addition to the CLI itself

**Can you submit a pull request?**

Yes.

**Comment by erezrokah** [comment]
Hi @albertodeago! Thank you for opening the issue. This is available via `BROWSER=none ntl dev`, due to the underlying library we use to open the browser.

We can probably document it better, so maybe adding it under https://cli.netlify.com/commands/dev or https://cli.netlify.com/netlify-dev#usage (or both) will make it more visible.

**Comment by albertodeago** [comment]
thanks @erezrokah for the quick response.
Oh wow I didn't find this info anywhere so I think it would be a nice addition in the docs, do you want me to submit a pr on the dev docs?

**Comment by erezrokah** [comment]
A PR would be very helpful, thanks @albertodeago!

**Comment by albertodeago** [comment]
I'll do that
