### ISSUE TITLE
functions are running on different port while frontend is running on another port

### ISSUE THREAD

**Issue by saswatsam786** [netlify/cli#4110]
**Describe the bug**
Netlify functions are not running on port 8888, the functions are listening on some random port 60248 which is causing error in running locally

**To Reproduce**

1. Run `git clone git@github.com:owner/repo-with-cli-bug.git`
2. Navigate to the cloned repository
3. Run `netlify dev`
4. See that the CLI exits with an error

**Configuration**

- If possible, please copy/paste below your `netlify.toml`.
- Please enter the following command in a terminal and copy/paste its output:

```bash
npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
```

**Expected behavior**

**CLI Output**

If applicable, add the CLI output to help explain your problem.

**Additional context**

<img width="709" alt="Screenshot 2022-01-22 at 2 21 41 AM" src="https://user-images.githubusercontent.com/77463804/150598558-2ac9744c-814d-48e0-acec-42081dc43fb8.png">

**Comment by saswatsam786** [comment]
@croaky

**Comment by erezrokah** [comment]
Hi @saswatsam786, can you fill in the missing parts from the issue template? 
Specifically `To Reproduce`, `Configuration` and `Expected behavior`.

Running the functions server on a different port is the expected behavior. Can you describe what issue it's causing for you?

**Comment by saswatsam786** [comment]
Actually, the function addData is not working on (http://localhost:8888/.netlify/functions/addData)  as specified but it is working on port 60248.

**Comment by erezrokah** [comment]
Thanks @saswatsam786, can you share a reproduction scenario that reproduces the "not working on port 8888" and "working on port  60248".

The function should work on port 8888, so it would be great to understand the reason it doesn't

**Comment by shryme** [comment]
Is there some news about this problem? One year later and I have the exact same problem, functions are listening on some random port wich I can't call from my frontend. :(

**Comment by luisjuarros** [comment]
Same problem here ... functions are running in a random port every time

**Comment by shryme** [comment]
I had Netlify CLI installed globally, I just tried installing it locally and it works!

`npm install --save-dev netlify-cli`

It may be worth it to try installing it locally if you're still experiencing issue like me!

**Comment by serhalp** [comment]
Marking this as stale as it is is several years old. Please feel free to reopen if you are still having issues.
