### ISSUE TITLE
netlify functions:serve shows an undefined port in loaded function URL

### ISSUE THREAD

**Issue by Soviut** [netlify/cli#4116]
**Describe the bug**

When using `netlify functions:serve` the URLs for the loaded functions have an `undefined` port.

```
◈ Loaded function test-function (​http://localhost:undefined/.netlify/functions/test-function​).
```

Directly after the list of loaded functions, the default port is listed.

```
◈ Functions server is listening on 9999
```

If you copy the URL for the function and replace `undefined` with `9999` the function works and returns its response.

**To Reproduce**

1. Create a function in `netlify/functions`
2. Run `netlify functions:serve`
3. Observe the loaded function URL has the port `undefined`

**Configuration**

```
  System:
    OS: Linux 4.19 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz
    Memory: 23.45 GB / 50.14 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.7.0 - ~/.nvm/versions/node/v16.7.0/bin/node
    Yarn: 1.16.0 - /mnt/c/Users/Ian/AppData/Roaming/npm/yarn
    npm: 7.20.3 - ~/.nvm/versions/node/v16.7.0/bin/npm
    Watchman: 2021.06.07.00 - /home/linuxbrew/.linuxbrew/bin/watchman
  npmGlobalPackages:
    netlify-cli: 8.13.0
```

**Expected behavior**

The URL would contain port `9999` instead of `undefined`.

**Comment by karagulamos** [comment]
Hi @Soviut.

Thanks for reporting this issue. I can confirm that my experience is the same when I use the `functions:serve` command.

I'll investigate why the port is not captured in the functions URL and issue a fix soon.

Humble regards,
Alexander.
