### ISSUE TITLE
Include `client-ip` header on event object

### ISSUE THREAD

**Issue by estrattonbailey** [netlify/cli#412]
Hey there 👋

**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
It appears that although it exists on a deployed function, the `client-ip` header is not set when running `netlify dev` locally.

**- If the current behavior is a bug, please provide the steps to reproduce.**
I'm using a "dump" route that just returns the entire `event` and `context` objects as JSON, *a la*:

```javascript
exports.handler = async (ev, ctx) => {
  return {
    statusCode: 200,
    body: JSON.stringify({
      ev,
      ctx
    })
  }
})
```

**- What is the expected behavior?**
It should be populated locally, if available, like it is in production.

**- Please mention your node.js, and operating system version.**
Node: v10.15.3
OS: macOS Mojave 10.14.5

* * *
P.S. [Originally posted this](https://community.netlify.com/t/include-request-ip-address-on-event-object/1820) on the Netlify Community.

**Comment by raeesbhatti** [comment]
Fixed in latest merge https://github.com/netlify/cli/pull/396/commits
