### ISSUE TITLE
[feature?] reload netlify dev functions when new functions added

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#413]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
if i have a netlify dev session running and i add a new function in another terminal, netlify dev isn't aware of it and i have to kill and restart.

**- What is the expected behavior?**
netlify dev should watch the *folder* and restart as changes are seen

**Comment by caesarsol** [comment]
+1!
Pointing out another watch-related issue: https://github.com/netlify/cli/issues/909
