### ISSUE TITLE
Support Gatsby’s programmatic createRedirect

### ISSUE THREAD

**Issue by ryanditjia** [netlify/cli#414]
Currently Netlify Dev’s redirects feature only works with `_redirects` and `netlify.toml` files. It would be nice if it supports Gatsby’s `createRedirect`.

Thanks.

**Comment by RaeesBhatti** [comment]
This should work in the latest version. We're handing all request to app server (Gatsby in this case) without rewriting the URL when there's no other matching criteria.
Please update your `netlify-cli` to latest version `2.46.0` and let us know if it is still a problem.
