### ISSUE TITLE
netlify open:site hangs with Brave browser

### ISSUE THREAD

**Issue by whitep4nth3r** [netlify/cli#4160]
**Describe the bug**

`netlify open:site` hangs or fails silently with Brave browser set as default.

The following command ran successfully and opened Firefox as expected:

```
BROWSER=firefox ntl open:site
```

**To Reproduce**

Steps to reproduce the behavior on Mac OS:

1. Use latest CLI version
2. Set Brave to default system browser
3. Run `netlify open:site`
4. Notice that Brave browser has not opened after a considerable amount of time

I've noticed that sometimes the command completes after some minutes, but generally fails silently forever.

**Configuration**

No netlify.toml was used for this site.

```
  System:
    OS: macOS 12.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.51 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.0 - /opt/homebrew/bin/npm
  npmGlobalPackages:
    netlify-cli: 8.14.1
```

**Expected behavior**

Brave browser opens in a timely manner when running `netlify site:open`.

**CLI Output**

Terminal hangs in this state:

![A screenshot of the terminal showing that the CLI is attempting to open a site](https://user-images.githubusercontent.com/52798353/151804344-9a1060ae-a696-4b59-87b5-b3637802f113.png)

**Comment by erezrokah** [comment]
The log line is here https://github.com/netlify/cli/blob/f1c4d1017acba380048c06efa98b51b967f763d2/src/commands/open/open-site.js#L27

which means it probably hangs on https://github.com/netlify/cli/blob/f1c4d1017acba380048c06efa98b51b967f763d2/src/utils/open-browser.js#L36.

And to add more context @whitep4nth3r, `ntl dev` doesn't experience the same behavior, correct?

**Comment by whitep4nth3r** [comment]
`ntl dev` experiences the same behaviour. Whilst the development server has started and I can navigate to a working development site in a browser manually, ntl dev does NOT open a browser tab.

**Comment by whitep4nth3r** [comment]
Interestingly, when I kill the `ntl dev` process, that's when the browser tab opens.

**Comment by tinfoil-knight** [comment]
@whitep4nth3r Are you still experiencing this issue?
I installed Brave & set it as my default browser. Then tried the `open:site` command. 

Brave Browser opens the the url as expected.

P.S. : I'm using `netlify-cli/10.15.0`

**Comment by whitep4nth3r** [comment]
Not experiencing this issue anymore. Thanks for following up!
