### ISSUE TITLE
feat: Run prettier automatically on generated code

### ISSUE THREAD

**Issue by sgrove** [netlify/cli#4180]
**Is your feature request related to a problem? Please describe.**

We generate various bits of code from the `graph` piece of the CLI, but we won't know the project's specific settings, so the user always has to run prettier on the result to get it to conform to their expectations.

**Describe the solution you'd like**

If prettier is available in the path, it would be a better DX to run it over the resulting files so that the output seamlessly conforms with the user's expectations.

**Describe alternatives you've considered**

We could also bundle prettier with the CLI and run it ourselves which would reduce the overhead of invoking another process, but the the bundle size increase + locking into a given version of prettier doesn't seem worth the benefits.

**Can you submit a pull request?**

Yes

**Comment by erezrokah** [comment]
I think you could use `execa` with `preferLocal: true` and ignore the failure.
See example usage in https://github.com/netlify/cli/blob/0577c151838ef36f6e2cb21fab646fc54a9e9d97/src/commands/dev/dev.js#L80

**Comment by ehmicky** [comment]
Yes, that should work.
To ignore the failure, you can also use [the `reject: false` option](https://github.com/sindresorhus/execa#reject).

**Comment by sgrove** [comment]
@ehmicky But in that case we'd have to include `prettier` in our runtime `dependencies`, right?

**Comment by ehmicky** [comment]
For both the CLI and programmatic solutions, if we want to run Prettier, its code must be installed either by us (i.e. be a production `dependencies`) or by our users (i.e. be a `peerDependencies`).

**Comment by sgrove** [comment]
> In general, I would recommend using the user's Prettier installation

I agree, that'd be the nicest. We effectively need to be able to say, "Whatever prettier setup you have, run it on the file at `<path>`"

I suspect that the `execs` approach is the easiest to approach, and we can give a one-time warning to install prettier when it fails, then continue on.

**Comment by ehmicky** [comment]
IMHO both approaches work, with different cons, coming down to speed of execution vs code quality:
  - The binary approach is slower (since it requires spawning a process). It is harder to control its output (we can mostly just forward `stdout`/`stderr` and possibly filter it) and is generally less flexible.
  - The programmatic approach is harder to implement.

**Comment by sgrove** [comment]
I'll take the binary approach first and we can implement the programmatic
approach if it causes issues with the DX
