### ISSUE TITLE
[build].command is not run in dev

### ISSUE THREAD

**Issue by raquo** [netlify/cli#419]
**- Do you want to request a *feature* or report a *bug*?**

Eeh seems to me like this is by design, so I guess a feature?

**- What is the current behavior?**

netlify.toml:
```
[build]
  base = "site/"
  publish = "site/public"
  command = "npm run less"
```

site directory has package.json:
```
{
  "name": "site",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "less": "lessc index.less index.css"
  },
  "dependencies": {
    "less": "^3.9.0"
  }
}
```

In production, netlify runs `npm run less` when deploying. It generates an index.css file.

In dev, no such thing happens, `npm run less` is not called.

Moreover, overriding the `command` under `[dev]` in netlify.toml does not work either, I'm guessing it expects a command that will launch a persistent server rather than one that will quit when done.

**- What is the expected behavior?**

I would expect `netlify dev` to run the `command` provided in `[build]`, and ideally re-run it when any files in base directory change. From what I understand, Netlify Dev is delegating this whole watch-and-serve task to static site generators, which ironically complicates things when I'm trying to do the simplest possible setup and not use one of those.

**- Please mention your node.js, and operating system version.**

node 8.x, macos 10.14.5

**Comment by erezrokah** [comment]
Closing in favour of https://github.com/netlify/cli/issues/179
