### ISSUE TITLE
failed deploys exit with zero

### ISSUE THREAD

**Issue by travi** [netlify/cli#42]
**- Do you want to request a *feature* or report a *bug*?**
considering that this is still the behavior after others have used the tool for a while, i assume this is more of a feature request, but it could be considered a bug considering common behavior of most cli tools

**- What is the current behavior?**
exits with 0 after authentication failure (incorrect token) when attempting to deploy

[example build that should have failed](https://travis-ci.org/dsmjs/site/builds/395319951#L4299-L4328)

**- If the current behavior is a bug, please provide the steps to reproduce.**
`netlify deploy --site-id $NETLIFY_SITE_ID --access-token $NETLIFY_ACCESS_TOKEN --path ./public` with an invalid token

**- What is the expected behavior?**
should exit with a non-zero exit code so that failure can be detected programatically. (most ci services with report the build as failed when commands exit non-zero)

**- Please mention your node.js, and operating system version.**
node: 9.4.0
OS: Ubuntu 14.04.5 LTS (Travis CI)

**Comment by bcomnes** [comment]
Agreed, failed deploys should not exit 0.  If you spot this behavior in the soon to be released CLI we can revisit.
