### ISSUE TITLE
Running netlify dec and then confirming not working

### ISSUE THREAD

**Issue by Saifadin** [netlify/cli#420]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

When I accidently run `netlify dec` and then confirm the prompt, the CLI gives a success message, but also stops at the same time.

![Screenshot 2019-06-12 at 10 37 30](https://user-images.githubusercontent.com/1507057/59336111-375e0080-8cfe-11e9-9ee9-4766e13232f9.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. `netlify dec` in a gatsby Project
2. confirm prompt
3. build fails.

**- What is the expected behavior?**

The command runs just like running `netlify dev`, which works just fine.

**- Please mention your node.js, and operating system version.**

Node v10.15.1 - MacOS Mojave 10.14.3 (18D109) - new fresh installation of the netlify CMS

**Comment by tinfoil-knight** [comment]
Closing this issue since it doesn't occur any longer. Tested using `gatsby/4.24.0`, `netlify-cms-app/2.15.72` & `netlify-cli/11.8.3` on `node-v16.15.1`.
