### ISSUE TITLE
netlify dev --live returns 'objectMode' of undefined

### ISSUE THREAD

**Issue by cj** [netlify/cli#421]
When running `netlify dev --live` I get the following error `TypeError: Cannot read property 'objectMode' of undefined`.

<details>
<summary>Backtrace</summary>
cj-osx ~/apps/hulsacbd/hulsa ➤ 0d7a400|design/homepage⚡
14:12 ± : npm run netlify:dev:live                               [2d0h52m]! ✹ ✭

> gatsby-starter-typescript-default@0.0.1 netlify:dev:live /Users/cj/apps/hulsacbd/hulsa
> netlify dev --live

◈ Netlify Dev ◈
◈ Injected build setting env var:  SITE_URL
◈ Starting Netlify Dev with gatsby

> gatsby-starter-typescript-default@0.0.1 develop /Users/cj/apps/hulsacbd/hulsa
> run-s cleanup gatsby:develop

> gatsby-starter-typescript-default@0.0.1 cleanup /Users/cj/apps/hulsacbd/hulsa
> run-p cleanup:public cleanup:cache

> gatsby-starter-typescript-default@0.0.1 cleanup:public /Users/cj/apps/hulsacbd/hulsa
> rimraf public

> gatsby-starter-typescript-default@0.0.1 cleanup:cache /Users/cj/apps/hulsacbd/hulsa
> rimraf .cache

Waiting for localhost:8000.
◈ Lambda server is listening on 34567

> gatsby-starter-typescript-default@0.0.1 gatsby:develop /Users/cj/apps/hulsacbd/hulsa
> gatsby develop --host 0.0.0.0

..◈ .netlify/functions/sync-shopify.js modified, reloading...
success open and validate gatsby-configs - 0.061 s
success load plugins - 1.304 s
success onPreInit - 0.015 s
success initialize cache - 0.014 s
success copy gatsby files - 0.069 s
success onPreBootstrap - 0.007 s

gatsby-source-shopify/hulsa starting to fetch data from Shopify

gatsby-source-shopify/hulsa fetched and processed blogs: 186.827ms

gatsby-source-shopify/hulsa fetched and processed collections: 223.596ms

gatsby-source-shopify/hulsa fetched and processed articles: 253.979ms

gatsby-source-shopify/hulsa fetched and processed pages: 258.644ms

gatsby-source-shopify/hulsa fetched and processed policies: 301.958ms

gatsby-source-shopify/hulsa fetched and processed productTypes: 326.195ms
⠀

gatsby-source-shopify/hulsa fetched and processed products: 442.935ms

gatsby-source-shopify/hulsa finished fetching data from Shopify: 468.451ms
success loading DatoCMS content - 2.320 s
success source and transform nodes - 2.894 s
warn Multiple node fields resolve to the same GraphQL field
warn Multiple node fields resolve to the same GraphQL field
warn Multiple node fields resolve to the same GraphQL field
success building schema - 0.450 s
success createPages - 0.051 s
success createPagesStatefully - 0.041 s
success onPreExtractQueries - 0.009 s
success update schema - 0.035 s
success extract queries from components - 0.257 s
success run static queries - 0.556 s — 4/4 7.27 queries/second
success run page queries - 0.166 s — 11/11 68.66 queries/second
success write out page data - 0.613 s
success write out redirect data - 0.141 s

Generating image thumbnails [=======-----------------------] 34/152 1.3 secs 22%Generating image thumbnails [============------------------] 62/152 2.3 secs 41%Generating image thumbnails [==================------------] 92/152 3.4 secs 61%⠀
success Build manifest and related icons - 0.110 s
success onPostBootstrap - 0.120 s
⠀
info bootstrap finished - 16.113 s
⠀

.....
Connected!
Waiting for localhost:34567.
Connected!
Waiting for localhost:8888.
Connected!
◈ Installing Live Tunnel Client
/Users/cj/apps/hulsacbd/hulsa/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^

TypeError: Cannot read property 'objectMode' of undefined
    at Source.Writable.write (/Users/cj/apps/hulsacbd/hulsa/node_modules/netlify-cli/node_modules/readable-stream/lib/_stream_writable.js:317:22)
    at Extract._write (/Users/cj/apps/hulsacbd/hulsa/node_modules/netlify-cli/node_modules/tar-stream/extract.js:230:21)
    at Extract._continue (/Users/cj/apps/hulsacbd/hulsa/node_modules/netlify-cli/node_modules/tar-stream/extract.js:213:28)
    at oncontinue (/Users/cj/apps/hulsacbd/hulsa/node_modules/netlify-cli/node_modules/tar-stream/extract.js:68:10)
    at Extract.onheader [as _onheader] (/Users/cj/apps/hulsacbd/hulsa/node_modules/netlify-cli/node_modules/tar-stream/extract.js:183:5)
    at Extract._write (/Users/cj/apps/hulsacbd/hulsa/node_modules/netlify-cli/node_modules/tar-stream/extract.js:250:8)
    at doWrite (/Users/cj/apps/hulsacbd/hulsa/node_modules/netlify-cli/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/cj/apps/hulsacbd/hulsa/node_modules/netlify-cli/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Extract.Writable.write (/Users/cj/apps/hulsacbd/hulsa/node_modules/netlify-cli/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Gunzip.ondata (_stream_readable.js:696:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! gatsby-starter-typescript-default@0.0.1 netlify:dev:live: `netlify dev --live`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the gatsby-starter-typescript-default@0.0.1 netlify:dev:live script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
</details>

`netlify --version`: netlify-cli/2.11.22 darwin-x64 node-v11.12.0

**Comment by justinwaite** [comment]
@bricksroo I removed the `netlify-lambda build` from my normal `build` script, and I still get this error. Any other thoughts? Using gatsby + netlify + functions

**Comment by erezrokah** [comment]
Closing this per my comment [here](https://github.com/netlify/cli/issues/719#issuecomment-826297308).
Please comment with a reproduction if the issue still happens
