### ISSUE TITLE
reconsider "preferred scripts" strategy, possibly get rid of it in favor of prompting

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#422]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**

right now we build in preferential behavior for npm scripts named `start` but people trying out netlify dev often overload `start` to do some extra work we often don't want, including, for example, running a `netlify-lambda` server (this is true of the old `create-react-app-lambda`), or running Zeit's `serve` (see https://community.netlify.com/t/cannot-find-module-package/1236/5).

we have the ability to look up scripts by what they call under the hood, maybe that should be ALL we do (as well as build a tree of scripts and have logic to resolve the top level node? maybe too magic.)

the most ideal non magic thing is, when no `command` is specified in `netlify.toml` dev block, to offer the matching available options, let the user pick one, persist it to `netlify.toml`, and then carry on. the biggest technical hurdle with this is the netlify.toml modifying.

**Comment by erezrokah** [comment]
Closing as stale as the logic had changed quite a bit.
We can re-open if still relevant
