### ISSUE TITLE
Access denied to config file after installing CLI when running netlify command

### ISSUE THREAD

**Issue by nicholaschedid** [netlify/cli#4243]
**Describe the bug**

I installed the netlify-cli package globally using `npm install netlify-cli -g` , the installation completed. After that I ran `netlify` command and got this error

`Error: EACCES: permission denied, open '/Users/{USER_FOLDER}/Library/Preferences/netlify/config.json.2846113261'
You don't have access to this file.`

**To Reproduce**

1. Run `npm install netlify-cli -g`
2. Installation succeed
3. Run `netlify`
4. Gets the error about not having access to config.json file

**Comment by erezrokah** [comment]
Hi @nicholaschedid, I believe this similar to https://github.com/netlify/cli/issues/3870.

Can you please try the workaround suggested in https://github.com/netlify/cli/issues/3870#issuecomment-1018483719

**Comment by nicholaschedid** [comment]
Yes, I followed your comment and solved. Thank you so much

**Comment by michael-evrythngwrx** [comment]
Hi, for future reference instead of installing the package with NPM try installation with homebrew. This will solve the access issues from installing as root user.

**Comment by adamaslan** [comment]
Hmmm Im still having issues loggin in after using brew...

 maybe I need to remove the cli? 

Wondering if it got installed twice since I used npm first then brew?

**Comment by michaelWired** [comment]
> Hmmm Im still having issues logging in after using brew...
> 
> 
> 
>  maybe I need to remove the cli? 
> 
> 
> 
> Wondering if it got installed twice since I used npm first then brew?
> 
> 
> 
> So I actually had to go into my library folder and manually delete the netlify folder.
> 
> 
> 
> I then reinstalled the netlify cli via brew

Yes exactly make sure to delete after installing via npm and then reinstall using brew!
