### ISSUE TITLE
Graph should check if `state.json` is committed to git, and if so, give a warning

### ISSUE THREAD

**Issue by sgrove** [netlify/cli#4245]
**Is your feature request related to a problem? Please describe.**

@localden shared an example app using Netlify Graph but also committed `.netlify/state.json`, and this caused a few hours of [confusion/debugging](https://netlify.slack.com/archives/C02JVT8TBDK/p1644263085172559?thread_ts=1644016093.631899&cid=C02JVT8TBDK). Graph relies on `state.json["oneGraphSessionId"]` to reuse sessions, but sessions are also guarded per-user, so when @amberleyromo was testing initially the cli picked up on @localden's sessionId, tried to connect using that, and failed with a terrible error message.

We should fix the error message as well, but separately it's important to warn the user that they're walking into some pain. We should probably also warn if:
1. We're in a git repository
2. `.netlify/state.json` _isn't_ in `.gitignore`

**Can you submit a pull request?**

Yes

**Comment by iib0011** [comment]
For which commands should we warn ?
