### ISSUE TITLE
doens't work with chrome's experimental native image and iframe lazy-loading via html attributes

### ISSUE THREAD

**Issue by neefrehman** [netlify/cli#429]
**- Do you want to request a *feature* or report a *bug*?**
Report a bug

**- What is the current behavior?**
In my project ([repo here](https://github.com/ustwo/ustwoadventure)), after creating the site and getting the success message, when I got to localhost:8888 only the initial HTML content and linked stylesheets are loaded. No Javascript or image resources.

Screenshot:
![image](https://user-images.githubusercontent.com/29544565/58027034-ab4a2600-7b0f-11e9-8b8e-212cdd942ec7.png)

As soon as the above loads terminal gives me the below error from `netlify-redirector/lib/redirects.js`, and the server shuts down so refreshing the page brings up nothing:
```bash
/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^

Error: Parse Error
    at Socket.socketOnData (_http_client.js:432:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:635:20)
```

I do have a redirects section in my `netlify.toml`:
```toml
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
```

However I have the exact same .toml file in [another project](https://github.com/neefrehman/generative) and `netlify dev` works totally fine there.

UPDATE: removing the `netlify.toml` file still produces the same error, so seemingly this is unrelated.

I've also run `git checkout` to various commits that I know `netlify dev` was working for, and am still getting the same error, so seemingly it's not something I've changed in the codebase that's the issue (which is ever odder considering my other project works fine)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Run `netlify dev` in [project folder](https://github.com/ustwo/ustwoadventure), and then try to access localhost:8888

**- What is the expected behavior?**
The site should load as normal (which was happening fine until the second half of last week)

**- Please mention your node.js, and operating system version.**
node: v10.4.0
OS: MacOS Mojave v10.14.4 (18E226)

UPDATE:
Just tried visiting via localhost:3999 after running `netlify dev`. The site loads fine initially, but then still triggers the same error in terminal so can't be refreshed after, and lazily-loaded images won't load as the connections will be refused after the inital load.

**Comment by sarahetter** [comment]
Closing as stale
