### ISSUE TITLE
Add clarifying delete text

### ISSUE THREAD

**Issue by lorensr** [netlify/cli#43]
**- Do you want to request a *feature* or report a *bug*?**

feature

**- What is the current behavior?**

When I did this:
```sh
$  netlify delete a-different-deployment
? Are you sure you want to delete this site? Yes
```
(missing `-s`), it deleted the deployment of the directory I was in, causing downtime.

**- What is the expected behavior?**

Either use the second argument as the site, or give more information in the confirmation, for instance: "defaulting to the current directory, deployment id X. would you like to delete X?"

**- Please mention your node.js, and operating system version.**

```
$  node -v
v8.11.2
```
latest macOS high sierra and npm package

**Comment by bcomnes** [comment]
We'll take this into consideration in the new CLI's delete command.
