### ISSUE TITLE
Error building Hugo site with netlify dev

### ISSUE THREAD

**Issue by jwulf** [netlify/cli#430]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
```
◈ Netlify Dev ◈
◈ Starting Netlify Dev with hugo
Total in 2 ms
Error: Error building site: open /Users/sitapati/workspace/www.parkride.com.au/content: no such file or directory
```

**- If the current behavior is a bug, please provide the steps to reproduce.**
Run netlify dev in a checkout of https://github.com/jwulf/www.parkride.com.au

**- What is the expected behavior?**
Magic - local hot-reloading dev version

**- Please mention your node.js, and operating system version.**
➜ netlify --version
netlify-cli/2.11.18 darwin-x64 node-v10.9.0

**Comment by erezrokah** [comment]
Closing this as stale as it seems an issue with building that specific site in Hugo (not a Netlify CLI one).
Please comment if still relevant and I'll re-open.
