### ISSUE TITLE
netlify-cli should respect your decision when you answer "No" to a question

### ISSUE THREAD

**Issue by whitep4nth3r** [netlify/cli#4303]
**Describe the bug**

If you make a typo on the command line and Netlify asks you to confirm your decision, and you reply with "No", Netlify goes ahead and runs a command anyway.

**To Reproduce**

1. Type `netlify ddev` or a similar typo
2. Reply with "No" when Netlify asks "Did you mean dev"
3. Observe that `netlify dev` is run anyway

**Configuration**

```bash
System:
    OS: macOS 12.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.52 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.0 - /opt/homebrew/bin/npm
  npmGlobalPackages:
    netlify-cli: 8.14.1
```

**Expected behavior**

When I answer "No", I expect the CLI not to run.

**CLI Output**

![image](https://user-images.githubusercontent.com/52798353/154025480-8447ea92-df20-4585-b4d5-b26de99a2df8.png)

**Additional context**

This issue might be linked to [#2873](https://github.com/netlify/cli/issues/2873)

**Comment by iib0011** [comment]
solved https://github.com/iib0011/cli/commit/648edc81219d1c3538fa82f22786ca22061093a7
