### ISSUE TITLE
Can't access Shared environment variables from `netlify dev`

### ISSUE THREAD

**Issue by theostanton** [netlify/cli#431]
**- Do you want to request a *feature* or report a *bug*?**
Report a bug. 

**- What is the current behavior?**
The `netlify dev` command correctly pulls in env vars for the linked project but doesn't pull in team wide env vars from the Shared Environment Variables section of Team Settings. 

**- If the current behavior is a bug, please provide the steps to reproduce.**
Link a project and call `netlify dev`

**- What is the expected behavior?**
See the same env vars when calling `netlify dev` as when building remotely in Netlify.

**Comment by Eddie-CooRo** [comment]
Hey @sw-yx 
Any updates about this?
We recently upgraded our account to be able to use the `shared environment variables` feature, included in the pro plan. But unfortunately, I found out that netlify-dev doesn't support this feature yet.
I was able to make it work by tweaking some parts of the `addEnvVariables` function. I'm going to open a PR for it today; it'll be great if you can find time to review it.
Thanks
