### ISSUE TITLE
make detector loading robust to bad files

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#434]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
netlify dev will completely fail if a single bad detector is submitted from community. e.g. netlify/netlify-dev-plugin#177 

we will eventually extract it out and automate tests, but also want to build in more resilience from the netlify dev/cli side.

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your node.js, and operating system version.**

**Comment by DavidWells** [comment]
`try {} catch` on the detector loader will do wonders

**Comment by sw-yx** [comment]
i think i already implemented this
