### ISSUE TITLE
[future feature?] live reload env vars when changed from the admin UI

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#435]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
when i'm in netlify dev, and i change a env var on my site, i have to kill netlify dev and reload it again to pick up the change.

**- What is the expected behavior?**
no killing

**- Please mention your node.js, and operating system version.**
n/a

**Comment by RaeesBhatti** [comment]
I think this is a bit too much to ask considering the other issues we have. Not planning to implement it for now. Will reconsider if more interest is presented. Thanks for opening this ticket!
