### ISSUE TITLE
Netlify Identity Widget broken

### ISSUE THREAD

**Issue by DavidChouinard** [netlify/cli#436]
**- Do you want to request a *feature* or report a *bug*?**

Bug.

**- What is the current behavior?**

While using Netlify Dev (i.e. on a `....netlify.live` URL), the Netlify Identity Widget appears broken. Triggering `netlifyIdentity.open()` unhides a dark overlay over the entire content but doesn't open the model.

There are no Javascript errors in the console. Everything works fine when accessing `http://localhost:8000` directly. I've done `localStorage.removeItem('netlifySiteURL');` on both the netlify.live and localhost.

![brokenlogin](https://user-images.githubusercontent.com/388552/57333884-f78a7480-70d2-11e9-8577-656203cce2b8.gif)

**- If the current behavior is a bug, please provide the steps to reproduce.**

Start a new Gatsby project, include `netlify-identity-widget` and trigger `netlifyIdentity.open()`.

**- What is the expected behavior?**

`netlifyIdentity.open()` trigger a dark overlay and a login modal. (only dark overlay is shown)

**- Please mention your node.js, and operating system version.**

`v11.14.0` on Mac OS Mojave.

**Comment by erezrokah** [comment]
Closing this as stale. If still happens please comment/re-open here https://github.com/netlify/netlify-identity-widget
