### ISSUE TITLE
Support non-random port assignment?

### ISSUE THREAD

**Issue by mattlenz** [netlify/cli#438]
Is it possible to run netlify dev and specify which port the dev server will listen on?

At the moment it seems to select a random open port which makes it difficult to integrate with existing development processes.

The `--port` argument and config currently relate to the application port that will be proxied by netlify dev, but it looks like there is no way to configure netlify dev's port.

**Comment by oles** [comment]
@sw-yx this still seems to be a lovely mess.

as far as I can tell, none of the port configs even work or do anything.

I wanted to change which port the "Server now ready on ..." uses.

Neither --port flag or lines in the netlify.toml [dev] block have seemingly any effect.

Frustrating.

**Comment by oles** [comment]
Great! Thank you, @RaeesBhatti 🎉
