### ISSUE TITLE
Bug: Gridsome page query WebSocket error

### ISSUE THREAD

**Issue by zefman** [netlify/cli#439]
**- What is the current behavior?**

When using `netlify dev --live` with Gridsome pages that have a <page-query> to load GraphQL data with not load.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Create a new gridsome project:

`gridsome create my-gridsome-site`

Add a page query to any Page component such as Index

```
<page-query>
query {
  allPage {
    title
  }
}
</page-query>
```

Run `netlify dev --live`

Navigate to the page via the live url. You will get an error:

![Screenshot 2019-05-02 at 20 22 07](https://user-images.githubusercontent.com/1266503/57100916-feeb0000-6d17-11e9-8268-caee5cbfdb56.png)

This is because when running gridsome develop, graphql queries happen live over a websocket that isn't proxied by Netlify dev. The SockJS server url is by default http://localhost:9001/echo

**- What is the expected behavior?**

No errors and the websocket it proxied.

**Comment by erezrokah** [comment]
Sorry for the very late reply. I couldn't reproduce this on a gridsome site with the latest CLI and live tunnel client.
Closing as stale, if this still happens please comment with a reproduction (possibly a public repo) and I'll re-open.
