### ISSUE TITLE
CLI argument context being replaced with env variable CONTEXT in build 

### ISSUE THREAD

**Issue by sohailykhan94** [netlify/cli#4403]
**Describe the bug**

When cli is run like
`netlify build --context deploy-preview  --debug` the correct context and build command is reported at first, but the config gets replaced with the value set in env variable set in `CONTEXT` or defaults to `production`

**To Reproduce**

| Step | Command | Result |
| --- | --- | --- |
| 1 | Run `netlify build --context deploy-preview  --debug` with env variable `CONTEXT` unset | N/A |
| 2 | Correct config is picked in `Netlify Build` | <img width="459" alt="image" src="https://user-images.githubusercontent.com/7306676/156192481-fbf093cc-5a3b-4d42-9cfc-f5c463d412d7.png"> |
| 3 | Config is updated to pick the `command` for production in `1. @netlify/plugin-nextjs (onPreBuild event)` | <img width="629" alt="image" src="https://user-images.githubusercontent.com/7306676/156192986-462e3313-2947-4bac-8d82-efe015a7e664.png"> |
| 4 | When the cli command is run with `CONTEXT=deploy-preview` then the command runs as expected | <img width="365" alt="image" src="https://user-images.githubusercontent.com/7306676/156193390-33c0cc59-e7b1-446c-88b3-7165598925ec.png"> <img width="618" alt="image" src="https://user-images.githubusercontent.com/7306676/156193428-d8adc871-1dd5-4a50-89b5-dcace2124e2c.png"> |

**Configuration**

```
# Rough toml outline
[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-nextjs"

# Production context: all deploys from the Production branch set in your site’s
# Branches settings in the UI will inherit these settings.
[context.production]
  command = "echo 'production'"
...
[context.deploy-preview]
  command = "echo 'deploy-preview'"
...
[context.branch-deploy]
  command = "echo 'branch-deploy'"
```

**Expected behavior**

The command line context argument should be used at all time.

**Comment by ehmicky** [comment]
This should be fixed in [`9.9.3`](https://github.com/netlify/cli/releases/tag/v9.9.3).
