### ISSUE TITLE
"Starting Netlify Dev with gatsby" and then nothing

### ISSUE THREAD

**Issue by johnmryan** [netlify/cli#441]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Followed the prerequisites section, ran `netlify dev` in a Gatsby project with netlify functions. Receive the following output:
```
◈ Netlify Dev ◈
◈ Injected build setting env var:  CLIENT_ID
... other injects
◈ Starting Netlify Dev with gatsby
```
Nothing else happens, it just exits after this with no warning. And nothing is running on local. Will try to step through the `netlify dev` code locally in the meantime to see if something jumps out at me.

**- Please mention your node.js, and operating system version.**
Ubuntu 18.04, Node 10.15.2

**Comment by meronek** [comment]
Hi, amateur here also having this issue. Have been using netlify dev for a few weeks now on other projects but on this new one using react-static, netlify dev won't start up.

OSX, VS Code.

Just ran npm install netlify-cli -g
then netlify dev
and I get:

◈ Netlify Dev ◈
◈ Starting Netlify Dev with react-static
Waiting for localhost:3000.
◈ Lambda server is listening on 34567
And it exits back to terminal prompt.

Repo:
https://github.com/meronek/gfl-series-react-static

Thanks for any help or insight you can provide.
