### ISSUE TITLE
`netlify dev` reload causes error: "Module did not self-register" with node-canvas

### ISSUE THREAD

**Issue by joshuaellis** [netlify/cli#4410]
**Describe the bug**

This is the same as #2641.

**To Reproduce**

1. Run `git clone git@github.com:joshuaellis/netlify-dev-canvas-bug.git`
2. Navigate to the cloned repository
3. Run `yarn` to install the deps
4. Run `netlify dev`
5. Navigate to `http://localhost:8888/.netlify/functions/generate-static?handle=123`
6. It'll work!
7. Change something in the function e.g. the statusCode
8. Refresh `http://localhost:8888/.netlify/functions/generate-static?handle=123`
9. It'll fail saying `Error: Module did not self-register: ...`

**Configuration**

```toml
[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/generate/dynamic"
  to = "/.netlify/functions/generate-dynamic"
  status = 200
```

^^^ this is included in the repo

```bash
  System:
    OS: macOS 12.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 128.91 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.6.0 - ~/.nvm/versions/node/v17.6.0/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v17.6.0/bin/yarn
    npm: 8.5.1 - ~/.nvm/versions/node/v17.6.0/bin/npm
    Watchman: 2022.02.28.00 - /opt/homebrew/bin/watchman
  npmGlobalPackages:
    netlify-cli: 9.10.0
```

**Expected behavior**

Not to unregister and require me to manually stop and start the dev server

**CLI Output**

If applicable, add the CLI output to help explain your problem.

```shell
Request from ::1: GET /.netlify/functions/generate-static?handle=123
{"level":"error","message":"End - Error:"}
{"errorMessage":"Module did not self-register: '/Users/josh/code/netlify-dev-canvas-bug/.netlify/functions-serve/generate-static/src/node_modules/canvas/build/Release/canvas.node'.","errorType":"Error","level":"error","stackTrace":["Object.Module._extensions..node (node:internal/modules/cjs/loader:1181:18)","Module.load (node:internal/modules/cjs/loader:975:32)","Function.Module._load (node:internal/modules/cjs/loader:822:12)","Module.require (node:internal/modules/cjs/loader:999:19)","require (node:internal/modules/cjs/helpers:102:18)","Object.<anonymous> (/Users/josh/code/netlify-dev-canvas-bug/.netlify/functions-serve/generate-static/src/node_modules/canvas/lib/bindings.js:3:18)","Module._compile (node:internal/modules/cjs/loader:1097:14)","Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)","Module.load (node:internal/modules/cjs/loader:975:32)","Function.Module._load (node:internal/modules/cjs/loader:822:12)"]}
```

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed

**Comment by joshuaellis** [comment]
@sarahetter, are you able to explain how you think an issue is stale when no one has replied? :)

**Comment by sarahetter** [comment]
Hi @joshuaellis 

I'm sorry you didn't get a response when you posted this. However, as we haven't had any other reports of this issue, and we are in the process of combing the backlog for priority issues in the netlify-cli, I have marked this as stale. 

If this is still an outstanding issue for you, feel free to reopen or post in the [Netlify Support Forums](https://answers.netlify.com/)
