### ISSUE TITLE
test all of netlify dev with space separated dirs. or weird errors arise

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#442]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**

Shawn Makinson   [Today at 2:33 PM]
Something else I see, trying to run  `netlify functions:create hello-world` and I get `Cannot find module` for `.netlify-function-template.js`. It does exist, but I happen to be using my fork and it’s path has a dir with spaces in the name, could that be the issue?

https://netlify.slack.com/archives/C7G3WHB7U/p1556044395043000

**- What is the expected behavior?**
it should work with space separation

**Comment by erezrokah** [comment]
Closing this as stale.
Not sure what is the bug or how to reproduce.
Please comment if still relevant
