### ISSUE TITLE
Redirects don't seem to work with esbuild enabled for node_bundler

### ISSUE THREAD

**Issue by makingthingswork** [netlify/cli#4424]
The redirects are a really useful feature but it appears if one has `esbuild` enabled for `node_bundler` the redirects don't work as you get a message saying "Too many redirects". In this case I can easily switch node fetch back to version 2 from version 3 and drop esbuild to get the redirect working.

Can anyone confirm that the "Too many redirects" issues I am experiencing is known or expected with the scenario I describe with `esbuild` on? It not a real problem so if I want a custom Url for a function that requires me to use esbuild then I will find a way to revert it back to the default like the scenario described above.

```
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
```

**Comment by erezrokah** [comment]
Hi @makingthingswork, can you follow the [bug report template](https://github.com/netlify/cli/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md&title=Please+replace+with+a+clear+and+descriptive+title)?

The template ensures we have the information needed to understated, reproduce and fix the issue.
