### ISSUE TITLE
feat(command-deploy): Specify a deploy name/header/id

### ISSUE THREAD

**Issue by blakegearin** [netlify/cli#4426]
### Which problem is this feature request solving?

When using CD, deploys to production look like this.

<img width="230" alt="image" src="https://user-images.githubusercontent.com/17950836/156911898-0fc986f0-c485-4c7f-bfa2-00b37992f10f.png">

With the CLI, you can only specify a `message` flag (represented here as `Removed alias`).

<img width="230" alt="image" src="https://user-images.githubusercontent.com/17950836/156911997-193477e8-7d27-4189-a6c0-e832cd088f44.png">

I would like to pass in `main@6e34b17` or a similar string. This would make the UI consistent between the CLI and CD. It would also allow easier tracking between deploys and commits (or other user-specified identifiers).

### Describe the solution you'd like

I see ~two~ three ways to approach this:

1. Make the `prod` flag accept a string, though this wouldn't extend support to branch deploys

1. Make the `alias` flag value appear at this location in the UI, though this wouldn't extend support to production deploys

1. Add a new flag (e.g. `name`, `header`, `customId`) that accepts a string (could have a character limit like `alias`)

### Pull request (optional)

- [ ] I can submit a pull request.

**Comment by erezrokah** [comment]
Hi @blakegearin, I believe this is covered in https://github.com/netlify/cli/issues/1122.

Closing as a duplicate. If #1122 doesn't cover this use case, comment and I'll re-open
