### ISSUE TITLE
netlify dev --live error - "missing release version"

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#445]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
https://twitter.com/amacarthur/status/1120736679218827266

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your node.js, and operating system version.**

**Comment by erezrokah** [comment]
Closing this as stale. If this still happens please comment.
I think GitHub rate limits is can be a valid cause for this issue. We even workaround it in our tests:
https://github.com/netlify/cli/blob/4f6fc93a2a79dbae0dc2ce9a1c885834308b330b/src/lib/exec-fetcher.js#L17
