### ISSUE TITLE
`.DS_Store` causing a failure in Remix

### ISSUE THREAD

**Issue by jlengstorf** [netlify/cli#4453]
### Describe the bug

Remix ignores `.*` files in the routes folder, but when running Netlify CLI a `.DS_Store` file will cause a routing failure:

```sh
[1] Invalid route module file: /app/routes/api/.DS_Store
[1] ◈ Command failed with exit code 1: remix watch. Shutting down Netlify Dev server
[1] cross-env NODE_ENV=development netlify dev exited with code 1
^C[0] npm run dev:css exited with code 0
```

It's unclear where this is coming from, but is it possible that the Netlify CLI is overriding ignore settings in Remix?

### Steps to reproduce

1. Create a Remix project
2. Add a `.DS_Store` file to the `/app/routes/api` directory
3. Try to run `netlify dev`

### Environment

Reported by a user; unsure what env.

**Comment by mattevans-dev** [comment]
I'm currently facing this exact same issue. I'm trying to setup my project running the Netlify CLI and receiving:
`Error: Invalid route module file: /app/routes/account/.DS_Store`
I have `ignoredRouteFiles: [".*"]` added in my remix.config file but that doesn't fix this issue.
@jlengstorf Did you happen to find a workaround for this?

**Comment by jlengstorf** [comment]
@mattevans-dev my workaround was to delete the `.DS_Store` manually, but I haven't figured out a more permanent fix.

**Comment by danez** [comment]
Does anyone of you two have a repo with a remix project where I can test this?

**Comment by tinfoil-knight** [comment]
@jlengstorf Is this issue still occurring for you? If yes, could you please provide a repo with the reproduction.

I tried a few Remix templates with the `.DS_Store` file in routes but wasn't able to reproduce this error.

**Comment by serhalp** [comment]
Marking this as stale as it is is several years old. Please feel free to reopen if you are still having issues.
