### ISSUE TITLE
Malicious Attacks - security vulnerability

### ISSUE THREAD

**Issue by EmilyNecciai** [netlify/cli#4460]
### Describe the bug

Malicious attacks via our feedback form from a specific IP address (help.bolt.com) despite honeypot fields and recaptchas. Your security policy says to open an issue with the label: security but I can't edit my label. 

### Steps to reproduce

None

### Configuration

Private repo. 

### Environment

npx: installed 1 in 1.262s

  System:
    OS: macOS 11.6
    CPU: (8) x64 Apple M1
    Memory: 60.95 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.4 - /usr/local/bin/node
    npm: 6.14.14 - /usr/local/bin/npm

**Comment by erezrokah** [comment]
Hi @EmilyNecciai and thank you for this issue. Per our security policy we accept reports to Netlify public repos (like the CLI) via Hacker one. See https://github.com/netlify/cli/security/policy.

Do you mind submitting this via https://hackerone.com/netlify?type=team?

**Comment by EmilyNecciai** [comment]
Thank you! :)

**Comment by erezrokah** [comment]
Ah, thanks for clarifying @EmilyNecciai.

In that case I recommend using one of our support channels, see https://www.netlify.com/support/ for example. You can select abuse in the dropdown.
