### ISSUE TITLE
Add support for forms

### ISSUE THREAD

**Issue by fool** [netlify/cli#447]
**- Do you want to request a *feature* or report a *bug*?**

*feature*

**- What is the current behavior?**

*netlify forms are not supported*

**- If the current behavior is a bug, please provide the steps to reproduce.**

*attempt to use a netlify form from a dev instance, get 404*

**- What is the expected behavior?**

*attempting to use a netlify form from a dev instance should return successful response and further run the event-triggered function, if any*

**- Please mention your node.js, and operating system version.**

*all*

**Comment by cannikin** [comment]
I could see Phase 1 being as simple as creating a `forms.txt` file in the root of the app and appending the raw body from any POSTs to it. But the browser should display the same "Thank you" page that you get in production. Likewise an AJAX submit to the form should behave like production.

Phase 2 lets you browse to /.netlify/forms and you see the real Forms UI just like on app.netlify.com 😉

**Comment by erikwoods** [comment]
For me personally, I would at least like to have the Netlify Form use the action attribute to redirect a Dev user to the appropriate page. Otherwise it just looks like the form/page is busted. I don't want my engineering friends to get hung up on this - and they will as things are today. :(
