### ISSUE TITLE
netlify dev --live hangs indefinitely without deploying 

### ISSUE THREAD

**Issue by aamorozov** [netlify/cli#448]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
After running `netlify dev --live` in the initialized project folder with `./.netlify/state.json` file that has a site id specified, the command just keeps running indefinitely without deploying the preview link. 

**- If the current behavior is a bug, please provide the steps to reproduce.**
It's a private project, but I'll put together a repo to reproduce tonight. 

**- What is the expected behavior?**
The local env is deployed with a preview link available. 

**- Please mention your node.js, and operating system version.**
MacOS Mojave 10.14.4 
Node: v11.14.0
NPM: 6.9.0
netlify-cli: 2.11.11

**- Screenshot for reference**
<img width="1439" alt="Screen Shot 2019-04-22 at 10 10 39 AM" src="https://user-images.githubusercontent.com/10227658/56504760-93b75780-64e7-11e9-8c11-8be3a1fc2f3c.png">

**Comment by bitwhys** [comment]
Can we please fix this? I had to revert to 2.12 back in December from 2.25, you're now at 2.30 yet a fundamental issue is still present.

**Comment by erezrokah** [comment]
Closing this as stale and per my comment [here](https://github.com/netlify/cli/issues/719#issuecomment-826297308).

If this still happens, please provide a reproduction and we'll re-open the issue.
