### ISSUE TITLE
Notify users that this tool is deprecated

### ISSUE THREAD

**Issue by lorensr** [netlify/cli#45]
perhaps by publishing an update to the tool that prints a deprecation notice when used?

**Comment by bcomnes** [comment]
See https://github.com/netlify/netlify-cli/issues/40#issuecomment-403915485 for some updates.  tldr we are redoing a node cli and will have something to replace this soon, and will come up with a smoother transition strategy once thats ready.

**Comment by bcomnes** [comment]
Since we are moving back to a re-written node CLI in the coming days, we decided to continue the use of this repo.  Stay tuned for more announcements and info.
