### ISSUE TITLE
Redirects with query params

### ISSUE THREAD

**Issue by zigomir** [netlify/cli#450]
```
netlify -v
netlify-cli/2.11.11 darwin-x64 node-v10.15.3
```

Seems like query params in redirects are not working with `netlify dev`.
I tried same config on prod with `netlify deploy` and it works fine there.

Contents of my `_redirects`

```
/oauth_callback state=:state code=:code /.netlify/functions/login?code=:code&state=:state 301
```

**Comment by raeesbhatti** [comment]
Fixed in https://github.com/netlify/cli/pull/534
