### ISSUE TITLE
Bug: content-length header makes proxy fail on a deployed site

### ISSUE THREAD

**Issue by sanderhahn** [netlify/cli#451]
**- If the current behavior is a bug, please provide the steps to reproduce.**

Deploying the following function will result in a 502 proxy error:

```javascript
exports.handler = async function (event, context) {
    return {
        statusCode: 200,
        headers: {
            "Content-Length": 3,
        },
        body: "123",
    };
};
```

**- What is the expected behavior?**

Netlify dev works correctly and doesn't generate a 502 proxy error.

**Comment by sarahetter** [comment]
Closing as stale
