### ISSUE TITLE
Deploy Preview is a blank page

### ISSUE THREAD

**Issue by NicoleJaneway** [netlify/cli#4535]
### Describe the bug

After trying many different things, my deploy preview is still compiling into a blank page. I’m able to successfully deploy from GitHub to production, but not to deploy preview.

Production deploy: (https://www.datastrategypros.com/).

Sample repo: [https://github.com/NicoleJaneway/netlify-build 1](https://github.com/NicoleJaneway/netlify-build)

Sample deploy: [https://deploy-preview-38–hungry-noyce-fb652c.netlify.app/](https://deploy-preview-38--hungry-noyce-fb652c.netlify.app/) ← blank page

Note that there is no “homepage” property in my package.json, so an incorrect value here must not be my problem. I think there’s something in my Netlify settings that’s messed up (maybe even some property that I don’t have access to as a frontend user of the site), and I would like someone from Netlify to help or at least confirm this is not the case.

### Steps to reproduce

[https://deploy-preview-38–hungry-noyce-fb652c.netlify.app/](https://deploy-preview-38--hungry-noyce-fb652c.netlify.app/)

### Configuration

```
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  
[build]
  functions = "functions" 
  publish = "build"

[dev]
  command = "npm run start"
  port = 8888
  targetPort = 3000
  publish = "dist" 
  autoLaunch = true
  framework = "create-react-app"

[functions]
  directory = "functions"
  included_files = ["./src/data/payments.json"]
```

### Environment

  System:
    OS: macOS 12.1
    CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
    Memory: 53.65 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  npmPackages:
    netlify-cli: ^9.16.6 => 9.16.6

**Comment by Hrishikesh-K** [comment]
Hey @NicoleJaneway,

The repository is only for issues with CLI and yours in not one of that, sadly. Please note that, the Support Team doesn't monitor this space and you're directly engaging with one of our engineers here in many cases.

It would be great if you could engage with the Support Team before and we'll escalate the issues to the engineers if needed.

I see you were talking to Coel may on the forums here: https://answers.netlify.com/t/54728/ and most likely didn't get a helpful feedback, but do note that Coel is not a member of the official Support Team. They're a volunteer. I'll be closing this issue now, feel free to continue the discussion on the forums or if you're on a paid plan, you can write in to support@netlify.com.

We hope you understand.
