### ISSUE TITLE
[DX] automatically bootstrap functions dependancies

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#454]
imperative for dx

On `netlify init` and `netlify link` cd into functions, if specified and install try to install `node_modules` for netlify dev users with teammates who clone their repos.

**Comment by erezrokah** [comment]
Closing this as we recommend users to put functions dependencies in the top level `package.json` https://docs.netlify.com/functions/build-with-javascript/#unbundled-javascript-function-deploys
