### ISSUE TITLE
Feature request: support secure HTTPS local dev environnement

### ISSUE THREAD

**Issue by borisschapira** [netlify/cli#455]
Right now, I'm developping locally with a compiled Jekyll with a self-signe cert. To use Netlify Dev, I would need it to support secure environment and the ability to either produce it's own self-signed cert, or be able to pass mine as argument.

**Comment by jhull** [comment]
Wondering the update on this...it's February 2020...

**Comment by RaeesBhatti** [comment]
`http://localhost` is already treated as [Secure Context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) by [major browsers](https://www.chromestatus.com/feature/6269417340010496), so, you don't really need an `https://` address.
Or are you using a custom hostname for local development? In which case I would suggest using `localhost` instead.
Please elaborate on your problem if this doesn't work for you!

**Comment by borisschapira** [comment]
Use case: several web projects and each of them has its own context (cookies, service workers, local storage…). If you expose all of them on http://localhost, you mix the contexts. You'd rather want independant self-signed certs on development domains to be able to work on several contexts without interferences.

**Comment by erezrokah** [comment]
> Use case: several web projects and each of them has its own context (cookies, service workers, local storage…). If you expose all of them on http://localhost, you mix the contexts.

Thanks @borisschapira, can this issue be resolved by using a different port per context?

**Comment by borisschapira** [comment]
@erezrokah Yes, it could, with [the appropriate certificate](https://letsencrypt.org/docs/certificates-for-localhost/).

**Comment by erezrokah** [comment]
@borisschapira, I think was not clear with my suggestion.
Won't `http://localhost:8000` and `http://localhost:9000` have different context (cookies, service workers, local storage…)?
So to resolve your use case you could run each project on a different port via the `--port` option?

**Comment by probablyup** [comment]
I think this is needed. Gatsby CLI for example supports running an HTTPS environment via the "-S" flag which uses some library to automatically provision the needed self-signed certificates (I think it's called "devcert".)

`localhost` isn't enough in a lot of cases to bypass the need for HTTPS, for example some browser APIs won't work without being in an explicit SSL context.

**Comment by erezrokah** [comment]
> for example some browser APIs won't work without being in an explicit SSL context.

Thank you for the additional information @probablyup, can you share those APIs and cases? That would make it easier to verify those work when the CLI is running in HTTPS mode.

**Comment by probablyup** [comment]
@erezrokah https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts

**Comment by erezrokah** [comment]
> @erezrokah https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts

The link at the bottom of that page to [Secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) shows that `localhost` is a secure context:

![image](https://user-images.githubusercontent.com/26760571/100231005-16f42700-2f2f-11eb-8103-aff4d2dc20bb.png)

**Comment by mmiller42** [comment]
We have a lot of code that depends on an internal OAuth client hardcoded to require the https protocol. I know this could be fixed with code changes, but I also would really love to be able to have this. I build my frontend with [`parcel serve --https`](https://parceljs.org/cli.html#enable-https) which has worked great in the past, but it's unfortunate that I can't make it work with netlify-dev.

**Comment by probablyup** [comment]
Agreed. It's also something that's made very easy with https://github.com/davewasmer/devcert

Would love to see it made available!

**Comment by mashaalmemon** [comment]
Any plans to add this functionality netlify team?

**Comment by probablyup** [comment]
ButcherBox is interested in sponsoring a bug bounty for this feature, if a maintainer could chat me.

**Comment by erezrokah** [comment]
Hello 👋  We are planning on adding this feature (we don't have a timeline yet).
I think the implementation would auto generate a self signed certificate with an option to override it.
https://github.com/davewasmer/devcert installs a root CA and requires admin/sudo access so we would like to avoid it.

**Comment by borisschapira** [comment]
A hell of a news! Thanks, keep us posted.

**Comment by erezrokah** [comment]
Following up here after an internal discussion we had. 

> That should also work with the live tunnel `--live --secure`, although the tunnel connection is already secure by default.

Will the above suggestion cover your use cases? cc @mmiller42, @probablyup, @borisschapira 

You should get an `https` URL to access your local dev environment when running `netlify dev --live`.

If that doesn't work, it would be great if you can provide a reproduction for it.

**Comment by probablyup** [comment]
@erezrokah I'm not comfortable allowing remote access just so I can use a secure context locally

**Comment by seanarnold** [comment]
@erezrokah I ran into this in the weekend too.

My usecase is:
- I have an OAuth login to an API that requires an HTTPS redirect URL
- I am using Netlfiy functions

I got around the first point by following https://dev.to/nakib/using-https-on-next-js-local-development-server-bcd, which uses `mkcert` to issue a cert. But that has downsides such as creating a root CA like you mentioned in https://github.com/netlify/cli/issues/455#issuecomment-754121681.

This works well for being able to serve my local site over HTTPS, but the Netlify functions return `404` - I suppose they only work with `netlify dev`?

It'd be great if we could point a certificate and key to `netlify dev` and tie these two together. (Maybe configurable in a `netlify.toml.local` too?)

**Comment by erezrokah** [comment]
Thanks @seanarnold, that use case makes sense. You're correct about Netlify functions - `netlify dev` starts the server for those.

**Comment by erezrokah** [comment]
Hi all 👋 Support for HTTPS local development support is released in [v3.18.0](https://github.com/netlify/cli/releases/tag/v3.18.0). See more [here](https://cli.netlify.com/netlify-dev#running-an-https-server-for-local-development).

I've opened a follow up issue https://github.com/netlify/cli/issues/2136 to auto generate certificates.

**Comment by moshfeu** [comment]
I can't find this in the current version nor in the docs. [This file](https://github.com/netlify/cli/blob/bb0a633c107f133476f6c69c6694c1d7dc0b1e28/docs/netlify-dev.md) is no longer exist in the main branch
Is this option dropped along the way?

**Comment by ramonsnir** [comment]
> I can't find this in the current version nor in the docs. [This file](https://github.com/netlify/cli/blob/bb0a633c107f133476f6c69c6694c1d7dc0b1e28/docs/netlify-dev.md) is no longer exist in the main branch Is this option dropped along the way?

It is still documents in the docs site: https://docs.netlify.com/configure-builds/file-based-configuration/#netlify-dev:~:text=https%3A%20property%20that%20specifies%20an%20SSL/TLS%20certificate%20and%20key%20file%20for%20the%20Netlify%20Dev%20local%20server.%20By%20default%2C%20Netlify%20Dev%20starts%20an%20HTTP%20server%2C%20but%20you%20can%20configure%20a%20certificate%20and%20key%20file%20if%20you%20require%20HTTPS.%20The%20https%20configuration%20is%20an%20object%20with%20the%20following%20properties%3A

Most docs were moved to the docs site from this repository.

Note that Netlify support is available at https://answers.netlify.com/

**Comment by moshfeu** [comment]
Thanks @ramonsnir
