### ISSUE TITLE
Netlify Dev Server with Edge Functions defaults to Vite in a Remix application with Vite dependency

### ISSUE THREAD

**Issue by baiirun** [netlify/cli#4564]
### Describe the bug

If `vite` is present as a dependency in your application using **Edge Functions**, the Netlify Dev Server will default to bundling your application with Vite instead of the Remix toolchain. If you remove `vite` from your dependencies, it will use Remix's toolchain as expected.

### Steps to reproduce

[Here's a reproduction repo with the below steps already done.
](https://github.com/ByronGuina/netlify-functions-remix-reproduction)
1. Create a remix application with the netlify/remix-edge template `npx create-remix@latest --template netlify/remix-edge-template`
2. Add vite `npm install -D vite`
3. Start your dev server `npm run dev`

The application should bundle using vite which breaks with Remix
<img width="743" alt="CleanShot 2022-04-25 at 16 42 24@2x" src="https://user-images.githubusercontent.com/26263630/165186521-3577af92-3adb-41d2-a4c6-f037a8af9c87.png">
.

### Environment

  System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 135.50 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm

**Comment by serhalp** [comment]
Marking this as stale as it is several years old. Please feel free to reopen if you are still having issues.

(I believe we fixed this quite some time ago, actually!)
