### ISSUE TITLE
support local environment variables and dev-specific settings in netlify.toml, with optional context flag

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#457]
@davidwells already has a prototype of this. 

related: 

- https://github.com/netlify/netlify-dev-plugin/issues/114
- https://github.com/netlify/netlify-dev-plugin/issues/60
- also raised in community
- also raised in slack (internal channel) for an enterprise customer:  https://netlify.slack.com/archives/C8VD55Q23/p1562004405020500

**Comment by cavatron** [comment]
As a workaround, set your variable in the UI to the value you want it to be while developing, which Netlify Dev will use. Then use `netlify.toml` to set up other contexts, which will override the ones in the UI when needed.
```
[context.production.environment]
  MY_ENV = "something for prod"
```
