### ISSUE TITLE
Netlify-Dev won't run edge function services locally

### ISSUE THREAD

**Issue by jdesherlia** [netlify/cli#4584]
### Describe the bug

I can't get netlify-cli to start edge function services when running netlify dev. It displayed the message the first time, but I had to stop the build to add the path and function to my netlify.toml. Since then, I can't get it to display the message or start the service. I am following the hello world documentation, so nothing crazy.

### Steps to reproduce

Follow the [hello world documentation](https://docs.netlify.com/netlify-labs/experimental-features/edge-functions/get-started/) then try to start netlify-cli.

### Configuration

[functions]
  directory = "lambdas/"

[[edge_functions]]
  path = "/hello-test"
  function = "hello"

# [[plugins]]
# package = "@netlify/plugin-gatsby"

# Testing build settings for disabling post processing on this specific branch
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = false

[build.processing.images]
  compress = false

### Environment

  System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 40.64 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Netlify-cli: netlify-cli/10.2.0 darwin-x64 node-v16.13.2
  Gatsby-cli: 4.13.0

**Comment by jdesherlia** [comment]
Our repo is private, so I won't be able to share access to it. I was hoping there was some debugging help you could provide that could help me track down what might be happening.

**Comment by jackiewmacharia** [comment]
Closing this for now as per Slack follow up chat, issue to be reopened later if need be.
