### ISSUE TITLE
Node experimental feature warning leaking to CLI

### ISSUE THREAD

**Issue by danisztls** [netlify/cli#4608]
### Describe the bug

The following warning appear when I run netlify-cli.

```
(node:359487) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

### Steps to reproduce

Run `netlify status`.

*Note: Also happens with other commands*

### Configuration

None.

### Environment

  System:
    OS: Linux 5.17 Arch Linux
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 6.53 GB / 15.61 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.1.0 - /bin/node
    Yarn: 1.22.18 - /bin/yarn
    npm: 8.5.5 - /bin/npm
  npmGlobalPackages:
    netlify-cli: 10.3.1

**Comment by tinfoil-knight** [comment]
NodeJS currently doesn't allow suppressing individual categories of warning. There are multiple feature requests to do this in NodeJS: https://github.com/nodejs/node/issues/40940, https://github.com/nodejs/node/issues/30810.

All warning can be disabled though by setting `NODE_NO_WARNINGS=1` or by passing the `--no-warnings` to the nodejs executable. 

@minivan Do you think we should do this? 

Ref:
https://nodejs.org/api/cli.html#node_no_warnings1
https://nodejs.org/api/cli.html#node_no_warnings1

**Comment by danez** [comment]
This is fixed with #4998 

Once the next release is published it will go away.

**Comment by AgentEnder** [comment]
@tinfoil-knight Excuse me from necroing this a bit, I wanted to put forth an idea. Do you think it would be reasonable, as a library author, to use something like this to selectively remove warnings? I stumbled across this issue while dealing with a similar problem for a library I maintain, its just something I wanted to think about 🤔.

I don't see a **_huge_** issue with it, and it makes it pretty clear that you are explicitly ignoring a class of warnings.

```javascript
process.removeAllListeners('warning');
process.on('warning', (l) => {
  if (l.name !== 'ExperimentalWarning') {
	console.warn(l)
  }
});

fetch('some-url').catch(() => {});
```

**Comment by tinfoil-knight** [comment]
@AgentEnder Considering that `process` is global, you'd end up hiding the warnings in any codebase where your library is used AFAIK. Seems slightly problematic to me.

**Comment by AgentEnder** [comment]
Huh, yeah that definitely makes sense. I think as the author of CLI tooling, that should be fine, just not as a library-type dependency.

For instance, I work on Nx. If we were to do that I think it'd be fine (we don't need to right now of course), but I wouldn't want a plugin author to do that.

**Comment by Azzedine-zemmari** [comment]
hy i have the same problem but where should I pass --no-warnings
