### ISSUE TITLE
Flaky tests umbrella ☂️

### ISSUE THREAD

**Issue by danez** [netlify/cli#4625]
Our tests are failing from time to time with different errors. These errors are unrelated to the actual changes in PRs.

As a first step, I thought it would be a good idea to collect these errors.

- Add errors as separate comments.
- Add logs where this happened to the comment. (I guess maximum 5 or so)

**Comment by danez** [comment]
> Error: listen EADDRINUSE: address already in use :::\<PORT\>

https://github.com/netlify/cli/runs/6597781685?check_suite_focus=true

**Comment by danez** [comment]
> yarn → should install the cli and run the help command
  ✖ Timed out while running tests

https://github.com/netlify/cli/runs/6598249957?check_suite_focus=true

**Comment by danez** [comment]
> EBUSY: resource busy or locked, rmdir ...

Windows

https://github.com/netlify/cli/runs/6612669436?check_suite_focus=true

**Comment by danez** [comment]
> Error: EPERM: operation not permitted, rename 'C:\\Users\\runneradmin\\AppData\\Roaming\\netlify\\Config\\config.json.3515056301' -> 'C:\\Users\\runneradmin\\AppData\\Roaming\\netlify\\Config\\config.json'`,

Windows

https://github.com/netlify/cli/runs/6612669436?check_suite_focus=true

**Comment by JWhist** [comment]
Eleventy test frequently fails with connection refused error

<img width="1004" alt="Screen Shot 2022-06-29 at 12 24 54 PM" src="https://user-images.githubusercontent.com/63815686/176487661-81f0a090-07df-46ea-a0ff-14ad79e599e7.png">

**Comment by danez** [comment]
Closing, it is a lot better now, and we should handle the ones that come up.
