### ISSUE TITLE
atfter canceling the batchi run  > npm install netfly-cli -g

### ISSUE THREAD

**Issue by Morazee** [netlify/cli#4636]
atfter canceling the batchi run  > npm install netfly-cli -g 
after that i run > ntl dev  , but didnt work?
![devrun](https://user-images.githubusercontent.com/100149661/170692211-534e4bfd-e05c-45bd-8ac7-20c0cde0408e.png)

_Originally posted by @Morazee in https://github.com/netlify/cli/issues/3242#issuecomment-1139539424_

**Comment by minivan** [comment]
Closing as stale
