### ISSUE TITLE
Terminal command netlify dev --live generating broken links

### ISSUE THREAD

**Issue by c-semaan** [netlify/cli#4656]
![image](https://user-images.githubusercontent.com/73475621/171252410-f58b036a-3050-48e0-9584-5df4ab3baa80.png)
![image](https://user-images.githubusercontent.com/73475621/171252478-94402c15-f9f1-4c75-95d6-8371df21f09f.png)

There seems to be an issue with generating links using `netlify dev --live`. It sometimes output the link as "netllify" or "netlifyy" as seen in the image attached. 

I search through my entire projected to see if i have mispelled netlify and everything seems to be find. Spend quite sometime pointlessly debugging just to notice this in the end.

**Comment by Skn0tt** [comment]
Hi! This is a super interesting bug 😲 Is there some specific thing you can do to reproduce this, or does this show up randomly? Also, is it only the *rendering* that's broken? Or are your functions also available under the misspelled endpoint?

**Comment by c-semaan** [comment]
I am on cli 8.16.1

### **Reproducing the issue:**
**First try:**
1. Opened the project in VScode
2. `Netlify build` in terminal
3. `Netlify dev --live` in terminal
-> Works as expected.
![image](https://user-images.githubusercontent.com/73475621/171408530-3201740b-adc3-4979-81c4-30cb568cdfe3.png)

**Second try:**
1. Again `Netlify dev --live` 
-> Works as expected
![image](https://user-images.githubusercontent.com/73475621/171408865-9c6a45a0-8f89-4987-8368-855d2101ca99.png)

**Third try:**
1. I split my screen in two windows. [ half google chrome, other half vscode]
2. `Netlify build` in terminal
3. `Netlify dev --live`
**-> Issue reproduced!**
![image](https://user-images.githubusercontent.com/73475621/171409638-9661315e-a13c-482a-9b0c-fc3331bf3c82.png)
![image](https://user-images.githubusercontent.com/73475621/171409716-7b36e6a0-6bb3-4033-8492-f64ea887308a.png)

### **"is it only the rendering that's broken? Or are your functions also available under the misspelled endpoint?"**
-> Functions works as expected when I manually correct the spelling mistakes in the links.

**Comment by Skn0tt** [comment]
Wow, what a riddle! This is interesting :D

What stands out to me is that in the first screenshot you share, the duplicated letter is always the last one before it wraps around to the next line. Could you try playing around with the terminal width to see if that's true always?
It kind of looks like a rendering bug in the terminal. I see you're on windows, what terminal is this (VS-Code builtin terminal/powershell/cmd.exe/something else)?

**Comment by Skn0tt** [comment]
@jackiewmacharia I see you worked on https://github.com/netlify/cli/issues/4311, do you have an idea what might be causing this?

**Comment by c-semaan** [comment]
### **Trying out different VScode width**

1. Width 1300x852
->Issue with links persists
![image](https://user-images.githubusercontent.com/73475621/171414918-24e6c978-8146-4d43-b972-1d6c0d2336dd.png)

2. Width 1530x943
-> No issue with links. **Even after resizing window!**
![image](https://user-images.githubusercontent.com/73475621/171415646-f19bbe9c-ebcc-434e-b2cf-d7c82d24fc24.png)
![image](https://user-images.githubusercontent.com/73475621/171416198-2687ce7f-cfe3-412f-b6e1-5b5372338767.png)

It seems that the issue occurs when there is a line break upon generating the link in correlation with the terminal width size.

**what terminal is this (VS-Code builtin terminal/powershell/cmd.exe/something else)?**
-> I am on VScode builtin terminal. 

Version: 1.67.2 (user setup)
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by serhalp** [comment]
Marking this as stale as it is several years old. Please feel free to reopen if you are still having issues.
