### ISSUE TITLE
gatsby detector fails with "npm run dev" script

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#466]
Hey! This works for me now, thanks so much!

One thing maybe for the documentation: I got an error on first run because I don't have an "npm run develop" script but an "npm run dev" script because I am lazy. Maybe other people are lazy like this & it should check for such a script?

But thanks again for something that seems like it could be really useful.

_Originally posted by @dbvisel in https://github.com/netlify/netlify-dev-plugin/issues/110#issuecomment-481940760_

**Comment by RaeesBhatti** [comment]
Seems like a user error. Please reopen if otherwise
