### ISSUE TITLE
DX: No publish folder error message

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#470]
When running latest create-react-app I ran into this error:

```
[Netlify Dev] No dev server detected, using simple static server
[Netlify Dev] Unable to determine public folder for the dev server.
 Setup a netlify.toml file with a [dev] section to specify your dev server settings.
```

The real issue was no `publish` directory defined in the netlify.toml file

After adding the `publish` directory this error goes away and everything works 😁

Small DX update, we should show an error that addresses "No publish dir found in netlify.toml, please add and run `netlify dev` again"

See video: https://drive.google.com/a/netlify.com/file/d/1u1IO_rMFyeHYQAhOthGgEPKPXuLJu-0R/view?usp=drivesdk

**Comment by erezrokah** [comment]
I believe `create-react-app` now works out of the box and I believe `netlify dev` also works without a publish directory configured.
Please comment if you experience otherwise
