### ISSUE TITLE
Nuxt HMR not working

### ISSUE THREAD

**Issue by mkummer225** [netlify/cli#4727]
### Describe the bug

Nuxt Hot Module Reloading not being passed through the proxy – pages reload on port :3000 but do not auto reload on netlify-cli's proxy :8888

Noticed this when upgrading netlify-cli from 9.16.0 to the latest 10.6.0

Also tested 10.5.0 with the same result (HMR not working on netlify's port :8888), rolled back to 9.16.7 and it's working again

### Steps to reproduce

netlify dev

### Environment

  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  npmGlobalPackages:
    netlify-cli: 10.6.0
    @nuxt/cli v2.15.8

**Comment by tinfoil-knight** [comment]
@mkummer225 Please update `netlify-cli` to `v12.1.0`. HMR should work for Nuxt now.

---
Note for maintainers: This issue was fixed in https://github.com/netlify/cli/pull/5200
