### ISSUE TITLE
functions NODE_ENV === production

### ISSUE THREAD

**Issue by kentcdodds** [netlify/cli#473]
Ok, so here's a bit of an issue that I think will confuse a lot of people: `netlify dev` actually runs as if everything's in production (NODE_ENV=production), BUT it runs your `develop` script rather than your `start` script.

This is problematic because I expect to be able to run everything in development (like NODE_ENV=development) because the script is called `dev` and it runs my `develop` script. So it's confusing that my functions would run with NODE_ENV=production.

Does that make sense? I think this could probably be resolved if `netlify dev` just basically replaced `netlify-lambda` and ran the `netlify-lambda serve` script for me. What would be best is if `netlify dev` could find the script in my `package.json` that runs `netlify-lambda serve` and just run that, because my scripts looks like this:

```
"functions:build": "netlify-lambda build netlify/functions",
"functions:dev": "dotenv -e ./netlify/.env netlify-lambda serve netlify/functions",
```

If `netlify dev` just found the script that runs `netlify-lambda serve` and ran that, then I think this issue would be resolved as would netlify/netlify-dev-plugin#61 and netlify/netlify-dev-plugin#60.

**Comment by tysonmatanich** [comment]
When I running `netlify dev`, `process.env.NODE_ENV` is always `undefined`. I would expect `netlify dev` to set it to `'development'`. I would also expect other [Netlify build environment variables](https://docs.netlify.com/configure-builds/environment-variables/) to get set such as `CONTEXT`.

**Comment by eduardoboucas** [comment]
Hi! I wanted to share a couple of updates on the items mentioned in this issue.

> I would expect netlify dev to set it to 'development'. I would also expect other Netlify build environment variables to get set such as CONTEXT.

@tysonmatanich This should be available in the latest version of CLI.

> Even with the following,
>
> ```
> [build.environment]
>   NODE_ENV="development"
> ```

@jonathan-mothership variables declared in `build.environment` are now picked up by `netlify dev`.

---

As for making `NODE_ENV=development` by default, it's something we're looking into and we'll update this issue as soon as there's any progress there.

Thanks all!

**Comment by erezrokah** [comment]
Adding more context to clear up confusion.
1. `netlify-lambda` uses Webpack under the hood. Webpack inlines environments variables so `netlify dev` cannot override them. As a workaround you can use a [custom Webpack config](https://github.com/netlify/netlify-lambda#webpack-configuration):
```js
const webpack = require('webpack');

module.exports = {
  plugins: [
    new webpack.DefinePlugin({
      // mirror Netlify Dev envs
      ...process.env,
      // force NODE_ENV to 'development'
      NODE_ENV: 'development',
    }),
  ],
};
```

2. The current default for `NODE_ENV` is `undefined` for both `netlify dev` and our production environment, so I'm inclined to keep it that way.

I'll keep this issue open for a bit to allow more feedback.

**Comment by erezrokah** [comment]
> I'll keep this issue open for a bit to allow more feedback

Closing the issue. We're still open for feedback so please comment if you feel this is something we should change.

**Comment by BiskremMuhammad** [comment]
I added a custom env var to come over this issue on Environment variables sections so i called it: `NEXT_PUBLIC_NETLIFY_NODE_ENV` and added different values depending on `deploy context`
