### ISSUE TITLE
split out detectors and templates, invite contributors

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#476]
(slack mention: https://netlify.slack.com/archives/CGW2Y6XPH/p1553102448110100)

we dont want to re-release the CLI and netliy dev plugin every time we add a new detector (or template).

we should use https://www.npmjs.com/package/live-plugin-manager or https://www.npmjs.com/package/pacote to make this scale.

however we should also have some consideration for offline dev experience.

**Comment by erezrokah** [comment]
Closing in favor of https://github.com/netlify/cli/issues/1495
