### ISSUE TITLE
Incorrect local ports in links generated by Hugo SSG

### ISSUE THREAD

**Issue by calavera** [netlify/cli#477]
Steps to reproduce:

1. Start with a Hugo project, its default local port is 1313.
2. Create an html that includes a link to other page.
3. Run `netlify dev`.
4. Try browsing through the link.

Current behavior:

You'll get redirected to `http://localhost:1313`

Expected behavior:

You continue browsing the site under `http://localhost:8888`

**Comment by erezrokah** [comment]
FYI, this requires using `.RelPermalink` instead of `.Permalink` in Hugo templates

**Comment by sarahetter** [comment]
Closing as stale
