### ISSUE TITLE
Support role based access control w/JWT's

### ISSUE THREAD

**Issue by fool** [netlify/cli#479]
**- Do you want to request a *feature* or report a *bug*?**

feature

**- What is the current behavior?**

it is impossible to test JWT site behavior using netlify-dev

**- If the current behavior is a bug, please provide the steps to reproduce.**

Set up redirects with a `Role=x` condition and observe that things do not work as expected.

**- What is the expected behavior?**

Redirects with a `Role=x` specification should work as expected.

**- Please mention your node.js, and operating system version.**

all versions.

**Comment by calavera** [comment]
I'm going to close this one in favor of #529 because that issue has more information.
