### ISSUE TITLE
/functions/fauna-graphql/sync-schema.js no worky out of boxy

### ISSUE THREAD

**Issue by PaulKElliott** [netlify/cli#481]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
When calling:
netlify dev:exec ./functions/fauna-graphql/sync-schema.js
I get a "Invalid authorization header." response.

Changed line 26 from 
headers: { Authorization }
to this
headers: { "Authorization": "Basic " + Authorization }
fixes things.

**Comment by sw-yx** [comment]
can you upgrade your version? this pr fixe dit https://github.com/netlify/netlify-dev-plugin/pull/238
