### ISSUE TITLE
Merge netlify-lm-plugin into this repo

### ISSUE THREAD

**Issue by calavera** [netlify/cli#483]
We should merge https://github.com/netlify/netlify-lm-plugin into this repository like we already did with netlify-dev-plugin in #396. It'd be easier to maintain that way.

**Comment by DavidWells** [comment]
Sounds good to me.

Idk it the `ts` will play nicely with the rest of the repo tho

**Comment by verythorough** [comment]
Adding the `needs docs` label in case the new plugin location affects the [Large Media installation docs](https://www.netlify.com/docs/large-media/#enabling-netlify-large-media).
