### ISSUE TITLE
Sync git remote parsing logic

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#486]
Issue with git remote parsing logic

0. User has a private bitbucket server, with .git/config remote:  url = ssh://git@bitbucket.companyxyz.com/~steve.steve/netlify-test.git

1. user uses `netlify init --manual` and we create a repo with a bad spec:  Repo.path is set to ~steve.steve/netlify-test.git meaning we don't try to reach his server when cloning and fail

2. user uses `netlify sites:create --manual --with-ci` and it works correctly, setting Repo.path to git@bitbucket.companyxyz.com:~steve.steve/netlify-test.git which works well.

---

It would appear that `init` and `sites:create` are using a slightly different `git remote` parsing mechanism. 

one uses `parseGitRemote` https://github.com/netlify/cli/blob/master/src/commands/sites/create.js#L119 looks like its working and the other uses `getRepoData` https://github.com/netlify/cli/blob/master/src/commands/init.js#L61 which appears to not be working

The git remote parsing logic appears to be different for each. 

It appears that the parsing logic for `netlify sites:create --manual --with-ci` is working correctly in the scenario above

**Comment by DavidWells** [comment]
The `repo_path` is added from prompt here https://github.com/netlify/cli/blob/master/src/commands/sites/create.js#L122 in the working path.

It's not added in this https://github.com/netlify/cli/blob/master/src/commands/init.js#L61 init flow

**Comment by verythorough** [comment]
Related: https://github.com/netlify/cli/issues/233

**Comment by Thms-Brnrd** [comment]
Hi, this issue with git remote parsing logic remains problematic in some cases. We have an existing production website, self-hosted on a private GitLab and running on Netlify, and we deploy using Netlify CLI. We would like to connect our repository to Netlify to use Deploy Previews but the `netlify init --manual` command can't reach our GitLab server.
Everything is working fine for our production website so a new site creation is not really an option for us.
I agree with @zachhardesty7, a repository link edit via UI would be very usefull in this case :)

**Comment by verythorough** [comment]
@zachhardesty7 or @Thms-Brnrd can you explain what you mean by "a way to modify the repo link via UI"?

**Comment by zachhardesty7** [comment]
@verythorough if I remember this issue correctly, I ran into the [same problem as here](https://github.com/netlify/cli/issues/233#issuecomment-460119792). `netlify init --manual` leaves out the host and username needed for the repo to work. The ability to change the "Repository" link in the `/settings/deploys#continuous-deployment` settings would at least help mitigate this issue.

**Comment by verythorough** [comment]
Ah, I see what you mean now. However, since that UI field is directly connected to the "automatic" setup for continuous deployment, I think that would actually be a much bigger change than fixing the bug in this issue.

In the end, maintaining two different commands that do essentially the same thing doesn't really make sense. I suspect that the best path forward is to make sure `sites:create` includes all of the functionality of `init` and then gradually deprecate `init`.

**Comment by zachhardesty7** [comment]
@verythorough I agree. Having both commands is mostly just confusing.

Idea: instead of the ability to change the link, creating a CI-enabled site via arbitrary Git URL on the "/start" page would also alleviate the issue. Currently it just shows the big three online repos, but since it appears that Netlify supports any git-based VCS repo, a field to enter a link would be nice.

**Comment by verythorough** [comment]
@zachhardesty7 It turns out we have an internal feature request filed for that very thing! I've added a link to your comment for tracking.

**Comment by rhtenhove** [comment]
Came across this very problem today; it's still a thing with CLI `netlify-cli/17.16.2 wsl-x64 node-v20.11.1`. After some frustrating steps, the `--manual --with-ci` parsed the correct repo path, and allowed changing it. I'll remember to use this from now on.

This is the first time though, as in previous attempts, `init` parsed the path correctly. Not sure what is different.

**Comment by rhtenhove** [comment]
I celebrated too early; the initial build indeed pulled the correct repo, however after a `git push` with some small changes, the repo url had changed again to the faulty one with just the project path.

It appears the CLI does have the ability to change the repo url. Would love to have control over its choices!
