### ISSUE TITLE
Huge increase in install size

### ISSUE THREAD

**Issue by XhmikosR** [netlify/cli#494]
https://packagephobia.now.sh/result?p=netlify-cli

v2.12.0: 79.7 MB
v2.13.0: 117 MB

Also, you guys even have husky listed in dependencies which results to errors when installing via npm. Not sure if there are even more devDependencies listed wrongfully in dependencies.

**Comment by XhmikosR** [comment]
There's definitely more devDependencies wrongfully listed in dependencies after v2.12.0.

https://github.com/netlify/cli/compare/v2.12.0...v2.13.0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R61-R134

lint-staged, mocha, chai probably too.

**Comment by snario** [comment]
As of 2.30.0 it seems to be 151.3M, the largest dependency in our project by a factor of 5. Any plans on shrinking it down?

**Comment by XhmikosR** [comment]
v2.41.0 was 219MB 😛 https://packagephobia.now.sh/result?p=netlify-cli@2.41.0

TBH this is a very serious situation security-wise also. The more packages one depends on, the bigger the risk all people who use the netlify-cli package are put into.

**Comment by RaeesBhatti** [comment]
We want to be minimal with dependencies and package size but compared to other issues this one is not a priority right now. We understand that this is not optimal. And since this is an open-source project, we would invite you (the community) to help us fix it. If you can create a PR to optimize dependencies or reduce package size in general. We would gladly accept it.

**Comment by XhmikosR** [comment]
An increase happened again recently :/

https://packagephobia.com/result?p=netlify-cli

There are plenty of unmet dependencies, vulnerable ones etc. This issue should be higher priority for sure.

**Comment by erezrokah** [comment]
Thank @XhmikosR, the latest bump is probably due to https://github.com/netlify/cli/pull/1469.
Don't think that's a major concern at the moment as the binary files (which are contributing to the size increase) are `optionalDependencies` so you'd only get the one that matches your platform.

For vulnerable ones we have https://github.com/netlify/cli/issues/1497 which we are currently looking into as a part of https://github.com/netlify/netlify-plugin-edge-handlers/issues/97.
If you know of more can you please open specific issues for those?

I opened 2 issues regarding unmet and deprecated ones:
https://github.com/netlify/cli/issues/1527
https://github.com/netlify/cli/issues/1528

**Comment by XhmikosR** [comment]
TBH at this point I care about the size. 231MB and counting. With so many dependencies, the chances of something going wrong are too many. It's just so many bytes wasted, it takes minutes to install on my VM. It's just not a a good sign for the package.

* https://packagephobia.com/result?p=netlify-cli
* https://npm.anvaka.com/#/view/2d/netlify-cli

**Comment by XhmikosR** [comment]
Also, https://lgtm.com/projects/g/netlify/cli?mode=list. Personally I'd add [CodeQL](https://github.com/github/codeql-action) too.

**Comment by XhmikosR** [comment]
>3.4.3 | Publish Size: 575 kB | Install Size: **236 MB** | Publish Date: 2021-01-26 | Publish Files: 287 | Install Files: **22761**

And the size keeps increasing. With every release, more packages are added, the bigger the size and the risk something goes wrong in one of the dependencies...

**Comment by eduardoboucas** [comment]
Hi @XhmikosR. Can you share some more details about any limitation you're experiencing? We haven't added any new dependencies in a while, and when we do, we're very rigorous about the vetting process to ensure code quality and good security practices.

If you have any additional concerns, or you have suggestions about a specific aspect of the codebase or any dependency we're using, feel free to reopen the issue or create a new one. Until then, I'll close this one.

Thanks for your input!

**Comment by XhmikosR** [comment]
Well, I can't reopen the issue myself since you closed it...

There's nothing more to add to the issue itself; netlify-cli is ~236MB, needs ~22.7K files to install, it takes a long time to do so (more than 90s on a Windows 10 machine with an NVMe driver), and poses a pretty big security risk due to the number of dependencies.

Now, you may choose to close the issue, but the gist remains the same.

**Comment by corneliusroemer** [comment]
In November 2023 it's 281 MB and 48,028 files

**Comment by westonsoftware** [comment]
Any tips on speeding this up?  It recently took up 7mins of my build time ...

2025-02-25T20:01:48.6115825Z ==============================================================================
2025-02-25T20:01:48.6115983Z Task         : Install Netlify CLI
2025-02-25T20:01:48.6116087Z Description  : Install Netlify CLI
2025-02-25T20:01:48.6116179Z Version      : 1.0.0
2025-02-25T20:01:48.6116256Z Author       : Justin Yoo
2025-02-25T20:01:48.6117031Z Help         : This installs the netlify-cli
2025-02-25T20:01:48.6117127Z ==============================================================================
2025-02-25T20:01:49.1347559Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" install -g netlify-cli"
2025-02-25T20:03:49.0660200Z npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
2025-02-25T20:03:49.0661745Z npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
2025-02-25T20:03:49.3164372Z npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
2025-02-25T20:09:00.1415135Z 
2025-02-25T20:09:00.1417471Z added 1218 packages in 7m
2025-02-25T20:09:00.1417931Z

**Comment by serhalp** [comment]
We've actually just started work on making the package smaller (by shrinking its dependency tree), so expect some improvements in the coming months.

Are you running this on a CI platform? You should be able to cache the installed package for a good performance boost. You'll have to check your specific CI platform's docs for how to do that.
