### ISSUE TITLE
Improved automatic framework support in `ntl build`

### ISSUE THREAD

**Issue by ascorbic** [netlify/cli#4948]
### Which problem is this feature request solving?

Currently running `ntl dev` in an unliked project has a good experience: it detects the framework and runs the correct command. However this is not true for `ntl build`. First, it won't allow the site to build without `--offline`, and it doesn't do framework build command detection or build plugin installation. This means it's not possible to build a site without either creating a toml or linking the site. This adds friction for users trying out builds.

### Describe the solution you'd like

`ntl build` should behave like `ntl dev`. It should run even if the site is unlinked, and it should use framework-info to detect settings - including auto-installing plugins.

### Pull request (optional)

- [ ] I can submit a pull request.

**Comment by eduardoboucas** [comment]
@ascorbic I believe this can be closed now?

**Comment by ascorbic** [comment]
No, this still won't work, but it's less critical now that `dev` handles plugins. One for later. What I want is the `ntl build` experience to be just as good!
