### ISSUE TITLE
Offer autocomplete and sort alphabetically for Netlify Link command

### ISSUE THREAD

**Issue by swyxio** [netlify/cli#496]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**

currently when you `netlify link` and pick from your list of sites, you have to scroll through ALLLLLLL your sites to find the site you want, and it is sorted by creation order not alphabetically

**- What is the expected behavior?**

show most recent 5, but also sort sites alphabetically, and also offer autocomplete

the relevant code to edit is here https://github.com/netlify/cli/blob/58ec7f07adb03821724da45c15dec42b9b23d1eb/src/utils/link/link-by-prompt.js#L93-98

**Comment by verythorough** [comment]
It doesn't _quite_ have autocomplete, but v2.11.23 had the ability to search by partial site name. It was lost when the "choose from a list" option was introduced in #335. 

If running v2.11.13, choose the "site name" option for `netlify link`, then type a partial site name and hit enter. You'll get a list of matches to select from — just like the Netlify UI, actually. Unfortunately, the prompt didn't really indicate that it was a search or that you could type a partial name, so I don't think people realized this was possible.

**Comment by verythorough** [comment]
@sw-yx Created #502 to bring back (and more clearly explain) the "search by site name" option, if you're curious.

**Comment by sw-yx** [comment]
i saw. v nice!

**Comment by sarahetter** [comment]
Closing as stale
