### ISSUE TITLE
netlify link doesn't recognize sites in different teams

### ISSUE THREAD

**Issue by raeesbhatti** [netlify/cli#498]
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
`netlify link` doesn't recognize a site in non-default team.
**- If the current behavior is a bug, please provide the steps to reproduce.**
* Have a site in a friend's team where you're added as a collaborator
* `netlify link`
* It will not recognize the Netlify site and error out

**- What is the expected behavior?**
`netlify link` should recognize sites in all teams I'm a member of.
**- Local Environment Information**
Paste the results of `netlify status --info` here
```
›   Error: Unexpected argument: --info
›   See more help with --help
```

**Comment by verythorough** [comment]
This happens because the `listSites()` calls in `link-by-prompt.js` don't have the `filter: 'all'` parameter set. I'm working on a quick PR that includes this fix, plus a partial fix for #496.
