### ISSUE TITLE
netlify status --info is invalid command

### ISSUE THREAD

**Issue by raeesbhatti** [netlify/cli#499]
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
`netlify status --info` errors out the following
```
 ›   Error: Unexpected argument: --info
 ›   See more help with --help
```
**- If the current behavior is a bug, please provide the steps to reproduce.**
`netlify status --info`
**- What is the expected behavior?**
It should print out information about the local environment.
**- Local Environment Information**
Paste the results of `netlify status --info` here
That is why the bug is about!

**Comment by DavidWells** [comment]
```
netlify status --help
```

Are you looking for `netlify status --verbose`?

**Comment by DavidWells** [comment]
Fixed in github issue template pointing to `netlify status --verbose`
