### ISSUE TITLE
Netlify deploy command parameter --prod doesn't work properly

### ISSUE THREAD

**Issue by ansidev** [netlify/cli#4997]
### Describe the bug

I want to deploy the `dist/` folder as a prod/preview site based on an environment variable PROD:
- export PROD=true => Deploy to main site
- export PROD=false => Deploy to preview site

But if I run

```
netlify deploy -a ${NETLIFY_ACCESS_TOKEN} -s ${NETLIFY_SITE_ID} -d dist -m "Deploy" -p ${PROD}
```

Netlify will always deploy to the main site. The only way to deploy to the preview site is by removing -p from the command.

### Steps to reproduce

1. Install Netlify globally.
2. Get NETLIFY_ACCESS_TOKEN and NETLIFY_SITE_ID.
3. Run the following command:
```
export PROD=false && \
export NETLIFY_ACCESS_TOKEN=your_netlify_auth_token && \
export NETLIFY_SITE_ID=your_netlify_site_id
```
4. Run
```
netlify deploy -a ${NETLIFY_ACCESS_TOKEN} -s ${NETLIFY_SITE_ID} -d dist -m "Deploy" -p ${PROD}
```

Expected behavior: Netlify deploy to the preview site.
Actual behavior: Netlify deploy to the main site.

### Configuration

There is no file `netlify.toml`.

### Environment

  System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 63.61 MB / 16.00 GB
    Shell: 3.5.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm

**Comment by danez** [comment]
This is the expected behavior for a boolean flag. I do not think we want to change this, because this is the same behaviour for all boolean flags.
