### ISSUE TITLE
npm install error on termux

### ISSUE THREAD

**Issue by McJoe21** [netlify/cli#5019]
### Describe the bug

npm ERR! code FETCH_ERROR
npm ERR! errno FETCH_ERROR
npm ERR! invalid json response body at https://registry.npmjs.org/netlify-cli reason: Invalid response body while trying to fetch https://registry.npmjs.org/netlify-cli: EACCES: permission denied, link '/data/data/com.termux/files/home/.npm/_cacache/tmp/6abcf009' -> '/data/data/com.termux/files/home/.npm/_cacache/content-v2/sha512/7f/9a/042d49b88ee5a2396a4975cd40bb74569275cb475d96beaeaea2552b3a5908afca5b6764eccde7a1d6e017096491f58ffb9ff703e7cbe8563bcd5a500642'

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-09-04T13_16_58_143Z-debug-0.log

### Steps to reproduce

$ npm i netlify-cli -g

### Environment

termux

**Comment by ztroy** [comment]
Same issue during install @vue/cli

i tried a suggestion, but still not work : 
`npm clean cache --force`

**Comment by AnadeB** [comment]
Same here, package nodejs 18.7.0-1, (updated) npm 8.19.1.
I tried to downgrade npm:
`pkg reinstall nodejs`
`npm --version`
`8.15.0`
And it helped.

**Comment by anantaw81** [comment]
i'm installing @vue/cli via npm. It worked when using node v16.17.0 (npm v8.15.0). My device is pop os.

**Comment by Anhunghezo** [comment]
I have the same problem when using npx create-react-app

**Comment by chinzou** [comment]
I have the same issue when running:
```npx create-react-app my-app```

error message:
> npm ERR! invalid json response body at https://registry.npmjs.org/create-react-app reason: Invalid response body while trying to fetch https://registry.npmjs.org/create-react-app: EACCES: permission denied

**Comment by Dnmrk4** [comment]
I got the same problem creating a new react app today and used `sudo` and worked for me
`sudo create-react-app my-app`

**Comment by CriticalRange** [comment]
> 

This fixed it. Thank you
(Imagine updating things without thinking it would break :) )

**Comment by IoannisKarpasitis** [comment]
Hi, I have the same issue, tried everything but nothing works. Note that I am in Windows and I try running the terminal as administrator but with no avail.

**Comment by danez** [comment]
Please report this to termux or npm. I don't think we can do anything about this in the netlify-cli here.

**Comment by McJoe21** [comment]
```
/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/@netlify/esbuild/install.js:81
    throw new Error(`Unsupported platform: ${platformKey}`);
          ^

Error: Unsupported platform: android arm LE
    at pkgAndSubpathForCurrentPlatform (/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/@netlify/esbuild/install.js:81:11)
    at checkAndPreparePackage (/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/@netlify/esbuild/install.js:220:28)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/@netlify/esbuild/install.js:247:1)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

Latest version
