### ISSUE TITLE
Nextjs export step no longer working when build runs

### ISSUE THREAD

**Issue by omniphx** [netlify/cli#5043]
### Describe the bug

Export step no longer working when running `netlify build`

My build function is defined in my package.json as is suggested by [nextJS documentation](https://nextjs.org/docs/advanced-features/static-html-export):
```
{
    "build": "next build && next export",
}
```

It seems after version [v11.6.0](https://github.com/netlify/cli/releases/tag/v11.6.0), the export command is skipped.

### Steps to reproduce

Create a nextJS app with package.json defined as:
```
{
    "build": "next build && next export",
}
```

Run `netlify build`

### Configuration

[build.environment]
  NEXT_PUBLIC_IS_PR_PREVIEW = 'false'
  NODE_VERSION = '16'
[context.deploy-preview.environment]
  NEXT_PUBLIC_IS_PR_PREVIEW = 'true'

[dev]
  targetPort=4200

### Environment

System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 112.98 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  npmGlobalPackages:
    netlify-cli: 11.5.1

**Comment by m-jovanovic** [comment]
@omniphx Did you find any workaround? I'm also affected by this, my deploy pipeline is crashing.

It worked fine up to 5 days ago for me.

**Comment by m-jovanovic** [comment]
@tinfoil-knight I'm installing it in my deploy pipeline with `netlify-cli@latest`. When deploying, it's using `@netlify/build 27.18.4`

The trouble is when it reads the build command from `netlify.toml`, instead of using `next build && next export` it defaults to `next build` and then tries to publish from the default output folder which isn't there.

**Comment by tinfoil-knight** [comment]
@m-jovanovic Sorry for the delayed response.

I tried this out today with `netlify-cli/12.0.11` & `next/13.0.0`.

- Created the default app with `npx create-next-app@latest`
- Changed the `"build"` script in `package.json` to `next build && next export`
- Added a `netlify.toml` file with:

```
[build]
	command = "npm run build"
```


The static build is working for me. An `out` directory is created with all the files.
Can you update both `netlify-cli` & `next` and see if you're still experiencing the issue?

**Comment by m-jovanovic** [comment]
Hey @tinfoil-knight, it sorted itself out after a few days. Once one of the packages was updated.

**Comment by tinfoil-knight** [comment]
@omniphx Could you add the build command config in `netlify.toml` and check? In case of missing configuration, Netlify CLI might be defaulting to the `next build` command.

```toml
[build]
	command = "npm run build" # or something like "yarn build" as per your package manager
```

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
