### ISSUE TITLE
netlify cli 11.7.1

### ISSUE THREAD

**Issue by andremoreno** [netlify/cli#5050]
### Describe the bug

Updating to 11.7.1 and when i try using 'netlify build' it asking

? Multiple possible start commands found (Use arrow keys or type to search)
❯ [Hugo] 'hugo server -w'
  [Zola] 'zola serve'
  
and after i choose the first choice, it prompts me:

Add 'framework = "hugo"' to the [dev] section of your netlify.toml to avoid this selection prompt next time.

I try to add the 'framework = "hugo"' to my [dev] section, and the I dont have to choose the start commands..
? Multiple possible start commands found (Use arrow keys or type to search)

The build complete, but it doesnt minify the output.

I use netlify-plugin-inline-critical-css plugins, it says completed, but the output dont have inline css.

I dont have problems with version 11.5.1 

![netlify-cli-1171-capture](https://user-images.githubusercontent.com/142023/190324691-3ebe0568-ffd9-4a92-88b7-cabfc7cb7f03.jpg)

### Steps to reproduce

1. run 'npm i -g netlify-cli'
2. run 'netlify build'

### Configuration

[build]
  publish = "public"
  command = "hugo --gc --minify"

[dev]
  framework = "hugo"
  command = "hugo server --disableFastRender --gc --minify"

[deploy]
  command = "netlify deploy --prod --dir=public"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[plugins]]
  package = "netlify-plugin-inline-critical-css"

[[headers]]
  for = "/fonts/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

### Environment

$ npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli

  System:
    OS: Linux 4.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64         Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
    Memory: 5.83 GB / 15.96 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.19.1 - ~/.nvm/versions/node/v16.15.1/bin/npm
  npmGlobalPackages:
    netlify-cli: 11.7.1

**Comment by tinfoil-knight** [comment]
@andremoreno Is the repository you're working on public? If not, could you provide a minimal reproducible example?

**Comment by andremoreno** [comment]
@tinfoil-knight yes.. its public..

my repo is https://github.com/andremoreno/www.andremoreno.com
When I try the 'netlify build' it only shows:
`
────────────────────────────────────────────────────────────────
  1. build.command from netlify.toml
────────────────────────────────────────────────────────────────
​
$ hugo
Start building sites …
hugo v0.103.0-DEV-bef31b58aa4c43a4d36fc22397d2344136953f2f+extended linux/amd64 BuildDate=2022-09-01T10:34:57Z`


but when im trying to reproduce using this test repo : https://github.com/andremoreno/test
it working just fine... 
it shows "hugo --gc --minify"

something wrong with my netlify.toml maybe...

anyway, im updating to 11.8.3 and it seems solving the problem..
when im running the 'netlify build',
it shows build.command from netlify.toml
"hugo --gc --minify"

and the plugins is working too.
