### ISSUE TITLE
Redirect rule with US country condition blocks every country

### ISSUE THREAD

**Issue by hosainnet** [netlify/cli#5051]
### Describe the bug

When applying a redirect/rewrite rule that targets the US, the rule always triggers when even when accessing the site from outside the US locally.

This makes it difficult to locally when a site-wide rule is applied to block the US for example and the `--country` cli option does not override this behaviour.

### Steps to reproduce

1. Create a Netlify project from one of the templates (e.g Next.js Starter) 
2. Add the following configuration in netlify.toml

```
[[redirects]]
  from = "/"
  to = "/blocked.html"
  status = 200
  force = true
  conditions = {Country = ["US"]}
```
3. Run `netlify dev` 
4. Attempt to access `http://localhost:8888`

An example repo you can clone and run to replicate:  https://github.com/hosainnet/netlify-geo

Expected: you should be able to view the homepage

Result: you'll be served `/blocked.html` (assuming that file exists in the `public` folder)

A quick poke around suggests the rules-proxy https://github.com/netlify/cli/blob/main/src/utils/rules-proxy.js#L83 always fallsback to getCountry (hardcoded to US).

### Configuration

[[redirects]]
  from = "/"
  to = "/blocked.html"
  status = 200
  force = true
  conditions = {Country = ["US"]}

### Environment

N/A

**Comment by tinfoil-knight** [comment]
@hosainnet Is this happening only on Netlify CLI locally or are you getting the same behaviour on production deployments too?

**Comment by hosainnet** [comment]
> @hosainnet Is this happening only on Netlify CLI locally or are you getting the same behaviour on production deployments too?

This is only happening locally

**Comment by tinfoil-knight** [comment]
@hosainnet Thank you for reporting the issue.

The `dev` command will now respect the `--country` flag so you can properly test out country based redirects.

Update the `netlify-cli` package to `v12.0.1` for the fix.

**Comment by hosainnet** [comment]
> @hosainnet Thank you for reporting the issue.
> 
> The `dev` command will now respect the `--country` flag so you can properly test out country based redirects.
> 
> Update the `netlify-cli` package to `v12.0.1` for the fix.

Awesome that works, thank you so much!
