### ISSUE TITLE
`build` does not respect `command` nor `publish` settings when using a framework

### ISSUE THREAD

**Issue by damiencornu** [netlify/cli#5080]
### Describe the bug

I'm trying to run `netlify build` locally using netlify-cli on a project that was created with Create React App.
Now that the framework detection (#5029) is merged my custom settings are overwritten by the build.command and build.publish found by the `detectServerSettings` new method introduced. 

I have a custom "Build command" defined in the Netlify UI (and now in a local `netlify.toml` as well), I can see them being taken into account as per the `netlify build --debug` command but they later get overwritten afterwards.

Here's a look at parts of the build command with debug option output:

```
❯ Resolved config
build:
  command: echo 'Hello'
  commandOrigin: config

<Omitted>

────────────────────────────────────────────────────────────────
  Netlify Build
────────────────────────────────────────────────────────────────

<Omitted>

❯ Resolved config
  build:
    command: react-scripts build
    commandOrigin: config
```

The issue comes from framework detection block in the `lib/build.js`, more specifically there https://github.com/netlify/cli/blob/fc2030468cab8a402c544a702e03e8629d542313/src/lib/build.js#L80

When entering this block the config is as stated by the --debug
```
{
  environment: {},
  publish: '<local-path-on-my-machine>/build',
  publishOrigin: 'ui',
  processing: { css: {}, html: {}, images: {}, js: {} },
  services: {},
  command: "echo 'Hello'",
  commandOrigin: 'config',
  ignore: 'exit 0',
  base: undefined
}
```

And result in this config after going through the settings from framework detection being applied
```
{
  environment: {},
  publish: 'react-scripts build',
  publishOrigin: 'ui',
  processing: { css: {}, html: {}, images: {}, js: {} },
  services: {},
  command: 'react-scripts build',
  commandOrigin: 'config',
  ignore: 'exit 0',
  base: undefined
}
```

### Steps to reproduce

1. Create a repo using CRA (_could also be / Next.js / your framework of choice_. It's not CRA specific)
2. Modify the `build` command in your package.json / Netlify UI / netlify.toml
3. Launch `netlify build` locally

You'll see that the command being executed by the build is not the one you defined.

### Configuration

[build]
  command = "echo 'Hello'"

### Environment

System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 176.64 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  npmGlobalPackages:
    netlify-cli: 11.8.2

**Comment by tinfoil-knight** [comment]
@damiencornu Can you update the Netlify CLI package to the latest release (`v11.8.3`) & confirm if the issue is still occurring or if it has been resolved?

**Comment by damiencornu** [comment]
Yes, newer version did resolve my issue, closing the issue. Thank you for the quick fix @sarahetter!
Feel free to ping me if you need me to test the framework detection feature versus build workflow in the future.
