### ISSUE TITLE
`ntl deploy --build` fails without `netlify.toml` file

### ISSUE THREAD

**Issue by orinokai** [netlify/cli#5082]
### Describe the bug

Both `ntl dev` and `ntl build` now use framework detection to run correctly without a toml file.

However, while `ntl deploy --build` correctly detects the framework and runs the build successfully, it fails when trying to modify the `netlify.toml` when it doesn't exist:

`TypeError: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined`

The deploy function should create the toml file if it doesn't exist and the remove it again in the clean up (pending a better solution, as discussed in https://github.com/netlify/cli/issues/3906)

### Steps to reproduce

1. Init a new repo and install the `next` package
2. Create a `pages` folder with a minimal index.js page
3. Run `ntl deploy --build` and observe the above error
4. Create an empty `netlify.toml`, run `ntl deploy --build` again and observe the correct behaviour

### Environment

-

**Comment by tinfoil-knight** [comment]
Closing this as it has been fixed in the linked PR.
