### ISSUE TITLE
Broken SPA routing for assets

### ISSUE THREAD

**Issue by frederikheld** [netlify/cli#5085]
### Describe the bug

This has nothing to do with the CLI, it is an issue that occurs when I deploy my app to production on the Netlify platform. I don't know where else to put this, so I put it here.

Your [docs about SPA routing](https://docs.netlify.com/routing/redirects/rewrites-proxies/#history-pushstate-and-single-page-apps) (and all the default answers in your forums and tons of blog posts) state this as the simple solution for SPA routing:

```
/*    /index.html   200
```

After all I have read, this should work - but it doesn't.

I'm deploying a Vue3 app. After the build step, I have the following files in the `dist` directory (from which the app is being deployed):

```
dist/assets/index.3d0d314e.css
dist/assets/index.8eab93c6.js
dist/favicon.ico
dist/index.html
```

The following happens: If I enter the SPA via its root, the assets are being loaded correctly. If I enter it via `/some/path`, it tries to load the assets from `/assets/some/path`.

I tried to set the above redirect rule via `netlify.toml` (which I tried to put in the project root as well as in the `dist` directory), I tried it via a `_redirects` file in the `dist` directory. I even tried to do it GitHub Pages style with a custom `404.html` file that is a copy of `index.html`. I also tried it with Node 18.x and 16.x. None of those work. The only way my SPA is working correctly is if the user enters it from its root.

Am I doing something wrong here or is this a bug?

### Steps to reproduce

Build Vue3 app with vue-router
Test it locally --> routing works fine
Push it to GitHub repo
Create site on Netlify
Link it to the above GitHub repo
Configure automatic deploys
Push changes to repo
See how build and deployment is successful
Open site in browser
Browse around from https://example.netlify.app --> works fine
Enter via https://example.netlify.app/some/route --> doesn't load assets

### Configuration

```
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

#### NodeJS

NodeJS 18.x (I also tried with 16.x)

#### VueJS

"vue": "^3.2.38",
"vue-router": "^4.1.5"

#### Netlify Build Settings

Base Directory: client
Build command: npm run build (which executes the Vue3 default build routine `run-p type-check build-only`)
Publish Directory: client/dist
Builds: Activate builds

**Comment by frederikheld** [comment]
I'm not sure how Netlify handles Vue builds behind the scenes, but all the docs mention `vue-cli` ([1], [2]), but vue-cli is not used in Vue3 anymore in favor of `create-vue` ([3]).

[1]: https://docs.netlify.com/integrations/frameworks/
[2]: https://docs.netlify.com/integrations/frameworks/vue-cli/
[3]: https://cli.vuejs.org/guide/

**Comment by jasiqli** [comment]
> This has nothing to do with the CLI, it is an issue that occurs when I deploy my app to production on the Netlify platform. I don't know where else to put this, so I put it here.

The appropriate place is Netlify Forums: https://answers.netlify.com/

**Comment by sarahetter** [comment]
Closing as the correct place to post this is indeed https://answers.netlify.com/ :)
