### ISSUE TITLE
Netlify dev stuck in Miro React app (using Vite)

### ISSUE THREAD

**Issue by bennofatius** [netlify/cli#5182]
### Describe the bug

Trying to run `netlify dev` command with a Miro React app (which uses vite 3.0.3), it gets stuck at:

` vite preview

  ➜  Local:   http://localhost:4173/
  ➜  Network: use --host to expose
`

Based on researching this problem, I've already tried:
- using all kinds of different node versions (esp. 16, as suggested by many)
- using different targetPorts (such as 5173)

None of this helped. 
 

### Steps to reproduce

Create a new miro app with `npx create-miro-app@latest`
Link app to Netlify site
Run `netlify dev`

### Environment

 System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 205.95 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  npmPackages:
    netlify-cli: ^12.0.11 => 12.0.11

**Comment by tinfoil-knight** [comment]
@bennofatius Could you try using `netlify dev --command "npm run start"` & see if that works for you.

The CLI seems to be auto-detecting `vite` as the framework & applying its settings which is causing the issue.

---
You can specify the command permanently in the `netlify.toml` configuration file like this:
```
[dev]
	command = "npm run start"
```

See https://docs.netlify.com/configure-builds/file-based-configuration/ for more info on configuration.

**Comment by bennofatius** [comment]
Hi, thanks for replying! This did not solve the issue – still stuck at:

> vite preview

  ➜  Local:   http://localhost:4173/
  ➜  Network: use --host to expose
  
 I can open the Vite preview at port 4173, but it's supposed to proceed to hosting on port 8888 with Netlify function injected, no?

**Comment by tinfoil-knight** [comment]
@bennofatius You shouldn't be getting the `vite preview` command in the logs. 

```json
"scripts": {
    "start": "vite",
    "build": "vite build",
    "serve": "vite preview"
  }
```
^Creating the new miro app produce a `package.json` file with the `scripts` section as above. 

The `vite preview` command doesn't really work for me (even without Netlify CLI) but the `vite` command works fine.

Using `netlify dev --command "npm run start"` should cause only the `vite` command to run & not `vite preview`.

Can you check the configuration in the `package.json` once again & try out `netlify dev --command "npm run start"`?

**Comment by bennofatius** [comment]
It's working now, thank you! Oddly enough my "scripts" were defined like that already, but may have been unsaved?  So the combination of setting the "scripts" in package.jso as mentioned above, and using "netlify dev --command "npm run start", solves this issue.

**Comment by tinfoil-knight** [comment]
@nickytonline

This issue was mainly occurring because framework detection was recognising it as `Vite` & suggesting `npm run serve` as the dev command due to the order here: 

https://github.com/netlify/framework-info/blob/6e19105dbef40c75f55004376ee8baa56a071674/src/dev.js#L61-L64

Weekly downloads for [create-miro-app](https://www.npmjs.com/package/create-miro-app) seem very low so I'm letting this issue stay closed unless you think we should create a fix in https://github.com/netlify/framework-info for this.
