### ISSUE TITLE
Error upon serverless function trigger in netlify dev

### ISSUE THREAD

**Issue by yplaxma** [netlify/cli#5183]
### Describe the bug

In a netlify dev environment, whenever one of the serverless functions is triggered I get:
`Request from ::1: GET /.netlify/functions/posts`

Followed by
`C:\Users\...\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\netlify-redirector\lib\redirects.js:1`

Then a string of the file itself (redirects.js, no need to put the whole thing here I think)
Then:
```
NestedError: Cannot read from `C:/Users/.../project_name/node_modules/.prisma`: EISDIR: illegal operation on a directory, read
    at Object.exports.createReadStream (C:\Users\...\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\cp-file\fs.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at cpFileAsync (C:\Users\...\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\cp-file\index.js:14:21)
    at C:\Users\...\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\p-map\index.js:57:22
Caused By: Error: EISDIR: illegal operation on a directory, read {
  nested: [Error: EISDIR: illegal operation on a directory, read] {
    errno: -4068,
    code: 'EISDIR',
    syscall: 'read'
  },
  errno: -4068,
  code: 'EISDIR',
  syscall: 'read',
  name: 'CpFileError'
}
```

### Steps to reproduce

1. Clone https://github.com/jlengstorf/prisma-serverless-planetscale-netlify
2. npm i
3. Add .env with a `DATABASE_URL = connect prisma link from planetscale`
4. Remove `shadowDatabaseUrl    = env("SHADOW_DATABASE_URL")` from schema.prisma
5. `netlify dev` OR `netlify dev --targetPort 5173` if you don't use the repo above because netlify dev expects vite to use port 3000 for some reason (it's not a problem in the repo above since it uses older package versions but with updated ones it's a problem)

### Environment

System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 5.33 GB / 11.91 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE      
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD

**Comment by danez** [comment]
I got it working by updating all dependencies (especially prisma) 

```diff
diff --git a/package.json b/package.json
index e390a13..bb6dfa6 100644
--- a/package.json
+++ b/package.json
@@ -7,13 +7,13 @@
     "serve": "vite preview"
   },
   "dependencies": {
-    "@prisma/client": "^3.4.2",
-    "preact": "^10.5.13"
+    "@prisma/client": "^4.5.0",
+    "preact": "^10.11.2"
   },
   "devDependencies": {
-    "@preact/preset-vite": "^2.0.0",
-    "prisma": "^3.4.2",
-    "typescript": "^4.3.2",
-    "vite": "^2.6.4"
+    "@preact/preset-vite": "^2.4.0",
+    "prisma": "^4.5.0",
+    "typescript": "^4.8.4",
+    "vite": "^3.1.8"
   }
 }
```

And also running `npm exec prisma migrate deploy` before running netlify dev to initialize the database.

Let me know if that helps.

**Comment by janpio** [comment]
We at Prisma have 2 reports of this `netlify dev` behavior as well: https://github.com/prisma/prisma/issues/16708 and https://github.com/prisma/prisma/issues/16021 Seems both users are on Windows (as is @yplaxma above). I tried to reproduce on Windows as well, but could not with the provided reproduction one user claims is failing for him. 

Could you reproduce this here @danez before you updated the dependencies?

From our (Prisma's) side we are pretty clueless what could be going on.
