### ISSUE TITLE
Starting Netlify Dev with Hydrogen is stucked on Waiting for framework port 3000 

### ISSUE THREAD

**Issue by sajanbasnet75** [netlify/cli#5201]
### Describe the bug

after running netlify dev for a hydrogen project it gets stuck

![Screenshot from 2022-11-03 19-40-14](https://user-images.githubusercontent.com/22407698/199740767-dd41c812-f872-4f03-a471-3e6e63946a41.png)

```netlify-cli/12.0.11 linux-x64 node-v16.17.1```

same problem if i do netlify dev --targetPort 3000

``` It works if I run , yarn run dev and netlify dev in parallel```

### Steps to reproduce

1. run netlify dev in terminal

### Configuration

[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "public"

### Environment

  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 1.92 GB / 7.66 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /media/john/externals/FetchlyProjects/hydra-core/node_modules/.bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  npmGlobalPackages:
    netlify-cli: 12.0.11

**Comment by tinfoil-knight** [comment]
Hey @sajanbasnet75, I tried using `netlify dev` with a hydrogen project & it was working fine for me. 

Is the repository you're working on public? If not, could you create a minimal reproducible example to help me debug the issue you're facing?

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
