### ISSUE TITLE
refactor all js function templates to use async/await syntax

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#522]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**

some of our [function templates](https://github.com/netlify/cli/tree/master/src/functions-templates/js) use the legacy callback syntax (`(event, context, callback)`) for AWS Lambda.  ([example](https://github.com/netlify/cli/blob/a0160b1b98352914b3818af891c5f8ae15cf4db6/src/functions-templates/js/slack-rate-limit/slack-rate-limit.js))

this isn't something we should encourage as it leads to more complicated code. We should refactor to more modern async/await syntax (`async (event, context)`). ([example](https://github.com/netlify/cli/blob/a0160b1b98352914b3818af891c5f8ae15cf4db6/src/functions-templates/js/stripe-subscription/stripe-subscription.js))

**Comment by arpitbatra123** [comment]
Hey. Can I work on this?

**Comment by sw-yx** [comment]
be my guest!

**Comment by arpitbatra123** [comment]
I opened a WIP PR here: https://github.com/netlify/cli/pull/576. Can you please review and tell me whether I'm going in the right direction? Also, have we written tests for the function templates?

**Comment by sw-yx** [comment]
hi! yes you are! thanks for contributing! no there are currently no automated tests for the function templates, we just try them out manually with `netlify functions:invoke`

**Comment by Esacpe-beep** [comment]
？

**Comment by arpitbatra123** [comment]
Hey @Esacpe-beep , Unfortunately, I am no longer working on this.

**Comment by erezrokah** [comment]
Fixed via https://github.com/netlify/cli/pull/1494
