### ISSUE TITLE
ntl dev fails in cli 12.1.1

### ISSUE THREAD

**Issue by SteveALee** [netlify/cli#5221]
### Describe the bug

Any attempt to build `ntl dev` with 12.1.1 results in error. works fine ins 12.1.0

```
◈ Netlify Dev ◈
◈ Injected netlify.toml file env var: RUBY_VERSION
◈ Injected site settings env var: GITHUB_PAT
◈ Injected site settings env var: NODE_ENV
◈ Ignored general context env var: LANG (defined in process)
◈ Cannot read properties of undefined (reading 'dev')
```

Here's an example [netlify.toml](https://github.com/w3c/wai-authoring-tools-list/blob/master/netlify.toml)

### Steps to reproduce

grab the repo linked above and run `ntl dev`

### Configuration

see above

### Environment

see above

**Comment by danez** [comment]
This is fixed in 12.2.6
