### ISSUE TITLE
7 severe vulnerabilities 

### ISSUE THREAD

**Issue by maxmillionbeatz** [netlify/cli#5234]
### Describe the bug

version 12.2.0 is giving me a bunch of severe vulnerabilities after adding the pack.

### Steps to reproduce

1.) npm install netlify-cli --save-dev

### Environment

  System:
    OS: macOS 12.3.1
    CPU: (8) x64 Apple M1
    Memory: 34.59 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.4.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  npmPackages:
    netlify-cli: ^2.37.0 => 2.37.0

**Comment by danez** [comment]
This is an issue we are aware of, see #4921
