### ISSUE TITLE
Respect XDG Base Directory Specification

### ISSUE THREAD

**Issue by psnszsn** [netlify/cli#526]
Netlify CLI should use `$XDG_CONFIG_HOME/netlify`(or `~/.config/netlify` if `$XDG_CONFIG_HOME` is not set) instead of `~/.netlify ` to store config files.
This keeps users' home directories clean of dotfiles. It is being widely adopted by Linux/BSD applications.

See https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html for more info.

**Comment by JGAntunes** [comment]
Hey folks, this has been addressed in #1725 and is part of the `3.3.0` release 👍
