### ISSUE TITLE
Don't suggest `svelte-kit build` in `netlify init`

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#5280]
### Describe the bug

when i `netlify init` on a new sveltekit project, there is this suggestion to add `netlify init` as the build command.

but it is no longer supported:

![image](https://user-images.githubusercontent.com/6764957/204200315-aaa79945-d422-4ce8-9204-af7957ea86af.png)

### Steps to reproduce

1. init  new sveltekit project
2. ntl init
3. take all default suggestion
4. see it fail

https://app.netlify.com/sites/repro-sveltekit-adapter-bug-72/deploys/638445041f565909c0878b66

### Configuration

n/a

### Environment

n/a

**Comment by brittneypostma** [comment]
I believe this is coming from [this line](https://github.com/netlify/framework-info/blob/main/src/frameworks/svelte-kit.json#L17) and needs to be updated.

**Comment by sw-yx** [comment]
i realized i was using netlify cli v11.5 so just closing for now but looks like britt found another thing that was outdated
