### ISSUE TITLE
Problems with netlify dev and redirectors with jwt secret

### ISSUE THREAD

**Issue by richtera** [netlify/cli#529]
Bug:

It's not possible to assign the jwtSecret and in theory it defaults to "secret" but it it doesn't work.

**- Problem:**
passing JWT secrets is not possible.
sending nf_jwt with "secret" as the secret doesn't work.

**- What is the expected behavior?**
It should work like deployment

**- Local Environment Information**
Paste the results of `netlify status --verbose` here
Netlify is not linked for this, it's only a local dev site.

The code currently doesn't pass jwtSecret.
```javascript
  const rewriter = rulesProxy({ publicFolder: settings.dist })
```

```sh
$ node_modules/.bin/netlify status --verbose
──────────────────────┐
 Current Netlify User │
──────────────────────┘
Name:  Andreas Richter
Email: ****
Teams: 
  SelfStudy:              Owner Collaborator Controller
  Andreas Richter's team: Collaborator
 ›   Warning: Did you run `netlify link` yet?
 ›   Error: You don't appear to be in a folder that is linked to a site
```

**Comment by calavera** [comment]
I think we should generate a shared secret that any client can use to generate those tokens. If I remember right, the default path to check roles is `app_metadata.authorization.roles` which means that we expected a payload like this in the JWT:

```
  {
    "app_metadata": {
      "authorization": {
        "roles": ["admin"]
      }
    },
    "exp": 2149017956
  }
```

The proxy in the dev subsystem should read the `nf_jwt` cookie, verify the token with the secret, and then check that the role is in the payload.

**Comment by richtera** [comment]
Right the webassembly is loaded with the default secret "secret" but does not correctly decode and redirect the rules according to roles.
