### ISSUE TITLE
[Bug] Nextjs plugin not detected when using sites:create-template

### ISSUE THREAD

**Issue by taty2010** [netlify/cli#5309]
Used the `sites:create-template` to clone & deploy the next-toolbox template, Netlify did not detect that I was using Nextjs and never installed the plugin which ended up producing a 404 error. 

I initially thought it might be related to the git clone error we've been experiencing [here](https://github.com/netlify/cli/issues/4212) but you will still run into the same issue whether you try to clone it or not. I also tested it out with the Gatsby template and the Gatsby plugin was installed successfully.

**Comment by tinfoil-knight** [comment]
The `@netlify/plugin-nextjs` plugin isn't getting installed for production builds (through `ntl deploy --build`) as reported but the plugin is getting installed by Netlify Build when the development environment runs (through `ntl dev`)

**Comment by serhalp** [comment]
Closed by https://github.com/netlify/cli/pull/6729
