### ISSUE TITLE
netlify deploy and build warnings

### ISSUE THREAD

**Issue by cfjedimaster** [netlify/cli#531]
**- Do you want to request a *feature* or report a *bug*?**
Feature request

**- What is the current behavior?**
I used `netlify deploy` to upload a site and my build command never ran, even after specifying one in my `netlify.toml`.

**- If the current behavior is a bug, please provide the steps to reproduce.**
The current behavior is not a bug (as described here: https://community.netlify.com/t/issue-with-deploying-a-site-with-cli/3291)

**- What is the expected behavior?**
While things worked as expected, it would be nice if the CLI had noticed build comments in my netlify.toml and *warned* me that they would not be used.

**Comment by sw-yx** [comment]
indeed this is as designed but we could do with a warning. @raeesbhatti

**Comment by DavidWells** [comment]
Hey @cfjedimaster 

What do you mean by 

>  it would be nice if the CLI had noticed build comments

---

The current flow is 

```bash
npm run build
# soon™ it will be
netlify build

# then
netlify deploy
```

**Comment by cfjedimaster** [comment]
Um, I kinda don't remember. I think the issue was that build commands ONLY work when you deploy via GitHub, not via CLI. If so, then I'd like the CLI to notice the commands and tell me something.
