### ISSUE TITLE
[netlify deploy] Don't tell me Live URL when my deploys are locked

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#536]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**

i have locked deploys. i publish using `netlify deploy --prod`. CLI tells me this:

```

Deploying to live site URL...
✔ Finished hashing 180 files✔ CDN requesting 81 files
😄  (72/82) Uploading client/app.0a6d7911.css..✔ Finished uploading 82 assets
✔ Deploy is live!

Logs:              https://app.netlify.com/sites/scout-videos-51664/deploys/5d7e64a6fa03b8fb214cb84a
Unique Deploy URL: https://5d7e64a6fa03b8fb214cb84a--scout-videos-51664.netlify.com
Live URL:          https://www.swyx.io
```

the last line is misleading, because what i just deployed is not live. we should not show that and prompt people to go and manually publish if they are sure they want to

**Comment by fool** [comment]
I suspect this is likely an issue in the API rather than the CLI, as tracked in this internal-to-netlify-staff issue.  If not it is anyway related so crosslinking them here :)

https://github.com/netlify/bitballoon/issues/572

**Comment by sw-yx** [comment]
excellent thank you!

**Comment by DavidWells** [comment]
We can handle this in CLI. Will require additional fetches about current site information before deploys.

```
 netlify api getSite -d '{"site_id": "your-site-id"}'
```

![image](https://user-images.githubusercontent.com/532272/64981702-748fdc80-d871-11e9-8d52-c4bdde6471fc.png)

`published_deploy.locked` is the property

**Comment by DavidWells** [comment]
This should solve the trick. 

https://github.com/netlify/cli/blob/master/src/commands/deploy.js#L145

```
const remoteSiteData = await api.deploy(siteId)
if(`prod` flag && remoteSiteData.published_deploy.locked) {
  // exit early and show other console messgae
}
```

**Comment by laurenskling** [comment]
I just had a similair confusion. I have turned auto-publishing off, but still `netlify deploy --prod` gives me the Live URL as if it has published it, which it hadn't

**Comment by RaeesBhatti** [comment]
This has been fixed in latest version
