### ISSUE TITLE
How to use this for Go functions?

### ISSUE THREAD

**Issue by whssports** [netlify/cli#537]
Netlify indicates it handles Go and JS functions, yet all the info I find relates only to the JS functions. How do we run go functions locally for development purposes, as well as information on how to call locally vs when deployed on netlify?

**Comment by whssports** [comment]
I was assuming so, yet I cant find anything on how you do something similar for Go functions. How do I run them locally to test against? Also, forgive me.. you say you are transferring me.. is there a separate Github project for Go functions that I should be posting this to? Or are you saying that you are referring me to those two individuals who will contact me in some manner to discuss this? Either way, after you comment we can close this if this is not the correct place. I am just not finding much in the way of how to work with Go functions. As well, adding a .toml file seems to override my auto build of the nodejs site itself. I assume the way to do this is use a .toml file that refers to a Makefile (e.g. make build) and in THAT Makefile you put the go AND npm build instructions?

**Comment by sw-yx** [comment]
i already transferred you! see you are now in the cli repo. @futuregerald and @raeesbhatti can take it from here. i don’t work much with go myself.

**Comment by futuregerald** [comment]
Hi @whssports ,

Since the CLI isn't doing anything with Go functions, this probably isn't the place to talk about it. I recommend writing in to the Netlify community: https://community.netlify.com/c/netlify-platform/functions

The short answer is that we have docs on using Go functions at https://www.netlify.com/docs/functions/#go-lambda-functions

Go produces binaries, so you can build it locally on your machine with `GOOS=linux GOARCH=amd64` so it targets the right architecture and operating system. 

Or you can build it in the Netlify build environment since Go is installed. I have a repo that builds a go function with the relevant build lines in my package.json: https://github.com/futuregerald/functions-react-mongo/blob/master/package.json#L28

> go get ./src/lambda/... && go build -o lambda/validate-user ./src/lambda/validate-user.go

**Comment by whssports** [comment]
Hi. Thank you for your reply. I also added a post on the forums. To follow up, I was able to get the Go function to be called on the Netlify site. Used the make build bit and netlify builds the go func and the nodejs react site, deploys it, I see the lambda is deployed, and it appears my button click from the site using the /.netlify/functions/func works. Apparently a parsing error on the request was causing an immediate 401 but I think I have that figured out.

The main question now is, how can I do this locally? How do I run the Go func locally so that my local npm run site using the same /.netlify/.. path works so that I can much more quickly iterate on the Go function which is where the bulk of the work needs to happen right now. Uploading it every time takes way too long unfortunately.  I tried the netlify-lambda serve ... option and figured it wouldnt work, naturally it doesnt. So is there a Go specific utility that is needed to run Go functions locally for dev mode?

**Comment by fredjens** [comment]
Any updates on this?

**Comment by whssports** [comment]
Sadly.. no. I gave up on it. It wasn't worth the hassle hoping someone would reply with how to do it, and I have since gone to just deploying a complete solution for my own stuff rather than rely on what may or may never be a solution from netlify.

**Comment by fredjens** [comment]
I see... Think I am going to switch back to JS for my functions... To much hassle to run them locally (Docker++)...

**Comment by RaeesBhatti** [comment]
It seems like Lambda is just [listening for RPC](https://github.com/aws/aws-lambda-go/blob/ba3152827fb20751d929ecbc5582af9616d688aa/lambda/entry.go#L50-L62) on a specific port. It should be doable to run Go functions directly without Docker if user has GoLang installed.

**Comment by han-so1omon** [comment]
What is the current recommended method to test Go functions before deployment?

**Comment by HugoDF** [comment]
@han-so1omon I think you can use https://github.com/lambci/docker-lambda#run-examples

**Comment by han-so1omon** [comment]
@HugoDF I have been successfully using localstack to simulate the lambda environment. However there are still some necessary adaptations to make once I integrate into the localstack environment, for instance the lambda endpoint changes.

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
