### ISSUE TITLE
Move the GitHub/GitLab/Bitbucket linking feature to the JavaScript client

### ISSUE THREAD

**Issue by ehmicky** [netlify/cli#549]
**- Do you want to request a *feature* or report a *bug*?**

The GitHub/GitLab/Bitbucket [linking feature](https://github.com/netlify/cli/tree/master/src/utils/init) should probably be moved to the JavaScript client, what do you think?

We have [several users](https://github.com/netlify/open-api/issues/143#issuecomment-533533119) that are trying to perform this action programmatically. Having it as part of the JavaScript client would be more convenient (calling the CLI is not).

**Comment by DavidWells** [comment]
Related: https://github.com/netlify/cli-utils/issues/2

`app.netlify.com`, the `cli`, and https://www.netlify.com/blog/2018/11/29/deploying-netlify-sites-with-aws-cloudformation/ all have duplicated logic for creating sites & wiring up the deployment hooks for netlify CI to start a build when new code is pushed into a given repo.

**Proposed solution:**

Centralize this functionality in a single library (or service) that anyone internal/external can use.

**Other details**

app.netlify.com currently uses github apps (more fine grained controls) and the CLI doesn't use github app flow but instead creates deployment keys and webhooks via api token https://github.com/netlify/cli/blob/master/src/utils/init/config-github.js#L34

Github app logic lives in bitballoon API layer created by @kitop

**Comment by ehmicky** [comment]
@DavidWells sounds like a good plan. Would it make sense to add this to `js-client` instead of using a separate repository?

**Comment by sarahetter** [comment]
Closing as stale
