### ISSUE TITLE
[feature] add environment variables by CLI

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#558]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
have to go to web UI to do it

**- What is the expected behavior?**

something like `netlify env:set` and `netlify env:get` and `netlify env:list`

**Comment by DavidWells** [comment]
Related https://github.com/netlify/cli/issues/142

**Comment by 2color** [comment]
Any update or expected timeline on this?

**Comment by RaeesBhatti** [comment]
We already have mechanisms for setting the remote env variables to Netlify Dev in both app server and functions server. Not sure what purpose this would serve.

**Comment by sw-yx** [comment]
hehe ok

**Comment by 2color** [comment]
> We already have mechanisms for setting the remote env variables to Netlify Dev in both app server and functions server. Not sure what purpose this would serve.

This would allow for automation through CI/CD pipelines.

**Comment by 2color** [comment]
Any thoughts on this @sw-yx ?

**Comment by RaeesBhatti** [comment]
@2color I've added some basic docs around env var injection here: https://cli.netlify.com/netlify-dev#environment-variables
Variable injection is supported in `netlify dev` and `netlify dev:exec` right now if your project is linked and you're logged in.

> This would allow for automation through CI/CD pipelines.

Could you explain your use case a bit more please! Are you using a CI/CD other than Netlify? Even if we implement this, it will still require you to provide a Netlify API access token.

**Comment by 2color** [comment]
Thanks for the info @RaeesBhatti. 

My question was more about setting production env vars from the CLI for the actual production deployment on Netlify.
