### ISSUE TITLE
Functions To Function Proxying Results in Different Path With Netlify Dev vs Netlify Cloud

### ISSUE THREAD

**Issue by oscartbeaumont** [netlify/cli#559]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
Netlify Dev and Netlify Production deployments handle the `_redirects` proxying differently.

**- If the current behavior is a bug, please provide the steps to reproduce.**
I have a `_redirects` file with the below route which makes my Netlify Functions available at `/api/{function_name}`.
```
/api/* /.netlify/functions/:splat 200
```
I also have a function setup (code below) which returns its calling path (`event.path`).
```javascript
exports.handler = async function(event, context) {
  return {
    statusCode: 200,
    body: event.path
  };
};
```
If I access `/api/test` on my deployment (running in the Netlify cloud) I get the response `/api/test` which is what I would expect. Whether when using Netlify Dev I get the response `/.netlify/functions/test`.

**- What is the expected behavior?**
Netlify Dev should act the same as the Netlify cloud and parse the same url. This means Netlify Dev should result in the `event.path` being set to `/api/test` when `/api/test` is requested.

**- Local Environment Information**
Paste the results of `netlify status --verbose` here
I don't see relevance but if it is required I can add it.

**Comment by sw-yx** [comment]
nice catch!

**Comment by nonissue** [comment]
Was this ever fixed? I'm calling a function from another function and have an ugly workaround in place for local dev / deployment.
