### ISSUE TITLE
"TypeError: deployConfigDeclarations is not iterable" error with Edge Functions

### ISSUE THREAD

**Issue by thonkinator** [netlify/cli#5592]
### Describe the bug

When using `netlify dev` with Edge Functions, when it tries to load an Edge Function, you get this error:
```
TypeError: deployConfigDeclarations is not iterable
    at Module.mergeDeclarations (file:///Users/patrick/Library/pnpm/global/5/.pnpm/@netlify+edge-bundler@8.13.0/node_modules/@netlify/edge-bundler/dist/node/declaration.js:10:56)
    at EdgeFunctionsRegistry.matchURLPath (file:///Users/patrick/Library/pnpm/global/5/.pnpm/netlify-cli@13.2.1_@types+node@18.15.3/node_modules/netlify-cli/src/lib/edge-functions/registry.mjs:261:39)
    at file:///Users/patrick/Library/pnpm/global/5/.pnpm/netlify-cli@13.2.1_@types+node@18.15.3/node_modules/netlify-cli/src/lib/edge-functions/proxy.mjs:112:82
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async onRequest (file:///Users/patrick/Library/pnpm/global/5/.pnpm/netlify-cli@13.2.1_@types+node@18.15.3/node_modules/netlify-cli/src/utils/proxy.mjs:525:33)
```

### Steps to reproduce

1. Create a new, empty directory
2. Create a file at `netlify/edge-functions/test.js`
3. Paste this into the file (example edge function from [the docs](https://docs.netlify.com/edge-functions/get-started/#test-locally)):
```js
export default () => new Response("Updated hello!");

export const config = { path: "/test" };
```
4. Run `netlify dev`

### Configuration

_None needed_

### Environment
```
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 612.98 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  npmGlobalPackages:
    netlify-cli: 13.1.6
```

**Comment by thonkinator** [comment]
I tested different versions of netlify-cli to see which was the latest to not have this bug, and it seems that it's 13.1.3. However, with 13.1.3 I get some other error about relative imports, so it's possible it does have the bug, but it's never getting to that point.

**Comment by mamunonweb** [comment]
@thonkinator 
I think it's a `pnpm` thing. I also had something similar, then I switched to `npm` and now it's good.

```bash
pnpm remove -g netlify-cli
npm install -g netlify-cli
```

**Comment by thonkinator** [comment]
switching to `npm` worked, but this is still an issue. i shouldn't be forced to switch to an arguably worse package manager just to use Netlify Edge Functions.

**Comment by serhalp** [comment]
Marking this as stale as it is several years old. Please feel free to reopen if you are still having issues.
