### ISSUE TITLE
split basic and advanced commands in netlify cli help. also document `ntl` alias

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#560]
![image](https://user-images.githubusercontent.com/6764957/65839776-6c5a8700-e2de-11e9-8061-da676838cb39.png)
![image](https://user-images.githubusercontent.com/6764957/65839777-6fee0e00-e2de-11e9-91fb-8e424f744bef.png)

**Comment by DavidWells** [comment]
This would be nice.

Will require a fork of oclif or an upstream PR to get this working

**Comment by sw-yx** [comment]
good candidate for [patch-package](https://github.com/ds300/patch-package) to maintain a low cost fork

**Comment by DavidWells** [comment]
Closing this for now. 

Will probably do this if we migrate off of oclif
