### ISSUE TITLE
Trigger builds on monorepo subdirectories

### ISSUE THREAD

**Issue by seanemmer** [netlify/cli#561]
I have a monorepo project in which separate subdirectories of the project are linked to different Netlify sites - e.g provider app, consumer app, marketing page, gatsby theme.  

The monorepo has been implemented using yarn workspaces, and there are dependencies between one subdirectory and another - e.g. the marketing page depends on the gatsby theme.  In order to correctly resolve these dependencies I set the base directory to the root folder and use the following build command:

`npm i yarn@latest && yarn && yarn workspace [subdirectory] build`

I have been unable to find a way to decouple deployment of one site from all the others.  Any push to the monorepo triggers a redeploy of all the Netlify sites.  While I could hack something together using branches/contexts, it would be much cleaner if I could instruct Netlify to watch a subdirectory of my repo and build based off of that.

**Comment by erezrokah** [comment]
Sorry for the late reply. Oddly enough, shortly after this issue was opened this was announced:
https://www.netlify.com/blog/2019/10/09/launching-monorepo-support-for-netlify-sites/

Regardless, not a CLI issue.
