### ISSUE TITLE
[Addons] netlify addons:delete fauna fails once in bad state

### ISSUE THREAD

**Issue by wes566** [netlify/cli#562]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
I cannot config or delete the fauna addon

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a fauna addon
2. go into the fauna dashboard and delete the database there
3. Try to config or delete the addon in the netlify cli

**- What is the expected behavior?**
I can delete the addon so that I can recreate a new one

**- Local Environment Information**
Paste the results of `netlify status --verbose` here

```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 59.0.1
    Safari: 12.1.1
```

I'd rather not paste all account info here... can I email that info?

netlify CLI version: netlify-cli/2.15.0 darwin-x64 node-v10.15.3

This is the output of `netlify addon:delete fauna`:
<img width="1262" alt="Screen Shot 2019-10-02 at 8 25 38 AM" src="https://user-images.githubusercontent.com/3293318/66058051-8d91c200-e4ee-11e9-88f4-da6883a6d41e.png">

**Comment by BrunoQuaresma** [comment]
Hi @wes566 , can you try again and see if it works for you?

**Comment by DavidWells** [comment]
Hey @wes566 just wanted to follow up on this.

Were you able to get it working?

**Comment by wes566** [comment]
@DavidWells @BrunoQuaresma I don't have my environment setup anymore, I'm fine with closing this out, if I come back around to it and hit issues again then I can make a new issue.
