### ISSUE TITLE
standardize port terminology

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#563]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**

it is unnecessarily confusing to teach/understand/document what `port` means in netlify dev. it causes us to shoot ourselves in the foot and likely has caused bugs as well as user confusion.

there are 3 kinds of ports.

- the dev server port we are proxying, which is what we spin up or the project spins up via our detector
- the functions server port
- the final port that we expect netlify users to use

the codebase is a mess when it comes to this.

for example, what do you expect netlify dev to do when someone sets `port` in the `[dev]` block of `netlify.toml`?

[it sets the netlify dev port, right? so obvious?](https://github.com/netlify/cli/blob/8ebf422ee4400c2ae74eaec8e72a057827655ad1/src/commands/dev/index.js#L396-L399)

[umm idk](https://github.com/netlify/cli/blob/8ebf422ee4400c2ae74eaec8e72a057827655ad1/src/commands/dev/index.js#L173) maybe it also sets the final port too?

i think we owe it to ourselves and our users to clarify all this. in the process we may uncover some bugs.

**- What is the expected behavior?**

clarity.

**Comment by sw-yx** [comment]
cc @davidwells

**Comment by DavidWells** [comment]
Whats the proposal for the new names?

**Comment by sw-yx** [comment]
up to you
