### ISSUE TITLE
[feature] allow specification of  exposed `netlify dev` port in `netlify.toml` or via cli

### ISSUE THREAD

**Issue by drewwyatt** [netlify/cli#564]
My team is working on adding some netlify functions to our workflow (which is currently just `webpack-dev-server` running on port `1337`). Because of the addition, we have taken the following steps to improve our local workflow:

- move webpack-dev-server command from start to start:app
- remap start to netlify dev
- add this to netlify.toml

```
[dev]
    command = "yarn start:app"
    port = 1337 # the port webpack-dev-server runs on, set in webpack.config.js
    functionsPort = 34567
    publish = "build" 
```

This works! But the port is inconsistent and sometimes the `netlify dev` output gets swallowed by the `webpack-dev-server` output. Is there a way to specify the port that netlify dev runs on? (as-is `port` in `netlify.toml` seems to want to map to the port of the app’s dev server it's going to proxy).

(Is it/can it be) possible to specify the port exposed by `netlify dev` so that even if the console output is swallowed by the app server we can still rely on a given port?

**Comment by sw-yx** [comment]
related #563

**Comment by raeesbhatti** [comment]
`netlify dev` tries to bind to the specified port to start its own server, and in this case since your `webpack-dev-server` is also running on the same port, it chooses a different port.
This is a know point of confusion for a lot of people and there is a PR to fix that: https://github.com/netlify/cli/pull/488
Please hold on

**Comment by oles** [comment]
What is the status of this madness?

No port config:
![Screenshot from 2020-03-11 15-48-54](https://user-images.githubusercontent.com/7634050/76429961-0b1c0100-63b0-11ea-88ce-49fbf62056a6.png)

Port config:
![Screenshot from 2020-03-11 15-49-09](https://user-images.githubusercontent.com/7634050/76429963-0c4d2e00-63b0-11ea-8d8d-e05eb66576e7.png)

The config does nothing?

**Comment by RaeesBhatti** [comment]
This has been fixed recently. The order of preference for `port` is as follows (each overrides the previous):
1. Framework detector config
2. `netlify.toml` config
3 `netlify dev` flags

If `port` is specified in `netlify.toml` or in `netlify dev` flags and we're unable to acquire it, it will throw an error stating the fact.

Thank you all for your patience. Please make sure to update your `netlify-cli` to latest version and let us know if the issue still persists.

**Comment by bradley** [comment]
I cant test if this was fixed because of [this other issue that asks me to roll back to 2.46.0](https://community.netlify.com/t/env-node-no-such-file-or-directory-when-using-netlify-cli/12391/2?u=bradleygriffith)
