### ISSUE TITLE
New Routes not generated 

### ISSUE THREAD

**Issue by soongsta** [netlify/cli#5648]
### Describe the bug

We are finding that new routes are not generated when using the command "netlify deploy --prod --timeout 24000"

We have to run the deploy a second time for the routes to be generated. 

We suspect that the checksum issue

![build](https://user-images.githubusercontent.com/17092846/233487849-49123eda-8da7-445c-836a-b0e5b0f0174e.png)

RSS feeds to our social media pages causes urls to show "page not found"

### Steps to reproduce

1. Run "netlify deploy --prod --timeout 24000"
2. Wait a few hours for it to complete
3. Check urls
4. Urls not found
5. Run ""netlify deploy --prod --timeout 24000" again
6. urls found the 2nd time around

### Configuration

[[redirects]]
  from = "/api/*" # simplify all calls to serverless functions
  to = "/.netlify/functions/:splat" # all function calls will go to this path
  status = 200 # ok code
  force = true # ensure to always redirect

### Environment

  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 5.01 GB / 15.84 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.0 - ~\AppData\Roaming\npm\npm.CMD

**Comment by serhalp** [comment]
Marking this as stale as it is over a year old. Please feel free to reopen if you are still having issues.
