### ISSUE TITLE
Serve functions programmatically

### ISSUE THREAD

**Issue by pimterry** [netlify/cli#566]
It'd be really useful to be able to serve functions programmatically. In my case, I'd like to do this for automated testing: I want to run all my functions with a real server locally, and write tests that make requests to them and check the results.

In theory you could do so by spawning the CLI as a subprocess and automating it through there, but that's messy and requires a separate node process, so you can't use things like [rewire](https://www.npmjs.com/package/rewire) to stub out dependencies.

All the code is here for this already, this would just require a little reorganization. Right now, the best I can see is:

```javascript
import { serveFunctions } from 'netlify-cli/src/utils/serve-functions';

describe("My functions", () => {
  it("should handle requests", () => {
    serveFunctions({
        functionsDir: path.join(__dirname, '..', 'functions'),
        port: 9090
    });
    
    const response = await fetch('http://localhost:9090/netlify/.functions/paddle-webhook');
    expect(response.status).to.equal(200);
  });
});
```

This has a couple of problems though:

* You can't cleanly shut the server down.
* There's no easy way to tell when the server has started: you need to poll `/` until you get a 404 response.
* You're importing an internal undocumented API, which could presumably change any time

Any chance you'd be open to fixing these issues?

**Comment by sw-yx** [comment]
what’s the api you want? 

all this code is internals, yes, but theres nothing really stopping you copying out the code and writing your own tool if u wanna do that. we can even link to you if you think this would help others

**Comment by pimterry** [comment]
> what’s the api you want?

Something like this:

```javascript
import { Server } from 'netlify-cli';

describe("My functions", () => {
  
  const server = new Server();

  beforeEach(async () => {
    await server.start();
  });

  afterEach(async () => {
    await server.stop();
  });

  it("should handle requests", () => {    
    const response = await fetch(`http://localhost:${server.port}/netlify/.functions/paddle-webhook`'`);
    expect(response.status).to.equal(200);
  });
});
```

I.e. take `netlify dev` and separate the CLI part (args parsing etc) from actually running the server, export the server, and let me use it directly. In this perfect world this doesn't need the `functionsDir` arg of the previous example either, as it just reads from my `netlify.toml`, and does exactly the same thing the production environment would do.

> all this code is internals, yes, but theres nothing really stopping you copying out the code and writing your own tool

True, but it'd be nice to have this built-in & supported by Netlify, since you've already written the code for 99% of it, and duplicating it myself means maintaining it as that changes.

I think this is doable without too many changes, just some internal refactoring. Would you be interested if I opened up a PR for it?
