### ISSUE TITLE
cant login with netlify login command

### ISSUE THREAD

**Issue by bipul-toddleapp** [netlify/cli#5694]
### Describe the bug

throws following error

```
netlify login
Logging into your Netlify account...
 ›   FetchError: request to https://api.netlify.com/api/v1/oauth/tickets?client_id=d6f37de6614df7ae58664cfca524744d73807a377f5ee71f1a254f78412e3750 failed, reason: Socket connection timeout
```

i checked this page 
https://answers.netlify.com/t/netlify-cli-cannot-login/29512

i tried the ping one it is working

output from ping
```
ping -c 3 35.201.69.186
PING 35.201.69.186 (35.201.69.186): 56 data bytes
64 bytes from 35.201.69.186: icmp_seq=0 ttl=117 time=78.903 ms
64 bytes from 35.201.69.186: icmp_seq=1 ttl=117 time=54.623 ms
64 bytes from 35.201.69.186: icmp_seq=2 ttl=117 time=57.198 ms

--- 35.201.69.186 ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 54.623/63.575/78.903/10.890 ms
```

so no issue with my isp blocking the ip addr

i also tried the copy paste url on browser suggestion also. following screen comes
![image](https://github.com/netlify/cli/assets/116153194/3e9a3dbc-9b67-46c4-8710-5ef181b8e708)

let me know how to fix it.

thanks

### Steps to reproduce

netlify login

### Environment

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M2
    Memory: 86.27 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.1.0 - ~/.nvm/versions/node/v20.1.0/bin/node
    npm: 9.6.4 - ~/.nvm/versions/node/v20.1.0/bin/npm
  npmGlobalPackages:
    netlify-cli: 15.0.2

**Comment by sarahetter** [comment]
Is this still an issue?

**Comment by bipul-toddleapp** [comment]
no there is no such issue now, thanks
