### ISSUE TITLE
npm install netlify-cli failing in Github action

### ISSUE THREAD

**Issue by mjgs** [netlify/cli#5728]
### Describe the bug

I’m running into failures installing netlify-cli. It started happening sometime in the past few weeks, just noticed yesterday.

npm install netlify-cli
…
npm ERR! netlify-cli@15.0.2 postinstall: `node ./scripts/postinstall.mjs`

Exit status 7
Failed at the netlify-cli@15.0.2 post install script

I have it running in a Github action:

```
      - name: Install Netlify CLI
        run: |
          npm install netlify-cli
```

It’s running on Ubuntu:

```
runs-on: ubuntu-latest
```

It’s in the middle of what looks like a king compilation, the last thing printed mentions something about skipping some optional dependencies (see screenshot).

### Steps to reproduce

Run `npm install netlify-cli` in a Ubuntu Github action.

### Configuration

Not relevant

### Environment

Screenshot of error:

![33650603-9509-4FED-9674-5533BA2EF46B](https://github.com/netlify/cli/assets/1915855/e401482a-08c5-4e49-9105-2dcd396e26ba)

**Comment by danez** [comment]
Thanks for reporting, can you please post the complete logs for the install and also which Node.js version are you using?

**Comment by danez** [comment]
If you have more information feel free to reopen. Right now there is not enough information.
