### ISSUE TITLE
The `watch` command is missing from the cli docs table of contents

### ISSUE THREAD

**Issue by klavavej** [netlify/cli#577]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
The `watch` command is covered in the CLI docs, but missing from the table of contents

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to https://cli.netlify.com/commands/watch/ - note that this page about the `watch` command exists
2. Go to https://cli.netlify.com/commands/ - note that the `watch` command is included in the list of available CLI commands
3. Check the cli docs table of contents and note that the `watch` command is missing despite there being a page about it.

<img width="1099" alt="Screen Shot 2019-10-18 at 1 20 37 PM" src="https://user-images.githubusercontent.com/35638702/67125825-7ae3e200-f1aa-11e9-9b82-fd995a0af85c.png">

**- What is the expected behavior?**
`watch` is included in the table of contents

**- Additional context**
Reported by a community member in https://community.netlify.com/t/cli-documentation-watch-command/4161

**Comment by DavidWells** [comment]
This is by design the command might go away
