### ISSUE TITLE
`netlify dev --live` URL output gets overwritten

### ISSUE THREAD

**Issue by DavidChouinard** [netlify/cli#579]
When running `netlify dev --live`, the deployed URL gets briefly shown in the console, but then is overwritten by further console output. My workflow for getting the URL: screen record the terminal output, pause the video and try to transcribe the URL (not great!).

Seems to have changed recently.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/388552/67178371-4d07c480-f387-11e9-9ace-1afa600edbae.gif)

**Comment by aidenBarrett96** [comment]
Until this is fixed, I have been outputting the terminal to a text file when running a live development server and accessing the link from there

**Comment by DavidChouinard** [comment]
That's a much better workaround, thanks

**Comment by moreguppy** [comment]
This has also been flagged in #666
