### ISSUE TITLE
[Dev] cleanup processes if `netlify dev` dies

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#580]
If an error happens in the `netlify dev` server, the process crashes and prints something like:

```
◈ Error during invocation:  Lambda response was undefined.
Please verify you are returning an object with { statusCode } in your function code
/Users/davidwells/Netlify/repos/cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:580:17)
    at ServerResponse.write (_http_outgoing.js:575:10)
    at handleErr (/Users/davidwells/Netlify/repos/cli/src/utils/serve-functions.js:19:12)
    at /Users/davidwells/Netlify/repos/cli/src/utils/serve-functions.js:143:18
    at /Users/davidwells/Netlify/repos/cli/src/utils/serve-functions.js:183:7
```

Afterwards, if you try to start `netlify dev` again you run into an error like this:

```
Something is already running on port 3000.
```

To fix, the user must `killall -9 node` to kill the lingering process (from create react app in this case), then they can `netlify dev` a fresh session.

## Solution

We should be automatically killing these processes so users don't need to remember/know that they need to run `killall -9 node`

So if `netlify dev` fatals and exits, we should kill the dev server, function server, and frontend server processes that are running

**Comment by DavidWells** [comment]
Is the redirect library just used in one place? https://github.com/netlify/cli/blob/cb26ae74f0e0dd9bc820c8194cea40574bb9cee6/src/utils/rules-proxy.js#L100-L105

**Comment by cannikin** [comment]
I've started running `netlify dev` by doing `killall node; netlify dev` :( Sucks because I haven't more than one project running at time that way.

**Comment by raeesbhatti** [comment]
Okay, this is trickier than I originally thought. I've tried catching any error in the `netlify dev` command and sending a `SIGTERM` to the child process but it doesn't seem to respect that or any other kill signal.
Looking into it further, any suggestions appreciated

**Comment by therobinkim** [comment]
@raeesbhatti I saw there was a new release and updated netlify-cli via `npm install -g netlify-cli@latest` and confirmed via `netlify --version` (got `netlify-cli/2.22.0 darwin-x64 node-v10.16.0`).

Alas, when I reran `netlify dev` after a `socket hang up` error, I still got `Something is already running on port 3000.` 😭

Here's my terminal output, in case it's helpful:

```
[omitted]/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketCloseListener (_http_client.js:364:25)
    at Socket.emit (events.js:203:15)
    at TCP._handle.close (net.js:606:12)
```
```
$ netlify dev
◈ Netlify Dev ◈
◈ Injected build setting env var:  [omitted]
◈ Injected build setting env var:  [omitted]
◈ Injected build setting env var:  [omitted]
◈ Starting Netlify Dev with create-react-app
Waiting for localhost:3000.
◈ Lambda server is listening on 34567

Connected!
Waiting for localhost:34567.
Connected!

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘


> [omitted] 0.0.1 start [omitted]
> react-scripts start

Something is already running on port 3000.
```
```
$ netlify --version
netlify-cli/2.22.0 darwin-x64 node-v10.16.0
```

**Comment by raeesbhatti** [comment]
I realize this is very frustrating @therobinkim. Is is possible to share a minimal version of your project as a repo for me to reproduce?

**Comment by therobinkim** [comment]
@raeesbhatti Not one that I can quickly/easily share at the moment, but I'll be sure to report back if/when I'm able to dig into it! (If not in the next 48 hours, it might be a while.)

**Comment by therobinkim** [comment]
@raeesbhatti One found out that while a standard `CTRL + C` to quit out of `netlify dev` seems to properly close down port 3000, `socket hang up` errors do not. I'll post one way I figured out how to recreate `socket hang up` errors in #404 as it seems to be a better thread for such info.

**Comment by robnewton** [comment]
I've been dealing with `CTRL + C` not properly closing down port 3000 for a couple months now and would very much like to find a solution on Windows 10.

I keep another Windows console open just to run `netstat -ano | findstr :3000` and then `taskkill /F /PID <the_found_port>`.

This is a real pain but figure it was just because I was behind a few versions. Well I've updated VSCode to `1.41` and Netlify Dev to `netlify-cli/2.25.0 win32-x64 node-v8.11.3` but it's still happening.

**Comment by kaladivo** [comment]
What resolved this issue for me was to run `killall node`.

**Comment by kotAPI** [comment]
Any fix for this yet? Still an issue on Windows 10. Everytime there is a 500 error on one of the functions the whole netlify dev instance shuts down and I have to restart the server again just to get an error that something else is running on the port

is there any config to stop server from crashing?

**Comment by erezrokah** [comment]
> Any fix for this yet? Still an issue on Windows 10. Everytime there is a 500 error on one of the functions the whole netlify dev instance shuts down and I have to restart the server again just to get an error that something else is running on the port
> 
> is there any config to stop server from crashing?

Hi @kotAPI do you mind opening a new issue for the crash? A 500 error in a function should not crash the entire `netlify dev` process

**Comment by AndreasDeveloper** [comment]
Thought to join the conversation now. I've been playing with netlify functions for few months now. Experiencing same issue as @therobinkim mentioned. 

Also, @kotAPI , yeah, same here, whenever I get 500 error, everything crashes. Running on latest netlify-cli version. Is there any update coming up for this?
