### ISSUE TITLE
Failed to install with npm mentioning a  zip-it-and-ship-it git repo

### ISSUE THREAD

**Issue by stratosgear** [netlify/cli#584]
Over the last 12 hours or so, some Gitlab CI pipelines are failing with a:

```
npm install -g netlify-cli
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/netlify/zip-it-and-ship-it.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

As this is installed inside a docker container I do not have easy access for further logs (at least, for now)

This has failed while being executed inside a  `node:10.16.3-alpine` (that was running happily for a couple of months now) docker image and a just updated `node:12.13.0-alpine` one.

Does any one have any ideas what causes this?

**Comment by ehmicky** [comment]
Hi @stratosgear, thanks for reporting this issue.

This is due to your environment (Node alpine) not having `git` installed. Some of our npm dependencies are using git URLs. I am working on a fix to remove this so that `netlify/cli` works on Node alpine.

**Comment by scopsy** [comment]
Failing on our Circle CI builds as well

**Comment by ehmicky** [comment]
Until a fix has landed, installing `git` in your Docker image should fix this problem (as a workaround).

**Comment by ehmicky** [comment]
This should be fixed in the latest version `2.19.3`.
Please let us know if the problem still happens. Thanks!

**Comment by stratosgear** [comment]
I verify that our Gitlab CI pipelines are working correctly now.

So, I think some of your **new** dependencies required git, because this used to work up until yesterday, sometime.

Nonetheless, everything is smooth again.  Thanks for the quick fix!

**Comment by ehmicky** [comment]
Thanks for confirming this is now working!
