### ISSUE TITLE
Netlify Dev - Error: Command failed with Unknown system error -88

### ISSUE THREAD

**Issue by FileManagerKim** [netlify/cli#5854]
### Describe the bug

When running netlify dev, it will open the server on port 8888, then quickly shut off and print a large garbled system error trace, followed by this resulting error block of unknown system error -88:

```
Error: Command failed with Unknown system error -88: /Users/<redacted>/Library/Preferences/netlify/deno-cli/deno run --allow-all --import-map=data:application/json;base64,eyJpbXBvcnRzIjp7Im5ldGxpZnk6ZWRnZSI6Imh0dHBzOi8vZWRnZS5uZXRsaWZ5LmNvbS92MS9pbmRleC50cyJ9LCJzY29wZXMiOnt9fQ== --no-config --quiet /var/folders/74/0krmhkmn1hnf94gmvvw4qff40000gn/T/tmp-1653-BtDik531bzvf/dev.js --port 49283

spawn Unknown system error -88
    	at ChildProcess.spawn (node:internal/child_process:420:11)
    	at Object.spawn (node:child_process:743:9)
    	at execa (file:///Users/<redacted>/node_modules/execa/index.js:84:26)
    	at DenoBridge.runWithBinary (file:///Users/<redacted>/node_modules/@netlify/edge-bundler/dist/node/bridge.js:98:25)
    	at DenoBridge.runInBackground (file:///<redacted>/node_modules/@netlify/edge-bundler/dist/node/bridge.js:150:31)
    	at async EdgeFunctionsRegistry.startServer (file:///<redacted>/node_modules/@netlify/edge-bundler/dist/node/server/server.js:39:9)
    	at async #build (file:///<redacted>/node_modules/netlify-cli/src/lib/edge-functions/registry.mjs:150:51)
    	at async #doInitialScan (file:///Users/<redacted>/node_modules/netlify-cli/src/lib/edge-functions/registry.mjs:132:7) 
{
  	errno: -88,
  	
	code: 'Unknown system error -88',
  	
	syscall: 'spawn',
  	
	originalMessage: 'spawn Unknown system error -88',
  	
	shortMessage: 'Command failed with Unknown system error -88: /Users/<redacted>/Library/Preferences/netlify/deno-cli/deno run --allow-all --import-map=data:application/json;base64,eyJpbXBvcnRzIjp7Im5ldGxpZnk6ZWRnZSI6Imh0dHBzOi8vZWRnZS5uZXRsaWZ5LmNvbS92MS9pbmRleC50cyJ9LCJzY29wZXMiOnt9fQ== --no-config --quiet /var/folders/74/0krmhkmn1hnf94gmvvw4qff40000gn/T/tmp-1653-BtDik531bzvf/dev.js --port 49283\n' +
    
	'spawn Unknown system error -88',
  command: '/Users/<redacted>/Library/Preferences/netlify/deno-cli/deno run --allow-all --import-map=data:application/json;base64,eyJpbXBvcnRzIjp7Im5ldGxpZnk6ZWRnZSI6Imh0dHBzOi8vZWRnZS5uZXRsaWZ5LmNvbS92MS9pbmRleC50cyJ9LCJzY29wZXMiOnt9fQ== --no-config --quiet /var/folders/74/0krmhkmn1hnf94gmvvw4qff40000gn/T/tmp-1653-BtDik531bzvf/dev.js --port 49283',
  
	escapedCommand: '"/Users/<redacted>/Library/Preferences/netlify/deno-cli/deno" run --allow-all "--import-map=data:application/json;base64,eyJpbXBvcnRzIjp7Im5ldGxpZnk6ZWRnZSI6Imh0dHBzOi8vZWRnZS5uZXRsaWZ5LmNvbS92MS9pbmRleC50cyJ9LCJzY29wZXMiOnt9fQ==" --no-config --quiet "/var/folders/74/0krmhkmn1hnf94gmvvw4qff40000gn/T/tmp-1653-BtDik531bzvf/dev.js" --port 49283',
  
  	exitCode: undefined,
  	signal: undefined,
  	signalDescription: undefined,
  	stdout: '',
  	stderr: '',
  	all: '',
  	failed: true,
  	timedOut: false,
  	isCanceled: false,
  	killed: false
}
```

 I am working with a team of 3, and we are all using the same exact project base and I am the only one with this error, so I am confident the project is configured properly. The only difference between us is our machines, with my teammates using m1 chips and I using an m2 chip (which shouldn't cause any problems). 

Any assistance debugging this further would be appreciated!

### Steps to reproduce

1. run netlify dev

### Environment

  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M2
    Memory: 60.11 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.0.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.1.1 - /opt/homebrew/bin/npm
  npmPackages:
    netlify-cli: ^15.8.1 => 15.8.1

**Comment by danez** [comment]
I found [this](https://github.com/Shopify/cli/issues/1817#issuecomment-1517837309) in another repo, and also [here](https://www.mongodb.com/community/forums/t/realm-cli-unknown-system-error-86/204900/4).

As far as I understood that some of the dependencies might be built for intel MacBooks and not Apple Sillicon. To solve this rosetta is needed to enable the emulation. I'm not sure why though only on M2 and not on M1.
Can you try and see if installing rosetta helps?

```
softwareupdate --install-rosetta
```

**Comment by FileManagerKim** [comment]
Hmm, interesting.

Unfortunately it appears even installing rosetta and double checking its running by checking via 

`pgrep oahd`

**Comment by danez** [comment]
It seems that the deno binary is not working.
Can you run this command in the console and post the output? I wonder if the netlify CLI download the wrong architecture of deno:
```
file /Users/<redacted>/Library/Preferences/netlify/deno-cli/deno
```

To workaround you can try:

removing the folder `/Users/<redacted>/Library/Preferences/netlify/deno-cli/`. The netlify CLI will download deno again next time you run it.

If that did not work, you can also install your own version of deno with brew for example `brew install deno`.

**Comment by FileManagerKim** [comment]
Hey @danez danez, 

Looks like wiping the deno file and letting the CLI re-install it worked. Looks like installing the CLI without rosetta installed will install the intel platform deno, so most likely to resolve this issue for anyone coming into this forward:

**for all macOS devices, be sure to install Rosetta (or Rosetta 2) before installing or running the netlify cli.**

Thumbs up for @danez and good luck for anyone else who runs into this problem!
