### ISSUE TITLE
Why it always redirects POST request to function server instead of Next.js?

### ISSUE THREAD

**Issue by dmytrobaida** [netlify/cli#5916]
https://github.com/netlify/cli/blob/b08bcac82fbd6cde8a636e806c67f01cdc261dc3/src/utils/proxy.mjs#L590C2-L597C4

I'm trying to run my project locally using netlify dev command but after some investigating I've found this part of code.
It causes a bug when I use next-auth library in my project. All post requests are handler by functions by default and it says that Function not found…
It is right but in my case I don't have this function at all. Everything is handled by next.js api routes

**Comment by dmytrobaida** [comment]
It started working when I added additional check to this statement
`functionsServer &&
    req.method === 'POST' &&
    !isInternal(req.url) &&
    (ct.endsWith('/x-www-form-urlencoded') || ct === 'multipart/form-data') 
    && isFunction(settings.functionsPort, req.url)
`
Is there reasons of this behavior? Or it should be fixed?

**Comment by myeager-innovativeinc** [comment]
@dmytrobaida — looks like this is also being tracked in #4873, for whatever that's worth to you.

**Comment by sangamk** [comment]
I am having the same issue. How did you fix it?

**Comment by serhalp** [comment]
Marking this as stale as it is a year old. Please feel free to reopen if you are still having issues.
