### ISSUE TITLE
netlify build fails to bundle edge function

### ISSUE THREAD

**Issue by maddsua** [netlify/cli#5923]
### Describe the bug

Current version of the CLI uses `@netlify/build 29.17.3` which fails to bundle any edge function in production mode.

Error log:
```bash
C:\Users\maddsua\Desktop\New folder>ntl build
​
Netlify Build
────────────────────────────────────────────────────────────────
​
> Version
  @netlify/build 29.17.3
​
> Flags
  dry: false
  offline: false
​
> Current directory
  C:\Users\maddsua\Desktop\New folder
​
> Config file
  No config file was defined: using default values.
​
> Context
  production
​
Edge Functions bundling
────────────────────────────────────────────────────────────────
​
Packaging Edge Functions from netlify\edge-functions directory:
 - hello
Could not load configuration for edge function at 'C:\Users\maddsua\Desktop\New folder\netlify\edge-functions\hello.js'
error: Uncaught (in promise) SyntaxError: The requested module '../log/logger.ts' does not provide an export named 'deta
chedLogger' at https://edge.netlify.com/bootstrap/util/redirect.ts:3:10
const { Netlify } = await import(bootstrapURL)
                    ^
    at async file:///C:/Users/maddsua/AppData/Roaming/nodejs/node_modules/netlify-cli/node_modules/@netlify/edge-bundler
/deno/config.ts:4:21
​
(Edge Functions bundling completed in 2.7s)
​
Netlify Build Complete
────────────────────────────────────────────────────────────────
​
(Netlify Build completed in 2.7s)
```

Example edge function:

```javascript
//netlify/edge-functions/hello.js

export default () => new Response("Hello world");

export const config = { path: "/test" };

```

Edge functions seem work fine in `dev` mode, this only happens when trying to build for production.

This is just a reproduction example to keep things simple, the issue can be seen in other projects too.

### Steps to reproduce

1. Download and extract this example project (or just create a new one with an edge function, does not really matter)
2. Try building it with `netlify build`
3. Get an error on edge functions bundle stage

[example.zip](https://github.com/netlify/cli/files/12261438/example.zip)

### Configuration

A totally blank configuration, just a single example edge function in a project.

### Environment

  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 22.90 GB / 31.92 GB
  Binaries:
    Node: 18.12.1 - ~\AppData\Roaming\nodejs\node.EXE
    npm: 9.7.2 - ~\AppData\Roaming\nodejs\npm.CMD

**Comment by Skn0tt** [comment]
Forget that, it looks like `deno cache --reload` doesn't mutate the global cache, but only the local one. Working on a fix! Thanks for opening the issue and bringing this to our attention!

**Comment by Skn0tt** [comment]
Once https://github.com/netlify/build/pull/5221 is released, we can pass in [`getBootstrapURL()`](https://github.com/netlify/cli/blob/b029a888358ef6d05dbc62e7d00330d0daee6e58/src/lib/edge-functions/bootstrap.mjs#L5) here: 

https://github.com/netlify/cli/blob/b029a888358ef6d05dbc62e7d00330d0daee6e58/src/utils/run-build.mjs#L39-L58

**Comment by frankroc2022** [comment]
Last working version for me is 15.2.0.
What I have to change to use a later version?

**Comment by maddsua** [comment]
> Last working version for me is 15.2.0. What I have to change to use a later version?

Looks like @Skn0tt added changes to the future version, now we just wait, I don't see anything we can do as users/customers. If you have build minutes left, you might use cloud builds instead of building locally for the time being.

**Comment by Skn0tt** [comment]
Sorry for the delay, yeah. I'm expecting a version with a fix to land today or tomorrow.

**Comment by Skn0tt** [comment]
The fix was released as part of v16.0.1. It fixed it for me, so I hope it also does for you :) If it doesn't feel free to ping & reopen the issue.

**Comment by maddsua** [comment]
Can confirm, it's working again after updating to v16.0.1. @Skn0tt thank you very much!

**Comment by frankroc2022** [comment]
> Last working version for me is 15.2.0.
> What I have to change to use a later version?

Still the same. I tested latest version v17.1.0 and v16.0.1.
