### ISSUE TITLE
Support blob storage when running deploying via the CLI

### ISSUE THREAD

**Issue by nickytonline** [netlify/cli#5988]
When chatting with @eduardoboucas we realized that you currently can not use the blob storage API if using the Netlify CLI to deploy. For a build it's expected not to work, but it should be supported for `ntl deploy`.

## Related Documents & Issues

https://netlify.slack.com/archives/C01TKAEBP3Q/p1694187798174969?thread_ts=1694187555.201599&cid=C01TKAEBP3Q

**Comment by lukasholzer** [comment]
done
