### ISSUE TITLE
fs re-evaluating native module source is not supported warning on netlify deploy

### ISSUE THREAD

**Issue by Krustal** [netlify/cli#6]
Getting a warning when running `netlify deploy -e alpha`

```
> netlify deploy "-e" "alpha"

(node:18814) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Deploying folder: _site
```

Running latest node v6.

**Comment by envygeeks** [comment]
Any news on updating dependencies?

**Comment by bcomnes** [comment]
We eliminated all native deps from the upcoming 2.0.0 release.  Feel free to reopen if the issue persists once we release that.
