### ISSUE TITLE
The onEnd build event is invoked before deploy

### ISSUE THREAD

**Issue by orinokai** [netlify/cli#6050]
### Describe the bug

The [documentation](https://docs.netlify.com/integrations/build-plugins/create-plugins/#plug-into-events) for the `onEnd` build plugin event says… “runs after completion of the deploy stage, regardless of build error or success; is useful for resources cleanup”.

However, in my testing, if I do any cleanup in this build stage then those changes affect the deploy. For example, [this plugin](https://github.com/orinokai/test-build-plugin/tree/main/plugin) deletes the index page during `onEnd` and you can see the [deploy](https://6511aca94262923db861bbea--test-rs-build-plugin.netlify.app/) has no index page.

This is different to running a build vi CI/Buildbot, where `onEnd` and `onSuccess` run after the deploy has completed.

For context, this makes it difficult to clean up artifacts created during a build with the Next Runtime. We need to manipulate the files in the publish directory and, ideally, we would do so and then revert the changes after deploy. However, we can't, so we currently workaround it by updating the publish directory in the plugin. This mutates the TOML and is reverted after deploy, but can be problematic - for example if the build is cancelled and the TOML is not reverted.

### Steps to reproduce

See the repro above

### Environment

System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 863.92 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 8.7.1 - ~/Library/pnpm/pnpm
  npmGlobalPackages:
    netlify-cli: 16.5.1

**Comment by sarahetter** [comment]
Closed CT-151
