### ISSUE TITLE
Wrong browser invocation

### ISSUE THREAD

**Issue by jcuenod** [netlify/cli#6054]
### Describe the bug

`netlify login` results in:

```
Logging into your Netlify account...
Opening https://app.netlify.com/authorize?response_type=ticket&ticket=55e28d0b05ebb54fbd8e051073c1e967
⠋ Waiting for authorization...
 ›   Error: Netlify CLI has terminated unexpectedly
```

After installing older versions, I realized this crash was caused by failure to spawn firefox.

```
Error: spawn firefox ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn firefox',
  path: 'firefox',
  spawnargs: [
    'https://app.netlify.com/authorize?response_type=ticket&ticket=c61e3b3f335675b473951919320a21d9'
  ]
}
```

Note that I tested on different versions of Node and different versions of `netlify-cli` before I figured out the issue. Symlinking `firefox` in my `$PATH` to my `firefox-developer-edition` binary solved the issue.

So two problems:
1. I couldn't debug the issue on a recent release of netlify-cli
2. Netlify-cli couldn't spawn firefox because the binary is not `firefox` on my machine, it's `firefox-developer-edition`

### Steps to reproduce

Uninstall firefox
Install firefox-developer-edition
Install netlify-cli
Try to login

### Environment

  System:
    OS: Linux 6.5 EndeavourOS
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 11.13 GB / 31.08 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.0/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
  npmGlobalPackages:
    netlify-cli: 16.6.1

**Comment by sarahetter** [comment]
Hi JC - we use `better-opn` to open browsers programatically - it uses the environment variable `BROWSER`. You can try running `BROWSER=firefox-developer-edition netlify login` or find out if you have `BROWSER=firefox` exported somewhere in your path.
