### ISSUE TITLE
Function builds fail silently

### ISSUE THREAD

**Issue by erquhart** [netlify/cli#606]
**- Do you want to request a _feature_ or report a _bug_?**
sort of both, I'd call it a bug

**- What is the current behavior?**
When running Netlify Dev, Netlify Lambda is watching and rebuilding my functions on the fly. If I break a function build, the only way to tell is that the console doesn't log the "changes detected, rebuilding" line from Lambda.

If I don't notice this, everything will still work because the last successful function build will continue to be used until I delete built files. This means I can spend a fair amount of time refactoring a function, not realizing it broke a while ago.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Using Netlify Lambda, write a broken function that will produce a failed build while Netlify Dev is running.

**- What is the expected behavior?**
The full error message and stack trace from Netlify Lambda should be allowed to print to console.

**- Local Environment Information**
Using cli 2.20.2
```
  System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.87
    Safari: 13.0.2
```

**Comment by erezrokah** [comment]
This was fixed in https://github.com/netlify/cli/pull/988 and requires latest `netlify-lambda` due to https://github.com/netlify/netlify-lambda/pull/239
