### ISSUE TITLE
.eslintrc.js in /functions causes deploy issues

### ISSUE THREAD

**Issue by JeffML** [netlify/cli#609]
I have different ESLint settings for /function than in the rest of my project. If I store these in JavaScript format, I  get the following error:

```
➜  pgnfen2 git:(cleanup) ✗ netlify deploy                                                   git:(cleanup|●23 
Deploy path:        /home/jlowery2663/projects/pgnfen2/build
Functions path:     /home/jlowery2663/projects/pgnfen2/functions
Configuration path: /home/jlowery2663/projects/pgnfen2/netlify.toml
Deploying to draft URL...
✔ Finished hashing 16 files and 2 functions
✔ CDN requesting 0 files and 1 functions
✷ (0/1) Uploading .eslintrc... ›   Warning: TextHTTPError: 404
 ›   Warning: 
 ›   TextHTTPError: Not Found
 ›
✸ (0/1) Uploading .eslintrc...TextHTTPError: Not Found
    at NetlifyAPI.uploadDeployFunction (~/.config/yarn/global/node_modules/netlify/src/open-api/index.js:173:13)
    at runMicrotasks (<anonymous>)
➜  pgnfen2 git:(cleanup) ✗ TextHTTPError: Not Found     
```

If I store them in JSON format, the issue goes away.

I didn't spot anything in the netlify.toml docs about ignoring files for deployment.

**Comment by DavidWells** [comment]
Any file in the `functions` dir will be deployed as a function right now.

You will want to keep that file out of there and in a parent directory

**Comment by JeffML** [comment]
Yes, I suspected that was happening. The parent dir is the project folder, which also contains the client website folder under /src.  So a top-level eslintrc.js configured for /functions would need to be overridden at the /src folder with another eslintrc.js.  This would also have to be done for any other sibling folder of /functions that needs a different eslint configuration.

Or I can just convert the eslintrc.js to eslintrc.json in the /functions folder like I have done. Since that doesn't get picked up by the function build process on the Netlify server, that should be okay, right? It's only a dev dependency, after all.

**Comment by sarahetter** [comment]
Closing as stale
