### ISSUE TITLE
`netlify dev` crashes when using url in an iframe

### ISSUE THREAD

**Issue by bzin** [netlify/cli#610]
**- Description of what I am trying to achieve**
I am updating my website www.bzin.net to have a blog and other pages while hosted on Netlify. The webpage uses Craft CMS to get its data and in the frontend the technical stack is Sapper and Svelte. At this moment I am trying to enable the preview feature from the CMS when its on its headless mode. This means that updating my data in Craft CMS I should be able to see current changes on an iframe before trigger a deployment. I am able to see and set this preview if I do not use Netlify dev and if I directly call my API endpoint. Although my intention is to use lambda functions on Netlify so I can do this in a more  secure way, without exposing my API and keys in the javascript.

**- Do you want to request a _feature_ or report a _bug_?**
bug

**- What is the current behavior?**
`netlify dev` breaks when url of project is loaded in an iframe.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1 - run `netlify dev`
2 - open the dev url in a browser where its in an iframe

See attached screenshot:

<img width="934" alt="Screen Shot 2019-11-04 at 11 15 57 PM" src="https://user-images.githubusercontent.com/382735/68530817-4b894680-030c-11ea-83a9-338dc7854469.png">

PS: This was posted from a suggestion in https://community.netlify.com/t/netlify-dev-crashes-when-using-url-in-an-iframe/4738/4

**- What is the expected behavior?**
to be able to continue developing when opening the url in an iframe.

**- Local Environment Information**

  **_System:_**
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  **_Binaries:_**
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.4.0/bin/npm
  **_Browsers:_**
    Chrome: 78.0.3904.97
    Firefox: 69.0.1
    Safari: 13.0.3

**Comment by mraerino** [comment]
while in this repository there might be a maintainer coming back to you, you'll probably get a faster answer on community.netlify.com

**Comment by bzin** [comment]
Thanks @mraerino, I've done that before. 

It was a Netlify member that mention there that I should post the issue here.

**Comment by RaeesBhatti** [comment]
The socket hangup has been fixed for quite some time now. Thank you for your patience and reporting this. Please update your `netlify-cli` to the latest version and let us know if it is still a problem.
