### ISSUE TITLE
Make function timeout editable OR inherit from linked site

### ISSUE THREAD

**Issue by fool** [netlify/cli#6125]
### Which problem is this feature request solving?

Users who request an increased function timeout applied to their site or account from Netlify staff frequently expect the CLI to behave like production, but it does not by default.

### Describe the solution you'd like

Perhaps a flag to specify a timeout, or automatically checking the timeout set in Netlify's system for the linked site, would be a better UX?

### Pull request (optional)

- [ ] I can submit a pull request.

**Comment by platform-kit** [comment]
@fool has there been any motion on this? I am running into this right now, and it is creating a blockage - can't work on code that currently works in production on Netlify but fails due to the 10sec timeout in `netlify dev`.
