### ISSUE TITLE
Make automatic open of the browser optional

### ISSUE THREAD

**Issue by janbaer** [netlify/cli#615]
Could it be possible to make it possible that the **netlify dev** command opens the browser automatically? My browser is constantly opened and I don't need this feature. It's also some annoying for me because the browser that I use is not the default browser. It's a special nightly build of the Chromium browser. So whenever I run the **netlify dev** command a second instance of my browser will be startet. Could you please make this *feature* optional? Thanks in advance!

**Comment by frednomoon** [comment]
massively in favour of this! very annoying at the moment

**Comment by therobinkim** [comment]
One thing I've noticed is that if I close the browser tab/window too soon after it opens up, I immediately get a `socket hang up` error and `netlify dev` crashes.

**Comment by raeesbhatti** [comment]
I've [created a PR](https://github.com/netlify/cli/pull/631) to allow the users to configure this behavior. I'll try to get this merged and released today. But in the mean time you can do a local `npm link` of `raees/autoLaunchConfig` branch to use the changes.

**Comment by raeesbhatti** [comment]
A new config parameter was added in the latest release of 2.23.0 where you can specify `autoLaunch` in your `netlify.toml` to disable the auto-launch of browser when `netlify dev` starts. e.g.
```
[dev]
  autoLaunch = false
```
