### ISSUE TITLE
Show both progress and JSON output on deployment command

### ISSUE THREAD

**Issue by kalinchernev** [netlify/cli#618]
**- Do you want to request a _feature_ or report a _bug_?**

Feature

**- What is the current behavior?**

When running a deployment command with `--json` option in this way:

```sh
netlify deploy --site 1234-5678 --message "foo" --json
```
There is no progress displayed on the output, only the end result.

**- What is the desired behavior?**

Be able to have something as:

```sh
netlify deploy --site 1234-5678 --message "foo" --json --verbose
```

Which will show progress of the deployment and will print out the json in the end.

**- What is goal of the feature?**

After moving the build processes out of netlify platform to save from build minutes, a convenient way to take deployment status is marking the `--json` flag. This output can be directred to a `.json` file later feeded into another script to set preview status on github issues similarly to Netlify preview.

However, asking for the `--json` output, deployment process' progress cannot be seen any more.

Is there a way to achieve that without having a new feature? Checked [this part of the code](https://github.com/netlify/cli/blob/master/src/commands/deploy.js#L159) and can't quite imagine what options to pass.

**Comment by DavidWells** [comment]
Hey @kalinchernev thanks for the request.

I'm not sure this would be possible. Mainly because all the `stdout` of the CLI would be parse of the response. This would effectively break the `json` if you are trying to parse it.

**Comment by kalinchernev** [comment]
Mixing types of data to the output is brittle, I agree.

Would it be better to have the listDeploys
<https://open-api.netlify.com/#operation/listSiteDeploys> as a param or
option to the deploy <https://cli.netlify.com/commands/deploy> so to get
info about the last deployment somehow and make use of it instead of the
JSON output.

**Comment by DavidWells** [comment]
Yeah what you could do it:

```
netlify deploy # to see progress
# then
netlify api listDeploys --json ....other args
```

I'd recommend putting 2 commands together. We can't support terminal piping if we add non JSON output to the deployment command

**Comment by kalinchernev** [comment]
Of course, that's what I meant, 2 commands. Managed to get deploys info with 

```
netlify api listSiteDeploys --data '{ "site_id": "1234-5678"}' > deploys.json
```

From the `deploys.json` it's easy to find the necessary info.

Thanks for pointing out to the `api` command, didn't know about it! :)
