### ISSUE TITLE
Error: unable to show help on `sites` or `addons` with Volta

### ISSUE THREAD

**Issue by DirtyF** [netlify/cli#633]
**- Do you want to request a _feature_ or report a _bug_?**

Bug 🐛 

**- What is the current behavior?**

Some commands like `sites` or `addons` don't show help by default on 2.23.0 when installed through https://volta.sh

**- If the current behavior is a bug, please provide the steps to reproduce.**

```
curl https://get.volta.sh | bash
volta install netlify-cli
netlify sites
/bin/sh: netlify: command not found
Error: Command failed: netlify sites --help
    at showHelp (~/.volta/tools/image/packages/netlify-cli/2.23.0/src/utils/show-help.js:4:3)
    at SitesCommand.run (~/.volta/tools/image/packages/netlify-cli/2.23.0/src/commands/sites/index.js:11:7)
    at SitesCommand._run (~/.volta/tools/image/packages/netlify-cli/2.23.0/node_modules/@oclif/command/lib/command.js:44:31)
netlify addons
netlify addons
/bin/sh: netlify: command not found
Error: Command failed: netlify addons --help
    at showHelp (~/.volta/tools/image/packages/netlify-cli/2.23.0/src/utils/show-help.js:4:3)
    at AddonsCommand.run (~/.volta/tools/image/packages/netlify-cli/2.23.0/src/commands/addons/index.js:11:7)
    at AddonsCommand._run (~/.volta/tools/image/packages/netlify-cli/2.23.0/node_modules/@oclif/command/lib/command.js:44:31)
```

**- What is the expected behavior?**

show help

**- Local Environment Information**

  System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
  Binaries:
    Node: 12.13.1 - ~/.volta/tools/image/node/12.13.1/6.12.1/bin/node
    Yarn: 1.19.0 - ~/.volta/tools/image/yarn/1.19.0/bin/yarn
    npm: 6.12.1 - ~/.volta/tools/image/node/12.13.1/6.12.1/bin/npm

**Comment by DavidWells** [comment]
Is the CLI installed locally in your project or globally on the machine?

**Comment by DirtyF** [comment]
Globally through https://volta.sh

**Comment by DavidWells** [comment]
Interesting. How do you install the CLI via https://volta.sh 

Sounds like the CLI bin path is wrong when installing that way

**Comment by DavidWells** [comment]
More specifically when `showHelp` is called, we shell out to the globally installed `netlify` binary here https://github.com/netlify/cli/blob/0de2228ef2002a8ef7a85923570a3d4e6c64b134/src/utils/show-help.js#L4

I'm unfamiliar with volta.sh, is it installing things in a special way?

Follow up, is it possible to just install via `npm` with `npm install netlify-cli -g` ?

**Comment by DirtyF** [comment]
Volta does not support global install for now (it's kind of the point of Volta).

@charlespierce would know better how Volta install things.

**Comment by charlespierce** [comment]
Hi @DirtyF @DavidWells This is almost assuredly an issue with Volta itself, and not `netlify-cli`. One of our bigger remaining pain points at the moment is global tools calling global tools, see https://github.com/volta-cli/volta/issues/492

To clarify so I have the full context, the `netlify` command here shells out to itself (with the `--help` flag added) in these situations?

**Comment by DirtyF** [comment]
```netlify sites --> netlify sites --help
netlify addons --> netlify addons --help

**Comment by charlespierce** [comment]
Okay, thanks for clarifying! Given that, this is definitely the same issue as described in https://github.com/volta-cli/volta/issues/492 above, an issue within Volta itself. I think this is the first use-case I've seen where a tool calls itself through the command-line, but that would result in the same behavior we've seen when tools call other tools.

@DavidWells This shouldn't need any changes on the `netlify-cli` side.
