### ISSUE TITLE
Netlify Dev fails using v2.22.0, v2.23.0

### ISSUE THREAD

**Issue by talves** [netlify/cli#634]
There is an issue running [this repository](https://github.com/ChristopherBiscardi/party-corgi-discord-automations) with `netlify dev` on version > v2.21.0 (2.21.0 is working)

![image](https://user-images.githubusercontent.com/784848/70350531-c1a1a000-181b-11ea-8c92-1436b859151c.png)

**- What is the current behavior?**
If using `v2.21.0` of `netlify-cli`, the server will start without issue.

![image](https://user-images.githubusercontent.com/784848/70352241-8903c580-181f-11ea-9241-01d5c22621b0.png)

When running `v2.22.0` or greater, the server errors out and does not wait.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Clone the repository above at [this head](https://github.com/ChristopherBiscardi/party-corgi-discord-automations/tree/43d449440175c332fe3a708fb3a904fe8a6552e2)
Use `v2.22.0` or `v2.23.0` of `netlify-cli` to run `netlify dev`

**- What is the expected behavior?**

When running `v2.22.0` or greater, the server should wait.

**- Local Environment Information**

This was confirmed on windows and mac.

**Comment by raeesbhatti** [comment]
Thanks for reporting this @talves . Please try the latest release and let us know if the issue persists.

**Comment by ryancharris** [comment]
I am also experiencing this issue 👍

**Comment by raeesbhatti** [comment]
@ryancharris can you please upgrade to the latest version and report if you're still having this problem.

**Comment by talves** [comment]
Yes, it still has that error. If you checkout the repository I linked above, you can check it also.

**Comment by futuregerald** [comment]
Forgive me if I re-opened this in error but it seems like it's not fixed for @talves . Are you still having the same problem?

**Comment by talves** [comment]
Thanks @futuregerald , yes, this is still an issue and having the same issue. Just tested with v2.25.0 (failed).

**Comment by RaeesBhatti** [comment]
@talves Is this still an issue with latest version?
cc @ryancharris

**Comment by talves** [comment]
Just updated to version 2.40.0 and ran on Windows using Powershell and then using WSL (Ubuntu) and all is working as expected calling the functions. 🎉😃

I will close this and @ryancharris can request a re-open if it does not work on Mac.

Thanks for the hard work on this everyone!

**Comment by talves** [comment]
Just a note. I've been running and testing some `netlify functions` heavily in Windows using `netlify dev` and they have been working well using WSL. I forgot about this issue, and apologize for not circling back earlier.

Thanks for the heads up @RaeesBhatti

**Comment by RaeesBhatti** [comment]
Glad it worked for you! 🎉
