### ISSUE TITLE
[dev] Functions folder doesn’t get served if initially empty

### ISSUE THREAD

**Issue by kripod** [netlify/cli#638]
**- Do you want to request a _feature_ or report a _bug_?**

I would like to report a bug.

**- What is the current behavior?**

When running `netlify dev` with `build.functions` in `netlify.toml` pointing to a non-existing folder, functions generated in watch mode aren’t served via HTTP.

Reproduction: Run `yarn netlify dev` (instead of `yarn develop`) in the root of [kripod/exigo](https://github.com/kripod/exigo)

**- What is the expected behavior?**

Functions generated on the fly should be available in development mode.

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
