### ISSUE TITLE
Missing Types Package Event Dev Warn More Info Link 404s (typo)

### ISSUE THREAD

**Issue by hu0p** [netlify/cli#6400]
### Reference:
https://github.com/netlify/cli/blob/0c91f20e14e84e9b21d39d592baf10c7abd8f37c/src/lib/functions/registry.ts#L352-L357

Judging by the surrounding context, the link should be https://ntl.fyi/function-types. However, that link just redirects to https://www.netlify.com/?utm_campaign=devex&utm_source=shortlink&utm_medium=bitly, so it looks like it's out of date anyway.

**Comment by eduardoboucas** [comment]
The link has now been fixed and is pointing to the right place.

I'm sorry for the inconvenience and thank you for reporting it!

**Comment by hu0p** [comment]
No problem. Figured it was probably a combination of a bystander effect thing and something just getting lost in transit. Thanks for speedy fix! Good documentation is worth its weight in gold 💛
