### ISSUE TITLE
DNS configurations

### ISSUE THREAD

**Issue by ccsouthard** [netlify/cli#6417]
To whom it may concern:
it has been a while since I have looked at this particular site – however I cannot find the current domain  register company.
 the website appears to be working fine, however I can't recall what would have created a glitch
any and all thoughts are welcomed
  URL: https://app.netlify.com/sites/registrar-perfect-71167/configuration/general

**Comment by ramonsnir** [comment]
For general Netlify support inquiries please post here: https://answers.netlify.com/
