### ISSUE TITLE
[bug] Missing required param site_id

### ISSUE THREAD

**Issue by ItsCosmas** [netlify/cli#642]
**- Do you want to request a _feature_ or report a _bug_?**
Report a bug

**- What is the current behavior?**
running ```netlify deploy```  and following the prompts to select an existing site raises an error.

```
Site id saved to D:\Web\itscosmas\.netlify\state.json

You can now run other `netlify` cli commands in this directory
Deploy path: D:\Web\itscosmas\.netlify\build
Deploying to draft URL...
√ Finished hashing 0 files
- CDN diffing files... »   Warning: 
 »   {}
 »
\ CDN diffing files...Error: Missing required param site_id
    at Object.values.forEach.param (C:/Users/Cozy/AppData/Roaming/npm/node_modules/netlify-cli/node_modules/netlify/src/open-api/index.js:34:15)
    at Array.forEach (<anonymous>)
    at NetlifyAPI.createSiteDeploy (C:/Users/Cozy/AppData/Roaming/npm/node_modules/netlify-cli/node_modules/netlify/src/open-api/index.js:28:43)
    at module.exports (C:/Users/Cozy/AppData/Roaming/npm/node_modules/netlify-cli/node_modules/netlify/src/deploy/index.js:77:26) 
```
**_ Additional information
on the ```.netlify/state.json``` file under I see the site id is set as ```
{
 "siteId":"<the id string>"
} ```

**_ Suggestion*
- This could be an issue with ``camelCase`` and ``snake_case`` for the ``site_id`` param
- Inside the `.netlify` folder there's a `build` folder, when deploying my reacts apps the netlify cli used to ask for the directory then I'd point it to my `build` to deploy but it doesn't ask in this latest update.

**- What is the expected behavior?**
Site should deploy normally without any issue

**- Local Environment Information**
This is on Node `Windows 10` ``v10.16.3``

**Comment by DavidWells** [comment]
Can you share the repo / directory structure of the site you are trying to deploy?

Also what operating system is this running on?

Thanks!

**Comment by ItsCosmas** [comment]
- Using the ``create-react-app`` directory structure.
- Had this issue on `Windows 10` `Node v10.16.3` and on `Ubuntu 18.04 LTS` `Node v10.17.0`. 
- Also kindly notice that I'm able to reproduce this exact issue after removing the `.netlify` folder and running the `netlify deploy` command again. 
- However if I run the deploy command with the `.netlify` folder present this is the stacktrace I get, Please Note it doesn't prompt me to enter the deploy path, also not sure if this output exposes any potential risky private data.
```
netlify deploy --prod
Deploy path: /home/cozy/projects/itscosmas/.netlify/build
Deploying to live site URL...
✔ Finished hashing 0 files
✔ CDN requesting 0 files
✔ Finished uploading 0 assets
└ Waiting for deploy to go live... ›   Warning: 
 ›   {
 ›      "deploy": {
 ›        "id": "<id string>",
 ›        "site_id": "<side id string>",
 ›        "build_id": null,
 ›        "state": "error",
 ›        "name": "<site name>",
 ›        "url": "<site url>",
 ›        "ssl_url": "<ssl url>",
 ›        "admin_url": "<admin url>",
 ›        "deploy_url": "<deploy url>",
 ›        "deploy_ssl_url": "<deploy ssl url>",
 ›        "created_at": "2019-12-09T20:45:17.915Z",
 ›        "updated_at": "2019-12-09T20:46:19.371Z",
 ›        "user_id": "<user id string>",
 ›        "error_message": "Deploy canceled",
 ›        "required": [],
 ›        "required_functions": null,
 ›        "commit_ref": null,
 ›        "review_id": null,
 ›        "branch": null,
 ›        "commit_url": null,
 ›        "skipped": null,
 ›        "locked": null,
 ›        "log_access_attributes": {
 ›          "type": "firebase",
 ›          "url": "https://netlify-builds3.firebaseio.com/deploys/5deeb25d704548019e678c3b/log",
 ›          "endpoint": "https://netlify-builds3.firebaseio.com",
 ›          "path": "/deploys/5deeb25d704548019e678c3b/log",
 ›          "token": "<token>"
 ›        },
 ›        "title": null,
 ›        "review_url": null,
 ›        "published_at": null,
 ›        "context": "production",
 ›        "deploy_time": null,
 ›        "available_functions": [],
 ›        "summary": {
 ›          "status": "unavailable",
 ›          "messages": []
 ›        },
 ›        "screenshot_url": null,
 ›        "site_capabilities": {
 ›          "title": "Netlify Team Free",
 ›          "asset_acceleration": true,
 ›          "form_processing": true,
 ›          "cdn_propagation": "partial",
 ›          "build_gc_exchange": "buildbot-gc",
 ›          "build_node_pool": "buildbot-external-ssd",
 ›          "domain_aliases": true,
 ›          "secure_site": false,
 ›          "prerendering": true,
 ›          "proxying": true,
 ›          "ssl": "custom",
 ›          "rate_cents": 0,
 ›          "yearly_rate_cents": 0,
 ›          "cdn_network": "free_cdn_network",
 ›          "ipv6_domain": "cdn.makerloop.com",
 ›          "branch_deploy": true,
 ›          "managed_dns": true,
 ›          "geo_ip": true,
 ›          "split_testing": true,
 ›          "id": "nf_team_dev"
 ›        },
 ›        "committer": null,
 ›        "skipped_log": null,
 ›        "manual_deploy": false
 ›      }
 ›   }
 ›
Error: Deploy <id> had an error
    at loadDeploy (/usr/lib/node_modules/netlify-cli/node_modules/netlify/src/deploy/util.js:92:29)
├ Waiting for deploy to go live...(base) 
```

**Comment by ItsCosmas** [comment]
actually I have faced this issue with another app that was otherwise deploying okay through the cli since like 2 or 3 days ago after cli update.

**Comment by XhmikosR** [comment]
Unfortunately this issue is very old. You need to run the command twice or run `netlify link` before deploy. I don't like it either, but that's what works for me.

**Comment by ItsCosmas** [comment]
Unfortunately `netlify link` or running the command twice doesn't work for me and thus I've resulted to using netlify CI/CD instead of the  cli for the moment.

> Unfortunately this issue is very old. You need to run the command twice or run `netlify link` before deploy. I don't like it either, but that's what works for me.

Unfortunately `netlify link` or running the command twice doesn't work for me and thus I've resulted to using netlify CI/CD instead of the  cli for the moment.

**Comment by raeesbhatti** [comment]
We've just released a new version with a fix for this bug. Please update to the latest version of `netlify-cli` and let us know if it's still a problem.

**Comment by ItsCosmas** [comment]
> We've just released a new version with a fix for this bug. Please update to the latest version of `netlify-cli` and let us know if it's still a problem.

Using the new cli version, `2.25.0`:
 - it doesn't ask for the deploy folder
- its stuck at `Waiting for deploy to go live` and eventually times out
- This is the stacktrace :
```
(base) cozy@Cozy:~/projects/itscosmas$ netlify deploy --prod
This folder isn't linked to a site yet
? What would you like to do? Link this directory to an existing site

netlify link will connect this folder to a site on Netlify

? How do you want to link this folder to a site? Choose from a list of your recently updated sites
Fetching recently updated sites...

? Which site do you want to link? itscosmas

Directory Linked

Admin url: https://app.netlify.com/sites/itscosmas
Site url:  itscosmas.me

Site id saved to /home/cozy/projects/itscosmas/.netlify/state.json

You can now run other `netlify` cli commands in this directory
Deploy path: /home/cozy/projects/itscosmas/.netlify/build
Deploying to live site URL...
✔ Finished hashing 0 files
✔ CDN requesting 0 files
✔ Finished uploading 0 assets
Waiting for deploy to go live... ›   Warning: 
 ›   {
 ›      "name": "TimeoutError"
 ›   }
 ›
TimeoutError: Promise timed out after 1200000 milliseconds
    at Timeout.setTimeout [as _onTimeout] (/usr/lib/node_modules/netlify-cli/node_modules/p-timeout/index.js:27:54)

```

**Comment by DavidWells** [comment]
Can you verify that your built site files are in `/home/cozy/projects/itscosmas/.netlify/build`

The deployment appears to be trying to deploy an empty directory

**Comment by ItsCosmas** [comment]
> Can you verify that your built site files are in `/home/cozy/projects/itscosmas/.netlify/build`
> 
> The deployment appears to be trying to deploy an empty directory

My build files ain't there, they are here `/home/cozy/projects/itscosmas/build` , previously I use to be prompted to enter a  folder to deploy everytime I ran the deploy command. Since `2.24.0` I never get the prompt.

**Comment by DavidWells** [comment]
Can you set a `build.publish` directory in the `netlify.toml` file? https://docs.netlify.com/configure-builds/file-based-configuration/ 

This should solve the problem.

```
[build]
  publish = "build"
```

Alternatively, you can use `netlify deploy --dir build` to specific the correct deploy directory.

**Comment by ItsCosmas** [comment]
> Can you set a `build.publish` directory in the `netlify.toml` file? https://docs.netlify.com/configure-builds/file-based-configuration/
> 
> This should solve the problem.
> 
> ```
> [build]
>   publish = "build"
> ```
> 
> Alternatively, you can use `netlify deploy --dir build` to specific the correct deploy directory.

Hey both the `netlify.toml` file and `netlify deploy --dir <your directory>` command deploys correctly. Thanks that seems to solve the issue.
