### ISSUE TITLE
[bug] Command netlify dev` dies immediately (v2.25.0)

### ISSUE THREAD

**Issue by b3u** [netlify/cli#647]
**- Do you want to request a _feature_ or report a _bug_?**
Bug
**- What is the current behavior?**
After updating the cli to v2.25.0, the command `netlify dev` crashes without error immediately after the server launches.
**- If the current behavior is a bug, please provide the steps to reproduce.**
Run `netlify dev` with netlify cli v2.25.0
**- What is the expected behavior?**
Server from `netlify dev` stays live.
**- Local Environment Information**
```sh
──────────────────────┐
 Current Netlify User │
──────────────────────┘
Name:  Binyamin Aron Green
Email: ************
Teams: 
  Greenhouse Tech: Collaborator
 »   Warning: Did you run `netlify link` yet?
 »   Error: You don't appear to be in a folder that is linked to a site
```

**Comment by RaeesBhatti** [comment]
@b3u Thanks for reporting this. It should have been fixed with the latest update. Please reopen if that's not the case.
