### ISSUE TITLE
[dev] pass process.exit() to child processes

### ISSUE THREAD

**Issue by waynevanson** [netlify/cli#653]
**- Do you want to request a _feature_ or report a _bug_?**
Bug

**- What is the current behavior?**
Pressing `CTRL + C` after running ~~`netlify dev:exec "parcel src/index.html"`~~ `netlify dev -c parcel src/index.html` closes only the netlify server. It should close both, so when I restart the server it can run both again. Instead, I end up with x11 servers running.

edit: I'm using the TOML to set the command, so I changed above to match.

**- If the current behavior is a bug, please provide the steps to reproduce.**
These are mentioned above.

**- What is the expected behavior?**
Both servers close when I press `CTRL + C` on keyboard in terminal

**- Local Environment Information**

```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 13.1.0 - ~/.nvm/versions/node/v13.1.0/bin/node
    Yarn: 1.19.2 - /usr/bin/yarn
    npm: 6.13.0 - ~/.nvm/versions/node/v13.1.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
```

I'd love to write a pull on this.

**Comment by raeesbhatti** [comment]
@waynevanson Thanks for reporting this. A PR would be very welcome!

**Comment by cco3** [comment]
This still seems to be a problem when using "--offline --dir"

**Comment by cco3** [comment]
I just tried `2.35.0` and still have a problem when using `--dir`. No `--dir` flag works fine now.

@RaeesBhatti Can you confirm that the fix should work with `--dir`?

**Comment by RaeesBhatti** [comment]
No longer a problem. Please upgrade to latest version `netlify-cli@2.45.0` and let us know if the problem persists. =
