### ISSUE TITLE
localhost:8888 not showing up after update

### ISSUE THREAD

**Issue by hyliancoder** [netlify/cli#659]
Ever since updating to 2.25.0 I cant get a server to run.

it no longer shows the 

`   ┌──────────────────────────────────────────────────────────────┐`
  ` │                                                              │`
   `│   [Netlify Dev] Server now ready on http://localhost:8888    │`
   `│                                                              │`
  ` └──────────────────────────────────────────────────────────────┘`

box and shows endless dots and never serves the files on a new port where the functions are working.

`Netlify Dev ◈
◈ Starting Netlify Dev with create-react-app
◈ Function builder netlify-lambda detected: Running npm script build:lambda
 ›   Warning: ◈ This is a beta feature, please give us feedback on how to improve at https://github.com/netlify/cli/
yarn run v1.21.1
$ react-scripts start
Starting the development server...

Waiting for localhost:3000.
◈ Lambda server is listening on 57397

Connected!
Waiting for localhost:34567...◈ lambda/open-graph-preview.js modified, reloading...
..................................................................................................Compiling...
.Compiled with warnings...................................................................................................` 

those warnings being linter warnings that show up when running the normal `yarn start` as well so nothing blocking it from serving. 

was working fine on 2.21.0. but now even when i roll back to 2.21.0 it still no longer works.

**Comment by reesecode** [comment]
after looking at the other issue here: https://github.com/netlify/cli/issues/657

thankfully rolling back to `2.11.13` got it working again, but for sure a pain that I cant update.

**Comment by michalhudecek** [comment]
Same issue here

**Comment by narrative1st** [comment]
Same issue. Rolled back to 2.11.13, endless dots remain...

**Comment by abettermap** [comment]
I think this is the same problem as #657.

**Comment by narrative1st** [comment]
Yes, and I was able to get it back working with a combination of rewriting some of Nuxt's default build scripts, and rolling back to `2.12.0` for `netlify-cli`.

**Comment by reesecode** [comment]
> I think this is the same problem as #657.

for sure, just unfortunately outside of being an issue with gatsby it seems. as my project frontend is just a CRA with apollo

**Comment by lazno** [comment]
same problem here with CRA. tried out versions 2.11.13, 2.12.0 and current 2.25.0 - to no avail

**Comment by SteveALee** [comment]
Arrg - I also hit this during my first experience of netlify-cli and functions using latest gatsby. I spent all the time I had to explore this try to debug / fix

https://community.netlify.com/t/netlify-dev-port-unknown/6705

Rolling back to netlify-cli@2.11.13 fixed it for me, though functions:invoke seems to be missing I could invoke via HTTP GET and an ReactJS button action.

I nearly gave up on netlify, but guess a bad release over the holiday is something anyone can do

**Comment by woubuc** [comment]
I'm having the same problem with Parcel atm. I tried rolling back to v2.11.13 and v2.12.0 as mentioned in earlier comments, but neither of those worked. It just kept displaying the endless dots.

**Comment by SteveALee** [comment]
@woubuc did you definitely uninstall the more recent version first eg `npm r -g netlify-cli`. Also check you don't have it also installed for the project? I'm not sure what search order npm performs.

Oh, I'm on Windows but I doubt that makes any difference

**Comment by woubuc** [comment]
Yep, I uninstalled and checked that it couldn't find the binary anymore before reinstalling 2.11.13.

I'm on Windows as well - Windows 10, Node v12.9.1, npm v6.10.2.

**Comment by abettermap** [comment]
Maybe try that version of netlify with an older version of Node if you can. This combo is working for me (Mac obviously):

```bash
netlify --version

# outputs:
netlify-cli/2.11.13 darwin-x64 node-v10.18.0
```

**Comment by SteveALee** [comment]
@abettermap @woubuc Good call, though I have `netlify-cli/2.11.13 win32-x64 node-v12.14.0` and all seems good.

**Comment by apuyou** [comment]
For those of you following here, 2.26.0 was just released and has some fixes for this!
@hyliancoder Does this fix your issue?

**Comment by hyliancoder** [comment]
> For those of you following here, 2.26.0 was just released and has some fixes for this!
> @hyliancoder Does this fix your issue?


It did! 

Had to force install as it failed to write as the folder already existed when trying to just `npm i -g netlify-cli` gave me this

`npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/netlify-cli/bin/run
npm ERR! dest /usr/local/bin/ntl
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/netlify-cli/bin/run' -> '/usr/local/bin/ntl'
npm ERR! File exists: /usr/local/bin/ntl
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
`

but doing the --force worked

but yeah, works again on latest version AWW YISS

**Comment by abettermap** [comment]
Looks like the fix/es worked, I am seeing `localhost:8888` again as well although getting some new warnings:

> *MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGBREAK listeners added to [process]. Use emitter.setMaxListeners() to increase limit*

#### Environment
```bash
node -v && npm -v && netlify -v

v12.14.0
6.13.4
netlify-cli/2.28.0 darwin-x64 node-v12.14.0
```

**Comment by apuyou** [comment]
@abettermap I've seen this too but I am not sure it is related to the ports issues. You should probably create a new issue so that it gets tracked if there is not one already.

**Comment by abettermap** [comment]
I'm actually still seeing the original issue:

![image](https://user-images.githubusercontent.com/4974087/73127131-0246ab80-3f79-11ea-88c0-2d6f4c8fe9ab.png)

### Environment

Same environment as my previous comment on January 9, but I changed some things in my project:

### package.json `scripts`

```diff
     "build": "gatsby build && (cd lambda && npm install)",
-    "start": "rm -rf .cache/caches/gatsby-plugin-mdx && netlify dev"
+    "start": "rm -rf .cache/caches/gatsby-plugin-mdx && gatsby develop -H 0.0.0.0"
   }
```

### netlify.toml

```diff
-[dev]
-  command = "gatsby develop"
+# [dev]
```

### Upgrading to netlify `2.30.0`

Would that resolve any of this? Happy to test other scenarios if needed.
