### ISSUE TITLE
TextHTTPError: Forbidden

### ISSUE THREAD

**Issue by dehghani-mehdi** [netlify/cli#660]
**- Do you want to request a _feature_ or report a _bug_?** I think it's a bug

**- What is the current behavior?**
I get `TextHTTPError: Forbidden` for _almost_ all cli commands

**- If the current behavior is a bug, please provide the steps to reproduce.**
If it's not a bug, I have no idea how I can fix it.

**- What is the expected behavior?**
Cli should work.

**- Local Environment Information**
Paste the results of `netlify status --verbose` here

Screenshot:
![netlify](https://user-images.githubusercontent.com/9152330/71238868-62af5100-231a-11ea-9a55-86ac0972de6c.png)

**Comment by RaeesBhatti** [comment]
@dehghani-mehdi Can you try `netlify logout` and `netlify login`!

**Comment by RaeesBhatti** [comment]
It could also be that the user you're logged in as doesn't have access to the site your project is linked to. In that case, doing `netlify unlink` and `netlify link` again might help.

**Comment by dehghani-mehdi** [comment]
> @dehghani-mehdi Can you try netlify logout and netlify login!

I set the `NETLIFY_AUTH_TOKEN` variable manually, should I try with new token?

> It could also be that the user you're logged in as doesn't have access to the site your project is linked to

I don't think so, I have only one Netlify account.

**Comment by RaeesBhatti** [comment]
Yes, try with a new token and see if that fixes the problem.

**Comment by dehghani-mehdi** [comment]
I just tried, but nothing changes.

I should point out, the `netlify login` also failed, that's why I set the token manually. so I think this issue is not related to token or user account.

**Comment by alvaroseparovich** [comment]
> @dehghani-mehdi Can you try `netlify logout` and `netlify login`!

Thank you @dehghani-mehdi , It worked for me, I could try it by my self, but the 'netlify help' do not show logout command...
Maybe someone can do a PR to fix it, unfortunately I currently have no time, if there is someone to do it would be awesome. 
Thank you man

**Comment by erezrokah** [comment]
Might be related to https://github.com/netlify/cli/issues/174, but not sure.
Revoking the CLI app permissions or using an invalid token results in `TextHTTPError: Unauthorized` and not `TextHTTPError: Forbidden` as specified in the original issue.

**Comment by joallard** [comment]
Confirming I got this too. Catching Unauthorized might be nice.

**Comment by vmohir** [comment]
The problem is that the login request is blocked in Iran. Use a VPN @dehghani-mehdi 

In my case, strangely my VPN wasn't working only for netlify! So I just switched to another VPN

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
