### ISSUE TITLE
Netlify dev --live "You can now view..." overwrites link to netlify

### ISSUE THREAD

**Issue by witcradg** [netlify/cli#666]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
This is a bug

**- What is the current behavior?**
When I run the “netlify dev --live” command, the output is written to my Linux terminal. This includes the commands being executed and their results (e.g. success). It also includes the link to the “live” server needed to click on to run it from the Netlify servers. In my local terminal the link is displayed then immediately overwritten by the “You can now view my-app in the browser.” line. I suspect this is a result of how the terminal his handling certain characters being written. Can you help? I’ve copied a section of the output below. The link should appear above the localhost:8000 line.

⠇ Building development bundle
——————————————————————————————————————
3 pages In Progress my-app

┌───────────────────────────────────────────────────┐
⠀
You can now view my-app in the browser.
⠀
http://localhost:8000/

**- If the current behavior is a bug, please provide the steps to reproduce.**
In a Linux termina (currently running Ubuntu 19.10) enter
netlify dev --live

**- What is the expected behavior?**
The link to the netlify server should display and not be overwritten by subsequent steps

**- Local Environment Information**
Paste the results of `netlify status --verbose` here
dean@ubuntu-ldt:~/projects/gatsby/csio-test2$ netlify status --verbose
──────────────────────┐
 Current Netlify User │
──────────────────────┘
Name:  Dean Witcraft
Email: witcradg@gmail.com
Teams: 
  Dean Witcraft's team: Collaborator

────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (4) x64 AMD Athlon 200GE with Radeon Vega Graphics
  Binaries:
    Node: 10.18.0 - /usr/bin/node
    npm: 6.13.4 - /usr/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 71.0

────────────────────┐
 Netlify Site Info  │
────────────────────┘
Current site: csio-test2
Netlify TOML: /home/dean/projects/gatsby/csio-test2/netlify.toml
Admin URL:    https://app.netlify.com/sites/csio-test2
Site URL:     https://csio-test2.netlify.com
Site Id:      e318cfe9-6b79-44da-99ec-7b19e5d1bb2e

**Comment by witcradg** [comment]
This is a screenshot of the terminal that I reproduced in text form (copy and paste) in the bug report
![bug-report](https://user-images.githubusercontent.com/3721839/71375995-ebc1c480-2574-11ea-92a9-965566bdde0a.png)

**Comment by moreguppy** [comment]
+1
