### ISSUE TITLE
versions newer than 2.21 have trouble with some deploys hanging at "waiting for deploy to go live"

### ISSUE THREAD

**Issue by fool** [netlify/cli#667]
**- Do you want to request a _feature_ or report a _bug_?**

bug

**- What is the current behavior?**

versions >2.21 can fail to complete deploys, "waiting for deploy to go live".  Two customers saw it and the fix worked for both, as described in this thread:   https://community.netlify.com/t/formerly-working-cli-deploys-now-hanging-on-waiting-for-deploy-to-go-live/6519

**- If the current behavior is a bug, please provide the steps to reproduce.**

I've asked the affected customers to post more details about their situations in comments.

**- What is the expected behavior?**

Deploys would either go live, or timeout usefully.

**- Local Environment Information**
hopefully the affected customers will post their info in the comments below.

**Comment by jumpalottahigh** [comment]
Same issue here when trying to deploy: https://github.com/jumpalottahigh/blog.georgi-yanev.com via netlify cli. Can confirm that rolling back to version `2.21.0` deploys successfully.

**Comment by leokyeung** [comment]
Same issue happening to me too

**Comment by swest06** [comment]
Same thing happened to me today. Timed out after 20 mins.

**Comment by notimewaste** [comment]
same thing happend for me ,worked on 2.21 👍

**Comment by javierfuentesm** [comment]
same issue

**Comment by splinterific** [comment]
looks like this was previously reported too - https://github.com/netlify/cli/issues/634

**Comment by hyliancoder** [comment]
same here https://github.com/netlify/cli/issues/659

**Comment by mrlubos** [comment]
Looks like this will be fixed soon thanks to https://github.com/netlify/cli/pull/674

**Comment by apuyou** [comment]
@mrlubos I haven't tested it for this bug, but #674 has already been released to 2.26.0 if you want to try it out :)

**Comment by mrlubos** [comment]
@apuyou I can confirm this issue has now been fixed. Thank you for the fix!

**Comment by amiroff** [comment]
Looks like netlify-cli@2.31.0 broke it again :/

**Comment by alejo4373** [comment]
Can confirm netlify-cli@2.31.0 hangs as described above. 👍 If you are encountering the same issue.

**Comment by fool** [comment]
We are still getting more reports in community of this with 2.31.0:  https://community.netlify.com/t/deploy-is-stuck-from-cli-web/8702

**Comment by fool** [comment]
(Reopening this bug, since it appears to be affecting current version)

**Comment by 0Ky** [comment]
Running _**'netlify-cli/2.32.0 linux-x64 node-v13.7.0'**_ and I can confirm that it hangs at _**'waiting for deploy to go live...'**_ after prompting the command `netlify deploy`.

**Comment by likanzhan** [comment]
> Same issue here when trying to deploy: https://github.com/jumpalottahigh/blog.georgi-yanev.com via netlify cli. Can confirm that rolling back to version `2.21.0` deploys successfully.

Could you let me know how can I roll back to version `2.21.0'?, Thanks

**Comment by codex-zaydek** [comment]
`netlify-cli/2.32.0 darwin-x64 node-v13.8.0` same here. Will continue to use the web app for now.

**Comment by whalesingswee** [comment]
`netlify-cli/2.32.0 darwin-x64 node-v12.14.0` having issues as well. Stucked in **Waiting for deploy to go live**.

**Comment by makadi88** [comment]
I have this same issue with netlify-cli/2.35.0 here.
Can you guys help me how to roll back to a previous version?

**Comment by amiroff** [comment]
> I have this same issue with netlify-cli/2.35.0 here.
> Can you guys help me how to roll back to a previous version?

`npm i -g netlify-cli@2.21.0` would do it.

**Comment by cperault** [comment]
I am also having this issue (netlify-cli/2.35.0 darwin-x64 node-v13.8.0), so I've rolled back to 2.21.0 and the CLI seems to be successful on `netlify deploy --prod` once more, but hopefully this can get resolved as it's been a recurring break. 🤞

**Comment by RaeesBhatti** [comment]
Thank you all for reporting this issue and hanging in there. We've identified the problem and confirmed a fix (https://github.com/netlify/cli/pull/726). The changes will be released soon. Thanks

**Comment by RaeesBhatti** [comment]
A few for this has been published recently. Please update to latest version of `netlify-cli` and let us know if it is still a problem.
