### ISSUE TITLE
Functions Not Found when Invoked using Gridsome

### ISSUE THREAD

**Issue by miljan-aleksic** [netlify/cli#670]
**- Do you want to request a _feature_ or report a _bug_?**

Report a bug or missleading behaviour.

**- What is the current behavior?**

When invoking a function with `netflix functions:invoke` it prompts asking which function to execute, but once executed it displays the following:

```<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /.netlify/functions/hello-world was not found on this server.</p>
</body></html>
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

I am not sure if its a bug or a missuse on my part. I don't know if the functions are supposed to be invokable as standalone or they always require a netlify dev session running in the background, I tried both with same result.

Or if I am missing some configuration, in which case the CLI should warn about.

Perhaps it all has to do with the fact I am using Gridsome?

**- What is the expected behavior?**

I would expect being able to invoke a function locally without anything else but running `netlify functions:invoke` as stated in the documentation.

**- Local Environment Information**

 System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 70.0.1
    Safari: 13.0.4

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
