### ISSUE TITLE
Netlify init command - No Matching Site Found

### ISSUE THREAD

**Issue by jamesgrubb** [netlify/cli#671]
**- Do you want to request a _feature_ or report a _bug_?**
Bug
**- What is the current behaviour?**
In the console when entering netlify init and choosing link to exisitng site. I get the error 'No Matching Site Found'
**- If the current behaviour is a bug, please provide the steps to reproduce.**
run npx create-react-app
git init
git add .
git commit
netlify init
❯ ⇄  Connect this directory to an existing Netlify site 
**- What is the expected behavior?**
netlify init should init a new site
**- Local Environment Information**
Paste the results of `netlify status --verbose` here
Name:   James
Email:  jamesgrubb@mac.com
Github: jamesgrubb
Teams: 
  James's team: Collaborator

**Comment by DavidWells** [comment]
Hey @jamesgrubb I'm seeing this when running your repro steps

```
 cli-init-bug git:(master) ✗ ../../repos/cli/bin/run init

No git remote was found, would you like to set one up?

It is recommended that you initialize a site that has a remote repository in GitHub.

This will allow for Netlify Continuous deployment to build branch & PR previews.

For more details on Netlify CI checkout the docs: http://bit.ly/2N0Jhy5

? Do you want to create a Netlify site without a git repository?
❯ Yes, create and deploy site manually
  No, I will connect this directory with GitHub first
```

Do you have a site already created in Netlify or a git remote already attached in github?

```
git remote -v 
```

^ will tell you your current git remotes

**Comment by jamesgrubb** [comment]
HI yes when I run git remote -v it show me mu push and fetch branches

**Comment by erezrokah** [comment]
Sorry for the late reply @jamesgrubb, closing this as stale.
If still an issue please comment and share a repo reproducing. 
The original reproduction instructions create a repo with not remotes

**Comment by charliegerard** [comment]
I just came across the same issue so I'm leaving a comment in case someone else comes across it.

I have 2 different accounts on Netlify, a personal one and a work one. I didn't realise I was logged in with my personal account in the Netlify CLI while trying to link a site that was under my work account. Using `netlify switch` to switch to my work account fixed it 🙂
