### ISSUE TITLE
Netlify CLI has terminated unexpectedly

### ISSUE THREAD

**Issue by M0ejr** [netlify/cli#6765]
### Describe the bug

```
TypeError: req.on is not a function
    at IncomingForm.parse (/home/moejr/Desktop/18/node_modules/formidable/dist/index.cjs:1218:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  Binaries:
    Node: 20.10.0 - /opt/nodejs/bin/node
    npm: 10.2.5 - /opt/nodejs/bin/npm
  Browsers:
    Chrome: 126.0.6478.182
  npmGlobalPackages:
    netlify-cli: 17.33.4

```

### Steps to reproduce

I don't have time for this, you got a bug you need to fix!

### Environment

--npmGlobalPackages netlify-cli
Need to install the following packages:
envinfo@7.13.0
Ok to proceed? (y) y

  System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 1008.98 MB / 3.62 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.10.0 - /opt/nodejs/bin/node
    npm: 10.2.5 - /opt/nodejs/bin/npm
  npmGlobalPackages:
    netlify-cli: 17.33.4

**Comment by sarahetter** [comment]
Closing as we require reproduction steps.
