### ISSUE TITLE
Deployment Production Boolean Flag - New Behavior? 17.33.4

### ISSUE THREAD

**Issue by ravilach** [netlify/cli#6769]
### Describe the bug

We recently upgraded the Netlify CLI from version 17.25.0 to the current version, 17.33.4 and looks like we have lost our preview deployment context. 

Per the documentation (https://cli.netlify.com/commands/deploy/), we would pass `--prod false` to deploy to generate a preview build as a boolean. 

Not sure if this has changed, looking at deployment.ts between versions looks like some changes. Thanks!

### Steps to reproduce

1. Upgrade or use 17.33.4
2. Deploy something that should not be headed to prod. 
3. `Executing: netlify deploy --auth key --site site--context deploy-preview --debug true --build false --dir ./build`

Then will get a successfully deployed without a preview address. 

<img width="475" alt="image" src="https://github.com/user-attachments/assets/962c2f08-5f5d-4a5b-b971-2eccfdb2578a">

### Configuration

```
[build]
 functions = "netlify/functions/"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/:splat"
```

### Environment

Netlify CLI and NodeJS Version: 
netlify-cli/17.33.4 linux-x64 node-v22.5.1

**Comment by ravilach** [comment]
Also looking at our account. Our `deployments` stopped when we upgraded. We are reverting back to 17.25.0.

**Comment by ravilach** [comment]
We reverted back to 17.25.0 and the deployments work as expected. Preview address displayed and on our Netlify Account looks to be the same.

**Comment by lukasholzer** [comment]
Hey, @ravilach, thanks for reporting the issue – do you have a reproducible example? 

> we would pass --prod false to deploy to generate a preview build as a boolean.
by default, it should be a deploy preview (non-production) only if you provide the `--prod` flag,. It is going to be promoted as a production deployment.

Using it without the `--prod` flag resulted in triggering a deploy preview:
![CleanShot 2024-07-31 at 13 51 31@2x](https://github.com/user-attachments/assets/39fdc9d6-b672-4367-bf68-c0310a8dc412)

**Comment by ravilach** [comment]
Thanks @lukasholzer that might be it. In at least 17.25.0 we would pass `prod true` or `prod false`.  

https://cli.netlify.com/commands/deploy/

<img width="429" alt="image" src="https://github.com/user-attachments/assets/7d314d52-af1d-430b-bcb6-b7a88771af1c">

Let me test with 17.33.4 the following and revert back to the thread. 

1. Remove the --prod flag at all to trigger a preview. 
2. Add --prod by it self [no true or false] itself to trigger a prod deployment. 

If so, docs got me, maybe a one liner update in the docs :-)

**Comment by lukasholzer** [comment]
Furthermore it seems like `--prod=false` seems like a invalid option (I suspect as you write it with a space separated it treats it as `--prod` flag and uses the `false` as argument to the command

Not sure where you have the documentation that `--prod false` should be used? 🤔 

![CleanShot 2024-07-31 at 14 47 25](https://github.com/user-attachments/assets/4c9744b0-be0c-4e45-a431-59d6cdeb7be0)

**Comment by lukasholzer** [comment]
![CleanShot 2024-07-31 at 14 59 36](https://github.com/user-attachments/assets/47146254-eb3e-4aa5-911a-ca52f82fb024)

Mhm maybe there was an update to commander (which we use under the hood for flags passing) but this is a boolean flag that should not accept an additional arg 🤔 

@ravilach can you point me to the docs where it's stated so that we can fix it there?

**Comment by ravilach** [comment]
Thanks for checking @lukasholzer. I interpreted the docs as `prod boolean` as passing in true/false as that seemed to work up until 17.25.0. 

Doc: https://cli.netlify.com/commands/deploy/

Line:

<img width="736" alt="image" src="https://github.com/user-attachments/assets/8ed5356e-8e56-4467-91e7-9ba616dae653">


Here is what I tried and still did not work in 17.33.4

1. Remove the --prod flag. This is with the debug command.

```
 netlify deploy --auth <token> --site <our_site>  --debug true --build false --dir ./build
```

CLI Output:

<img width="488" alt="image" src="https://github.com/user-attachments/assets/1dd1885d-9b9a-4a6a-9384-e29f4801dc55">

No corresponding Preview Deploy in our account. 

Vs 17.25.0

We get a Draft Address

<img width="530" alt="image" src="https://github.com/user-attachments/assets/8c3d5512-2bb1-4ecc-9b15-e963c3c5695b">

Might be the land hand off to what ever service submits the job/retrieves the preview address to Netlify?

**Comment by ravilach** [comment]
Sorry to bombard the thread. Even tried with 17.33.5

```
 Netlify CLI and NodeJS Version: 
netlify-cli/17.33.5 linux-x64 node-v22.5.1
```

Ran 

```
 netlify deploy --auth <token> --site <our_site> --prod --debug true --build false --dir ./build
```

Same the deployment did not occur. E.g the deployment step just gets skipped in the CLI. 

![image](https://github.com/user-attachments/assets/083a128d-0882-4530-b915-45a2228ca308)


Vs in 17.25.0

![image](https://github.com/user-attachments/assets/5451eeee-b09d-4544-9314-b36c7ce85ff2)

**Comment by lukasholzer** [comment]
@ravilach can you try running:

`--build` is true and the default value is false (boolean flags should not get a true false value

``` 
netlify deploy --auth <token> --site <our_site> --dir ./build
```

**Comment by ravilach** [comment]
Thanks @lukasholzer cleaning all of that up now. I think it is the flag issue just like you are stating. Worked or let it slide in 17.25.0 and newer versions [17.33.4+] does not let that slide anymore. 

```
--auth <token> --<site> --prod --debug true --dir ./build
```

Worked in 17.33.5.

![image](https://github.com/user-attachments/assets/86b83c86-c239-4381-9eb4-6f53972ea2ff)


Will tidy up the other flags to match the new scheme. 

Might be my interpretation of the documentation that passing '--flag(boolean)' means '--flag true/false`. Appreciate the responses and joint troubleshooting!

**Comment by ravilach** [comment]
Feel free to close this @lukasholzer.
