### ISSUE TITLE
Cannot read property 'proxyPort' of undefined

### ISSUE THREAD

**Issue by seawatts** [netlify/cli#677]
**- Do you want to request a _feature_ or report a _bug_?**
bug

**- What is the current behavior?**
I cannot run `netlify dev` or `netlify dev --live`

**- If the current behavior is a bug, please provide the steps to reproduce.**
Run `netlify dev` or `netlify dev --live` on a repo with functions

I get the following error
```
$ netlify dev --live 
◈ Netlify Dev ◈
◈ Injected build setting env var: DATABASE_URL
◈ Injected build setting env var: NODE_ENV
TypeError: Cannot read property 'proxyPort' of undefined
    at DevCommand.run (~/.config/yarn/global/node_modules/netlify-cli/src/commands/dev/index.js:349:39)
    at async DevCommand._run (~/.config/yarn/global/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (~/.config/yarn/global/node_modules/@oclif/config/lib/config.js:151:9)
    at async Main.run (~/.config/yarn/global/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (~/.config/yarn/global/node_modules/@oclif/command/lib/command.js:44:20)
```

**- What is the expected behavior?**
It creates a dev server with a proxy

**- Local Environment Information**
```
 netlify status --verbose
──────────────────────┐
 Current Netlify User │
──────────────────────┘
Name:  Chris
Email: 
Teams: 
  Chris's team: Collaborator

────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
  Binaries:
    Node: 13.5.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 70.0
    Safari: 13.0.4

────────────────────┐
 Netlify Site Info  │
────────────────────┘
Current site: staging-bot-slack
Netlify TOML: ./netlify.toml
Admin URL:    https://app.netlify.com/sites/staging-bot-slack
Site URL:     https://staging-bot-slack.netlify.com
Site Id:      6d3e3c39-8988-4331-9b92-b52d5857a8be
```
Netlify version 2.27.0

**Comment by DavidWells** [comment]
Thanks for the report 

Looks like an issue with `config` being null here https://github.com/netlify/cli/blob/master/src/commands/dev/index.js#L349

Do you have netlify dev config settings in your netlify.toml file?

Also what static site generator are you using?

**Comment by DavidWells** [comment]
@RaeesBhatti which port is the `proxyPort`?

The docs have 2 ports `functionsPort` & `targetPort` https://cli.netlify.com/commands/dev

- functionsPort (option) - port for functions server
- targetPort (option) - port of target app server

**Comment by seawatts** [comment]
- I'm not specifying any port.
- I do not have any dev settings in `netlify.toml`
- I'm not using a static site generator, only creating functions

**Comment by seawatts** [comment]
Looks like this.netlify.config doesn't initiate the dev object
https://github.com/netlify/cli/blob/master/src/utils/command.js#L61

Therefore, https://github.com/netlify/cli/blob/master/src/commands/dev/index.js#L349 `config.dev` is null. 

It looks like it's being correctly checked in other places

https://github.com/netlify/cli/blob/master/src/commands/dev/index.js#L359
https://github.com/netlify/cli/blob/master/src/commands/dev/index.js#L378

**Comment by DavidWells** [comment]
Thanks @seawatts 

Can you try running 

```
netlify dev --targetPort 8080
```

^ this should* work temporarily

I've updated the logic https://github.com/netlify/cli/blob/master/src/commands/dev/index.js#L349 for the defaults to work correct. This will be released shortly in new CLI version

**Comment by seawatts** [comment]
Great thanks!

Seems like maybe just defining it at the top of the function would be better so you don't have to check everywhere

`config.dev = config.dev || {}`

**Comment by DavidWells** [comment]
Found the deeper issue coming from new config parser in https://github.com/netlify/build

We will fix that up stream and make sure the log "you need a publish directory" error message shows correctly
