### ISSUE TITLE
Bad colored output for conemu

### ISSUE THREAD

**Issue by bcomnes** [netlify/cli#68]
@verythorough was reporting that we are getting odd color output on conemu and some text is the same color as the background:

  
![only-with-help](https://user-images.githubusercontent.com/166301/44758143-917f3380-aae7-11e8-84ce-e6ca183edc44.png)

The help text is auto printed by oclif, so it may be an upstream issue.  Just to note, conemu does not support 256 colors:

![256colors](https://user-images.githubusercontent.com/166301/44758172-b1165c00-aae7-11e8-8c19-955af7ae757f.png)

**Comment by DavidWells** [comment]
Closing this for now. Can revisit if more reports
