### ISSUE TITLE
kill call targets a non-existing PID: causes `env: node: No such file or directory`

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#684]
**- Do you want to request a _feature_ or report a _bug_?**
bug

**- What is the current behavior?**
when we run netlify dev on https://github.com/netlify/netlify-react-ui/, with CLI version 2.29, it results in this

![image](https://user-images.githubusercontent.com/6764957/72442828-351fc100-377b-11ea-9457-1ee8d9bf74da.png)

(ignore the console.log of settings, thats me trying to debug)

**- If the current behavior is a bug, please provide the steps to reproduce.**
as above

**- What is the expected behavior?**
netlify dev should work on netlify app

@ehmicky thinks it is a recent regression - we are killing a non existent PID here, causing the [Kill ESRCH](https://unix.stackexchange.com/questions/258955/what-does-esrch-mean) error https://github.com/netlify/cli/blob/a1151afbefb9599052fc104b814270493eceec14/src/commands/dev/index.js#L327

however when i tweak that line i still cant get it to work

**Comment by RaeesBhatti** [comment]
Hey @sw-yx , thanks for reporting this issue. I've identified the problem and provided a fix in https://github.com/netlify/cli/pull/685. Please try it out and let me know.
