### ISSUE TITLE
Branch Deploys from the CLI?

### ISSUE THREAD

**Issue by zbruhnke** [netlify/cli#687]
**- Do you want to request a _feature_ or report a _bug_?**
This is a feature request (I Think)

**- What is the current behavior?**
When I run a deploy from Gitlab CI it will do deploy previews and production deploys fine, but what if we would also like to do branch deploys? 

The use case for us is to be able to have some branches that we point to URLs (using th branchname-- trick)

We would love to be able to have this like if its a branch that is defined in `netlify.toml`

if not preview deploys would be fine and then finally `--prod` can still work as is.

My suggestion would be to have this as a `--branch` flag that could verify the branch context exists in `netlify.toml` and if it does perform a branch deploy otherwise it could just fall back to a deploy preview

Would love to hear if there's any thought around this.

We use Gitlab CI for all of our other projects and prefer to be able to use it to run our linter, our tests and our end to end tests before deploying which is not solved simply by linking to git.

Maybe I'm missing something and there is a way to only have the netlify build start after all of our pipeline passes when linked to git?

Thanks in advance for the help/thoughts!

**Comment by RaeesBhatti** [comment]
Hey @zbruhnke , thanks for opening this ticket. We don't have support for branch deploys in CLI right now but an issue has been raised with API team to implement an endpoint that will allow us to do that.
You can follow the latest updates on this topic here: https://github.com/netlify/cli/issues/275

**Comment by RaeesBhatti** [comment]
Closing in favor of: https://github.com/netlify/cli/issues/275
