### ISSUE TITLE
Do not require `--data` CLI flag with `netlify api`

### ISSUE THREAD

**Issue by ehmicky** [netlify/cli#688]
**- Do you want to request a _feature_ or report a _bug_?**

Bug.

**- What is the current behavior?**

`netlify api getCurrentUser` does not print the API response.

However this works when passing the additional `--data '{}'` CLI flag. This should not be required for `GET` endpoints.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Run `netlify api getCurrentUser`. Nothing is printed.

**- What is the expected behavior?**

The API response should be printed.

**- Local Environment Information**

```
  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  Binaries:
    Node: 13.6.0 - ~/.nvm/versions/node/v13.6.0/bin/node
    Yarn: 1.21.1 - node_modules/.bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.6.0/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.1
```

**Comment by RaeesBhatti** [comment]
Thanks for opening this issue @ehmicky. It seems like a fix has already been merged here: https://github.com/netlify/cli/pull/701

Please reopen if otherwise.

**Comment by ehmicky** [comment]
Yes it works, thanks @RaeesBhatti!
