### ISSUE TITLE
netlify dev doesn't pass query params to a function during rewrite

### ISSUE THREAD

**Issue by omaiboroda** [netlify/cli#691]
**- Do you want to request a _feature_ or report a _bug_?**
a bug
**- What is the current behavior?**
A redirect to a function 
```js
[build]
  functions = "myfunctions/"

[[redirects]]
  from = "/test/*"
  to = "/.netlify/functions/test/:splat"
  status = 200
```
doesn't carry query params

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Define redirect as above
2. Create `myfunctions/test.js`
3. Start `netlify dev`
4. Call `localhost:8888/test?foo=bar`
5. Ensure `event.queryStringParameters` is empty

**- What is the expected behavior?**
The function should receive query params during the rewrite.
Works as expected on the deployed environment.

**- Local Environment Information**
Paste the results of `netlify status --verbose` here
netlify-cli/2.30.0 darwin-x64 node-v10.15.3

**Comment by RaeesBhatti** [comment]
Thanks for reporting this issue @omaiboroda. The fix will be published in the upcoming release.
