### ISSUE TITLE
[ERR_HTTP_INVALID_HEADER_VALUE]

### ISSUE THREAD

**Issue by AaronPowell96** [netlify/cli#692]
**- Do you want to request a _feature_ or report a _bug_?**
Bug
**- What is the current behavior?**
Server runs for a while, crashes with this error randomly.
**- If the current behavior is a bug, please provide the steps to reproduce.**
Start by "Netlify dev", server runs, I use it.
Then I get this error:
`TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "x-forwarded-for"
    at ClientRequest.setHeader (_http_outgoing.js:458:3)
    at new ClientRequest (_http_client.js:221:14)
    at Object.request (http.js:44:10)
    at Array.stream (C:\Users\Aaron\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\http-proxy\lib\http-proxy\passes\web-incoming.js:126:74)
    at ProxyServer.<anonymous> (C:\Users\Aaron\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\http-proxy\lib\http-proxy\index.js:81:21)
    at Object.web (C:\Users\Aaron\AppData\Roaming\npm\node_modules\netlify-cli\src\commands\dev\index.js:122:20)
    at C:\Users\Aaron\AppData\Roaming\npm\node_modules\netlify-cli\src\commands\dev\index.js:175:13
    at C:\Users\Aaron\AppData\Roaming\npm\node_modules\netlify-cli\src\utils\rules-proxy.js:124:7
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "x-forwarded-for"`
**- What is the expected behavior?**
Not to crash
**- Local Environment Information**
Windows 10,
netlify-cli/2.30.0 win32-x64 node-v12.4.0,
In my netlify TOML file I do not declare any header values etc.
Paste the results of `netlify status --verbose` here
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 12.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0

Not sure but this seems to be recently changed could req.connection.remoteAddress be undefined?

  const handlers = {
    web: (req, res, options) => {
      req.proxyOptions = options
      req.alternativePaths = alternativePathsFor(req.url)
      req.headers['x-forwarded-for'] = req.connection.remoteAddress
      return proxy.web(req, res, options)
    },
    ws: (req, socket, head) => proxy.ws(req, socket, head)
  }

  return handlers
}

In src/commands/dev/index.js

or potentially an issue in https://www.npmjs.com/package/netlify-redirector redirects.js file but I cannot find the repo for it.

**Comment by RaeesBhatti** [comment]
Thanks for reporting the issue @AaronPowell96. This was a very rare case. The fix will be published in the next release.

**Comment by AaronPowell96** [comment]
@RaeesBhatti Hi, sorry. When is the release because currently it runs every 10th try for about 10mins. Thank you!

**Comment by RaeesBhatti** [comment]
I just published a new release. Please try it out and let me know if there's a problem.
