### ISSUE TITLE
`netlify api` Command doesn't work when you don't pass the data flag to it

### ISSUE THREAD

**Issue by Eddie-CooRo** [netlify/cli#700]
**- Do you want to request a _feature_ or report a _bug_?**
_bug_/_feature_

**- What is the current behavior?**
I don't know if it's intended or not (it seems like it is, but I can't find out why). but the `netlify api` command doesn't work at all when no data is passed to it. I've struggled with it a lot until I found that I need to pass a JSON even when the API endpoint doesn't need it (for example the `getCurrentUser` endpoint) 

**- What is the expected behavior?**
CLI sends the request with an empty JSON as the payload when no data is provided.

I'm going to open a pull request that solves this issue. please review it when you found time.

**Comment by RaeesBhatti** [comment]
Seems like the PR fixed this one. Thanks @Eddie-CooRo
