### ISSUE TITLE
Enable Git Gateway and Netlify Identity through API

### ISSUE THREAD

**Issue by mbj36** [netlify/cli#712]
Is there a way to enable git gateway and Enable identity through netlify api ?

**Comment by mraerino** [comment]
For git gateway it is possible:
`netlify addons:create git`

i'm not sure why exactly, but `netlify addons:create identity` **does not work** in the CLI.
If you need to know more, maybe head over to community.netlify.com

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed

**Comment by leomp12** [comment]
> Closing as stale. Please re-open if needed

I still think it would be very useful 🙃
