### ISSUE TITLE
Console.log no longer working in netlify-cli/2.35.0 

### ISSUE THREAD

**Issue by michalhudecek** [netlify/cli#716]
Console.log used to work in previous versions. After updating to 2.35.0, console.log statements no longer show.

**Comment by RaeesBhatti** [comment]
Hey @michalhudecek, can you give an example of this! Do you mean the console.logs in Netlify Cli codebase or your site generator or Netlify Functions?

**Comment by michalhudecek** [comment]
Sorry, I mean in Netlify functions. When I run `netlify dev`  I used to get console.log output from netlify functions when they were called. Now I do not get anything. I tried various functions I have it is the same everywhere.

**Comment by michalhudecek** [comment]
Here is a screenshot of the console. The function is successfully called but no console.logs show anymore.

![image](https://user-images.githubusercontent.com/1215304/74934788-40ec4c00-53e7-11ea-913a-87587bd0fe77.png)

**Comment by Philip-Owen** [comment]
Having the same issue here. Console logs from within exports.handler are not showing up in the terminal. I'm using netlify-cli/2.35.0 as well.

**Comment by michalhudecek** [comment]
If it helps, I am on Windows 10, node.js v12.16.0

**Comment by RaeesBhatti** [comment]
Thanks for reporting this. We have a PR in the works for this one. Please hold on

**Comment by RaeesBhatti** [comment]
If you can, please try out the changes from the PR (https://github.com/netlify/cli/pull/722) and provide feedback on if it is working as intended.

**Comment by itsravenous** [comment]
👋  This appears to have regressed again. I'm on cli version 2.57.0 and can't see console logs called from my handler function.
