### ISSUE TITLE
Error installing Netlify CLI on macOS Catalina 10.5.3

### ISSUE THREAD

**Issue by iChris** [netlify/cli#720]
**- Do you want to request a _feature_ or report a _bug_?**

Report a bug

**- What is the current behavior?**

Trying to install Netlify CLI using `npm install netlify-cli -g`

Error code: https://d.pr/n/GakcpO

**- If the current behavior is a bug, please provide the steps to reproduce.**

Above is what I did in Terminal.

**- What is the expected behavior?**

Successful install of Netlify CLI (I have it running on my iMac running 10.14)

**- Local Environment Information**
Paste the results of `netlify status --verbose` and `netlify version` here

I can't run them because Netlify CLI cannot install. I've installed the [latest version of Node](https://nodejs.org/en/download/).

**Comment by fool** [comment]
Can you install other NPM packages successfully, @iChris ?  Looks like general npm permissions issues, rather than anything specific to our package.  For instance, can you `npm install chalk-cli -g` without similar installation errors?

**Comment by iChris** [comment]
> Can you install other NPM packages successfully,

Oh dang I guess not. :( I had installed other things previously so not sure what changed. Alright. I guess I'll go back to the drawing board / Stackoverflow. :)

**Comment by iChris** [comment]
I do get this error at the top of the install process - is that an issue with your installer or with NPM? 

`
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
`

**Comment by iChris** [comment]
I followed [these instructions](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) and that seemed to fix whatever issues cropped up on my install. Netlfiy CLI now installed. Thanks for the time!
