### ISSUE TITLE
Functions timeout after 3 seconds

### ISSUE THREAD

**Issue by spencewood** [netlify/cli#724]
**- Do you want to request a _feature_ or report a _bug_?**
Feature request.

**- What is the current behavior?**
Netlify functions time out after three seconds using Netlify cli.

**- If the current behavior is a bug, please provide the steps to reproduce.**
While ideally functions _should_ take less than three seconds to run, I feel like the threshold is too low when running in a local environment -- especially since it does not match the timeout time of functions in production. Possible cases (and indeed my use case) involve pulling and combining data from multiple APIs with large datasets and potentially high latency (read: slow home internet).

Here is a simple repo that simply waits for three seconds before it responds, which times out before it is able to respond:

https://github.com/spencewood/netlify-timeout

```sh
$ yarn netlify dev
```

then, navigate to http://localhost:8888/.netlify/functions/hello

And this is what I get from the netlify instance testing in both Mac and Linux environments:

```
◈ Error during invocation:  { errorMessage: 'Task timed out after 3.00 seconds',
  errorType: 'TimeoutError',
  stackTrace:
   [ 'new TimeoutError (/home/test/Projects/netlify-timeout/node_modules/lambda-local/build/lib/utils.js:109:28)',
     'Context.<anonymous> (/home/test/Projects/netlify-timeout/node_modules/lambda-local/build/lib/context.js:110:19)',
     'ontimeout (timers.js:436:11)',
     'tryOnTimeout (timers.js:300:5)',
     'listOnTimeout (timers.js:263:5)',
     'Timer.processTimers (timers.js:223:10)' ] }
```

This function works as expected when deployed to netlify (waits 3 seconds and then responds with "Hello World").

**- What is the expected behavior?**
I expect to be able to run functions locally with the same timeout thresholds as in [production environments](https://docs.netlify.com/functions/overview/#custom-deployment-options) (10 seconds) or higher.

**- Local Environment Information**
```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.10.0 - /var/folders/cv/6z3rr1nx6rzgr91y8ldp2cwr0000gn/T/yarn--1582474716240-0.41285262057772476/node
    Yarn: 1.22.0 - /var/folders/cv/6z3rr1nx6rzgr91y8ldp2cwr0000gn/T/yarn--1582474716240-0.41285262057772476/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 73.0
    Safari: 13.0.5
```

```
netlify-cli/2.35.0 darwin-x64 node-v12.10.0
```

**Comment by jeremyswann** [comment]
Had the same issue after upgrading to v2.35.0, rolled back to netlify-cli@2.27.0. `ntl- dev` works again

**Comment by RaeesBhatti** [comment]
Thanks for reporting this issue. The cause has been identified and we have a PR in the works to fix this. If you would like to try it out, it is available here: https://github.com/netlify/cli/pull/725

**Comment by sarink** [comment]
Did this regress? In 2025 it's back to 3 seconds and doesn't seem configurable. I had to hack the underlying `lambda-local` package, specifically `node_modules/lambda-local/build/lambdalocal.js` which does take `opts.timeoutMs`. Why isn't this exposed as an option from `netlify dev` or `netlify.toml` ?
