### ISSUE TITLE
CLI Updates Announcements

### ISSUE THREAD

**Issue by djj0s3** [netlify/cli#727]
**- Do you want to request a _feature_ or report a _bug_?**
Feature request

**- What is the current behavior?**
As a user I want to know that there's a new version of the CLI available when I'm using an older version.

**Comment by jamesgeorge007** [comment]
[update-notifier](https://github.com/yeoman/update-notifier) would serve the purpose here.
> Inform users of your package of updates in a non-intrusive way

**Comment by erezrokah** [comment]
Closing as we're using update notifier for this:
https://github.com/netlify/cli/blob/01b3419f85b4bae941bafb3ad9ad85db473314a7/src/index.js#L5
