### ISSUE TITLE
netlify still connects to telemetry server when user does not consent to telemetry!

### ISSUE THREAD

**Issue by sneak** [netlify/cli#739]
# Bug

**- What is the current behavior?**

I ran `netlify --telemetry-disable` on a fresh install (`rm -rf ~/.netlify`) and it connected to `cli.netlify.com`:

<img width="1568" alt="Screen Shot 2020-03-07 at 07 24 56" src="https://user-images.githubusercontent.com/408977/76146078-c5c0a200-6044-11ea-9710-4ebb7618afe4.png">

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. install netlify cli via yarn/npm
1. run `netlify --telemetry-disable`

**- What is the expected behavior?**

Expected: I'm not spied on.

Actual: Your app violates my consent.

**- Local Environment Information**

Paste the results of `netlify status --verbose` and `netlify version` here

```
sneak@nostromo:~$ netlify status --verbose
Not logged in. Please log in to see site status.

Login with "netlify login" command
sneak@nostromo:~$
```

```
sneak@nostromo:~$ netlify version
netlify-cli/2.32.0 darwin-x64 node-v13.1.0
sneak@nostromo:~$
```

# Dear Netlify

Dear Netlify:

I use and really like your service.  I was happy to hear you guys raised some money recently.  I was deeply disappointed to see that you have telemetry enabled in your app; I disabled it on all my systems using it but apparently it's still spying on me.

This sort of spying is deeply unethical.  You are not entitled to silently spy on your users simply because they didn't realize that your app is spyware.  You are not entitled to *assume* consent just because you mentioned on your webpage that your apps will silently spy on your users.  This makes your app **malware**.

"We're going to silently spy on you unless you read our whole website, notice that it's a spyware app, and then disable the spyware part" is not an ethical business practice.  You must **OBTAIN CONSENT** from your users to use their personal data.  You may not *assume consent*.

What you're doing now is unethical and abusive.  That’s simply not affirmative consent. Imagine if you tried that in life! “Anyone who stays in this room after 5pm is consenting to be groped! Proceed at your own risk.”  Don't be that creep.  Please don't ship spyware.

Note that fixing only this bug (the issue of sending telemetry when the user explicitly opts out) is not a complete solution.  You must **stop spying on your users** unless they have *explicitly agreed* to permit you to their usage information.

Best,
-@sneak

PS: "everyone else is doing it" is *not* an acceptable excuse for unethical behavior.

PPS: "but the collection is anonymous!" is not an excuse either: transmitting a user's IP to your telemetry server leaks that user's location, which is a violation of their privacy.  IPs uniquely identify many, many users, and SNI is not yet encrypted.

**Comment by Omeryl** [comment]
I get there's probably a bug here, but I'd say that the entire "Dear Netlify" section is just .. not required here.

**Comment by Omeryl** [comment]
I tried doing the exact same thing, rm -rf'ing my netfify config folder and using Little Snitch 4 to monitor the process. 

I replaced the API_URL in `src/utils/telemetry/request.json` with a requestbin. It looks like it sends the following data:

```json
{
    "event": "cli:user_telemetryDisabled",
    "anonymousId": "e4b0355f-2838-4ff6-93a0-641479aec90d",
    "properties": {}
}
```

Presumably, this could be used to purge all previous analytical data. I haven't done any more validation past this, though.

**Comment by erquhart** [comment]
The cli has to connect to Netlify to work, hence the call to cli.netlify.com. If you disable telemetry, we don’t use telemetry.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sneak** [comment]
This is incorrect.  The connection to the telemetry server is not when doing any action, only disabling telemetry.  It's sending a telemetry event, saying the user has disabled telemetry, as shown above.

**Comment by erquhart** [comment]
Going to look into that call to the server, it's either accidental or we're using it to disable some sort of server side telemetry. I'll update when I get more info - in the meantime, if you're concerned about the impact of this, please run a fork and disable that line until this is resolved. Apologies for the confusion here.

**Comment by Omeryl** [comment]
Alternatively, in the meantime, it seems if you set `"telemetryDisabled": true,` in your config and don't run --disable-telemetry you'll be fine as well.

**Comment by sneak** [comment]
Please consider #737 as then the application can know from the first line that the user wishes to not be spied on (via standard env var, see https://consoledonottrack.com).

**Comment by erquhart** [comment]
@Omeryl good point - and since that approach is documented and does bypass this call, we'll go ahead and get a release out with the call excluded. @sneak thanks for raising this.

**Comment by sneak** [comment]
Why not disable telemetry by default for all installs, and then when a user in an interactive session does a `netlify init` or `netlify login`, just ask them for their consent that you send their data away?

Doing so silently and without any sort of notification or time window in which a user can cancel and not transmit is unethical and presumptuous, and, in my personal opinion, super rude.

**Comment by erquhart** [comment]
The CLI provides an alternative interface for interacting with the Netlify service. When signing up to the service, you agree to Netlify's terms of use and privacy policy as indicated in the [self serve subscription agreement](https://www.netlify.com/legal/self-serve-subscription-agreement/). Disabling the tracking call when disabling telemetry should be sufficient to close this issue - PR opened.

**Comment by sneak** [comment]
Nothing quite like being told that I consent to something when I actually don’t.

**Comment by cohunter** [comment]
> Netlify shall have the right to collect and analyze data and other information relating to the provision, use and performance of various aspects of the Services and related systems. Netlify will use such data to administer, improve and develop its products and services, including the Services; and Netlify may share aggregated information and non-identifying information with third parties.

That was seriously buried in the terms. It may legally excuse it, but certainly goes against reasonable expectations.

If this is how netlify operates, you can trust I’ll no longer be able to recommend your services.

It really isn’t that hard to ask the user for consent at first use.

**Comment by sneak** [comment]
Why bother having an option to disable telemetry if you legitimately believe that every single person using the tool has already consented to such spying by having a Netlify account?

**Comment by stronger108** [comment]
Man, nothing like asking your users just to paint a picture of having control over it to literally not do anything.

**Comment by Smit-tay** [comment]
I think I have the solution.
Stop using the product.
It does nothing that a few scp (or sftp) commands can't do for you

**Comment by KamranMackey** [comment]
> Nothing quite like being told that I consent to something when I actually don’t.

You sir, are an obnoxious human being. Learn to read agreements. And this whole issue is a case of tinfoil hatness. Grow up.

**Comment by chrisjohnson** [comment]
> Nothing quite like being told that I consent to something when I actually don’t

But you did? You agreed to their terms. That you did not read those terms that you agreed to, wherein you gave consent, is on you. Why is it the world's responsibility to bend to your whim?

The tone here is not useful at all. You aren't correct in your assumptions and you are painting people in an unnecessarily bad light just because you didn't take the time to read what you were agreeing to
