### ISSUE TITLE
Broken redirects on https://cli.netlify.com

### ISSUE THREAD

**Issue by aDENTinTIME** [netlify/cli#741]
On the page https://cli.netlify.com, when you click on one of the links under "Commands" you get redirected to a 404 page with a URL that ends with ".md" that has a list of the correct links. Take "addons" for example, you're directed to the following page https://cli.netlify.com/commands/addons.md, on this page if you click "addons" again you'll be directed to https://cli.netlify.com/commands/addons, which is correct. This is a minor inconvenience, but might not be terribly hard to fix. I took a quick look around the repo and don't feel confident enough to make a PR.

**Comment by RaeesBhatti** [comment]
Thank you for reporting this @aDENTinTIME 👍 . We found the problem and it will be fixed soon https://github.com/netlify/cli/pull/744
