### ISSUE TITLE
Deploy Operation never ends when I use toml file.

### ISSUE THREAD

**Issue by vijayhardaha** [netlify/cli#742]
![netlify error](https://user-images.githubusercontent.com/25227317/76305887-f7a76200-62eb-11ea-967c-1a4f35621d00.gif)

When I am using .toml config, deploy operation never ends. even .toml file is empty.

but without config file all works fine.

**Comment by RaeesBhatti** [comment]
Hey @vijayhardaha , thank you for reporting this issue. Do you encounter this issue one your other projects as well? Is it consistent or happens only sometimes? Does it only happen when using `netlify.toml` or with `netlify.yml` file as well?

Please fill out the following as well:

**- Local Environment Information**
Paste the results of `netlify status --verbose` and `netlify version` here

**Comment by vijayhardaha** [comment]
Hello @RaeesBhatti 

I've set up a new project and did the test. I am having same issue in new project as well. I've been only using `netlify.toml` only. Here the project and system details.

**Netlify Version**
```
netlify-cli/2.37.0 win32-x64 node-v12.16.1
```
**Netlify Status**
```
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD
Browsers:
    Edge: 44.18362.449.0

Current site: musing-swartz-01b0a8
Netlify TOML: C:\Users\Sincere\Desktop\templated-caminar\netlify.toml
Admin URL:    https://app.netlify.com/sites/musing-swartz-01b0a8
Site URL:     https://musing-swartz-01b0a8.netlify.com
Site Id:      b1ab6b5d-7312-4126-a75c-716ce2629cdb
```

![netlify error 2](https://user-images.githubusercontent.com/25227317/76363717-a201a280-6349-11ea-8325-ef3de0e110a7.gif)

**Comment by RaeesBhatti** [comment]
Can you please update to the latest version `2.38.0` (`npm i -g netlify-cli@latest`) and see if that fixes the problem!

**Comment by vijayhardaha** [comment]
OK, update fixed the issue. 👍
