### ISSUE TITLE
Setup CI/CD for netlify-cli npm package

### ISSUE THREAD

**Issue by RaeesBhatti** [netlify/cli#756]
**- Do you want to request a _feature_ or report a _bug_?**
None, I think.

**- What is the current behavior?**
Maintainers have to publish deploys manually on their computers.

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**
A new released is published on npm automatically when a release is created in Github repo.

**- Local Environment Information**

```
netlify-cli/2.40.0
```

**Comment by williamjacksn** [comment]
I was waiting for https://www.npmjs.com/package/netlify-cli to update for 2.41.0 this morning.

**Comment by RaeesBhatti** [comment]
@williamjacksn `2.41.0` has been published on npm. Please try again

**Comment by fonz24** [comment]
![Screenshot_20200505-105710](https://user-images.githubusercontent.com/3180223/81081242-aa94d600-8ebf-11ea-9514-e6789123e175.png)

**Comment by fonz24** [comment]
I need location

**Comment by erezrokah** [comment]
Closing this as resolved
