### ISSUE TITLE
Gatsby server continues running after CLI fails

### ISSUE THREAD

**Issue by erquhart** [netlify/cli#765]
Context: https://github.com/netlify/cli/pull/754#issuecomment-603747623

**- Do you want to request a _feature_ or report a _bug_?**
bug

**- What is the current behavior?**
The CLI can fail without properly exiting the Gatsby development server.

**- If the current behavior is a bug, please provide the steps to reproduce.**
- Be sure to run the latest netlify-cli locally from source
- Clone the Gatsby Netlify CMS starter: https://github.com/netlify-templates/gatsby-starter-netlify-cms
- Run `netlify dev` in the cloned repo

**- What is the expected behavior?**
A CLI error that leads to an exit should always include shutting down of processes that were started by the CLI.

**- Local Environment Information**

This issue is occurring on netlify/cli master, unreleased, as of this commit:
https://github.com/netlify/cli/commit/fa86a6179419bf38022f4bcc36643b758d059736

**Comment by RaeesBhatti** [comment]
Should've been fixed by https://github.com/netlify/cli/pull/818. Initial testing seems positive.
