### ISSUE TITLE
Headers files with TOML content allowed in CI but fail in CLI

### ISSUE THREAD

**Issue by erquhart** [netlify/cli#766]
Context: https://github.com/netlify/cli/pull/754#issuecomment-603792668

**- Do you want to request a _feature_ or report a _bug_?**
bug

**- What is the current behavior?**
Netlify CI allows `_headers` files to have TOML content, but the CLI doesn't mirror this behavior.

**- If the current behavior is a bug, please provide the steps to reproduce.**
- Be sure to run the latest netlify-cli locally from source
- Clone the Gatsby Netlify CMS starter: https://github.com/netlify-templates/gatsby-starter-netlify-cms
- Run `netlify dev` in the cloned repo

**- What is the expected behavior?**
The CLI should not fail to parse a headers file that Netlify CI parses successfully.

**- Local Environment Information**

This issue is occurring on netlify/cli master, unreleased, as of this commit:
https://github.com/netlify/cli/commit/fa86a6179419bf38022f4bcc36643b758d059736

**Comment by erquhart** [comment]
@rybit can you confirm whether we're allowing `_headers` files to have TOML content intentionally, or loop in someone who can?

**Comment by calavera** [comment]
I'm pretty sure that we do not parse `_header` files with any toml parser, however, deploys don't fail when there is a parsing error, we only log the errors and move on. That repository has probably just worked, but never actually injected any header.

**Comment by RaeesBhatti** [comment]
I just tested and can confirm that TOML styles rules in `_headers` files don't work on production. I think it's a good idea to let people know that they have invalid syntax when they run `netlify dev`. This will help save some frustration about why the rules are not being applied.

**Comment by jozsi** [comment]
New to Gatsby and Netlify, I've started with the recommended https://github.com/netlify-templates/gatsby-starter-netlify-cms starter, installed `netlify-cli`, ran `netlify dev` and got the `Error: path should come before headers` message. Took some time to find the culprit, downgrading to `v2.40.0` helped. I think the template should be updated.

**Comment by RaeesBhatti** [comment]
I opened a PR in the template repo to fix the syntax https://github.com/netlify-templates/gatsby-starter-netlify-cms/pull/546

**Comment by franva** [comment]
Hi there, I still have this issue event updated all my packages to the latest version.

After I saw this error, I saw the fix has been merged, so I thought by updating all packages to the latest version, it could solve this problem , so I ran
`npx npm-check-updates -u`

but the issue is still here.

please help

**Comment by erezrokah** [comment]
Hi @franva, do you mind opening a new issue with a reproduction?
