### ISSUE TITLE
Revisit random port assignment

### ISSUE THREAD

**Issue by erquhart** [netlify/cli#767]
**Context**
https://github.com/netlify/cli/pull/755#discussion_r396992876 by @erezrokah 
> Shouldn't we fail if the user explicitly sets a port but it is not available?
I'm assuming users set a specific port since they want to use it later on in their code/logic, so assigning a random one might create issues.

**- Do you want to request a _feature_ or report a _bug_?**
_feature_

**- What is the current behavior?**
- A random port is assigned if specified port is unavailable
- A random port is assigned if none is specified

**- What is the expected behavior?**
- If a port is specified and unavailable, we should fail and provide a helpful error message
- If no port is specified, using a random port is still a bit jarring - we should probably pick one that's generally not used instead

Thoughts?

**Comment by RaeesBhatti** [comment]
Yes, I thought about this when implementing the last change but held off because it changes the existing behavior. Should be straight forward if we want to go this route.
