### ISSUE TITLE
Update `mkdirp` to avoid warnings on `npm install`

### ISSUE THREAD

**Issue by ehmicky** [netlify/cli#772]
On `npm install netlify-cli` the following warning is shown:

```
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
```

This is due to the following dependencies:

```
$ npm ls mkdirp
netlify-cli@2.40.0 /home/ehmicky/.nvm/versions/node/v13.11.0/lib/node_modules/netlify-cli
├─┬ copy-template-dir@1.4.0
│ └── mkdirp@0.5.4  deduped
├─┬ gh-release-fetch@1.0.3
│ └── mkdirp@0.5.4  deduped
└── mkdirp@0.5.4
```

Fixing this problem would require:
  - [ ] Upgrading `mkdirp` to [latest version](https://github.com/isaacs/node-mkdirp/blob/master/package.json) in Netlify CLI
  - [ ] Upgrading `mkdirp` to [latest version](https://github.com/isaacs/node-mkdirp/blob/master/package.json) in [`netlify/gh-release-fetch`](https://github.com/netlify/gh-release-fetch/blob/master/package.json)
  - [ ] Switching [`copy-template-dir`](https://github.com/yoshuawuyts/copy-template-dir) to another library, since that one is not maintained anymore

Note: [`make-dir`](https://github.com/sindresorhus/make-dir) is an alternative that might be better maintained.

**Comment by RaeesBhatti** [comment]
Thanks for reporting this issue @ehmicky.

**Comment by RaeesBhatti** [comment]
Fixed in the latest version

**Comment by dessiemae004** [comment]
Currently having this issue on my computer, is there anything I can do to fix this. As I get this when I enter the command, " npm install -g express-generator"
