### ISSUE TITLE
Unable to invoke functions in Dev mode

### ISSUE THREAD

**Issue by areknow** [netlify/cli#773]
The `netlify functions:invoke` CLI commands always returns error:

```
~/Documents/Development/website master
❯ netlify functions:create --name function-xyz
? Pick a template js-hello-world
◈ Creating function function-xyz
◈ Created /Users/arnaud.crowther/Documents/Development/website/functions/function-xyz/hel
lo-world.js

~/Documents/Development/website master*
❯ netlify  functions:invoke
? Pick a function to trigger function-xyz
? Invoke with emulated Netlify Identity authentication headers? (pass --identity/--no-identity
 to override) Yes
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /.netlify/functions/function-xyz</pre>
</body>
</html>
```

Netlify dev is running, and I am able to reach the endpoint with postman. Am I missing a step to invoke the functions? This happens to me every time.

Thank you!

**Comment by RaeesBhatti** [comment]
@areknow Thanks for opening this ticket. I was able to invoke my function successfully following the steps you mentioned. Can you provide more context around you problem. Maybe share a minimal repo where this is reproducible.
Also, please make sure that you're running the latest version of Netlify CLI (`npm i -g netlify-cli`).

**Comment by areknow** [comment]
@RaeesBhatti thats so weird! I just made sure I am using the most up to date cli version. This repo is the one I am currently facing the issue in: https://github.com/areknow/covid-heroes

One thing to note that I noticed. When I start `netlify dev`, I see undefined in one of the outputs:
```
❯ netlify dev
◈ Netlify Dev ◈
◈ Injected build setting env var: SPARKPOST
◈ Starting Netlify Dev with undefined
Waiting for localhost:3000.
◈ Lambda server is listening on 34567
```

**Comment by areknow** [comment]
@RaeesBhatti  I just tried this repo https://github.com/netlify/dev-demo-example and it worked as expected. I do not understand what I am doing differently in my project 😄

**Comment by areknow** [comment]
@RaeesBhatti solved!

I had copied the entire `netlify.toml` from the example docs without reading what the properties were being used for. After deleting all the optional properties from my config file, I am able to invoke the functions correctly. 

Cheers

**Comment by RaeesBhatti** [comment]
Glad it worked out for you @areknow

**Comment by areknow** [comment]
Thanks for your quick assistance!
