### ISSUE TITLE
verbose flag doesn't serve the purpose

### ISSUE THREAD

**Issue by jamesgeorge007** [netlify/cli#778]
**- Do you want to request a _feature_ or report a _bug_?**
bug report

**- What is the current behavior?**
We've the `--verbose` flag as part of `status` command which shows up local environment information useful while submitting bug reports. But it doesn't display the information as expected.

https://github.com/netlify/cli/blob/d54b500c548c0e45d9a496eec988726e23cb67da/src/commands/status/index.js#L78
Moving the above block just below the respective line would serve the purpose.
https://github.com/netlify/cli/blob/d54b500c548c0e45d9a496eec988726e23cb67da/src/commands/status/index.js#L12

**- If the current behavior is a bug, please provide the steps to reproduce.**
Type in `netlify status --verbose`
If you're logged in, the respective information is being displayed or else an appropriate warning shows up.

**- What is the expected behavior?**
`netlify status --verbose` displays local environment information.

**Comment by jamesgeorge007** [comment]
I can shoot a PR 👍

**Comment by RaeesBhatti** [comment]
A PR would be awesome @jamesgeorge007
