### ISSUE TITLE
Netlify CLI unexpectedly invokes hugo

### ISSUE THREAD

**Issue by casey** [netlify/cli#791]
In the screenshot below, I'm trying to serve my blog locally, but the netlify CLI is unexpectedly invoking hugo:

![image](https://user-images.githubusercontent.com/1945/78419318-7b0d5800-75f9-11ea-97c4-5d04e046da76.png)

This is a bug report. The current behavior is that, upon `netlify dev`, it invokes hugo. My site is `rodarmor-blog`, and this behavior can be reproduced by typing `netlify dev`. The expected behavior is that it opens a dev server without invoking hugo

Netlify version:

`netlify-cli/2.40.0 darwin-x64 node-v13.11.0`

**Comment by casey** [comment]
I had a file called `config.toml` in my site directory, which caused hugo to trigger.

Is there a way to turn off auto-detection of build types? `config.toml` is a pretty common filename, so it would be nice if it didn't trigger changes to the way netlify previews sites.

**Comment by RaeesBhatti** [comment]
Hey Casey, thanks for opening this ticket. You can disable framework detection and use the static server by invoking `netlify dev -d [Project root directory here]`. This will not run the Hugo server.

**Comment by casey** [comment]
Hi Raees, thanks for the info!

It might be nice to make it configurable in `netlify.toml`, I think I already have the project root as `build.publish`, and it would be nice to avoid duplicating the configuration in two places.

**Comment by RaeesBhatti** [comment]
@casey `netlify-cli@2.47.0` has just been released. In the latest version you can specify `framework = "#static"` property in `netlify.toml` `[dev]` section to avoid passing `-d` flag every time. Like so:
```toml
[dev]
    command = "npm run serve"
    port = 8888
    targetPort = 3000 # port of your app server
    framework = '#static'
```

**Comment by casey** [comment]
Sweet, this is great. Thank you!
