### ISSUE TITLE
--prod flag is not making any effect

### ISSUE THREAD

**Issue by shakirovs** [netlify/cli#793]
**- Do you want to request a _feature_ or report a _bug_?**
Bug

**- What is the current behavior?**
I am building my frontend(react) in gitlab CI/CD and trying to deploy it using 
`netlify deploy --dir build --site {API Id} --auth {Token} --prod` command

Output
```
Deploy path: {path}/build
Deploying to live site URL...
✔ Finished hashing 30 files
✔ CDN requesting 0 files
✔ Finished uploading 0 assets
✔ Deploy is live!

Logs:              https://app.netlify.com/sites/...
Unique Deploy URL: https://....netlify.com
Live URL:          https://app.mydomaon.com
```
It is working file for unique deploy URL.
But problem is that I have still have old version of my site in production (app.mydomaon.com).
`--prod` flag is not deploying my project to production.

**- Local Environment Information**
netlify-cli/2.40.0 darwin-x64 node-v12.12.0

**Comment by RaeesBhatti** [comment]
@shakirovs It seems like the deploy is happening on the prod context indeed. Can you please make sure that the `build` directory has the updated files. It could be that your site generator is not updating the files or updating them in a different directory. You can test this by building the site locally, making sure `build` directory has the latest changes and then deploying and seeing if the production has the updated version or not.

**Comment by shakirovs** [comment]
1. I installed cli-on my local machine
2. Removed build directory
3. Changed site title to "Test title"
4. Built my site bu running `yarn build`
5. Checked `build/index.html` title. It is "Test title" there
6. Deploy `netlify deploy --dir build --site {API Id} --auth {Token}--prod` 

Result:
I have "Test title" here https://5e8c0581a99897046--site_name.netlify.com  
and old title here https://app.domain.com

**Comment by shakirovs** [comment]
Maybe I am missing something🤔

**Comment by RaeesBhatti** [comment]
I see. I just tested this scenario on a dummy `create-react-app` website and it seems to be working. You can take a look at the deploy settings for your Netlify site to make sure everything is fine. Maybe double check the domain name?

**Comment by RaeesBhatti** [comment]
Try hitting your site from a different browser or CURL. It could be a cache problem.

**Comment by shakirovs** [comment]
> You can take a look at the deploy settings for your Netlify site to make sure everything is fine.  

Could you be more specific?

**Comment by shakirovs** [comment]
I opened deploy logs page (app.netlify.com/sites/.../deploys/...) and published it manually by pressing the "Publish deploy" Now I can see changes in my production site!

Seems `--prod` flag is not working for me.
It is deploying project like draft.

**Comment by RaeesBhatti** [comment]
Actually, I'm not sure exactly. It should work just fine. Maybe @fool can shed some light

**Comment by shakirovs** [comment]
I found the issue. 
I pressed "stop auto publishing" button on deploys page to avoid publishing when I push changes(or merge) to master. Because I have to check lint and run tests in CI before deploy. 
When I unlocked publishing it worked. Unfortunately it is not gonna solve my issue, because now it is deploying my project every time when I push something to master.
I just want to trigger deploy manually.

**Comment by shakirovs** [comment]
May I just create project without binding it to git repository and push my artifacts manually(by netlify-cli)? (like firebase)

**Comment by RaeesBhatti** [comment]
Yes, that is possible if you want to go that route.

**Comment by shakirovs** [comment]
How can I unlink my site from git repository? I can't find it in settings

**Comment by RaeesBhatti** [comment]
I don't you can do this from Netlify dashboard. You can goto your git hosting provider and remove Netlify Deploy Keys and web hooks for that repository.

**Comment by shakirovs** [comment]
Git it, Thank you!
