### ISSUE TITLE
Netlify Dev /* 200 redirect not working

### ISSUE THREAD

**Issue by chris-pardy** [netlify/cli#794]
**- Do you want to request a _feature_ or report a _bug_?**
Report a Bug

**- What is the current behavior?**
200 redirects (rewrites) from `/*` are not working on netlify dev

**- If the current behavior is a bug, please provide the steps to reproduce.**
The following file structure:

```
- dist
|  ﹂ _headers
|  ﹂ _redirects
|  ﹂ index.html
|  ﹂ main.1aa6e6d947cb4c625748.js
|  ﹂ main.1aa6e6d947cb4c625748.js.map
﹂netlify.toml
```

_redirects file:
```
/*    /index.html    200
```

netlify.toml file
```
[dev]
  port = 8888 # Port that the dev server will be listening on
  publish = "dist"
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser
```

run `npx netlify-cli@latest dev`

navigate to [localhost:8888/test](localhost:8888/test) get a 404.

__Note:__ localhost:8888, localhost:8888/, and localhost:8888/index.html all work correctly.

**- What is the expected behavior?**
navigating to localhost:8888/test should rewrite and serve the /index.html file

**- Local Environment Information**
`netlify-cli/2.40.0 darwin-x64 node-v12.2.0`

**Comment by RaeesBhatti** [comment]
Thank you for opening this issue @chris-pardy. This is indeed a bug. We have a fix that will be released soon. https://github.com/netlify/cli/pull/796

**Comment by chris-pardy** [comment]
@RaeesBhatti is there a reason this rule is getting filtered out for non-static servers. While I gave steps to reproduce here ultimately I'd rather use a non static server (webpack dev server)

**Comment by RaeesBhatti** [comment]
@chris-pardy This rule says that if a URL is accessed that results in 404 or if it doesn't have a corresponding file, show the `/index.html` page instead.
This rule needs to be filtered out for non-static servers because the server will receive `/index.html` as pathname for every request, and this will mean that assets like CSS files and JS files won't load.
Imagine running a `create-react-app` server, when we request a page that doesn't exist, it will have it's own 404 handling logic in `react-router` or some other library. And it will handle the CSS and JS file requests correctly because even if those files don't exist, it has internal routing to handle those URLs.

**Comment by chris-pardy** [comment]
@RaeesBhatti my understanding was that the netlify dev server would only use that redirect if the server it was proxying returned a 404 when requesting a resource? Why would the rule apply if the proxied server returned a 200 response?

If you want I can re-open this issue for custom servers too.

**Comment by RaeesBhatti** [comment]
I think you're right. We're checking for static files instead of relying on the app server to return a 404. Which doesn't work in this case. I've changed the title and reopened the issue to track the problem.

**Comment by RaeesBhatti** [comment]
Thank you for suggesting this @chris-pardy . This change will be published in latest release.

**Comment by chris-pardy** [comment]
@RaeesBhatti thanks for working through this. I'm super excited to be rolling out Netlify Dev across our stack with these changes.

**Comment by RaeesBhatti** [comment]
Thanks for opening this issue. It made Netlify CLI better for so many others.

**Comment by erezrokah** [comment]
I believe there are still some issues with redirecting to non static servers. Opened a new issue to track this:
https://github.com/netlify/cli/issues/1242
