### ISSUE TITLE
Netlify Dev hangs if no functions dir detected

### ISSUE THREAD

**Issue by RaeesBhatti** [netlify/cli#802]
**- Do you want to request a _feature_ or report a _bug_?**
Bug

**- What is the current behavior?**
`netlify dev` in a static directory will hang, waiting for functions server if not functions directory is present.

**- If the current behavior is a bug, please provide the steps to reproduce.**
`netlify dev` in a static directory will hang if not functions directory is present.

**- What is the expected behavior?**
`netlify dev` runs without waiting on functions server indefinitely.

**- Local Environment Information**

netlify-cli/2.41.0 darwin-x64 node-v13.12.0

**Comment by atuttle** [comment]
The new version may or may not have fixed the issue at hand, but it definitely broke something for me.

![image](https://user-images.githubusercontent.com/46990/78891055-c037ec80-7a34-11ea-85d5-ca127ee793bd.png)

**Comment by ehmicky** [comment]
@atuttle This issue was reported here: https://github.com/netlify/cli/issues/809
