### ISSUE TITLE
Allow site creation during link/deploys?

### ISSUE THREAD

**Issue by bcomnes** [netlify/cli#81]
We've discussed adding prompts to allow simple site creation during the `link` and `deploy` commands when a folder isn't associated with a site yet.  While this would be convenient, it may distract or encourage people to avoid setting up CI with the `init` command (our golden path).

Currently you can create an empty site, link it and do manual deploys:

```command
$ netlify sites:create
# ...
$ netlify link --site-name foo
# ...
$ netify deploy ./folder
```

**Comment by DavidWells** [comment]
Closing this for now. Can revisit later
