### ISSUE TITLE
netlify dev: 'C:\Program' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by teachtyler** [netlify/cli#817]
**- Do you want to request a _feature_ or report a _bug_?**
report a bug

**- What is the current behavior?**
netlify dev fails on create-react-app

```
$ ntl dev
◈ Netlify Dev ◈
◈ Starting Netlify Dev with create-react-app
Waiting for localhost:3000.'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
◈ Error while killing child process: kill ESRCH
```

**- Local Environment Information**
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 13.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.13.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0

**Comment by teachtyler** [comment]
recreation steps:
```
npx create-react-app netlify-react-app
cd netlify-react-app
netlify dev
```
as well as 
https://github.com/teachtyler/create-react-app-lambda
https://github.com/teachtyler/deploy-create-react-app

**Comment by RaeesBhatti** [comment]
Thank you for reporting this issue @teachtyler. The problem has been identified and fixed here https://github.com/netlify/cli/pull/818 and the fix will be released soon. In the mean time, you can try out the PR branch and provide feedback on if it fixes your problem.
