### ISSUE TITLE
Redirects tag in netlify.toml causes bundle error

### ISSUE THREAD

**Issue by mrrosoff** [netlify/cli#827]
**- Do you want to request a _feature_ or report a _bug_?**

Report a bug.

**- What is the current behavior?**

When using a redirects tag in netlify.toml (intended for React Router), netlify dev finds bundle.js from webpack-dev-server as index.html.

This is similar to this issue: https://github.com/netlify/cli/issues/443

**- If the current behavior is a bug, please provide the steps to reproduce.**

The repository is here: https://github.com/tc30/blockchain-document-dapp

Running npm run dev will successfully link the files together under webpack-dev-server. When built for production, netlify handles redirects correctly. Issue only exists in netlify dev.

**- What is the expected behavior?**

It redirects correctly and finds bundle.js in dev mode.

**- Local Environment Information**

System:
    OS: Linux 5.3 elementary OS 5.1.3 Hera
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Chrome: 81.0.4044.92
  npmGlobalPackages:
    netlify-cli: 2.45.0

netlify-cli/2.45.0 linux-x64 node-v12.14.1

**Comment by RaeesBhatti** [comment]
@mrrosoff Thanks for opening this ticket! Can you please update to `netlify-cli@2.46.0` and see if that fixes this problem.

**Comment by mrrosoff** [comment]
@RaeesBhatti No problem. Updated, two interesting behaviors now occur. 

Netlify and Webpack port now both open, and the Netlify port has no data. Some communication link has been changed. This removes the core behavior of Netify-dev. This seems to occur with or without the redirect field in netlify.toml. As the core functionality has been removed, it is impossible to test the redirect functionality.

The webpack-dev-server port does not have lambda function access. This is expected.

Thank you for your help!

**Comment by mrrosoff** [comment]
This was on netlify-cli@2.47.0

**Comment by mrrosoff** [comment]
@RaeesBhatti Tested netlify@2.46.0, different issue than 2.47.0.

No discernible change between 2.46.0 and 2.45.0.

**Comment by RaeesBhatti** [comment]
@mrrosoff I see. Can you share you `netlify.toml` please, also the output from `netlify dev` command!

**Comment by mrrosoff** [comment]
Sure!

netlify.toml

`
[build]

  # Directory of Built Files

  publish = "dist/"

  # Production Build Command

  command = "npm run prod"

  # Directory with the Lambda functions to deploy to AWS

  functions = "Lambda/"

[dev]

  # Development Build Command

  command = "./netlify-dev.sh"

  # Webpack-Dev-Server Port

  targetPort = 3000

  publish = "./dist"
  autoLaunch = true

[[redirects]]

  # For React Router

  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]

  for = "/*"

  [headers.values]

      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "SAMEORIGIN"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "same-origin"
`

**Comment by mrrosoff** [comment]
netlify-dev

```
◈ Netlify Dev ◈
◈ Starting Netlify Dev with undefined
Waiting for localhost:3000.
◈ Functions server is listening on 34567
manpath: warning: $PATH not set

> sign-safe@1.0.0 dev /home/mrosoff/WebstormProjects/blockchain-document-dapp
> webpack-dev-server --mode development --devtool inline-source-map && npm run cp_files

.ℹ ｢wds｣: Project is running at http://localhost:3000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/mrosoff/WebstormProjects/blockchain-document-dapp
ℹ ｢wds｣: 404s will fallback to /index.html
.
Connected!
Waiting for localhost:34567.
Connected!
◈ Reloading files [ 'netlify.toml' ]

   ┌──────────────────────────────────────────────────┐
   │                                                  │
   │   ◈ Server now ready on http://localhost:39071   │
   │                                                  │
   └──────────────────────────────────────────────────┘

```

**Comment by RaeesBhatti** [comment]
Can you try out `raees/dev-config-improvements` branch, I think that will fix your problem. Just do `git clone https://github.com/netlify/cli.git && cd cli && git checkout raees/dev-config-improvements && npm i && npm link` outside of your current project.
And then run `netlify dev` in your project again

**Comment by mrrosoff** [comment]
Perhaps this is due to the fact that I am using nvm?

**Comment by mrrosoff** [comment]
Sure

**Comment by RaeesBhatti** [comment]
Can you try changing the `command` to `npm run dev`? Also, please elaborate on what

> the Netlify port has no data

Are you getting a 404 or is it just a blank page? After running `netlify dev`, can you try `curl -vvv http://localhost:8888` in your terminal and share the response.

**Comment by RaeesBhatti** [comment]
Please use `raees/dev-config-improvements` branch for any new tries.

**Comment by mrrosoff** [comment]
npm run dev is the command to run webpack-dev-server.

As for no data, I mean that it loads a blank html file. Attempting to save the page source results in black txt file through Chrome. Dev-tools show no sources. 

Here is the output to curl

```
mrosoff@Tatooine:~/cli$ curl -vvv http://localhost:8888
* Rebuilt URL to: http://localhost:8888/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET / HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< x-powered-by: Express
< accept-ranges: bytes
< content-type: text/html; charset=UTF-8
< content-length: 646
< etag: W/"286-J/I2QUjO6oMyKqJqBD9eZQ6Em1A"
< date: Sun, 19 Apr 2020 02:08:34 GMT
< connection: close
< 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Safe</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0, maximum-scale=1, minimum-scale=1"/>
    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
    <link rel="shortcut icon" href="favicon-16x16.png">
<link rel="shortcut icon" href="favicon.ico"></head>
<body>
    <div id="root"></div>
<script src="bundle.js"></script></body>
</html>
* Closing connection 0
```

**Comment by RaeesBhatti** [comment]
It seems like at least the HTML is being proxied correctly. Can you try share the results of `curl -vvv http://localhost:8888/bundle.js`!
Also, try [hard reloading](https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache) http://localhost:8888 in your browser. This can very well be a cache problem.

**Comment by mrrosoff** [comment]
That seemed to be the problem. To summarize:

With branch `raees/dev-config-improvements`, with `framework = "#custom"`, both `redirects` and `lambda functions` work properly.

Thank you for your help!

**Comment by RaeesBhatti** [comment]
Ah, I'm so glad it worked out for you!

**Comment by bradley** [comment]
It appears this also fixed my issue with `webpack-dev-server` and having to `cmd+shift+r` to get pages to load when ran through `netlify dev`. Is there a definite plan to include this branch in a release soon? Id like not to make my other devs do the symlink branch install flow nor document it. Thanks so much for the continued work @RaeesBhatti you've been helpful across issues.
