### ISSUE TITLE
"Forbidden" error with redirected function in folder since v2.42.0

### ISSUE THREAD

**Issue by oles** [netlify/cli#832]
**- Do you want to request a _feature_ or report a _bug_?**
Bug.

**- What is the current behavior?**
Broken redirection of functions in folders with `netlify dev`, with this config:

```
[[redirects]]
    from = '/functions/*'
    to = '/.netlify/functions/:splat'
    status = 200
```

`netlify-cli/2.42.0 linux-x64 node-v10.20.1`
(same with the newest release, `netlify-cli/2.46.0 linux-x64 node-v10.20.1`)
http://localhost:8888/.netlify/functions/example :heavy_check_mark: 
http://localhost:8888/.netlify/functions/nested-example :heavy_check_mark: 
http://localhost:8888/functions/example :heavy_check_mark: 
http://localhost:8888/functions/nested-example :no_entry_sign: Status: 403, response: Forbidden

`netlify-cli/2.41.0 linux-x64 node-v10.20.1`
http://localhost:8888/.netlify/functions/example :heavy_check_mark: 
http://localhost:8888/.netlify/functions/nested-example :heavy_check_mark: 
http://localhost:8888/functions/example :heavy_check_mark: 
http://localhost:8888/functions/nested-example :heavy_check_mark: 

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Clone https://github.com/oles/minimal-netlify-functions-with-redirect
2. `npm install netlify-cli@2.41.0 -g`
3. `netlify dev`
4. Open the urls above, confirm that they all work.
5. Stop `netlify dev`
5. `npm install netlify-cli@2.42.0 -g` (or newer)
6. `netlify dev`
7. Open the urls above, and the nested-example will not work

**- What is the expected behavior?**
For the nested/folder function to work.

**- Local Environment Information**
```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: Linux 5.6 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 10.20.1 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Firefox: 75.0
  npmGlobalPackages:
    netlify-cli: 2.42.0

netlify-cli/2.42.0 linux-x64 node-v10.20.1
```

**Comment by RaeesBhatti** [comment]
Thank you @oles for making such a excellent bug report! The problem has been identified and fixed in https://github.com/netlify/cli/pull/834. The solution will be released soon.

**Comment by oles** [comment]
Glad to help!
Awesome, looking forward to it - thank you!
