### ISSUE TITLE
netlify dev: default 404 page handling, file/url shadowing not functioning

### ISSUE THREAD

**Issue by moop-moop** [netlify/cli#848]
**- Do you want to request a _feature_ or report a _bug_?**

bug

**- What is the current behavior?**

When using `netlify dev` the documented default 404 and file shadowing behavior does not work.

- https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling

- https://docs.netlify.com/routing/redirects/rewrites-proxies/#shadowing

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a simple static site folder with a 404.html at the root and \index.html, \foo.html, \foo\bar.html or \not-foo\index.html or similar file patterns.
2. create a `_redirects` files with:
`/foo /not-foo 200`
3. Test 404, go to any non-existent url (http://localhost:8888/nothinghere) and you will receive a  default 404 status, but not the \404.html
4. Test file/url shadowing, go to http://localhost:8888/foo and you will receive the page from \not-foo\index.html
5. Add `/foo.html /not-foo 200` to the `_redirects` file
6. Test file/url shadowing, go to http://localhost:8888/foo.html and you will still receive the page from \not-foo\index.html

**- What is the expected behavior?**

1. the \404.html page should be used for 404 status as per documentation
2. when a request matches an existing static file, that should be returned and the proxying rule ignored as per documentation

**- Local Environment Information**

────────────┐
 Environment Info
────────────┘
  System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0

netlify-cli/2.47.0 win32-x64 node-v12.16.2

────────────┐ 
        netlify.toml
────────────┘
```
[dev]
  functions = "functions"
  publish = "public"
  framework= "#static"
```

**Comment by RaeesBhatti** [comment]
Thank you for reporting this @moop-moop and providing references. There's a PR to fix this behavior https://github.com/netlify/cli/pull/885. If you can, please try it out and let us know there's anything missing or wrong!
