### ISSUE TITLE
v2.47 breaks `netlify dev` with vue-cli

### ISSUE THREAD

**Issue by fjeddy** [netlify/cli#850]
Hello,

On the new 2.47 version running `netlify dev` on a vue-cli project will result in the following

```
◈ Netlify Dev ◈
◈ Starting Netlify Dev with vue-cli
Waiting for localhost:8080.
Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami
```

No errors, except a hint  saying a npm command that doesn't exist was used. Downgrading to version 2.46 will fix the problem, so something broke / changed in 2.47.

**Comment by marcorivm** [comment]
Setting the dev command manually on netlify.toml fixed it for me
```netlify.toml
[dev]
  command = "npm run dev"
```

**Comment by macguirerintoul** [comment]
Seeing this as well, but with Gridsome and on CLI v2.48

**Comment by RaeesBhatti** [comment]
@fjeddy , @marcorivm , @macguirerintoul Thank for you reporting this. Can you please try out https://github.com/netlify/cli/pull/843 branch and see if you're still facing the issue!

**Comment by chiubaca** [comment]
Same issue on v2.48 rolling back using `npm install netlify-cli@2.45 -g` is my workaround at the moment. 

Happy to test the fix if there are steps to follow. Please explain like i'm five.

**Comment by macguirerintoul** [comment]
Hi @RaeesBhatti, I'm quite inexperienced with this kind of development but I cloned your branch, ran `npm link`, and tried using `netlify dev` again. However, I'm getting the same error. Is that the right process to follow?

**Comment by RaeesBhatti** [comment]
@macguirerintoul Yes, that seems like the right process. Could you possibly show your `package.json`, specifically the `scripts` property!

**Comment by macguirerintoul** [comment]
```
{
	"name": "bluemoonorganics.com",
	"private": true,
	"scripts": {
		"build": "gridsome build && netlify-lambda build functions",
		"develop": "gridsome develop",
		"explore": "gridsome explore"
	},
	"dependencies": {
		"@gridsome/source-filesystem": "^0.6.2",
		"@gridsome/transformer-remark": "^0.4.0",
		"@sendgrid/mail": "^6.5.0",
		"dotenv": "^8.2.0",
		"gridsome": "^0.7.0",
		"netlify-lambda": "^1.6.3"
	},
	"devDependencies": {
		"eslint-config-prettier": "^6.11.0",
		"eslint-plugin-prettier": "^3.1.3",
		"node-sass": "^4.13.1",
		"sass-loader": "^8.0.2",
		"stylelint": "^13.3.3",
		"eslint": "^6.8.0",
		"stylelint-config-sass-guidelines": "^7.0.0"
	}
}
```

**Comment by RaeesBhatti** [comment]
@macguirerintoul Thanks for providing this information. I've pushed some changes to the `raees/dev-config-improvements` branch, can you do a `git pull` in your local instance and try running `netlify dev` again!
