### ISSUE TITLE
Error [ERR_REQUIRE_ESM] with `netlify link`

### ISSUE THREAD

**Issue by kaganjd** [netlify/cli#868]
**- Do you want to request a _feature_ or report a _bug_?**
Bug

**- What is the current behavior?**
`netlify link` with a fresh CLI install returns `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/local/lib/node_modules/netlify-cli/node_modules/is-promise/index.js
require() of ES modules is not supported.`

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. `npm install netlify-cli -g`
2. `netlify link`

**- Local Environment Information**
- MacOS
- v12.16.2

**Related**
- Community post: https://community.netlify.com/t/happy-path-broken-must-use-import-to-load-es-module/13303
- https://github.com/netlify/cli/issues/858

```
% netlify -v
netlify-cli/2.48.0 darwin-x64 node-v12.16.2
```

**Comment by ehmicky** [comment]
Oh oh oh, that might be related to the great 2020 `is-promise` one-line-of-code disaster: https://medium.com/javascript-in-plain-english/is-promise-post-mortem-cab807f18dcc

**Comment by TomPichaud** [comment]
https://github.com/netlify/cli/issues/863

**Comment by carlmjohnson** [comment]
I tried reinstalling as suggested in #863, but it's still caught up on the bad version.

**Comment by carlmjohnson** [comment]
Okay, I got it to work by running:

```bash
$ brew uninstall netlify-cli
Uninstalling /usr/local/Cellar/netlify-cli/2.48.0... (16,459 files, 153.0MB)

$ brew install -s netlify-cli
…
```

I think there should still be a new version pushed to Homebrew so that this is not necessary.

**Comment by RaeesBhatti** [comment]
Is this still a problem? I haven't been able to reproduce it recently.

**Comment by RaeesBhatti** [comment]
@kaganjd Can you please provide an update on whether this is still a problem!

**Comment by kaganjd** [comment]
Hey @RaeesBhatti, I haven't heard anything in response from the person who wrote into Community
