### ISSUE TITLE
Netlify Dev gets stuck in infinite build loop- possible to add ignore directory?

### ISSUE THREAD

**Issue by ChrisW-B** [netlify/cli#891]
I'm willing to bet this is just a configuration error, since I cannot find anyone else with this issue. 

**- Do you want to request a _feature_ or report a _bug_?**
Feature- or config help

**- What is the current behavior?**
Right now, if I run `netlify dev`, everything work correctly- however, it also watches the directory that my build command builds into, so it continually triggers the build command, until my computer crashes

**- What is the expected behavior?**
Netlify dev's watch should probably not care about the build dir

**- Local Environment Information**
Netlify.toml:
```
[build]
  command = "npm run build"
  functions = "build"
  publish = "build"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/graphql-api"
  status = 200
  force = true
```

file structure:
- build
- src
  - functions
    - [other files used by graphql-api.ts]
    - graphql-api.ts

build command:
`    "build": "netlify-lambda build src/functions --config webpack.functions.js",`

webpack config:
```
const nodeExternals = require('webpack-node-externals');

module.exports = {
  optimization: { minimize: false },
  externals: [nodeExternals()],
};

```

babelrc
```
{
  "presets": ["@babel/preset-typescript", ["@babel/env", { "targets": { "node": "current" } }]],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-object-assign",
    "@babel/plugin-proposal-object-rest-spread"
  ],
  "env": {
    "production": {
      "presets": [
        ["@babel/env", { "targets": { "node": "current" }, "forceAllTransforms": true, "useBuiltIns": "usage" }]
      ]
    }
  }
}
```

```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 12.16.3 - ~/.bin/n/bin/node
    Yarn: 1.22.4 - /Volumes/Projects/PersonalApi/node_modules/.bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Safari: 13.0.3

netlify-cli/2.50.0 darwin-x64 node-v12.16.3
```

**Comment by RaeesBhatti** [comment]
Thank you for opening this ticket @ChrisW-B . Can you see `Function builder netlify-lambda detected: Running npm script <script>` in the log when you run `netlify dev`?

**Comment by ChrisW-B** [comment]
@RaeesBhatti sure, here's all of the output from running netlify dev:
```
❯ npm run start

> [projectname]@1.0.0 start [projectpath]
> netlify dev

◈ Netlify Dev ◈
[[ ENV VARIABLES]]
◈ No app server detected and no "command" specified
◈ Running static server from "PersonalApi/build"
◈ Function builder netlify-lambda detected: Running npm script build
 ›   Warning: ◈ This is a beta feature, please give us feedback on how to improve at https://github.com/netlify/cli/

◈ Server listening to 3999
Waiting for localhost:3999.
◈ Functions server is listening on 34567

Connected!
Waiting for localhost:34567.
Connected!

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘
```

**Comment by RaeesBhatti** [comment]
@ChrisW-B I think you might be trying to build the wrong directory. `netlify dev` looks for the `npm` script to build your functions and infers the functions "source" directory from the script.
If you have an entry something like:
```json
...
"scripts": {
    "build": "netlify-lambda build build",
},
...
```
This will cause the problem where the source directory and functions directory, both are `build`. Please make sure that your `netlify-lambda` `npm` script is pointing to the right source directory. It should be something like `netlify-lambda build functionsSource`, where `functionsSource` is the source directory for your functions. If that doesn't fix the problem, please share your `package.json`!

**Comment by ChrisW-B** [comment]
unfortunately that doesn't seem to be it, unless I'm misreading something-- my build script is `netlify-lambda build src/functions --config webpack.functions.js`

here's the full thing: 
```json
{
  "name": "chriss-personal-site",
  "version": "1.0.0",
  "description": "A Simple Personal API",
  "keywords": [
    "personal",
    "site"
  ],
  "homepage": "https://github.com/ChrisW-B/PersonalAPI#readme",
  "bugs": {
    "url": "https://github.com/ChrisW-B/PersonalAPI/issues"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/ChrisW-B/PersonalAPI.git"
  },
  "license": "ISC",
  "author": "Chris Barry <me@chrisb.xyz>",
  "scripts": {
    "build": "netlify-lambda build src/functions --config webpack.functions.js",
    "clean": "rm -rf ./build",
    "lint:js": "eslint \"./src/**/*.{t,j}s{x,}\" --ignore-pattern 'build/**/*.js'",
    "lint:js:fix": "npm run lint:js -- --fix",
    "prettier": "prettier './src/**/*.{ts,js,jsx,tsx,gql,html,yml,json}' --write",
    "prettier:check": "prettier './src/**/*.{ts,js,jsx,tsx,gql,html,yml,json}' -c",
    "start": "netlify dev",
    "typescript": "tsc --noEmit"
  },
  "dependencies": {
    "apollo-server": "^2.13.1",
    "apollo-server-lambda": "^2.13.1",
    "body-parser": "^1.19.0",
    "compression": "^1.7.4",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "express-graphql": "^0.9.0",
    "graphql": "^15.0.0",
    "lastfm-njs": "^1.0.0",
    "node-fetch": "^2.6.0",
    "twitter": "^1.7.1",
    "twitter-text": "^3.1.0"
  },
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.6",
    "@babel/node": "^7.8.7",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/preset-env": "^7.9.6",
    "@babel/preset-typescript": "^7.9.0",
    "@commitlint/cli": "^8.3.5",
    "@commitlint/config-conventional": "^8.3.4",
    "@types/aws-lambda": "^8.10.51",
    "@types/node": "^14.0.1",
    "@types/node-fetch": "^2.5.7",
    "@types/twitter": "^1.7.0",
    "@types/twitter-text": "^2.0.0",
    "@typescript-eslint/eslint-plugin": "^2.34.0",
    "@typescript-eslint/parser": "^2.34.0",
    "@typescript-eslint/typescript-estree": "^2.34.0",
    "eslint": "^7.0.0",
    "eslint-config-airbnb-base": "^14.1.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-import-resolver-typescript": "^2.0.0",
    "eslint-import-resolver-webpack": "^0.12.1",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-unicorn": "^19.0.1",
    "import-sort": "^6.0.0",
    "import-sort-parser-typescript": "^6.0.0",
    "import-sort-style-react": "^5.1.0",
    "netlify-cli": "^2.51.0",
    "netlify-lambda": "^1.6.3",
    "nodemon": "^2.0.4",
    "prettier": "^2.0.5",
    "prettier-eslint": "^9.0.1",
    "prettier-plugin-import-sort": "0.0.4",
    "prettier-plugin-packagejson": "^2.2.3",
    "typescript": "^3.9.2",
    "webpack-node-externals": "^1.7.2"
  },
  "importSort": {
    ".js, .jsx, .es6, .es": {
      "parser": "babylon",
      "style": "react"
    },
    ".ts, .tsx": {
      "parser": "typescript",
      "style": "react"
    }
  }
}
```

**Comment by donavon** [comment]
The same thing happens to me. Wait long enough and it works, but I see that it build my 3 lambda functions about6 times each (sometimes more). I assume that it's compiling them all at the same time.

**Comment by skyfly200** [comment]
This may be what happening for me, I run netlify dev and my computer freezes. First time I was able to CTRL + C quit but this time I tried it actually crashed my PC with a BSOD about a watchdog timout

**Comment by donavon** [comment]
We "fixed" this by scrapping `netlify-lambda` altogether and writing our own custom build script. In doing so, our lambda functions have dropped in size dramatically – from 5.25 MiB when built with `netlify-lambda` to 18.5 KiB with our custom solution. I suspect that `netlify-lambda` is somehow including all of the client app (i.e. react, app, etc) in with the lambda function.

Note that they do share some source files – TypeScript types mostly.

**Comment by RaeesBhatti** [comment]
This should have been fixed by https://github.com/netlify/cli/pull/974

Please reopen if that is not the case

**Comment by Javarome** [comment]
I'm having such an infinite loop when using `netlify build`, while other commands like:
- `netlify-lambda build functions_dir` and
- `netlify dev`
work fine

**Comment by erezrokah** [comment]
Hi @Javarome, do you mind opening a new issue with a reproduction scenario?
This issue is quite old, so we'd like to verify your use case.
