### ISSUE TITLE
netlify dev --live returns 404 on function invocation

### ISSUE THREAD

**Issue by JonasTaulienSolutions** [netlify/cli#896]
**- Do you want to request a _feature_ or report a _bug_?**
_bug_

**- What is the current behavior?**
Netlify dev live returns `404` on function invocation.

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Start `netlify dev --live`
2. Open the page via `localhost` and execute call to `/.netlify/functions/my-function`
    It works!
3. Open the page via `*.netlify.live` and execute call to `/.netlify/functions/my-function`
    Returned status code is `404` with an html-page displaying `Cannot POST /.netlify/functions/my-function`

**- What is the expected behavior?**
`netlify dev --live` should find and execute the function and should not return an error.

**- Local Environment Information**
```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 75.0
    Safari: 13.1

netlify-cli/2.50.0 darwin-x64 node-v13.11.0
```

**Comment by RaeesBhatti** [comment]
Thank you @JonasTaulienSolutions for reporting this issue. `netlify-cli@2.51.0` has just been released which contains a fix for this issue. Please try it out and let us know

**Comment by JonasTaulienSolutions** [comment]
Works like a charm. Thank you really much!
