### ISSUE TITLE
Error: Could not acquire required "port": 3000

### ISSUE THREAD

**Issue by fregante** [netlify/cli#898]
**- Do you want to request a _feature_ or report a _bug_?**

_bug_

**- What is the current behavior?**

I can't run `netlify dev` because it can't open ports, whatever port I specify. Both Jekyll and browser-sync can open the ports they need when run from the same command line, but netlify can't.

This is the first time I'm using netlify-cli

**- If the current behavior is a bug, please provide the steps to reproduce.**

```toml
[build]
  publish = "dist"
  command = "npm run build"
  functions = ".netlify/functions/"
[dev]
  command = "npm run watch"
  framework = "#custom"
  port = "3000"
  targetPort = "3009"
```

```

```sh
$ netlify dev
Error: Could not acquire required "port": 3000
    at module.exports.serverSettings (/usr/local/lib/node_modules/netlify-cli/src/utils/detect-server.js:124:11)
    at async DevCommand.run (/usr/local/lib/node_modules/netlify-cli/src/commands/dev/index.js:422:20)
    at async DevCommand._run (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/config/lib/config.js:172:9)
    at async Main.run (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:43:20)
```

**- Local Environment Information**

```
❯ netlify version --verbose
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 7.30GHz
  Binaries:
    Node: 12.15.0 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
  npmGlobalPackages:
    netlify-cli: 2.50.0

netlify-cli/2.50.0 darwin-x64 node-v12.15.0
```

**Comment by RaeesBhatti** [comment]
@fregante It seems like something else it running on port 3000 on your computer. Please change the `port` option in your `netlify.toml` `[dev]` section or just remove the option to default to either `8888` (or a random port if `8888` is not available).

**Comment by fregante** [comment]
> whatever port I specify. Both Jekyll and browser-sync can open the ports they need when run from the same command line, but netlify can't.

👆


> just remove the option

Then it outputs this and exits with non-0:
```
◈ Netlify Dev ◈
◈ Starting Netlify Dev with #custom
◈ Netlify Dev doesn't know what port your site is running on.
◈ Please set --targetPort.

◈ Functions server is listening on 34567
TypeError: this.exit is not a function
    at startProxy (/usr/local/lib/node_modules/netlify-cli/src/commands/dev/index.js:165:10)
```

If I set `port = "34567"` I still get

```
Error: Could not acquire required "port": 34567
```

**Comment by RaeesBhatti** [comment]
You shouldn't see `port = "34567"`. Just to clarify `port` option specifies the port `netlify dev` server itself will run on. `targetPort` is the port of your framework server e.g. `create-react-app` server.
When `framework = "#custom"`, you must specify `command` and `targetPort`, so that, `netlify dev` can start your framework server using `command` and connect to it using `targetPort`.
I suggest that you remove `port` option and make sure that your framework server is available at `targetPort`. Maybe run `npm run watch` independently to test things out and try `curl http://localhost:3009/`

**Comment by fregante** [comment]
I found the issue. If you  set a string to `targetPort` it's silently ignored:

```toml
targetPort = "3000"
```
```
❯ netlify dev
◈ Netlify Dev ◈
◈ Starting Netlify Dev with #custom
◈ Netlify Dev doesn't know what port your site is running on.
◈ Please set --targetPort.

◈ Functions server is listening on 34567
TypeError: this.exit is not a function
    at startProxy (/usr/local/lib/node_modules/netlify-cli/src/commands/dev/index.js:165:10)
1
```

---

Using numbers appears to work, **but**

```toml
[build]
  publish = "dist"
  command = "npm run build"
  functions = ".netlify/functions/"
[dev]
  command = "echo 1"
  framework = "#custom"
  targetPort = 3000
```
```toml
❯ netlify dev

◈ Netlify Dev ◈
◈ Starting Netlify Dev with #custom
Waiting for localhost:3000.
◈ Functions server is listening on 34567

1

Connected!
Waiting for localhost:34567.⏎ 
```

This still instantly exits with 0 and `localhost:34567` isn't available. 

Note: the server on localhost:3000 is running separately and it works.

**Comment by fregante** [comment]
As an outsider/new entry, I have no idea what "port" and "targetPort" mean and the descriptions are confusing:

```toml
  command = "yarn start" # Command to start your dev server
```

Ok, `yarn start` is my server, like `parcel watch`

```
  port = 8888 # Port that the dev server will be accessible on
```

"the dev server"… mine? So it will be 3000?

```
  targetPort = 3000 # Port of target app server
```

What target?

---

Now I know what they mean, but the docs or the names should be improved.

**Comment by RaeesBhatti** [comment]
Yeah, sorry about that 😅 . We plan to depreciate `targetPort` soon. We're considering using `frameworkPort` instead. Please let us know if you think that is a good idea or suggest a different one.

**Comment by fregante** [comment]
That implies I'm using a framework, which I'm not.

Could they be more generically named `inputPort` and `outputPort`? I don't think anything else makes it clear that the first one is proxied by netlify-dev **_to_** the second one.
