### ISSUE TITLE
Add links to Guides to the CLI

### ISSUE THREAD

**Issue by bdougie** [netlify/cli#9]
I want to contribute something I notice in the CLI that was lacking. I also want to do this in the Go CLI, but starting somewhere more familiar for now.

``` bash
 Guides:
    Getting started     https://netlify.com/docs#quickstart
    Custom domains      https://netlify.com/docs/custom-domains
    SSL     https://netlify.com/docs/ssl
    API     https://netlify.com/docs/api#netlify-rest-api

... etc
```

**Comment by bcomnes** [comment]
We have something like this now in the upcoming 2.0.0 release.
