### ISSUE TITLE
Add ability to turn off netlify dev progress bar

### ISSUE THREAD

**Issue by cbetta** [netlify/cli#903]
The recently introduced progress bar (little dots) are obscuring the actual output from Gatsby. It would be great if we could turn this off instead.

**Comment by RaeesBhatti** [comment]
@cbetta Can you please post a screenshot of the problem!

**Comment by RaeesBhatti** [comment]
Also, please fillout the issue template. It helps save a lot of questioning/time and is good for documentation as well.


**- Do you want to request a _feature_ or report a _bug_?**

**- What is the current behavior?**

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Local Environment Information**

**Comment by cbetta** [comment]
@RaeesBhatti apologies, laziness got the best of me.

**Do you want to request a feature or report a bug?**

A feature, or maybe a feature change?

**What is the current/expected behavior?

So if I run `gatsby develop` directly my terminal output looks like this.

![Screenshot 2020-05-14 at 10 23 00](https://user-images.githubusercontent.com/7718/81917788-8cb92680-95cd-11ea-84b0-d68a3297f5bd.png)

As you can see, Gatsby draws its own progress bar for some of the processes that take a long time. 

Now if I instead run `netlify dev` using the Netlify CLI I get this output.

![Screenshot 2020-05-14 at 10 26 26](https://user-images.githubusercontent.com/7718/81917943-c25e0f80-95cd-11ea-9340-e24691860fd8.png)

As you can see, the Netlify CLI is inserting dots that messes with Gatsby's own output, and it's somehow managing to hide the progress bars that Gatsby creates by overwriting them with dots.

**Local Environment Information**

```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 13.8.0 - ~/.nvm/versions/node/v13.8.0/bin/node
    Yarn: 1.22.4 - ~/code/box/developer.box.com-framework/node_modules/.bin/yarn
    npm: 6.14.3 - ~/.nvm/versions/node/v13.8.0/bin/npm
  Browsers:
    Chrome: 84.0.4143.2
    Firefox: 75.0
    Safari: 13.1

netlify-cli/2.51.0 darwin-x64 node-v13.8.0
```

**Comment by cbetta** [comment]
Thank you for the fix @RaeesBhatti 👏
