### ISSUE TITLE
Please improve this sentence in the Readme

### ISSUE THREAD

**Issue by DavidSabine** [netlify/cli#916]
You said, in the Readme:

>If your SSG has a devserver on port 8000 for example, Netlify Dev needs to be told to proxy that port so it can merge it in with the rest of the local Netlify environment (say, running on port 8888), which is what you want to get the full Netlify Dev experience with Functions, Redirects, and so on.

That is a terrible sentence. I consider myself an intelligent, logical person. But that sentence wouldn't survive scrutiny of ANY of my English teachers. Starting with what does SSG mean?

Notice: your users are duly confused by port behaviour and configuration. Perhaps their (my) confusion is the result of the docs.

**Comment by RaeesBhatti** [comment]
@DavidSabine thank you for opening this issue. We understand that port configuration is confusing right now and that documentation doesn't help either in this matter. We're planning to rename `port` and `targetPort` options them with more self-explanatory options. Please provide your suggestions here: https://github.com/netlify/cli/issues/911
