### ISSUE TITLE
netlify addons:create fauna Internal Server Error

### ISSUE THREAD

**Issue by Bulletninja** [netlify/cli#922]
**- Do you want to request a _feature_ or report a _bug_?**
_bug_

**- What is the current behavior?**
I run `netlify addons:create fauna` in a new project and it shows an error wit the following output:
```
Creating addon
Error: Error {"error":"{/"message/": /"Internal server error/"}"}
    at createAddon (~/.npm-packages/lib/node_modules/netlify-cli/node_modules/netlify/src/addons.js:24:11)
```
I looked into addons.js: 
```
async function createAddon(settings, netlifyApiToken) {
...
if (response.status === 422) {
    throw new Error(`Error ${JSON.stringify(data)}`)
  }

return data
```

**- If the current behavior is a bug, please provide the steps to reproduce.**
Just run netlify addons:create fauna

**- What is the expected behavior?**
That it successfully creates fauna

**- Local Environment Information**

netlify-cli/2.11.15 darwin-x64 node-v10.18.1

**Comment by erezrokah** [comment]
I was able to run `netlify addons:create fauna` successfully. Maybe this was temporary down?
Closing as stale. Please comment if still relevant
