### ISSUE TITLE
netlify dev is not "downloading" env variables

### ISSUE THREAD

**Issue by cfjedimaster** [netlify/cli#930]
**- Do you want to request a _feature_ or report a _bug_?**
Report a bug.

**- What is the current behavior?**
When running netlify dev, and site has a few ENV variables set at Netlify, I do not see the variables available locally. 

**- If the current behavior is a bug, please provide the steps to reproduce.**
Based on my repo: https://github.com/cfjedimaster/raymondcamden2020

**- What is the expected behavior?**
When I run netlify dev, I expect to see in the output that it knows about my 3 or 4 environment variables.

**- Local Environment Information**
```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: Linux 4.19 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
    Yarn: 1.16.0 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm
  npmGlobalPackages:
    netlify-cli: 2.52.0

netlify-cli/2.52.0 linux-x64 node-v14.3.0
```

**Comment by RaeesBhatti** [comment]
@cfjedimaster Can you try `netlify link` and try `netlify dev` after linking the project to your existing Netlify site!

**Comment by cfjedimaster** [comment]
I can confirm that fixed the issue. And it looks like it _is_ documented (https://docs.netlify.com/cli/get-started/#link-and-unlink-sites). Thank you.

**Comment by RaeesBhatti** [comment]
Glad it worked out for you!
