### ISSUE TITLE
netlify dev --dir not working with dev command configured

### ISSUE THREAD

**Issue by cco3** [netlify/cli#932]
```
> mkdir dist
> echo -e '[dev]\n  command = "mkdir dist"' > netlify.toml
> netlify dev --dir dist
◈ Netlify Dev ◈
◈ Using simple static server because --dir flag was specified
◈ Running static server from "mydir/dist"
◈ "command" option cannot be used in conjunction with "dir" flag which is used to run a static server
```

netlify-cli: 2.52.0

**Comment by RaeesBhatti** [comment]
@cco3 Can you please explain what you think correct behavior should be. It would be helpful if you can fillout the issue template, it helps reduce the back-and-forth questioning.
`--dir` **flag** is used to run a static server while the purpose of `command` option is to run an app server.
If you want to run `netlify dev` in a specific directory with a command, you can specify `publish` and `command` options in `netlify.toml` `[dev]` section.

**Comment by cco3** [comment]
**- Do you want to request a _feature_ or report a _bug_?**

Bug

**- What is the current behavior?**

--dir option does not work if a dev build command is configured.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Steps provided above.

**- What is the expected behavior?**

I can use the --dir option even if my project is configured to build when running dev without the dir option, as in previous versions of netlify-cli.

Configuring defaults in a project should not make explicit invocations fail.

**- Local Environment Information**

```
  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 76.0.1
  npmGlobalPackages:
    netlify-cli: 2.52.0

netlify-cli/2.52.0 linux-x64 node-v12.14.0
```

**Comment by cco3** [comment]
@RaeesBhatti I've offered a justification above for classifying this as a bug.  Would you be willing to give this a second consideration?

**Comment by RaeesBhatti** [comment]
@cco3 I see the problem. It is indeed a bug. Thank you!

**Comment by RaeesBhatti** [comment]
@cco3 Can you please try out https://github.com/netlify/cli/pull/936 and let me know if that works for you!

**Comment by cco3** [comment]
It works, thanks!
