### ISSUE TITLE
Netlify template.environment vs build.environment vs .env file vs config.toml

### ISSUE THREAD

**Issue by goldcoders** [netlify/cli#935]
I know this question is very trivial,
I just wanna know the sequence how ENV VAR is injected
let say i have this
```
[template.environment]
  HUGO_BASEURL = "add your custom domain name url with https protocol"
  PAYMONGO_EMAIL = "type here your paymongo username/email"
  PAYMONGO_PASS = "type here your paymongo password"
  SES_ACCESS_KEY = "type here your AWS SES Access Key"
  SES_SECREKT_KEY = "type here your AWS SES Secret Key"

[build.environment]
  HUGO_BASEURL = "https://hugo-theme-twal-starter.netlify.app"
  HUGO_VERSION = "0.72.0"
  HUGO_THEME = "repo"
  HUGO_ENVIRONMENT = "production"
  HUGO_ENABLEGITINFO = "true"
```
When i deploy this to netlify i dont have .env
and the template.environment will prompt me for the value
Question that it overrides the build.environment variable for example the HUGO_BASEURL
this kind of variable has multiple areas where it is define 
for example in the config.toml it is also define.

So I really wanna know who will be the one taking effect in there are multiple instances
and the sequence of overriding this variable ...

Any help would be great thanks

**Comment by erezrokah** [comment]
I believe this was resolved in https://github.com/netlify/cli/pull/1698.
Please comment if still relevant
