### ISSUE TITLE
error while proxying request: connect ECONNREFUSED 127.0.0.1:57885

### ISSUE THREAD

**Issue by beamercola** [netlify/cli#941]
**- If the current behavior is a bug, please provide the steps to reproduce.**
Using latest Gatsby
run `netlify dev`, all requests to `localhost:8888` show the above error

**- Local Environment Information**

```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Safari: 13.1.1

netlify-cli/2.53.0 darwin-x64 node-v12.16.3
```

**Comment by RaeesBhatti** [comment]
@beamercola Thank you for opening this ticket! Are you sure that `netlify dev` server is running on port 8888? Can you please share your terminal output after running `netlify dev`!

**Comment by erezrokah** [comment]
Closing as stale. Please comment with the additional information if still an issue
