### ISSUE TITLE
`connect ETIMEDOUT` when running `netlify deploy`

### ISSUE THREAD

**Issue by likanzhan** [netlify/cli#945]
When I run

```
netlify deploy --prod
```

I got the following error:

```
 ›   Error: request to
 ›   https://api.netlify.com/api/v1/sites/97d670bf-a7e2-422b-abaa-b8dfc54fdff9
 ›   failed, reason: connect ETIMEDOUT 35.201.69.186:443
```

Any suggestions?

The environment of my computer is as follows:

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  Binaries:
    Node: 8.9.4 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  npmGlobalPackages:
    netlify-cli: 2.53.0

netlify-cli/2.53.0 darwin-x64 node-v8.9.4
```

**Comment by KieranO547** [comment]
@likanzhan I think this is a bug introduced in v2.53, I experienced it upgrading from 2.52->2.54, so give downgrading a try!

**Comment by erezrokah** [comment]
Sorry for the very late follow up. Is this still and issue?

**Comment by KieranO547** [comment]
@erezrokah I won't speak for @likanzhan but I've just re-tested `netlify deploy --prod` on versions: 2.52.0/2.53.0 (the one we both had issues on)/2.58.0 and all 3 seems to be fine now :)

**Comment by likanzhan** [comment]
Thanks fellows, but I still get the connect error, even with the latest version `v 2.58.0`.
P.S., I'm from China. Could it be the problem?

```
localhost:Teachings lzhan$ netlify deploy --prod
 ›   Error: request to
 ›   https://api.netlify.com/api/v1/sites/97d670bf-a7e2-422b-abaa-b8dfc54fdff9
 ›   failed, reason: connect ETIMEDOUT 35.201.69.186:443
/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/errors/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/errors/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
```

**Comment by erezrokah** [comment]
Thanks @KieranO547 and @likanzhan.

@likanzhan, can you run `curl -i https://api.netlify.com/api/v1/sites/97d670bf-a7e2-422b-abaa-b8dfc54fdff9` and share the response?

If you don't have `curl`, can you open `https://api.netlify.com/` in a browser and share the response (should be `Not Found`).

This way we can check if this is an issue with the network connection or the CLI.

**Comment by likanzhan** [comment]
```
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.netlify.com:443
```

**Comment by erezrokah** [comment]
@likanzhan see https://github.com/netlify/cli/issues/170#issuecomment-667674965
Closing this issue in favour of that feature request
