### ISSUE TITLE
Avoid calling `getSite` twice

### ISSUE THREAD

**Issue by ehmicky** [netlify/cli#958]
When the configuration is being resolved, `@netlify/config` is receiving the `siteId` from `@netlify/cli`. It retrieves the site information (such as UI build settings) [using a `getSite` API call](https://github.com/netlify/build/blob/a5d09eac3b3e81063c34fa1ba9ba59cea499b0f0/packages/config/src/api/site_info.js#L6). This is returned as a `siteInfo` object (which is only `{}` if neither the `siteId` nor API `token` was available, and `{ id: siteId }` if only the `siteId` was available).

However, there are about 20 places in `@netlify/cli` that call the `getSite` endpoint. Instead, those should simply re-use the return value from `@netlify/config`.

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
