### ISSUE TITLE
Rename `alias` to context?

### ISSUE THREAD

**Issue by ehmicky** [netlify/cli#962]
It seems that the `--alias` CLI flag of the `deploy` command corresponds to what we document as "deploy context" in [our Netlify documentation](https://docs.netlify.com/configure-builds/file-based-configuration/#deploy-contexts) and `context` in the `netlify.toml` (which is either a context alias or a branch name)? Is that the case?

If that's the case, shouldn't this flag be renamed to `--context`?

**Comment by RaeesBhatti** [comment]
The `--alias` flag we have right now is just that, an alias or friendly URL for that deployment. This is different from "context" or "branch" in other cases.
We have a ticket to support "branch" deployments form CLI. https://github.com/netlify/cli/issues/948

**Comment by ehmicky** [comment]
Thanks @RaeesBhatti for the additional context! :+1:
