### ISSUE TITLE
Regression from 2.54.0 - error: "Invalid Content-Type for Netlify Dev forms request"

### ISSUE THREAD

**Issue by mobidev111** [netlify/cli#972]
**- Do you want to request a _feature_ or report a _bug_?**
_bug_

**- What is the current behavior?**
On running netlify-cli the following error appears: 
```
"Invalid Content-Type for Netlify Dev forms request"
```

See also:
https://stackoverflow.com/questions/62662474/invalid-content-type-for-netlify-dev-forms-request

Seems to be a regression, worked in 2.54.0

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**
no error

**- Local Environment Information**

netlify-cli: 2.56.0

  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 14.4.0
    Yarn: 1.22.4
  Browsers:
    Safari: 13.1.1

**
happy to add further infos if needed

**Comment by RaeesBhatti** [comment]
Thank you for reporting this issue @mobidev111. We've identified the problem and there's an open PR to fix it: https://github.com/netlify/cli/pull/973

If you can, please try it out and let us know if it fixes the issue for you!

**Comment by petergoes** [comment]
@RaeesBhatti I get the exact same error when using `netlify-cli/2.58.0`

Going back to `2.54.0` resolved the issue.

**system**
OS: macOS Mojave 10.14.6
Binaries:
node: 13.13.0
npm: 6.14.5

**steps to reproduce**:
* have a function:
```js
exports.handler = async (event, context, callback) => {

  console.log(event.body)

  return {
    statusCode: 200,
    body: 'success',
  }
}
```

* run `netlify dev` @ `netlify-cli/v2.58.0`

* run:
```bash
echo '{"text": "Hello **world**!"}' | curl -X POST -d @- http://localhost:62308/post --header "Content-Type:application/json"
```

Result:
* Request keeps hanging
* `netlify dev` logs: `Invalid Content-Type for Netlify Dev forms request`

Thanks in advance for looking into it

**Comment by philiplindberg** [comment]
As far as I can tell, this is still happening with the latest version of netlify-cli (`2.64.1`). Anyone else still experiencing this issue?

I've noticed that I'm only seeing this error when doing POST requests to my netlify function; GET requests seem to work fine.

**Comment by erezrokah** [comment]
Hi @philiplindberg, do you mind opening a new issue with a reproduction?

**Comment by philiplindberg** [comment]
Just did, here's the link:
https://github.com/netlify/cli/issues/1279
