### ISSUE TITLE
Guard against missing repo urls 

### ISSUE THREAD

**Issue by bcomnes** [netlify/cli#98]
When looking for a matching site, watch out for missing repo urls.

![screen shot 2018-09-07 at 5 06 34 pm](https://user-images.githubusercontent.com/166301/45247945-70c19580-b2c0-11e8-804f-3b90ee5ddfe1.png)

**Comment by bcomnes** [comment]
This may be addressed by recent changes.  Someone needs to investigate again.

**Comment by DavidWells** [comment]
Fixed here https://github.com/netlify/cli/blob/master/src/utils/link/link-by-prompt.js#L66-L67
